import { env } from "cloudflare:workers";
import { authorizeLibrarianApi,isSameOriginRequest,librarianJson,librarianError } from "@/lib/librarian-api";
import { coverBucket } from "@/lib/cover-storage";
import { readBoundedJson } from "@/lib/bounded-json";
import { detectCoverImage } from "@/lib/cover-upload";
import { beginLibraryCommand,finishLibraryCommand,libraryCommand } from "@/lib/library-copy-store";
import { ReaderError,readerBatch,readerFail,requireChanged,type ReaderDatabase } from "@/lib/reader-core";
export const dynamic="force-dynamic";
const headers={"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff","Cross-Origin-Resource-Policy":"same-origin"};
export async function GET(request:Request){const auth=await authorizeLibrarianApi();if(!auth.ok)return auth.response;try{const url=new URL(request.url),id=url.searchParams.get("id")||"",kind=url.searchParams.get("kind")||"edition",db=env.DB as unknown as ReaderDatabase;
 const row=kind==="reader"?await db.prepare("SELECT p.photo_key storage_key,p.photo_mime mime_type,NULL external_url,NULL metadata FROM reader_profiles p WHERE p.reader_id=?").bind(id).first():await db.prepare("SELECT c.storage_key,c.mime_type,c.external_url,e.public_metadata_json metadata FROM library_editions e LEFT JOIN material_cover_assets c ON c.material_id=e.material_id AND c.status='ready' WHERE e.id=? AND e.fund='literature'").bind(id).first();
 if(!row)return new Response(null,{status:404,headers});let key=String(row.storage_key||""),mime=String(row.mime_type||"image/jpeg");
 if(kind!=="reader"){const meta=JSON.parse(String(row.metadata||"{}"));if(meta.literatureCoverKey){key=String(meta.literatureCoverKey);mime=String(meta.literatureCoverMime||"image/jpeg");}else if(!key&&/^[a-f0-9]{64}$/.test(String(meta.coverSha256||""))&&meta.coverKind!=="placeholder")key="librarika-covers/"+meta.coverSha256;}
 if(!key&&row.external_url){try{const external=new URL(String(row.external_url));if(external.protocol==="https:"&&!external.username&&!external.password)return new Response(null,{status:302,headers:{...headers,Location:external.href}});}catch{}}if(!key)return new Response(null,{status:404,headers});if(kind==="reader"&&!key.startsWith("reader-photos/"+id+"/"))return new Response(null,{status:404,headers});
 const object=await coverBucket()?.get(key);if(!object)return new Response(null,{status:404,headers});return new Response(object.body,{headers:{...headers,"Content-Type":["image/jpeg","image/png","image/webp"].includes(object.httpMetadata?.contentType||"")?object.httpMetadata!.contentType!:mime}});
 }catch{return new Response(null,{status:503,headers});}}
export async function POST(request:Request){const auth=await authorizeLibrarianApi();if(!auth.ok)return auth.response;if(!auth.value.access.writesEnabled||!auth.value.user.d1UserId)return librarianError(503,"writes_disabled","Запис вимкнено.",false);if(!isSameOriginRequest(request))return librarianError(403,"origin","Запит має надійти з цього сайту.",true);
 try{const input=await readBoundedJson(request,6000000),id=String(input.id||""),kind=String(input.kind),expected=Number(input.expectedVersion),db=env.DB as unknown as ReaderDatabase,actor={id:auth.value.user.d1UserId,email:auth.value.user.email||""};
 if(!["edition","reader"].includes(kind)||!/^[A-Za-z0-9_-]{1,100}$/.test(id)||!Number.isInteger(expected)||expected<1||typeof input.base64!=="string")readerFail("image","Перевірте фото та картку.");
 const command=await libraryCommand(db,actor,String(input.requestId),"literature.image",input);if(command.replayed)return librarianJson({success:true,result:command.replayed});
 const bytes=Uint8Array.from(atob(input.base64),c=>c.charCodeAt(0));const detected=detectCoverImage(bytes);if(!detected||bytes.length>4000000)readerFail("image","Фото має бути JPG, PNG або WebP до 4 МБ.");
 const target=kind==="edition"?await db.prepare("SELECT id FROM library_editions WHERE id=? AND version=? AND fund='literature'").bind(id,expected).first():await db.prepare("SELECT id FROM library_readers WHERE id=? AND version=?").bind(id,expected).first();if(!target)readerFail("changed","Картку змінено. Відкрийте її знову.",409);
 const digest=await crypto.subtle.digest("SHA-256",bytes),hash=Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join(""),key=kind==="reader"?`reader-photos/${id}/${hash}.${detected.extension}`:`literature-covers/${id}/${hash}.${detected.extension}`,bucket=coverBucket();if(!bucket)readerFail("storage","Сховище фото недоступне.",503);
 await bucket.put(key,bytes.buffer,{httpMetadata:{contentType:detected.contentType},customMetadata:{owner:id}});
 const now=new Date().toISOString(),result={id,version:expected+1},statements=[beginLibraryCommand(db,actor,String(input.requestId),"literature.image",command.hash,id,now)];
 if(kind==="edition")statements.push(db.prepare("UPDATE library_editions SET public_metadata_json=json_set(public_metadata_json,'$.literatureCoverKey',?,'$.literatureCoverMime',?),version=version+1,updated_at=? WHERE id=? AND version=? AND fund='literature'").bind(key,detected.contentType,now,id,expected),requireChanged(db,1));
 else statements.push(db.prepare("UPDATE library_readers SET version=version+1,updated_at=? WHERE id=? AND version=?").bind(now,id,expected),requireChanged(db,1),db.prepare("INSERT INTO reader_profiles(reader_id,display_name,photo_key,photo_mime,updated_at) VALUES(?,'Читач',?,?,?) ON CONFLICT(reader_id) DO UPDATE SET photo_key=excluded.photo_key,photo_mime=excluded.photo_mime,version=reader_profiles.version+1,updated_at=excluded.updated_at").bind(id,key,detected.contentType,now));
 statements.push(...finishLibraryCommand(db,actor,String(input.requestId),"literature.image",id,result,now));await readerBatch(db,statements);return librarianJson({success:true,result});
 }catch(error){return error instanceof ReaderError?librarianError(error.status,error.code,error.message,true):librarianError(400,"image","Не вдалося зберегти зображення. Перевірте файл і повторіть.",true);}}
