"use client";

/* eslint-disable @next/next/no-html-link-for-pages -- full-page anchors are intentional in Vinext production. */

import { type FormEvent, useEffect, useState } from "react";
import styles from "./suggest-book.module.css";

export default function SuggestBookForm() {
  const [classes, setClasses] = useState<Array<{ id: string; name: string }>>([]); const [academicYear,setAcademicYear]=useState("");
  const [className,setClassName]=useState(""); const [fullName,setFullName]=useState(""); const [title,setTitle]=useState("");
  const [author,setAuthor]=useState(""); const [year,setYear]=useState(""); const [quantity,setQuantity]=useState("1");
  const [sourceUrl,setSourceUrl]=useState(""); const [note,setNote]=useState(""); const [website,setWebsite]=useState("");
  const [startedAt,setStartedAt]=useState(()=>new Date().toISOString()); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState("");
  useEffect(()=>{const controller=new AbortController();void fetch("/api/public/acquisition-reference",{cache:"no-store",signal:controller.signal}).then(async(response)=>{const body=await response.json() as {classes?:typeof classes;academicYear?:string;error?:string};if(!response.ok)throw new Error(body.error||"Не вдалося завантажити класи.");setClasses(body.classes??[]);setAcademicYear(body.academicYear??"");}).catch((loadError)=>{if(!controller.signal.aborted)setError(message(loadError));});return()=>controller.abort();},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");setSuccess("");try{const response=await fetch("/api/public/book-suggestions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:crypto.randomUUID(),fullName,className,title,author,publicationYear:Number(year),requestedQuantity:Number(quantity),sourceUrl,note,website,startedAt})});const body=await response.json() as {publicNumber?:string;error?:string;fieldErrors?:Record<string,string>};if(!response.ok)throw new Error(body.error||Object.values(body.fieldErrors??{})[0]||"Не вдалося надіслати пропозицію.");setSuccess(`Дякуємо! Пропозицію ${body.publicNumber??""} передано бібліотекарю.`);setTitle("");setAuthor("");setYear("");setQuantity("1");setSourceUrl("");setNote("");setStartedAt(new Date().toISOString());}catch(submitError){setError(message(submitError));}finally{setBusy(false);}}
  return <main className={styles.shell}><header><a href="/"><strong>Єдина бібліотека</strong><span>Міжнародний ліцей МАУП</span></a><a href="https://nazarijshvetz1.github.io/library-site/">Каталог ↗</a></header><section className={styles.page}><div className={styles.intro}><span>Пропозиція учня</span><h1>Запропонувати книгу бібліотеці</h1><p>Укажіть видання, яке варто додати до фонду. Це пропозиція для розгляду, а не бронювання чи обіцянка придбання.</p></div>{error?<div className={styles.error} role="alert">{error}</div>:null}{success?<div className={styles.success} role="status">{success}</div>:null}<form onSubmit={submit} aria-busy={busy}><p className={styles.year}>Навчальний рік: <strong>{academicYear||"оновлюємо…"}</strong></p><div className={styles.fields}><label>Клас *<select required value={className} onChange={(event)=>setClassName(event.currentTarget.value)}><option value="">Оберіть клас</option>{classes.map((item)=><option key={item.id} value={item.name}>{item.name}</option>)}</select></label><label>Прізвище та ім’я *<input required minLength={3} maxLength={160} value={fullName} onChange={(event)=>setFullName(event.currentTarget.value)}/></label><label className={styles.wide}>Назва книги *<input required minLength={2} maxLength={320} value={title} onChange={(event)=>setTitle(event.currentTarget.value)}/></label><label>Автор *<input required minLength={2} maxLength={240} value={author} onChange={(event)=>setAuthor(event.currentTarget.value)}/></label><label>Рік видання *<input required type="number" min="1000" max="2100" value={year} onChange={(event)=>setYear(event.currentTarget.value)}/></label><label>Кількість *<input required type="number" min="1" max="50" value={quantity} onChange={(event)=>setQuantity(event.currentTarget.value)}/></label><label className={styles.wide}>Покликання на книгу *<input required type="url" maxLength={1000} value={sourceUrl} onChange={(event)=>setSourceUrl(event.currentTarget.value)} placeholder="https://…"/><small>Наприклад, сторінка видавництва або книгарні.</small></label><label className={styles.wide}>Чому ця книга потрібна?<textarea maxLength={500} value={note} onChange={(event)=>setNote(event.currentTarget.value)}/></label><label className={styles.trap} aria-hidden="true">Сайт<input tabIndex={-1} autoComplete="off" value={website} onChange={(event)=>setWebsite(event.currentTarget.value)}/></label></div><button type="submit" disabled={busy||!classes.length}>{busy?"Надсилаємо…":"Надіслати пропозицію"}</button><p className={styles.privacy}>Дані бачить лише бібліотекар. Вони не публікуються у відкритому каталозі. Не вказуйте телефон або електронну адресу.</p></form></section></main>;
}
function message(error:unknown):string{return error instanceof Error?error.message:"Сталася помилка.";}
