CREATE TABLE `reader_photo_cleanup` (
	`key` text PRIMARY KEY NOT NULL,
	`not_before` text NOT NULL,
	`created_at` text NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_reader_photo_cleanup_due` ON `reader_photo_cleanup` (`not_before`);--> statement-breakpoint
CREATE INDEX `idx_reading_message_rate` ON `reading_messages` (`reader_id`,`created_at`);--> statement-breakpoint
CREATE UNIQUE INDEX `idx_reading_book_active` ON `reading_threads` (`edition_id`) WHERE "reading_threads"."kind"='book' and "reading_threads"."status"='active';
--> statement-breakpoint
CREATE VIEW library_tracked_shelf_stock AS SELECT e.material_id,c.location_id,c.condition,COUNT(*) AS quantity FROM library_copies c JOIN library_editions e ON e.id=c.edition_id WHERE c.registration='registered' AND c.physical_state='on_shelf' GROUP BY e.material_id,c.location_id,c.condition;
--> statement-breakpoint
CREATE TRIGGER holdings_tracked_update_guard BEFORE UPDATE ON holdings WHEN EXISTS(SELECT 1 FROM library_tracked_shelf_stock t WHERE (t.material_id=OLD.material_id AND t.location_id=OLD.location_id AND t.condition=OLD.condition) OR (t.material_id=NEW.material_id AND t.location_id=NEW.location_id AND t.condition=NEW.condition)) BEGIN SELECT RAISE(ABORT,'tracked_stock_conflict') WHERE ((NEW.material_id!=OLD.material_id OR NEW.location_id!=OLD.location_id OR NEW.condition!=OLD.condition) AND COALESCE((SELECT quantity FROM library_tracked_shelf_stock t WHERE t.material_id=OLD.material_id AND t.location_id=OLD.location_id AND t.condition=OLD.condition),0)>0) OR NEW.quantity < COALESCE((SELECT quantity FROM library_tracked_shelf_stock t WHERE t.material_id=NEW.material_id AND t.location_id=NEW.location_id AND t.condition=NEW.condition),0)+COALESCE((SELECT SUM(r.reserved_quantity-r.issued_quantity-r.released_quantity) FROM material_request_reservations r WHERE r.material_id=NEW.material_id AND r.source_location_id=NEW.location_id AND r.condition=NEW.condition),0); END;
--> statement-breakpoint
CREATE TRIGGER holdings_tracked_delete_guard BEFORE DELETE ON holdings BEGIN SELECT RAISE(ABORT,'tracked_stock_conflict') WHERE COALESCE((SELECT quantity FROM library_tracked_shelf_stock t WHERE t.material_id=OLD.material_id AND t.location_id=OLD.location_id AND t.condition=OLD.condition),0)>0; END;
--> statement-breakpoint
CREATE TRIGGER reservation_tracked_insert_guard BEFORE INSERT ON material_request_reservations BEGIN SELECT RAISE(ABORT,'tracked_stock_conflict') WHERE NEW.reserved_quantity-NEW.issued_quantity-NEW.released_quantity+COALESCE((SELECT SUM(r.reserved_quantity-r.issued_quantity-r.released_quantity) FROM material_request_reservations r WHERE r.material_id=NEW.material_id AND r.source_location_id=NEW.source_location_id AND r.condition=NEW.condition),0)+COALESCE((SELECT quantity FROM library_tracked_shelf_stock t WHERE t.material_id=NEW.material_id AND t.location_id=NEW.source_location_id AND t.condition=NEW.condition),0)>COALESCE((SELECT quantity FROM holdings h WHERE h.material_id=NEW.material_id AND h.location_id=NEW.source_location_id AND h.condition=NEW.condition),0); END;
--> statement-breakpoint
CREATE TRIGGER reservation_tracked_update_guard BEFORE UPDATE ON material_request_reservations BEGIN SELECT RAISE(ABORT,'tracked_stock_conflict') WHERE NEW.reserved_quantity-NEW.issued_quantity-NEW.released_quantity+COALESCE((SELECT SUM(r.reserved_quantity-r.issued_quantity-r.released_quantity) FROM material_request_reservations r WHERE r.material_id=NEW.material_id AND r.source_location_id=NEW.source_location_id AND r.condition=NEW.condition AND r.id!=OLD.id),0)+COALESCE((SELECT quantity FROM library_tracked_shelf_stock t WHERE t.material_id=NEW.material_id AND t.location_id=NEW.source_location_id AND t.condition=NEW.condition),0)>COALESCE((SELECT quantity FROM holdings h WHERE h.material_id=NEW.material_id AND h.location_id=NEW.source_location_id AND h.condition=NEW.condition),0); END;
--> statement-breakpoint
CREATE TRIGGER copy_registered_insert_guard BEFORE INSERT ON library_copies BEGIN
SELECT RAISE(ABORT,'tracked_stock_conflict') WHERE NEW.registration='registered' AND (NOT EXISTS(SELECT 1 FROM library_editions e JOIN materials m ON m.id=e.material_id WHERE e.id=NEW.edition_id AND m.status='active') OR NOT EXISTS(SELECT 1 FROM locations WHERE id=NEW.location_id AND status='active' AND type!='service'));
SELECT RAISE(ABORT,'tracked_stock_conflict') WHERE NEW.registration='registered' AND NEW.physical_state='on_shelf' AND 1+(SELECT COUNT(*) FROM library_copies c WHERE c.edition_id=NEW.edition_id AND c.location_id=NEW.location_id AND c.condition=NEW.condition AND c.registration='registered' AND c.physical_state='on_shelf' )+COALESCE((SELECT SUM(r.reserved_quantity-r.issued_quantity-r.released_quantity) FROM material_request_reservations r WHERE r.material_id=(SELECT material_id FROM library_editions WHERE id=NEW.edition_id) AND r.source_location_id=NEW.location_id AND r.condition=NEW.condition),0)>COALESCE((SELECT quantity FROM holdings h WHERE h.material_id=(SELECT material_id FROM library_editions WHERE id=NEW.edition_id) AND h.location_id=NEW.location_id AND h.condition=NEW.condition),0); END;
--> statement-breakpoint
CREATE TRIGGER copy_registered_update_guard BEFORE UPDATE ON library_copies BEGIN SELECT RAISE(ABORT,'tracked_stock_conflict') WHERE OLD.registration='registered' AND (NEW.registration!='registered' OR NEW.edition_id!=OLD.edition_id);
SELECT RAISE(ABORT,'tracked_stock_conflict') WHERE NEW.registration='registered' AND (NOT EXISTS(SELECT 1 FROM library_editions e JOIN materials m ON m.id=e.material_id WHERE e.id=NEW.edition_id AND m.status='active') OR NOT EXISTS(SELECT 1 FROM locations WHERE id=NEW.location_id AND status='active' AND type!='service'));
SELECT RAISE(ABORT,'tracked_stock_conflict') WHERE NEW.registration='registered' AND NEW.physical_state='on_shelf' AND 1+(SELECT COUNT(*) FROM library_copies c WHERE c.edition_id=NEW.edition_id AND c.location_id=NEW.location_id AND c.condition=NEW.condition AND c.registration='registered' AND c.physical_state='on_shelf' AND c.id!=OLD.id)+COALESCE((SELECT SUM(r.reserved_quantity-r.issued_quantity-r.released_quantity) FROM material_request_reservations r WHERE r.material_id=(SELECT material_id FROM library_editions WHERE id=NEW.edition_id) AND r.source_location_id=NEW.location_id AND r.condition=NEW.condition),0)>COALESCE((SELECT quantity FROM holdings h WHERE h.material_id=(SELECT material_id FROM library_editions WHERE id=NEW.edition_id) AND h.location_id=NEW.location_id AND h.condition=NEW.condition),0); END;
--> statement-breakpoint
CREATE TRIGGER copy_registered_delete_guard BEFORE DELETE ON library_copies WHEN OLD.registration='registered' BEGIN SELECT RAISE(ABORT,'tracked_stock_conflict'); END;
--> statement-breakpoint
CREATE TRIGGER edition_material_immutable_guard BEFORE UPDATE OF material_id ON library_editions WHEN NEW.material_id IS NOT OLD.material_id AND EXISTS(SELECT 1 FROM library_copies WHERE edition_id=OLD.id AND registration='registered') BEGIN SELECT RAISE(ABORT,'tracked_stock_conflict'); END;
--> statement-breakpoint
CREATE TRIGGER material_tracked_archive_guard BEFORE UPDATE OF status,archived_at ON materials WHEN NEW.status!='active' OR NEW.archived_at IS NOT NULL BEGIN SELECT RAISE(ABORT,'tracked_stock_conflict') WHERE EXISTS(SELECT 1 FROM library_copies c JOIN library_editions e ON e.id=c.edition_id WHERE e.material_id=OLD.id AND c.registration='registered' AND c.physical_state!='withdrawn'); END;
--> statement-breakpoint
CREATE TRIGGER location_tracked_close_guard BEFORE UPDATE OF status ON locations WHEN NEW.status!='active' BEGIN SELECT RAISE(ABORT,'tracked_stock_conflict') WHERE EXISTS(SELECT 1 FROM library_copies WHERE location_id=OLD.id AND registration='registered' AND physical_state!='withdrawn'); END;
