import test from "node:test";
import assert from "node:assert/strict";
import {readerDatabase,actor} from "./helpers/reader-database.mjs";
const store=await import("../lib/library-copy-store.ts");
function setup(){const db=readerDatabase();db.sqlite.exec(`INSERT INTO library_import_runs(id,manifest_sha256,source_exported_at,state,expected_counts_json,recovery_sha256,actor_user_id,created_at) VALUES('run','${"a".repeat(64)}','2026-09-06','verified','{}','${"b".repeat(64)}','admin','2026-09-06');UPDATE library_import_runs SET reconciliation_json='{"contract":{"sourceCompleteness":{"authorDetailsComplete":true,"authorsVerified":1,"authorsPending":[]}}}';UPDATE library_editions SET publication_state='draft',import_run_id='run',public_metadata_json='{"author":"Автор","year":"2020","isbn13":"9786170953858"}';
 INSERT INTO library_copies(id,edition_id,accession_no,copy_no,created_at,updated_at) VALUES('copy-1','edition','1','1','2026-09-06','2026-09-06'),('copy-2','edition','2','2','2026-09-06','2026-09-06');
 INSERT INTO reader_circulations(id,copy_id,reader_id,status,issued_at,due_at,created_at,updated_at) VALUES('old-loan','copy-2','reader-a','overdue','2026-08-01','2026-08-15','2026-09-06','2026-09-06');`);return db;}
const activation=()=>({requestId:crypto.randomUUID(),editionId:"edition",expectedVersion:1,confirmation:"ACTIVATE_SOURCE_EDITION"});
test("source activation requires complete authors and confirmed non-placeholder covers",async()=>{
 const db=setup();try{
  const sha="f".repeat(64);
  db.sqlite.prepare("UPDATE library_editions SET public_metadata_json=json_set(public_metadata_json,'$.coverSha256',?,'$.coverKind','source_cover')").run(sha);
  await assert.rejects(store.activateImportedEdition(db,actor,activation()),/не підтверджене/);
  assert.equal(db.sqlite.prepare("SELECT count(*) n FROM mutation_commands").get().n,0);
  db.sqlite.prepare("INSERT INTO library_import_cover_receipts VALUES('run',?,?,4,'image/jpeg','2026-09-06')").run(sha,"librarika-covers/"+sha);
  db.beforeBatch=()=>db.sqlite.exec("UPDATE library_import_runs SET reconciliation_json=json_set(reconciliation_json,'$.contract.sourceCompleteness.authorDetailsComplete',0)");
  await assert.rejects(store.activateImportedEdition(db,actor,activation()));
  assert.equal(db.sqlite.prepare("SELECT count(*) n FROM mutation_commands").get().n,0);
  assert.equal(db.sqlite.prepare("SELECT count(*) n FROM library_copies WHERE registration='registered'").get().n,0);
 }finally{db.sqlite.close();}
});
test("edition activation counts source copies once, preserves source debt and replays",async()=>{const db=setup();try{const input=activation(),result=await store.activateImportedEdition(db,actor,input);assert.equal((await store.activateImportedEdition(db,actor,input)).materialId,result.materialId);const stock=db.sqlite.prepare("SELECT total_quantity,library_quantity,loaned_quantity FROM material_stock_totals").get();assert.deepEqual({...stock},{total_quantity:2,library_quantity:1,loaned_quantity:1});assert.equal(db.sqlite.prepare("SELECT count(*) n FROM library_copy_movements").get().n,2);assert.equal(db.sqlite.prepare("SELECT count(*) n FROM reader_notification_outbox").get().n,0);assert.equal(db.sqlite.prepare("SELECT access_status FROM library_readers WHERE id='reader-a'").get().access_status,"inactive");assert.equal(db.sqlite.prepare("PRAGMA foreign_key_check").all().length,0);}finally{db.sqlite.close();}});
test("copy issue and return are atomic, conserve stock and do not require reader login",async()=>{const db=setup();try{const start=await store.activateImportedEdition(db,actor,activation());const input={requestId:crypto.randomUUID(),copyId:"copy-1",expectedCopyVersion:2,readerId:"reader-b",expectedReaderVersion:1,issuedAt:"2026-09-06",dueAt:"2026-09-20",confirmation:"ISSUE_THIS_COPY"};const issue=await store.issueReaderCopy(db,actor,input);assert.equal((await store.issueReaderCopy(db,actor,input)).id,issue.id);assert.equal(db.sqlite.prepare("SELECT count(*) n FROM holdings").get().n,0);assert.equal(db.sqlite.prepare("SELECT loaned_quantity FROM material_stock_totals").get().loaned_quantity,2);
 await store.returnReaderCopy(db,actor,{requestId:crypto.randomUUID(),circulationId:issue.id,expectedCirculationVersion:1,expectedCopyVersion:3,returnLocationId:store.SOURCE_LOCATION,condition:"good",returnedAt:"2026-09-07",confirmation:"RETURN_THIS_COPY"});assert.equal(db.sqlite.prepare("SELECT total_quantity FROM material_stock_totals").get().total_quantity,2);assert.equal(db.sqlite.prepare("SELECT quantity FROM holdings").get().quantity,1);assert.equal(db.sqlite.prepare("SELECT physical_state FROM library_copies WHERE id='copy-1'").get().physical_state,"on_shelf");
 assert.throws(()=>db.sqlite.prepare("DELETE FROM holdings WHERE material_id=?").run(start.materialId),/tracked_stock_conflict/);assert.throws(()=>db.sqlite.exec("UPDATE library_copies SET registration='unreconciled' WHERE id='copy-1'"),/tracked_stock_conflict/);assert.throws(()=>db.sqlite.exec("UPDATE materials SET status='archived'"),/tracked_stock_conflict/);
}finally{db.sqlite.close();}});
test("reader or copy race rolls back issue, command and all quantities",async()=>{const db=setup();try{await store.activateImportedEdition(db,actor,activation());db.beforeBatch=()=>db.sqlite.exec("UPDATE library_readers SET version=version+1 WHERE id='reader-b'");const requestId=crypto.randomUUID();await assert.rejects(store.issueReaderCopy(db,actor,{requestId,copyId:"copy-1",expectedCopyVersion:2,readerId:"reader-b",expectedReaderVersion:1,issuedAt:"2026-09-06",dueAt:"2026-09-20",confirmation:"ISSUE_THIS_COPY"}));assert.equal(db.sqlite.prepare("SELECT count(*) n FROM mutation_commands WHERE id=?").get(requestId).n,0);assert.equal(db.sqlite.prepare("SELECT quantity FROM holdings").get().quantity,1);assert.equal(db.sqlite.prepare("SELECT count(*) n FROM reader_circulations").get().n,1);}finally{db.sqlite.close();}});
