import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {Miniflare} from 'miniflare';
import {saveLibraryEdition} from '../lib/library-editor.ts';
import {registerLibraryCopy,issueReaderCopy,returnReaderCopy} from '../lib/library-copy-store.ts';
import {saveLibraryReader} from '../lib/library-reader-admin.ts';
import {applyLibrarikaMemberSync,librarikaMemberSyncStatus,previewLibrarikaMemberSync,stageLibrarikaMemberSync,startLibrarikaMemberSync} from '../lib/librarika-member-sync.ts';
import {canonicalLibrarikaMemberDataset} from '../lib/librarika-member-format.ts';
import {recordScheduledHeartbeat} from '../lib/worker-schedule.ts';

test('reader copy receipt, stock guards and return execute on actual workerd D1',async()=>{
 const sqlite=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(name=>/^\d{4}_.*\.sql$/.test(name)).sort())sqlite.exec(fs.readFileSync('drizzle/'+file,'utf8'));const schema=sqlite.prepare("SELECT type,name,sql FROM sqlite_schema WHERE sql IS NOT NULL AND name NOT GLOB 'sqlite_*'").all();sqlite.close();
 const mf=new Miniflare({modules:true,script:"export default {fetch(){return new Response('reader D1 local test')}}",compatibilityDate:'2026-05-22',d1Databases:['DB']});
 try{const db=await mf.getD1Database('DB');for(const type of ['table','index','view','trigger'])for(const item of schema.filter(item=>item.type===type&&!/^materials_fts_/.test(item.name)))await db.prepare(item.sql).run();
 await db.prepare("INSERT INTO users(id,full_name,sort_name,email,role,status,created_at,updated_at) VALUES('admin','Admin','admin','admin@example.test','admin','active','2026-09-06','2026-09-06')").run();await db.prepare("INSERT INTO library_readers(id,member_no,full_name,sort_name,kind,status,access_status,created_at,updated_at) VALUES('reader','1','Читач','читач','student','active','inactive','2026-09-06','2026-09-06')").run();await db.prepare("INSERT INTO locations(id,name,type,status,created_at,updated_at) VALUES('loc','Бібліотека','library','active','2026-09-06','2026-09-06')").run();const actor={id:'admin',email:'admin@example.test'};
 const book=await saveLibraryEdition(db,actor,{requestId:crypto.randomUUID(),title:'Книга',metadata:{author:'Автор'},entityIds:[],published:true});const copy=await registerLibraryCopy(db,actor,{requestId:crypto.randomUUID(),editionId:book.id,expectedEditionVersion:1,accessionNo:'001',copyNo:'1',locationId:'loc',condition:'good'});const input={requestId:crypto.randomUUID(),copyId:copy.id,expectedCopyVersion:1,readerId:'reader',expectedReaderVersion:1,issuedAt:'2026-09-06',dueAt:'2026-09-20',confirmation:'ISSUE_THIS_COPY'},loan=await issueReaderCopy(db,actor,input);assert.equal((await issueReaderCopy(db,actor,input)).id,loan.id);assert.equal((await db.prepare('SELECT count(*) n FROM holdings').first()).n,0);await returnReaderCopy(db,actor,{requestId:crypto.randomUUID(),circulationId:loan.id,expectedCirculationVersion:1,expectedCopyVersion:2,returnLocationId:'loc',condition:'good',returnedAt:'2026-09-07',confirmation:'RETURN_THIS_COPY'});assert.equal((await db.prepare('SELECT total_quantity FROM material_stock_totals').first()).total_quantity,1);assert.equal((await db.prepare('SELECT count(*) n FROM library_copy_movements').first()).n,3);await assert.rejects(db.prepare('DELETE FROM holdings').run());assert.equal((await db.prepare('PRAGMA foreign_key_check').all()).results.length,0);
 }finally{await mf.dispose();}
});

test('reader allocation and frozen Librarika preview execute on actual workerd D1',async()=>{
 const sqlite=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(name=>/^\d{4}_.*\.sql$/.test(name)).sort())sqlite.exec(fs.readFileSync('drizzle/'+file,'utf8'));const schema=sqlite.prepare("SELECT type,name,sql FROM sqlite_schema WHERE sql IS NOT NULL AND name NOT GLOB 'sqlite_*'").all();sqlite.close();
 const mf=new Miniflare({modules:true,script:"export default {fetch(){return new Response('reader sync D1 local test')}}",compatibilityDate:'2026-05-22',d1Databases:['DB']});
 try{const db=await mf.getD1Database('DB');for(const type of ['table','index','view','trigger'])for(const item of schema.filter(item=>item.type===type&&!/^materials_fts_/.test(item.name)))await db.prepare(item.sql).run();
 await db.prepare("INSERT INTO users(id,full_name,sort_name,email,role,status,created_at,updated_at) VALUES('admin','Admin','admin','admin@example.test','admin','active','2026-09-08','2026-09-08')").run();const actor={id:'admin',email:'admin@example.test'};
 await assert.rejects(saveLibraryReader(db,actor,{requestId:crypto.randomUUID(),fullName:'Учень До Звірки',kind:'student',classYearId:null}),error=>error?.code==='reader_baseline_required');
 const rows=[{Id:'990',"Member No":'27000990',Name:'Учень Із Librarika',"Member Group":'7-А',Status:'Active'}],{sourceSha256}=await canonicalLibrarikaMemberDataset(rows);const started=await startLibrarikaMemberSync(db,actor,{requestId:crypto.randomUUID(),sourceSha256,expectedRows:1});await stageLibrarikaMemberSync(db,actor,{runId:started.runId,sourceSha256,partIndex:0,rows});await previewLibrarikaMemberSync(db,actor,{runId:started.runId,sourceSha256});
 await assert.rejects(stageLibrarikaMemberSync(db,actor,{runId:started.runId,sourceSha256,partIndex:1,rows:[{...rows[0],Id:'991',"Member No":'27000991'}]}));await applyLibrarikaMemberSync(db,actor,{runId:started.runId,sourceSha256,confirmation:'APPLY_MEMBERS_WITHOUT_DELETIONS',fullBaselineConfirmation:'THIS_IS_FULL_MEMBERS_EXPORT'});assert.equal((await db.prepare("SELECT member_no FROM library_readers WHERE source_member_id='990'").first()).member_no,'27000990');
 const first=await saveLibraryReader(db,actor,{requestId:crypto.randomUUID(),fullName:'Перший Учень',kind:'student',classYearId:null});const second=await saveLibraryReader(db,actor,{requestId:crypto.randomUUID(),fullName:'Другий Учень',kind:'student',classYearId:null});assert.equal(first.memberNo,'27000991');assert.equal(second.memberNo,'27000992');assert.equal((await db.prepare('PRAGMA foreign_key_check').all()).results.length,0);
 }finally{await mf.dispose();}
});

test('0051 through 0054 migrate an existing workerd D1 database statement by statement',async()=>{
 const sqlite=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(name=>/^\d{4}_.*\.sql$/.test(name)&&Number(name.slice(0,4))<=50).sort())sqlite.exec(fs.readFileSync('drizzle/'+file,'utf8'));const schema=sqlite.prepare("SELECT type,name,sql FROM sqlite_schema WHERE sql IS NOT NULL AND name NOT GLOB 'sqlite_*'").all();sqlite.close();
 const mf=new Miniflare({modules:true,script:"export default {fetch(){return new Response('migration test')}}",compatibilityDate:'2026-05-22',d1Databases:['DB']});
 try{const db=await mf.getD1Database('DB');for(const type of ['table','index','view','trigger'])for(const item of schema.filter(item=>item.type===type&&!/^materials_fts_/.test(item.name)))await db.prepare(item.sql).run();
 const applyMigration=async name=>{for(const source of fs.readFileSync('drizzle/'+name,'utf8').split('--> statement-breakpoint')){const sql=source.trim();if(sql)await db.prepare(sql).run();}};
 await applyMigration('0051_blushing_liz_osborn.sql');await applyMigration('0052_free_senator_kelly.sql');
 await db.prepare("INSERT INTO users(id,full_name,sort_name,email,role,status,created_at,updated_at) VALUES('admin','Admin','admin','admin@example.test','admin','active','2026-09-08','2026-09-08')").run();
 for(const [id,status,lease] of [['pending','pending',false],['processing','processing',true],['retry','retry',false],['sent','sent',false]])await db.prepare(`INSERT INTO telegram_delivery_outbox
   (id,recipient_user_id,dedupe_key,category,type,title,message,target_path,entity_type,entity_id,status,attempts,next_attempt_at,lease_token,lease_expires_at,sent_at,created_at,updated_at)
   VALUES (?,'admin',?,'orders','material_request_prepare_reminder','Відкликане нагадування','Не надсилати','/librarian/orders','material_request','MRQ-MIGRATION',?,0,'2099-01-01T00:00:00.000Z',?,?,?,'2026-09-08','2026-09-08')`).bind('TGO-MIG-'+id,'migration-'+id,status,lease?'lease':null,lease?'2099-01-01T00:00:00.000Z':null,status==='sent'?'2026-09-08':null).run();
 await applyMigration('0053_familiar_puff_adder.sql');await applyMigration('0054_worker_schedule_status.sql');
 assert.ok((await db.prepare("PRAGMA table_info('librarika_member_sync_rows')").all()).results.some(row=>row.name==='candidate_version'));assert.ok((await db.prepare("PRAGMA table_info('librarika_member_sync_rows')").all()).results.some(row=>row.name==='conflict_reason'));assert.ok((await db.prepare("PRAGMA table_info('librarika_member_sync_runs')").all()).results.some(row=>row.name==='is_full_baseline'));assert.ok((await db.prepare("PRAGMA index_list('reader_platform_links')").all()).results.some(row=>row.name==='idx_reader_platform_member_number'));
 assert.deepEqual((await db.prepare("SELECT status,lease_token,lease_expires_at,last_error_code FROM telegram_delivery_outbox WHERE id='TGO-MIG-processing'").first()),{status:'dead',lease_token:null,lease_expires_at:null,last_error_code:'pickup_reminders_withdrawn'});assert.equal((await db.prepare("SELECT COUNT(*) n FROM telegram_delivery_outbox WHERE id IN ('TGO-MIG-pending','TGO-MIG-processing','TGO-MIG-retry') AND status='dead'").first()).n,3);assert.equal((await db.prepare("SELECT status FROM telegram_delivery_outbox WHERE id='TGO-MIG-sent'").first()).status,'sent');
 await recordScheduledHeartbeat(db,new Date('2026-09-08T01:17:00.000Z'),new Date('2026-09-08T01:17:03.000Z'));await recordScheduledHeartbeat(db,new Date('2026-09-08T01:16:00.000Z'),new Date('2026-09-08T01:18:03.000Z'));assert.deepEqual((await db.prepare("SELECT scheduled_at,observed_at FROM worker_schedule_status WHERE id='minute'").first()),{scheduled_at:'2026-09-08T01:17:00.000Z',observed_at:'2026-09-08T01:17:03.000Z'});assert.deepEqual((await librarikaMemberSyncStatus(db)).worker,{scheduled_at:'2026-09-08T01:17:00.000Z',observed_at:'2026-09-08T01:17:03.000Z'});assert.equal((await db.prepare('PRAGMA foreign_key_check').all()).results.length,0);
 }finally{await mf.dispose();}
});
