import test from 'node:test';
import assert from 'node:assert/strict';
import {readerDatabase,actor} from './helpers/reader-database.mjs';
const admin=await import('../lib/literature-admin.ts'),editor=await import('../lib/library-editor.ts'),copies=await import('../lib/library-copy-store.ts');
const request=fields=>({requestId:crypto.randomUUID(),...fields});
const source=await import('../lib/literature-source-refresh.ts');
const url=query=>new URL('https://local.test/?'+query);

test('inline name reused after a dictionary rename creates the intended new entity',async()=>{
 const {db}=await fixture();try{
  const first=await editor.saveLibraryEdition(db,actor,request({title:'Перша',metadata:{},entityIds:[],entityNames:{author:['Автор А']},published:true}));
  const entity=(await admin.literatureBook(db,first.id)).entities[0];
  await admin.saveLiteratureEntity(db,actor,request({id:entity.id,expectedVersion:1,kind:'author',name:'Автор Б',metadata:{}}));
  const second=await editor.saveLibraryEdition(db,actor,request({title:'Друга',metadata:{},entityIds:[],entityNames:{author:['Автор А']},published:true}));
  const current=(await admin.literatureBook(db,second.id)).entities[0];assert.equal(current.name,'Автор А');assert.notEqual(current.id,entity.id);
  assert.equal((await admin.literatureBook(db,first.id)).metadata.author,'Автор Б');
 }finally{db.sqlite.close();}
});

test('independent catalogue suggestions preserve relations, allow new names and combine filters',async()=>{
 const {db}=await fixture();try{
  const input=request({title:'Каталог підказок',metadata:{year:'2026'},entityIds:[],entityNames:{author:['Леся Українка'],genre:['Поезія'],publisher:['Видавець'],tag:['Класика']},published:true});
  const saved=await editor.saveLibraryEdition(db,actor,input);assert.equal((await editor.saveLibraryEdition(db,actor,input)).id,saved.id);
  const book=await admin.literatureBook(db,saved.id);assert.equal(book.entities.length,4);assert.equal(book.metadata.author,'Леся Українка');assert.equal(book.metadata.tags,'Класика');
  const params=new URLSearchParams({author:'леся',category:'поезія',publisher:'Видавець',tag:'класика'});assert.equal((await admin.literatureBooks(db,url(params))).total,1);
  params.set('tag','Інший');assert.equal((await admin.literatureBooks(db,url(params))).total,0);
  await editor.saveLibraryEdition(db,actor,request({...input,requestId:crypto.randomUUID(),title:'Друга книга'}));assert.equal(db.sqlite.prepare("SELECT count(*) n FROM library_catalog_entities WHERE name='Леся Українка'").get().n,1);
  const author=book.entities.find(x=>x.kind==='author');await admin.saveLiteratureEntity(db,actor,request({id:author.id,expectedVersion:1,kind:'author',name:author.name,metadata:{country:'UA'}}));
  assert.equal((await admin.literatureBooks(db,url('country=UKR'))).total,2);assert.equal((await admin.literatureBooks(db,url('country=GB'))).total,0);
  const options=await admin.literatureOptions(db);assert.ok(options.years.includes('2026'));assert.equal(options.entities.find(x=>x.id===author.id).countryLabel,'Україна');
 }finally{db.sqlite.close();}
});

test('country labels use Ukrainian full names and explicit class aliases are not a global transliteration',async()=>{
 const labels=await import('../lib/literature-labels.ts'),classes=await import('../lib/literature-class-alignment.ts');
 assert.equal(labels.countryLabel('USA'),'Сполучені Штати');assert.equal(labels.countryLabel('GB'),'Велика Британія');assert.equal(labels.countryCode('Україна'),'UA');
 assert.equal(classes.sourceClassName('1-B'),'1-В');assert.equal(classes.sourceClassName('1-C'),'1-С');assert.equal(classes.sourceClassName('2-B'),'2-B');assert.equal(classes.sourceClassName('5-IT1'),'5-IT(1)');
});
test('a source book resumes after a lost completion receipt without a second copy',async()=>{const {db}=await fixture();try{const input=request({kind:'book',sourceId:'901',title:'Нова книга',entities:{},metadata:{author:'Автор'},sourceRow:{Id:'901',Title:' Нова книга'},copy:{sourceId:'902',accessionNo:'NEW-1',copyNo:'1',sourceRow:{Id:'902','Accession No':'NEW-1'}}});const batch=db.batch.bind(db);let n=0;db.batch=async statements=>{if(++n===5)throw Error('Interrupted before final receipt');return batch(statements);};await assert.rejects(source.applyLiteratureSourceItem(db,actor,input));db.batch=batch;const result=await source.applyLiteratureSourceItem(db,actor,input);assert.equal((await source.applyLiteratureSourceItem(db,actor,input)).id,result.id);assert.equal(db.sqlite.prepare("SELECT count(*) n FROM library_editions WHERE source_media_id='901'").get().n,1);assert.equal(db.sqlite.prepare("SELECT count(*) n FROM library_copies WHERE source_copy_id='902'").get().n,1);}finally{db.sqlite.close();}});
test('source reservation promotion resumes atomically after stock changed but provenance was not saved',async()=>{const {db,book,copy}=await fixture();try{db.sqlite.prepare('UPDATE library_editions SET source_media_id=? WHERE id=?').run('700',book.id);db.sqlite.prepare('UPDATE library_copies SET source_copy_id=? WHERE id=?').run('701',copy.id);db.sqlite.exec("UPDATE library_readers SET source_member_id='702' WHERE id='reader-a'");const reservation=await admin.reserveLiteratureCopy(db,actor,request({copyId:copy.id,expectedCopyVersion:1,readerId:'reader-a',expectedReaderVersion:1,issuedAt:'2026-09-01',dueAt:'2026-09-08'})),prior={ID:'703','Media ID':'700','ASN No':'LIT-TEST','Member No':'reader-a','Booking Date':'2026-09-01','Return Date':'2026-09-08',Status:'Reserved'};db.sqlite.prepare('UPDATE reader_circulations SET source_circulation_id=?,source_json=? WHERE id=?').run('703',JSON.stringify(prior),reservation.id);const input=request({kind:'loan',sourceId:'703',sourceCopyId:'701',sourceMemberId:'702',expectedVersion:1,expectedCopyVersion:1,expectedReaderVersion:1,previousSourceRow:prior,sourceRow:{...prior,Status:'Issued','Issued At':'2026-09-02'}}),batch=db.batch.bind(db);let n=0;db.batch=async statements=>{if(++n===3)throw Error('Interrupted before provenance');return batch(statements);};await assert.rejects(source.applyLiteratureSourceItem(db,actor,input));db.batch=batch;const result=await source.applyLiteratureSourceItem(db,actor,input);assert.equal(result.id,reservation.id);assert.equal((await source.applyLiteratureSourceItem(db,actor,input)).id,result.id);assert.equal(db.sqlite.prepare("SELECT count(*) n FROM reader_circulations WHERE status='issued'").get().n,1);assert.equal(db.sqlite.prepare('SELECT total_quantity,loaned_quantity FROM material_stock_totals WHERE material_id=?').get(book.materialId).loaned_quantity,1);}finally{db.sqlite.close();}});
test('historical returned source loans preserve missing return dates and never perform a new checkout',async()=>{const {db,book,copy}=await fixture();try{db.sqlite.prepare('UPDATE library_editions SET source_media_id=? WHERE id=?').run('710',book.id);db.sqlite.prepare('UPDATE library_copies SET source_copy_id=? WHERE id=?').run('711',copy.id);db.sqlite.exec("UPDATE library_readers SET source_member_id='712' WHERE id='reader-a'");const result=await source.applyLiteratureSourceItem(db,actor,request({kind:'loan',sourceId:'713',sourceCopyId:'711',sourceMemberId:'712',expectedCopyVersion:1,expectedReaderVersion:1,sourceRow:{ID:'713','Media ID':'710','ASN No':'LIT-TEST','Member No':'reader-a','Booking Date':'2026-09-01','Return Date':'2026-09-08','Received At':'',Status:'Returned'}}));assert.equal(db.sqlite.prepare('SELECT received_at FROM reader_circulations WHERE id=?').get(result.id).received_at,null);assert.equal(db.sqlite.prepare("SELECT count(*) n FROM library_copy_movements WHERE kind IN ('issue','return')").get().n,0);assert.equal((await admin.literatureBook(db,book.id)).available,1);}finally{db.sqlite.close();}});
async function fixture(){const db=readerDatabase();db.sqlite.exec("INSERT INTO locations(id,name,type,status,created_at,updated_at) VALUES('LOC-LRK-MAIN','Лібраріка','library','active','2026-09-10','2026-09-10');");const book=await editor.saveLibraryEdition(db,actor,request({title:'Книга для перевірки',metadata:{author:'Автор',type:'Книга'},entityIds:[],published:true}));const copy=await copies.registerLibraryCopy(db,actor,request({editionId:book.id,expectedEditionVersion:1,accessionNo:'LIT-TEST',copyNo:'1',locationId:copies.SOURCE_LOCATION,condition:'good'}));return {db,book,copy};}
test('catalogue, stock, dashboard and XLSX work over native literature records',async()=>{const {db,book,copy}=await fixture();try{assert.equal((await admin.literatureBook(db,book.id)).available,1);const reserved=await admin.reserveLiteratureCopy(db,actor,request({copyId:copy.id,expectedCopyVersion:1,readerId:'reader-a',expectedReaderVersion:1,issuedAt:'2026-09-01',dueAt:'2026-09-08'}));assert.equal((await admin.literatureBook(db,book.id)).available,0);assert.equal(db.sqlite.prepare('SELECT quantity FROM holdings').get().quantity,1);await assert.rejects(copies.issueReaderCopy(db,actor,request({copyId:copy.id,expectedCopyVersion:1,readerId:'reader-b',expectedReaderVersion:1,issuedAt:'2026-09-01',dueAt:'2026-09-08',confirmation:'ISSUE_THIS_COPY'})));
 const issueInput=request({copyId:copy.id,expectedCopyVersion:1,readerId:'reader-a',expectedReaderVersion:1,issuedAt:'2026-09-01',dueAt:'2026-09-08',reservationId:reserved.id,expectedReservationVersion:1,confirmation:'ISSUE_THIS_COPY'});const loan=await copies.issueReaderCopy(db,actor,issueInput);assert.equal((await copies.issueReaderCopy(db,actor,issueInput)).id,loan.id);assert.equal((await admin.literatureLoans(db,url('status=overdue'))).total,1);const dash=await admin.literatureDashboard(db,url('from=2026-09-01&to=2026-09-30'));assert.equal(dash.stats.copies,1);assert.equal(dash.stats.overdue,1);assert.equal(dash.activity[0].students,1);const reader=(await admin.literatureReaders(db,url(''))).items.find(r=>r.id==='reader-a');assert.equal(reader.overdue_count,1);assert.equal(JSON.parse(reader.active_books)[0].overdue,1);const excel=await admin.literatureReaderExcel(db,url('reader=reader-a&status=all'));assert.equal(Buffer.from(excel).subarray(0,2).toString(),'PK');
 await assert.rejects(admin.archiveLiteratureRecord(db,actor,request({kind:'reader',id:'reader-a',expectedVersion:1})));await assert.rejects(admin.archiveLiteratureRecord(db,actor,request({kind:'edition',id:book.id,expectedVersion:1})));
 await copies.returnReaderCopy(db,actor,request({circulationId:loan.id,expectedCirculationVersion:2,expectedCopyVersion:2,returnLocationId:copies.SOURCE_LOCATION,condition:'good',returnedAt:'2026-09-10',confirmation:'RETURN_THIS_COPY'}));assert.equal((await admin.literatureBook(db,book.id)).available,1);assert.equal((await admin.literatureLoans(db,url('status=issued'))).total,0);assert.equal(db.sqlite.prepare('SELECT total_quantity FROM material_stock_totals WHERE material_id=?').get(book.materialId).total_quantity,1);assert.equal(db.sqlite.prepare('PRAGMA foreign_key_check').all().length,0);
 }finally{db.sqlite.close();}});
test('new readers get unique numbers without enabling login or teacher linking, retries are idempotent',async()=>{const db=readerDatabase();try{const input=request({fullName:'Перевірочний Читач',kind:'student',phone:'+380991234567',groupLabel:'7-А'});const a=await admin.saveLiteratureReader(db,actor,input);assert.equal((await admin.saveLiteratureReader(db,actor,input)).id,a.id);const b=await admin.saveLiteratureReader(db,actor,{...input,requestId:crypto.randomUUID(),fullName:'Інший Читач'});const first=await admin.literatureReader(db,a.id),second=await admin.literatureReader(db,b.id);assert.notEqual(first.member_no,second.member_no);assert.equal(first.access_status,'inactive');assert.equal(first.linked_teacher_user_id,null);assert.equal(first.phone,input.phone);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM reader_invites').get().n,0);await admin.archiveLiteratureRecord(db,actor,request({kind:'reader',id:a.id,expectedVersion:1}));assert.equal((await admin.literatureReader(db,a.id)).status,'inactive');await admin.archiveLiteratureRecord(db,actor,request({kind:'reader',id:a.id,expectedVersion:2,restore:true}));assert.equal((await admin.literatureReader(db,a.id)).status,'active');}finally{db.sqlite.close();}});
test('dictionary rename immediately changes book fields, search and ordering',async()=>{const {db,book}=await fixture();try{const entity=await admin.saveLiteratureEntity(db,actor,request({kind:'author',name:'Старий Автор',metadata:{biography:'Біографія'}}));await editor.saveLibraryEdition(db,actor,request({id:book.id,expectedVersion:1,expectedMaterialVersion:1,title:'Книга для перевірки',metadata:{author:'Старий Автор'},entityIds:[entity.id],published:true}));await admin.saveLiteratureEntity(db,actor,request({id:entity.id,expectedVersion:1,kind:'author',name:'Новий Письменник',metadata:{}}));assert.equal((await admin.literatureBook(db,book.id)).metadata.author,'Новий Письменник');assert.equal((await admin.literatureBooks(db,url('q='+encodeURIComponent('новий письменник')))).items[0].id,book.id);assert.equal((await admin.literatureEntities(db,url('kind=author&id='+entity.id))).items[0].name,'Новий Письменник');await assert.rejects(admin.archiveLiteratureRecord(db,actor,request({kind:'entity',id:entity.id,expectedVersion:2})));}finally{db.sqlite.close();}});
test('education IDs are rejected and duplicate ISBN across independent funds is allowed',async()=>{const db=readerDatabase();try{db.sqlite.exec("INSERT INTO materials(id,catalog_number,title,sort_title,search_text,isbn_normalized,status,created_at,updated_at) VALUES('CAT-9000',9000,'Підручник','підручник','підручник','9786170953858','active','2026-09-01','2026-09-01'); INSERT INTO library_editions(id,material_id,fund,title,publication_state,created_at,updated_at) VALUES('education','CAT-9000','education','Підручник','published','2026-09-01','2026-09-01');");const before=db.sqlite.prepare("SELECT * FROM materials WHERE id='CAT-9000'").get();await assert.rejects(admin.literatureBook(db,'education'),e=>e.code==='literature_only');await assert.rejects(admin.archiveLiteratureRecord(db,actor,request({kind:'edition',id:'education',expectedVersion:1})),e=>e.code==='literature_only');await assert.rejects(editor.saveLibraryEdition(db,actor,request({id:'education',expectedVersion:1,expectedMaterialVersion:1,title:'Зміна',metadata:{},entityIds:[],published:true})));await editor.saveLibraryEdition(db,actor,request({title:'Хрестоматія окремого фонду',metadata:{isbn13:'9786170953858'},entityIds:[],published:true}));assert.deepEqual(db.sqlite.prepare("SELECT * FROM materials WHERE id='CAT-9000'").get(),before);assert.ok(!(await admin.literatureBooks(db,url(''))).items.some(x=>x.id==='education'));}finally{db.sqlite.close();}});
test('reservation and return concurrency cannot silently change stock',async()=>{const {db,copy}=await fixture();try{const input=request({copyId:copy.id,expectedCopyVersion:1,readerId:'reader-a',expectedReaderVersion:1,issuedAt:'2026-09-01',dueAt:'2026-09-08'});const reservation=await admin.reserveLiteratureCopy(db,actor,input);assert.equal((await admin.reserveLiteratureCopy(db,actor,input)).id,reservation.id);await assert.rejects(admin.reserveLiteratureCopy(db,actor,{...input,requestId:crypto.randomUUID()}));await admin.cancelLiteratureReservation(db,actor,request({id:reservation.id,expectedVersion:1}));assert.equal(db.sqlite.prepare('SELECT quantity FROM holdings').get().quantity,1);assert.equal((await admin.literatureBook(db,copy.editionId)).available,1);}finally{db.sqlite.close();}});
test('invalid dates and inherited sort keys are rejected before querying',async()=>{const db=readerDatabase();try{assert.throws(()=>admin.literatureDate('2026-02-30'));await assert.rejects(admin.literatureBooks(db,url('sort=toString')),e=>e.code==='sort');await assert.rejects(admin.literatureLoans(db,url('sort=constructor')),e=>e.code==='loan_filter');await assert.rejects(admin.literatureDashboard(db,url('from=2024-01-01&to=2026-09-11')),e=>e.code==='period');}finally{db.sqlite.close();}});
