import test from 'node:test';
import assert from 'node:assert/strict';
import {readerDatabase,publishReaderFixture} from './helpers/reader-database.mjs';
const notifications=await import('../lib/reader-notifications.ts');
const now='2026-09-06T08:00:00.000Z';
function fixture(count=1){const db=readerDatabase();publishReaderFixture(db);db.sqlite.exec("UPDATE library_readers SET access_status='active'; INSERT INTO reader_profiles(reader_id,display_name,notify_loans,notify_loans_since,notify_books,notify_books_since,updated_at) VALUES('reader-a','Читач',1,'2026-09-06',1,'2026-09-06T07:00:00Z','2026-09-06'); INSERT INTO reader_telegram_connections(telegram_user_id,reader_id,chat_id,linked_at) VALUES('100','reader-a','100','2026-09-06'); INSERT INTO locations(id,name,type,status,created_at,updated_at) VALUES('loc','Бібліотека','library','active','2026-09-06','2026-09-06');");for(let i=0;i<count;i++){db.sqlite.prepare("INSERT INTO library_copies(id,edition_id,accession_no,location_id,registration,physical_state,created_at,updated_at) VALUES(?,'edition',?,'loc','registered','on_loan',?,?)").run('copy-'+i,String(i),now,now);db.sqlite.prepare("INSERT INTO reader_circulations(id,copy_id,reader_id,status,issued_at,due_at,accounting_mode,created_at,updated_at) VALUES(?,?,'reader-a','issued','2026-09-01','2026-09-09','native',?,?)").run('loan-'+i,'copy-'+i,now,now);}return db;}
test('opt-in floor excludes past source debts and queue advances beyond the first twenty',async()=>{const db=fixture(26);try{db.sqlite.exec("UPDATE reader_circulations SET due_at='2026-09-05' WHERE id='loan-25'");await notifications.queueReaderNotifications(db,now);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM reader_notification_outbox').get().n,20);await notifications.queueReaderNotifications(db,now);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM reader_notification_outbox').get().n,25);await notifications.queueReaderNotifications(db,now);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM reader_notification_outbox').get().n,25);assert.equal(db.sqlite.prepare("SELECT count(*) n FROM reader_notification_outbox WHERE circulation_id='loan-25'").get().n,0);}finally{db.sqlite.close();}});
test('Kyiv consent day does not notify debts overdue before midnight consent',async()=>{const db=fixture();try{db.sqlite.exec("UPDATE reader_circulations SET due_at='2026-09-05'");await notifications.queueReaderNotifications(db,'2026-09-05T22:00:00.000Z');assert.equal(db.sqlite.prepare('SELECT count(*) n FROM reader_notification_outbox').get().n,0);assert.throws(()=>db.sqlite.exec("UPDATE reader_profiles SET notify_loans_since='2026-09-05T21:30:00Z'"),/CHECK/);}finally{db.sqlite.close();}});
test('delivery rechecks current loan version and preferences instead of sending a stale reminder',async()=>{const db=fixture(2);try{await notifications.queueReaderNotifications(db,now);db.sqlite.exec("UPDATE reader_circulations SET version=version+1 WHERE id='loan-0'");let sent=0;const fetcher=async()=>{sent++;return Response.json({ok:true,result:{message_id:1}});};const result=await notifications.drainReaderNotifications(db,{botToken:'test-token',now,fetcher});assert.equal(result.cancelled,1);assert.equal(sent,1);assert.equal((await notifications.drainReaderNotifications(db,{botToken:'test-token',now,fetcher})).attempted,0);}finally{db.sqlite.close();}});
test('rate limits retry but an ambiguous network delivery is not automatically duplicated',async()=>{const db=fixture();try{await notifications.queueReaderNotifications(db,now);await notifications.drainReaderNotifications(db,{botToken:'test-token',now,fetcher:async()=>{throw new Error('network unavailable');}});assert.equal(db.sqlite.prepare('SELECT status FROM reader_notification_outbox').get().status,'failed');await notifications.queueReaderNotifications(db,now);assert.equal((await notifications.drainReaderNotifications(db,{botToken:'test-token',now,fetcher:async()=>{throw new Error('must not send twice');}})).attempted,0);}finally{db.sqlite.close();}});
