import test from 'node:test';
import assert from 'node:assert/strict';
import {readerDatabase,publishReaderFixture,actor,readerRequest} from './helpers/reader-database.mjs';
const auth=await import('../lib/reader-auth.ts'),community=await import('../lib/reader-community.ts');
async function fixture(){const db=readerDatabase();publishReaderFixture(db);const ids=[];for(const id of ['reader-a','reader-b']){const invite=await auth.issueReaderInvite(db,actor,{readerId:id,purpose:'web',expectedVersion:1});const login=await auth.redeemReaderInvite(db,invite.token);ids.push(await auth.requireReaderSession(db,readerRequest(login.token)));}db.sqlite.exec("UPDATE reader_profiles SET community_enabled=1");return {db,a:ids[0],b:ids[1]};}
const create=(db,a,kind='group',extra={})=>community.createReadingThread(db,a,{requestId:crypto.randomUUID(),kind,title:kind==='group'?'Читацька група':'',...extra});
test('book-specific discussions and card attachments stay in Librarika',async()=>{const {db,a}=await fixture();try{await assert.rejects(create(db,a,'book',{editionId:'edition'}),(error)=>error?.code==='librarika_authoritative'&&error?.status===410);const t=await create(db,a);await assert.rejects(community.joinBookDiscussion(db,a,{requestId:crypto.randomUUID(),threadId:t.id}),(error)=>error?.code==='librarika_authoritative'&&error?.status===410);await assert.rejects(community.sendReadingMessage(db,a,{requestId:crypto.randomUUID(),threadId:t.id,body:'Картка',editionId:'edition'}),(error)=>error?.code==='librarika_authoritative'&&error?.status===410);assert.equal(db.sqlite.prepare("SELECT count(*) n FROM reading_threads WHERE kind='book'").get().n,0);assert.equal(db.sqlite.prepare("SELECT count(*) n FROM reading_messages").get().n,0);}finally{db.sqlite.close();}});
test('direct chat requires acceptance and blocking prevents new messages',async()=>{const {db,a,b}=await fixture();try{const t=await create(db,a,'direct',{recipientId:b.readerId});await assert.rejects(community.sendReadingMessage(db,a,{requestId:crypto.randomUUID(),threadId:t.id,body:'До згоди'}));await assert.rejects(community.getReadingMessages(db,b,t.id));await community.respondReadingInvite(db,b,{requestId:crypto.randomUUID(),threadId:t.id,accept:true});const input={requestId:crypto.randomUUID(),threadId:t.id,body:'Після згоди'};const message=await community.sendReadingMessage(db,a,input);assert.equal((await community.sendReadingMessage(db,a,input)).id,message.id);await community.blockCommunityReader(db,b,{requestId:crypto.randomUUID(),readerId:a.readerId,blocked:true});assert.equal((await community.getReadingMessages(db,b,t.id)).length,0);await assert.rejects(community.sendReadingMessage(db,a,{requestId:crypto.randomUUID(),threadId:t.id,body:'Після блокування'}));}finally{db.sqlite.close();}});
test('a removed member, closed conversation or revoked consent cannot race the message SELECT',async()=>{for(const sql of ["UPDATE reading_memberships SET status='removed' WHERE reader_id='reader-b'","UPDATE reading_threads SET status='closed'","UPDATE reader_profiles SET community_enabled=0 WHERE reader_id='reader-b'"]){const {db,a,b}=await fixture();try{const t=await create(db,a);await community.inviteReadingMember(db,a,{requestId:crypto.randomUUID(),threadId:t.id,recipientId:b.readerId});await community.respondReadingInvite(db,b,{requestId:crypto.randomUUID(),threadId:t.id,accept:true});await community.sendReadingMessage(db,a,{requestId:crypto.randomUUID(),threadId:t.id,body:'Приватне повідомлення'});const prepare=db.prepare.bind(db);db.prepare=query=>{const stmt=prepare(query);if(!query.startsWith('SELECT x.id'))return stmt;const bind=stmt.bind.bind(stmt);stmt.bind=(...values)=>{db.sqlite.exec(sql);return bind(...values);};return stmt;};assert.deepEqual(await community.getReadingMessages(db,b,t.id),[]);}finally{db.sqlite.close();}}});
test('reports require the exact visible conversation and cannot invent a message reference',async()=>{const {db,a}=await fixture();try{const t=await create(db,a);await assert.rejects(community.reportReadingMessage(db,a,{requestId:crypto.randomUUID(),threadId:t.id,messageId:'missing',reason:'Перевірити зміст'}));assert.equal(db.sqlite.prepare('SELECT count(*) n FROM reading_reports').get().n,0);}finally{db.sqlite.close();}});
