"use client";
import {useEffect,useRef,useState} from 'react';
import s from './literature.module.css';
type Plan={academicYear:string;assignments:any[];alreadyAssigned:number;excluded:{id:string;memberNo:string;fullName:string;reason:string}[];summary:{sourceGroup:string;className:string;count:number}[]};
export default function ClassAlignment({onDone,onBusy,disabled}:{onDone:()=>void;onBusy:(busy:boolean)=>void;disabled:boolean}){
 const [plan,setPlan]=useState<Plan|null>(null),[busy,setBusy]=useState(false),[completed,setCompleted]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState(''),jobs=useRef<{requestId:string;assignments:any[]}[]>([]);
 useEffect(()=>{const abort=new AbortController();fetch('/api/librarian/literature?view=class_plan',{signal:abort.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok||!d.success)throw Error(d.error||'Не вдалося звірити класи.');setPlan(d.result);jobs.current=[];for(let i=0;i<d.result.assignments.length;i+=20)jobs.current.push({requestId:crypto.randomUUID(),assignments:d.result.assignments.slice(i,i+20)});}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[]);
 async function apply(){if(!plan||busy||disabled)return;setBusy(true);onBusy(true);setError('');try{let done=0;for(const job of jobs.current){setProgress(`Призначення класів: ${done} із ${plan.assignments.length}…`);const r=await fetch('/api/librarian/literature',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'class_assign',input:job})}),d=await r.json();if(!r.ok||!d.success)throw Error(d.error||'Зміни не підтверджені. Повторіть той самий пакет.');done+=job.assignments.length;}setProgress(`Готово. Класи призначено ${done} учням. Дані входу й книги не змінено.`);setCompleted(true);onDone();}catch(e){setError((e as Error).message);}finally{setBusy(false);onBusy(false);}}
 return <>{!plan&&!error&&<p role="status">Звіряємо чинний довідник класів…</p>}{plan&&<><p>{plan.academicYear}: до призначення — {plan.assignments.length}; уже призначено — {plan.alreadyAssigned}.</p><p className={s.muted}>Лише точні відповідники з джерела. Наявний інший клас не перезаписується.</p><div className={s.chartData}><table><thead><tr><th>Librarika</th><th>Чинний клас</th><th>Учнів</th></tr></thead><tbody>{plan.summary.map(row=><tr key={row.sourceGroup}><td>{row.sourceGroup}</td><td>{row.className}</td><td>{row.count}</td></tr>)}</tbody></table></div>{plan.excluded.length>0&&<details><summary>Без автоматичного призначення: {plan.excluded.length}</summary>{plan.excluded.map(r=><p key={r.id}>{r.memberNo} · {r.fullName}: {r.reason}</p>)}</details>}<details><summary>Перелік призначень: {plan.assignments.length}</summary><div className={s.countryAuthors}>{plan.assignments.map(a=><p key={a.readerId}>{a.memberNo} · {a.fullName} → {a.className}</p>)}</div></details><button className={s.primary} type="button" disabled={busy||disabled||completed||!plan.assignments.length} onClick={apply}>Призначити перевірені класи</button></>}{progress&&<p className={s.notice} role="status">{progress}</p>}{error&&<p className={s.error} role="alert">{error}</p>}</>;
}
