"use client";
import EditionCover from "./edition-cover";
import {useEffect,useRef,useState} from "react";
import {readerFetch} from "@/app/reader/reader-types";
import s from "@/app/reader/reader.module.css";
type Entity={id:string;kind:string;name:string;public_metadata_json:string;version:number};
const FIELDS:Record<string,string>={author:"Автори (як на титулі)",publisher:"Видавництво (як на титулі)",year:"Рік",isbn:"ISBN",isbn13:"ISBN-13",issn:"ISSN",edition:"Видання",volume:"Том",language:"Мова",pages:"Сторінок",series:"Серія",genre:"Жанр (текст)",ddc:"Класифікація DDC",callNumber:"Шифр книги",type:"Тип матеріалу",coauthors:"Співавтори",editors:"Редактори",illustrators:"Ілюстратори",isbn10:"ISBN-10",asin:"ASIN",lccn:"LCCN",oclc:"OCLC",upc:"UPC",subject:"Предмет",description:"Опис",annotation:"Анотація"};
export default function EditionEditor({id,onSaved,onBusy,writesEnabled}:{id?:string;onSaved:()=>void;onBusy:(busy:boolean)=>void;writesEnabled:boolean}){
  const [cover,setCover]=useState<{materialId:string;version:number}|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[title,setTitle]=useState(""),[metadata,setMetadata]=useState<Record<string,string>>({}),[published,setPublished]=useState(true),[selected,setSelected]=useState<string[]>([]),[entities,setEntities]=useState<Entity[]>([]),[versions,setVersions]=useState({edition:0,material:0}),[entityKind,setEntityKind]=useState("author"),[entityId,setEntityId]=useState(""),[entityName,setEntityName]=useState(""),[entityMetadata,setEntityMetadata]=useState<Record<string,string>>({});
  const intent=useRef<{key:string;id:string}|null>(null);
  const loadEntities=async()=>{const data=await readerFetch<{result:Entity[]}>("/api/librarian/readers?view=entities");setEntities(data.result);return data.result;};
  useEffect(()=>{let live=true;Promise.all([loadEntities(),id?readerFetch<{result:{title:string;metadata:Record<string,unknown>;entityIds:string[];version:number;material_version:number;material_id:string;cover_version:number;publication_state:string}}>("/api/librarian/readers?view=edition&id="+encodeURIComponent(id)):Promise.resolve(null)]).then(([,data])=>{if(!live)return;if(data){setTitle(data.result.title);setCover({materialId:data.result.material_id,version:data.result.cover_version});setMetadata(Object.fromEntries(Object.keys(FIELDS).map(key=>[key,data.result.metadata[key]==null?"":String(data.result.metadata[key])])));setSelected(data.result.entityIds);setVersions({edition:data.result.version,material:data.result.material_version});setPublished(data.result.publication_state==="published");}}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[id]);
  async function mutate(action:string,input:Record<string,unknown>){if(busy||loading||!writesEnabled)return null;const key=JSON.stringify({action,input});if(intent.current?.key!==key)intent.current={key,id:crypto.randomUUID()};setBusy(true);onBusy(true);setError("");try{const data=await readerFetch<{result:{id:string}}>("/api/librarian/readers",{action,input:{...input,requestId:intent.current.id}});intent.current=null;return data.result;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);onBusy(false);}}
  function pickEntity(value:string){setEntityId(value);const entry=entities.find(e=>e.id===value);setEntityName(entry?.name||"");const source=entry?JSON.parse(entry.public_metadata_json):{};setEntityMetadata(Object.fromEntries(["biography","country","nickname","dateOfBirth","yearDied","publications","awards","website","description"].map(key=>[key,String(source[key]??(key==="dateOfBirth"?source.yearBorn:"")??"")])));}
  if(loading)return <p className={s.muted}>Завантажуємо картку й довідники…</p>;
  return <><p className={s.notice}>Опис видання й облік примірників — окремі дії. Збереження картки не додає книг до залишку.</p>{error&&<p className={s.error} role="alert">{error}</p>}<form onSubmit={async event=>{event.preventDefault();if(await mutate("edition_save",{...(id?{id,expectedVersion:versions.edition,expectedMaterialVersion:versions.material}:{}),title,metadata,entityIds:selected,published}))onSaved();}}><label className={s.field}>Назва книги<input value={title} onChange={e=>setTitle(e.target.value)} required maxLength={500}/></label><div className={s.fields} style={{marginTop:20}}>{Object.entries(FIELDS).map(([key,label])=><label className={s.field} key={key}>{label}{["description","annotation"].includes(key)?<textarea value={metadata[key]||""} onChange={e=>setMetadata(m=>({...m,[key]:e.target.value}))} maxLength={20000}/>:<input value={metadata[key]||""} onChange={e=>setMetadata(m=>({...m,[key]:e.target.value}))} maxLength={1000}/>}</label>)}</div><div className={s.fields} style={{marginTop:20}}>{[["author","Автори: фільтр і біографії"],["publisher","Видавництва: фільтр"],["genre","Жанри: фільтр"]].map(([kind,label])=><label className={s.field} key={kind}>{label}<select multiple size={5} value={selected.filter(id=>entities.find(e=>e.id===id)?.kind===kind)} onChange={e=>setSelected(prior=>[...prior.filter(id=>entities.find(e=>e.id===id)?.kind!==kind),...Array.from(e.target.selectedOptions,o=>o.value)])}>{entities.filter(e=>e.kind===kind).map(entity=><option key={entity.id} value={entity.id}>{entity.name}</option>)}</select><small>Оберіть потрібні записи; новий довідник можна додати нижче.</small></label>)}</div><label className={s.check}><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/>Показувати книгу читачам у каталозі</label><button className={s.button} disabled={busy||!writesEnabled}>Зберегти картку книги</button></form>
  {cover&&<EditionCover materialId={cover.materialId} initialVersion={cover.version} onBusy={value=>{setBusy(value);onBusy(value);}} disabled={busy||!writesEnabled}/>}
  <details className={s.notice}><summary>Автори, видавництва й жанри: додати або редагувати довідку</summary><form onSubmit={async e=>{e.preventDefault();const old=entities.find(x=>x.id===entityId),result=await mutate("entity_save",{...(old?{id:old.id,expectedVersion:old.version}:{}),kind:entityKind,name:entityName,metadata:entityMetadata});if(result){try{await loadEntities();setEntityId("");setEntityName("");setEntityMetadata({});}catch{setError("Довідку збережено. Оновіть картку, щоб отримати нові дані.");}}}}><div className={s.fields}><label className={s.field}>Тип<select value={entityKind} onChange={e=>{setEntityKind(e.target.value);pickEntity("");}}><option value="author">Автор</option><option value="publisher">Видавництво</option><option value="genre">Жанр</option></select></label><label className={s.field}>Запис<select value={entityId} onChange={e=>pickEntity(e.target.value)}><option value="">Створити новий</option>{entities.filter(e=>e.kind===entityKind).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label></div><label className={s.field}>Назва / ім’я<input value={entityName} onChange={e=>setEntityName(e.target.value)} required maxLength={300}/></label>{(entityKind==="author"?[["biography","Біографія"],["country","Країна"],["nickname","Псевдонім"],["dateOfBirth","Рік або дата народження"],["yearDied","Рік смерті"],["publications","Публікації"],["awards","Відзнаки"]]:entityKind==="publisher"?[["country","Країна"],["website","Вебсайт HTTPS"],["description","Опис"]]:[["description","Опис жанру"]]).map(([key,label])=><label className={s.field} key={key}>{label}<textarea value={entityMetadata[key]||""} maxLength={["biography","publications","awards","description"].includes(key)?20000:1000} onChange={e=>setEntityMetadata(m=>({...m,[key]:e.target.value}))}/></label>)}<button className={s.secondary} disabled={busy||!writesEnabled}>Зберегти довідку</button></form></details></>;
}
