"use client";
import {useEffect,useId,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {useDraftState} from './literature-navigation';
import {X,Plus} from 'lucide-react';
import s from './literature.module.css';
export type Choice={id:string;label:string;detail?:string};
type Props={label:string;value:string;onChange:(value:string)=>void;options?:Choice[];source?:string;onPick?:(choice:Choice)=>void;name?:string;placeholder?:string;required?:boolean;disabled?:boolean;validationMessage?:string;exclude?:string[]};
export const choiceSource=(kind:string)=>'/api/librarian/literature?view=choices&kind='+encodeURIComponent(kind);
// All relation inputs share the same focus, touch, paging and overlay behavior.
export function SuggestInput({label,value,onChange,options=[],source,onPick,name,placeholder,required=false,disabled=false,validationMessage='',exclude=[]}:Props){
 const field=useRef<HTMLInputElement>(null),list=useRef<HTMLDivElement>(null),wrap=useRef<HTMLDivElement>(null),paging=useRef(false),id=useId();
 const [open,setOpen]=useState(false),[active,setActive]=useState(-1),[take,setTake]=useState(30),[remote,setRemote]=useState<Choice[]>([]),[pages,setPages]=useState(1),[page,setPage]=useState(1),[loading,setLoading]=useState(false),[error,setError]=useState(''),[host,setHost]=useState<HTMLElement|null>(null),[search,setSearch]=useState(value),[position,setPosition]=useState({top:0,left:0,width:0,maxHeight:240});
 const tokens=value.trim().toLocaleLowerCase('uk-UA').split(/\s+/).filter(Boolean),all=(source?remote:options).filter(x=>!exclude.includes(x.id)&& (source||tokens.every(t=>(x.label+' '+(x.detail||'')).toLocaleLowerCase('uk-UA').includes(t)))),matches=source&&search!==value.trim()?[]:all.slice(0,take);
 useEffect(()=>{field.current?.setCustomValidity(validationMessage);},[validationMessage]);
 useEffect(()=>{setActive(-1);setTake(30);setPage(1);const t=setTimeout(()=>setSearch(value.trim()),180);return()=>clearTimeout(t);},[value]);
 useEffect(()=>{if(!open||!source)return;const a=new AbortController();setLoading(true);setError('');if(page===1)setRemote([]);fetch(source+'&q='+encodeURIComponent(search)+'&page='+page,{signal:a.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok||!d.success)throw Error('Не вдалося завантажити список.');return d.result;}).then(d=>{if(!a.signal.aborted){setRemote(old=>page===1?d.items:[...old,...d.items.filter((x:Choice)=>!old.some(y=>y.id===x.id))]);setPages(d.pages);}}).catch(e=>{if(!a.signal.aborted)setError(e.message);}).finally(()=>{if(!a.signal.aborted){setLoading(false);paging.current=false;}});return()=>a.abort();},[open,source,search,page]);
 useEffect(()=>{if(!open)return;setHost(field.current?.closest('dialog')||document.body);const place=()=>{const el=field.current;if(!el)return;const r=el.getBoundingClientRect(),vp=window.visualViewport,dialog=el.closest('dialog')?.getBoundingClientRect(),left=Math.max(vp?.offsetLeft||0,dialog?.left||0)+8,right=Math.min((vp?.offsetLeft||0)+(vp?.width||innerWidth),dialog?.right||innerWidth)-8,top=Math.max(vp?.offsetTop||0,dialog?.top||0)+8,bottom=Math.min((vp?.offsetTop||0)+(vp?.height||innerHeight),dialog?.bottom||innerHeight)-8,below=bottom-r.bottom,above=r.top-top,flip=below<160&&above>below,height=Math.max(44,Math.min(240,flip?above-4:below-4)),width=Math.min(r.width,right-left);setPosition({left:Math.max(left,Math.min(r.left,right-width)),top:Math.max(top,Math.min(flip?r.top-height-4:r.bottom+4,bottom-height)),width,maxHeight:height});};place();
 const outside=(e:Event)=>{const t=e.target as Node;if(!wrap.current?.contains(t)&&!list.current?.contains(t))setOpen(false);};document.addEventListener('pointerdown',outside);document.addEventListener('focusin',outside);window.addEventListener('scroll',place,true);window.addEventListener('resize',place);window.visualViewport?.addEventListener('resize',place);window.visualViewport?.addEventListener('scroll',place);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('focusin',outside);window.removeEventListener('scroll',place,true);window.removeEventListener('resize',place);window.visualViewport?.removeEventListener('resize',place);window.visualViewport?.removeEventListener('scroll',place);};},[open]);
 useEffect(()=>{if(open&&active>=0)list.current?.querySelectorAll<HTMLElement>('[role="option"]')[active]?.scrollIntoView({block:'nearest'});},[active,open]);
 const pick=(c:Choice)=>{onChange(c.label);onPick?.(c);setOpen(false);setActive(-1);};
 const more=()=>{if(take<all.length)setTake(n=>n+30);else if(source&&page<pages&&!loading&&!paging.current){paging.current=true;setTake(n=>n+30);setPage(n=>n+1);}};
 return <div ref={wrap} className={s.suggest}><label htmlFor={id}>{label}</label><div className={s.suggestInput}><input ref={field} id={id} name={name} value={value} onChange={e=>{onChange(e.target.value);setOpen(true);}} onFocus={()=>{setSearch(value.trim());setOpen(true);}} onClick={()=>setOpen(true)} placeholder={placeholder||'Оберіть або введіть…'} required={required} disabled={disabled} autoComplete="off" role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={id+'-list'} aria-activedescendant={open&&active>=0?id+'-'+active:undefined} onKeyDown={e=>{
  if(e.key==='Escape'){if(open){e.preventDefault();e.stopPropagation();}setOpen(false);}
  if(e.key==='Tab')setOpen(false);
  if((e.key==='ArrowDown'||e.key==='ArrowUp')&&matches.length){e.preventDefault();setOpen(true);setActive(i=>e.key==='ArrowDown'?(i+1)%matches.length:i<=0?matches.length-1:i-1);}
  if(e.key==='Enter'&&open){e.preventDefault();e.stopPropagation();if(active>=0)pick(matches[active]);}
 }}/>{value&&<button type="button" disabled={disabled} aria-label={`Очистити: ${label}`} onClick={()=>{onChange('');setOpen(false);setActive(-1);}}><X size={16}/></button>}</div>
 {open&&host&&createPortal(<div ref={list} id={id+'-list'} role="listbox" aria-label={label} className={s.suggestions} style={position} onScroll={e=>{const d=e.currentTarget;if(d.scrollHeight-d.scrollTop-d.clientHeight<45)more();}}>{matches.map((c,i)=><button type="button" role="option" aria-selected={i===active} id={id+'-'+i} key={c.id} onMouseDown={e=>e.preventDefault()} onClick={()=>pick(c)}><span>{c.label}</span>{c.detail&&<small>{c.detail}</small>}</button>)}{loading&&<p role="status">Завантажуємо…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&!matches.length&&<p>Нічого не знайдено.</p>}{(take<all.length||page<pages)&&<button type="button" disabled={loading} onMouseDown={e=>e.preventDefault()} onClick={more}>Показати ще</button>}</div>,host)}
 </div>;
}
export function RecordPicker({label,value,onChange,options=[],source,required=false,name,placeholder,disabled=false}:{label:string;value:Choice|null;onChange:(choice:Choice|null)=>void;options?:Choice[];source?:string;required?:boolean;name?:string;placeholder?:string;disabled?:boolean}){
 const editing=useRef(false),[query,setQuery]=useState(value?.label||'');useEffect(()=>{if(!editing.current)setQuery(value?.label||'');editing.current=false;},[value?.id,value?.label]);
 return <><input type="hidden" name={name} value={value?.id||''}/><SuggestInput label={label} value={query} onChange={v=>{editing.current=true;setQuery(v);if(value)onChange(null);}} onPick={c=>{setQuery(c.label);onChange(c);}} options={options} source={source} required={required} disabled={disabled} placeholder={placeholder} validationMessage={query&&!value?'Оберіть запис зі списку.':required&&!value?'Оберіть запис.':''}/></>;
}
export function EntityPicker({kind,label,initial,options}:{kind:string;label:string;initial:Choice[];options:Choice[]}){
 const [selected,setSelected]=useDraftState('entities:'+kind,initial),[query,setQuery]=useDraftState('entity-query:'+kind,'');
 const add=(choice:Choice)=>{setSelected(list=>list.some(x=>x.id?x.id===choice.id:x.label===choice.label)?list:[...list,choice]);setQuery('');};
 const exact=options.filter(x=>x.label.trim().toLocaleLowerCase('uk-UA')===query.trim().toLocaleLowerCase('uk-UA'));
 return <div className={s.entityPicker}><input type="hidden" name={'entities:'+kind} value={JSON.stringify(selected)}/><SuggestInput label={label} value={query} onChange={setQuery} options={options} source={choiceSource(kind)} exclude={selected.map(x=>x.id)} onPick={add} validationMessage={query.trim()?'Оберіть підказку або натисніть «Додати», щоб підтвердити назву.':''} placeholder={selected.length?'Додати ще…':'Оберіть або введіть назву…'}/>{selected.length>0&&<div className={s.chips}>{selected.map((c,i)=><span key={c.id||c.label}>{c.label}<button type="button" aria-label={`Прибрати: ${c.label}`} onClick={()=>setSelected(list=>list.filter((_,n)=>n!==i))}><X size={14}/></button></span>)}</div>}{query.trim()&&<button type="button" className={s.addValue} disabled={exact.length>1} onClick={()=>add(exact[0]||{id:'',label:query.trim()})}><Plus size={14}/>Додати «{query.trim()}»</button>}</div>;
}
