"use client";
import {createContext,useContext,useEffect,useRef,useState,type Dispatch,type ReactNode,type SetStateAction} from 'react';
import s from './literature.module.css';
type Snapshot=Record<string,any>;
type Draft={key:string;values:Map<string,any>;dirty:boolean;parent:Draft|null;fields:Map<string,{baseline:any;current:any;reset:(value:any)=>void}>};
type Layer={id:string;close:()=>void;dirty:()=>boolean;busy:()=>boolean;routed?:boolean;back?:()=>boolean;draft?:()=>Draft|null};
type FormGuard={id:string;active:()=>boolean;dirty:()=>boolean;busy:()=>boolean;save:()=>void|Promise<void>;discard:()=>void};
type Entry={index:number;route:Snapshot;layers:string[];scroll:number;positions:Record<string,number>;expanded:Record<string,boolean>};
type Nav={bind:(get:()=>Snapshot,restore:(v:Snapshot)=>void)=>()=>void;push:(url:string)=>void;request:(action:()=>void)=>void;form:(guard:FormGuard)=>()=>void;back:()=>void;complete:()=>void;hasBack:()=>boolean;layer:(layer:Layer)=>()=>void;update:()=>void;fallback:(fn:()=>void)=>()=>void};
const Navigation=createContext<Nav|null>(null),DraftContext=createContext<Draft|null>(null);
const viewState=new Map<string,any>(),drafts=new Map<string,Map<string,any>>(),liveDrafts=new Set<Draft>(),draftRegistry=new Map<string,Draft>();
const same=(a:any,b:any):boolean=>{if(Object.is(a,b))return true;if(a===null||b===null||typeof a!=='object'||typeof b!=='object')return false;if(a instanceof Blob||b instanceof Blob)return false;const keys=Object.keys(a);return keys.length===Object.keys(b).length&&keys.every(k=>Object.hasOwn(b,k)&&same(a[k],b[k]));};
async function serializeDraft(value:any):Promise<any>{if(value instanceof Blob){const bytes=new Uint8Array(await value.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return {$libraryDraftBlob:1,data:btoa(binary),type:value.type,name:value instanceof File?value.name:null,lastModified:value instanceof File?value.lastModified:0};}if(Array.isArray(value))return Promise.all(value.map(serializeDraft));if(value&&typeof value==='object')return Object.fromEntries(await Promise.all(Object.entries(value).map(async([k,v])=>[k,await serializeDraft(v)])));return value;}
function restoreDraftValue(value:any):any{if(value?.$libraryDraftBlob===1){const bytes=Uint8Array.from(atob(value.data),c=>c.charCodeAt(0));return value.name!==null?new File([bytes],value.name,{type:value.type,lastModified:value.lastModified}):new Blob([bytes],{type:value.type});}if(Array.isArray(value))return value.map(restoreDraftValue);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,restoreDraftValue(v)]));return value;}
const storageKey=(key:string)=>'library-form-draft:'+key;
function readDraft(key:string){try{return new Map<string,any>(restoreDraftValue(JSON.parse(sessionStorage.getItem(storageKey(key))||'[]')));}catch{return new Map<string,any>();}}
async function saveDraft(draft:Draft|null){if(!draft)return;for(const child of draftRegistry.values())if(child.parent===draft)await saveDraft(child);const encoded=await serializeDraft([...draft.values]);sessionStorage.setItem(storageKey(draft.key),JSON.stringify(encoded));}
function refreshParents(draft:Draft){let parent=draft.parent;while(parent){const current=parent;current.dirty=current.values.size>0||[...draftRegistry.values()].some(d=>d.parent===current&&d.dirty);parent=current.parent;}}
function discardDraft(draft:Draft|null){if(!draft)return;for(const child of draftRegistry.values())if(child.parent===draft)discardDraft(child);for(const [key,field]of draft.fields){field.current=field.baseline;field.reset(field.baseline);}draft.values.clear();draft.dirty=false;refreshParents(draft);drafts.delete(draft.key);try{sessionStorage.removeItem(storageKey(draft.key));}catch{}}
export function clearLiteratureDraft(key:string){for(const draft of draftRegistry.values())if(draft.key===key){draft.values.clear();draft.dirty=false;for(const field of draft.fields.values())field.baseline=field.current;refreshParents(draft);}drafts.delete(key);try{sessionStorage.removeItem(storageKey(key));}catch{}}
export function acceptLiteratureFields(draft:Draft|null,keys:string[]){if(!draft)return;for(const key of keys){draft.values.delete(key);const field=draft.fields.get(key);if(field)field.baseline=field.current;}draft.dirty=draft.values.size>0;refreshParents(draft);try{if(draft.values.size)void saveDraft(draft).catch(()=>{});else sessionStorage.removeItem(storageKey(draft.key));}catch{}}
export function useRetainedState<T>(key:string,initial:T):[T,Dispatch<SetStateAction<T>>]{const [value,setValue]=useState<T>(()=>viewState.has(key)?viewState.get(key):initial);return [value,next=>setValue(old=>{const result=typeof next==='function'?(next as (v:T)=>T)(old):next;viewState.set(key,result);return result;})];}
export const ModalBackContext=createContext<((callback:()=>boolean)=>()=>void)|null>(null);
export function useModalStepBack(callback:()=>boolean){const register=useContext(ModalBackContext),current=useRef(callback);current.current=callback;useEffect(()=>register?.(()=>current.current()),[register]);}
export function DraftScope({draftKey,children}:{draftKey:string;children:ReactNode}){const parent=useContext(DraftContext),ref=useRef<Draft|null>(null);if(!ref.current||ref.current.key!==draftKey){const values=drafts.get(draftKey)||readDraft(draftKey);drafts.set(draftKey,values);ref.current=draftRegistry.get(draftKey)||{key:draftKey,values,dirty:values.size>0,parent,fields:new Map()};ref.current.parent=parent;draftRegistry.set(draftKey,ref.current);}useEffect(()=>{const d=ref.current!;liveDrafts.add(d);refreshParents(d);return()=>{liveDrafts.delete(d);refreshParents(d);};},[draftKey]);return <DraftContext.Provider value={ref.current}>{children}</DraftContext.Provider>;}
export function useDraftState<T>(key:string,initial:T|(()=>T)):[T,Dispatch<SetStateAction<T>>]{
 const draft=useContext(DraftContext),baseline=useRef<{value:T}|null>(null);if(!baseline.current)baseline.current={value:typeof initial==='function'?(initial as ()=>T)():initial};
 const [value,setValue]=useState<T>(()=>draft?.values.has(key)?draft.values.get(key):baseline.current!.value);
 useEffect(()=>{if(draft){const prior=draft.fields.get(key);draft.fields.set(key,{baseline:prior?.baseline??baseline.current!.value,current:value,reset:setValue});}return()=>{draft?.fields.delete(key);};},[draft,key]);
 if(draft?.fields.has(key))draft.fields.get(key)!.current=value;
 return [value,next=>setValue(old=>{const result=typeof next==='function'?(next as (v:T)=>T)(old):next;if(draft){const original=draft.fields.get(key)?.baseline??baseline.current!.value;if(same(original,result))draft.values.delete(key);else draft.values.set(key,result);drafts.set(draft.key,draft.values);draft.dirty=draft.values.size>0;let parent=draft.parent;while(parent){parent.dirty=parent.values.size>0||[...draftRegistry.values()].some(d=>d.parent===parent&&d.dirty);parent=parent.parent;}}return result;})];
}
export function useDraftStatus(){return useContext(DraftContext);}
export function useDraftForm(active=true,busy=false){const nav=useLiteratureNavigation(),draft=useDraftStatus(),latest=useRef({active,busy,draft});latest.current={active,busy,draft};useEffect(()=>nav.form({id:crypto.randomUUID(),active:()=>latest.current.active,dirty:()=>!!latest.current.draft?.dirty,busy:()=>latest.current.busy,save:()=>saveDraft(latest.current.draft),discard:()=>discardDraft(latest.current.draft)}),[nav]);return {saved:()=>draft&&clearLiteratureDraft(draft.key)};}
export function useValueFormGuard(key:string,value:any,onRestore:(value:any)=>void,active=true,busy=false,initial:any={}){
 const nav=useLiteratureNavigation(),base=useRef(initial),current=useRef({value,onRestore,active,busy});current.current={value,onRestore,active,busy};
 useEffect(()=>{try{const stored=sessionStorage.getItem(storageKey(key));if(stored)current.current.onRestore(JSON.parse(stored));}catch{}return nav.form({id:key,active:()=>current.current.active,dirty:()=>!same(current.current.value,base.current),busy:()=>current.current.busy,save:()=>sessionStorage.setItem(storageKey(key),JSON.stringify(current.current.value)),discard:()=>{current.current.onRestore(base.current);sessionStorage.removeItem(storageKey(key));}});},[nav,key]);
 return {saved:()=>{base.current=current.current.value;sessionStorage.removeItem(storageKey(key));},persistRemainder:(value:any)=>{current.current.value=value;if(same(value,base.current))sessionStorage.removeItem(storageKey(key));else sessionStorage.setItem(storageKey(key),JSON.stringify(value));}};
}
function scrollState(){const positions:Record<string,number>={},expanded:Record<string,boolean>={};document.querySelectorAll<HTMLElement>('[data-scroll-key]').forEach(e=>positions[e.dataset.scrollKey!]=e.scrollTop);document.querySelectorAll<HTMLDetailsElement>('details[data-context-key]').forEach(e=>expanded[e.dataset.contextKey!]=e.open);return {scroll:window.scrollY,positions,expanded};}
function restoreScroll(e:Entry){
 let stopped=false;
 const apply=()=>{if(stopped)return;window.scrollTo({top:e.scroll,behavior:'instant'});document.querySelectorAll<HTMLElement>('[data-scroll-key]').forEach(n=>{if(n.dataset.scrollKey! in e.positions)n.scrollTop=e.positions[n.dataset.scrollKey!];});document.querySelectorAll<HTMLDetailsElement>('details[data-context-key]').forEach(n=>{if(n.dataset.contextKey! in e.expanded)n.open=e.expanded[n.dataset.contextKey!];});};
 const frame=requestAnimationFrame(apply),observer=new MutationObserver(apply);
 const stop=()=>{stopped=true;cancelAnimationFrame(frame);clearTimeout(timer);observer.disconnect();window.removeEventListener('wheel',stop);window.removeEventListener('touchstart',stop);window.removeEventListener('pointerdown',stop);window.removeEventListener('keydown',key);};
 const key=(event:KeyboardEvent)=>{if(['ArrowUp','ArrowDown','PageUp','PageDown','Home','End',' '].includes(event.key))stop();};
 const timer=setTimeout(()=>{apply();stop();},900);
 observer.observe(document.body,{childList:true,subtree:true});
 window.addEventListener('wheel',stop,{passive:true});window.addEventListener('touchstart',stop,{passive:true});window.addEventListener('pointerdown',stop,{passive:true});window.addEventListener('keydown',key);
 return stop;
}

export function LiteratureNavigation({children}:{children:ReactNode}){
 const state=useRef({get:()=>({} as Snapshot),restore:(_:Snapshot)=>{},fallback:()=>{},layers:[] as Layer[],forms:[] as FormGuard[],entries:new Map<number,Entry>(),current:0,session:'',moving:false,allow:false,allowUnload:false,undo:false,stopRestore:()=>{}});
 const [confirm,setConfirm]=useState<null|{go:()=>void;layers:Layer[];forms:FormGuard[]}>(null),[draftError,setDraftError]=useState(''),[draftSaving,setDraftSaving]=useState(false),confirmRef=useRef<HTMLDialogElement>(null),nav=useRef<Nav|null>(null);
 if(!nav.current){
  const save=()=>{const n=state.current,e:Entry={index:n.current,route:n.get(),layers:n.layers.map(l=>l.id),...scrollState()};n.entries.set(n.current,e);window.history.replaceState({...window.history.state,literature:{session:n.session,index:n.current}},'');return e;};
  const push=(url:string)=>{const n=state.current;n.stopRestore();n.moving=false;save();n.current++;window.history.pushState({...window.history.state,literature:{session:n.session,index:n.current}},'',url);save();};
  const request=(action:()=>void)=>{const n=state.current,layers=n.layers.filter(l=>l.dirty()),forms=n.forms.filter(f=>f.active()&&f.dirty());if(n.layers.some(l=>l.busy())||n.forms.some(f=>f.active()&&f.busy()))return;if(layers.length||forms.length){setDraftError('');setConfirm({go:action,layers,forms});}else action();};
  nav.current={bind(get,restore){state.current.get=get;state.current.restore=restore;return()=>{};},form(guard){state.current.forms.push(guard);return()=>{state.current.forms=state.current.forms.filter(f=>f!==guard);};},request,update(){if(state.current.session&&!state.current.moving)save();},push,
   back(){const n=state.current,top=n.layers.at(-1);if(top?.busy())return;if(top?.back?.())return;if(n.current>0)window.history.back();else if(top){const close=()=>{top.close();if(top.routed)n.fallback();};if(top.dirty())setConfirm({go:close,layers:[top],forms:[]});else close();}else request(n.fallback);},
   complete(){const n=state.current;if(n.current>0){n.allow=true;history.back();}else n.layers.at(-1)?.close();},hasBack(){return state.current.current>0;},fallback(fn){state.current.fallback=fn;return()=>{};},
   layer(layer){const n=state.current;if(!layer.routed)push(window.location.href);n.layers.push(layer);save();return()=>{n.layers=n.layers.filter(x=>x.id!==layer.id);if(!n.moving)save();};}};
 }
 useEffect(()=>{const n=state.current;n.session=crypto.randomUUID();n.current=0;const oldRestoration=history.scrollRestoration;history.scrollRestoration='manual';nav.current!.update();
  const pop=(event:PopStateEvent)=>{const marker=event.state?.literature,target=marker?.session===n.session?n.entries.get(marker.index):undefined;if(n.undo){n.undo=false;n.moving=false;return;}if(!target)return;
   const closing=n.layers.filter(l=>!target.layers.includes(l.id)),delta=target.index-n.current,forms=closing.length&&n.get().tab===target.route.tab?[]:n.forms.filter(f=>f.active()&&f.dirty());
   if(!n.allow&&delta<0&&closing.at(-1)?.back?.()){n.undo=true;n.moving=true;history.go(-delta);return;}
   if(!n.allow&&(closing.some(l=>l.busy()||l.dirty())||forms.length)){n.undo=true;n.moving=true;history.go(-delta);if(!closing.some(l=>l.busy())&&!forms.some(f=>f.busy())){setDraftError('');setConfirm({go:()=>{n.allow=true;history.go(delta);},layers:closing,forms});}return;}
   n.allow=false;n.moving=true;n.current=target.index;for(const l of [...closing].reverse())l.close();n.layers=n.layers.filter(l=>target.layers.includes(l.id));n.restore(target.route);n.stopRestore();n.stopRestore=restoreScroll(target);requestAnimationFrame(()=>{n.moving=false;nav.current!.update();});
  };
  const unload=(e:BeforeUnloadEvent)=>{if(n.allowUnload){n.allowUnload=false;return;}if(n.layers.some(l=>l.dirty())||n.forms.some(f=>f.active()&&f.dirty())){e.preventDefault();e.returnValue='';}};
  const link=(e:MouseEvent)=>{const a=(e.target as Element)?.closest?.('a[href]') as HTMLAnchorElement|null;if(!a||a.target==='_blank'||a.hasAttribute('download')||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||e.button!==0)return;if(!n.layers.some(l=>l.dirty())&&!n.forms.some(f=>f.active()&&f.dirty()))return;e.preventDefault();nav.current!.request(()=>{n.allowUnload=true;location.assign(a.href);});};
  window.addEventListener('popstate',pop);window.addEventListener('beforeunload',unload);document.addEventListener('click',link,true);return()=>{window.removeEventListener('popstate',pop);window.removeEventListener('beforeunload',unload);document.removeEventListener('click',link,true);n.stopRestore();history.scrollRestoration=oldRestoration;};
 },[]);
 useEffect(()=>{if(confirm)confirmRef.current?.showModal();},[confirm]);
 async function leave(discard:boolean){if(!confirm||draftSaving)return;setDraftSaving(true);try{for(const l of confirm.layers){if(discard)discardDraft(l.draft?.()||null);else await saveDraft(l.draft?.()||null);}for(const f of confirm.forms){if(discard)f.discard();else await f.save();}const go=confirm.go;setConfirm(null);go();}catch{setDraftError('Не вдалося зберегти чернетку на цьому пристрої. Дані залишились у формі. Продовжіть редагування або вийдіть без збереження.');}finally{setDraftSaving(false);}}
 return <Navigation.Provider value={nav.current}>{children}{confirm&&<dialog ref={confirmRef} className={s.dialog} aria-label="Зберегти зміни?" onCancel={e=>{e.preventDefault();if(!draftSaving)setConfirm(null);}}><header><h2>Зберегти зміни?</h2></header><div className={s.dialogBody}><p>Чернетка збережеться на цьому пристрої в поточній вкладці. Вона ще не надсилається до бібліотеки.</p>{draftError&&<p role="alert">{draftError}</p>}<div className={s.actions}><button disabled={draftSaving} type="button" className={s.primary} onClick={()=>setConfirm(null)}>Продовжити редагування</button><button type="button" disabled={draftSaving} className={s.secondary} onClick={()=>void leave(false)}>Зберегти чернетку й вийти</button><button type="button" disabled={draftSaving} className={s.danger} onClick={()=>void leave(true)}>Вийти без збереження</button></div></div></dialog>}</Navigation.Provider>;
}
export function useLiteratureNavigation(){const n=useContext(Navigation);if(!n)throw Error('Literature navigation missing');return n;}
export function useRouteState(snapshot:Snapshot,restore:(s:Snapshot)=>void){const nav=useLiteratureNavigation(),get=useRef(snapshot),put=useRef(restore);get.current=snapshot;put.current=restore;nav.bind(()=>get.current,s=>put.current(s));useEffect(()=>nav.update(),[snapshot]);return nav;}
export function useModalNavigation(onClose:()=>void,busy=false,extraDirty=false,back?:()=>boolean,routed=false,guardDraft=true){const nav=useLiteratureNavigation(),contextDraft=useDraftStatus(),draft=guardDraft?contextDraft:null,ref=useRef({onClose,busy,extraDirty,back,draft}),id=useRef('');ref.current={onClose,busy,extraDirty,back,draft};useEffect(()=>{id.current=crypto.randomUUID();return nav.layer({id:id.current,routed,close:()=>ref.current.onClose(),dirty:()=>!!ref.current.draft?.dirty||ref.current.extraDirty,draft:()=>ref.current.draft,busy:()=>ref.current.busy,back:()=>ref.current.back?.()||false});},[]);return nav.back;}
