"use client";
import {useEffect,useRef,useState} from "react";
import {Camera,ImagePlus,RotateCw,X} from "lucide-react";
import {photoCropDimensions,photoCropTransform,type PhotoCropEdit} from "@/lib/photo-crop-transform";
import s from "./literature.module.css";
import {useModalNavigation,useDraftState,useLiteratureNavigation,clearLiteratureDraft,useDraftStatus} from "./literature-navigation";
export type PreparedPhoto={base64:string;requestId:string};
const defaults=(kind:string):PhotoCropEdit=>({rotation:0,zoom:1,offsetX:0,offsetY:0,straighten:0,cropWidth:kind==="reader"?1:2,cropHeight:kind==="reader"?1:3});
export default function LiteraturePhotoEditor({id="",kind,version=1,onSaved,onClose,onPrepared}:{id?:string;kind:"reader"|"edition";version?:number;onSaved?:()=>void;onClose:()=>void;onPrepared?:(photo:PreparedPhoto)=>void|boolean|Promise<void|boolean>}){
 const dialog=useRef<HTMLDialogElement>(null),gallery=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null),canvas=useRef<HTMLCanvasElement>(null),bitmap=useRef<ImageBitmap|null>(null);
 const [file,setFile]=useDraftState<File|null>("photo-file:"+kind,null),[edit,setEdit]=useDraftState<PhotoCropEdit>("photo-edit:"+kind,defaults(kind)),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [uploadIntent,setUploadIntent]=useDraftState<{file:File;key:string;base64:string;requestId:string}|null>("photo-intent:"+kind+":"+id+":"+version,null),intent=useRef(uploadIntent);intent.current=uploadIntent;
 const nav=useLiteratureNavigation(),draft=useDraftStatus(),goBack=useModalNavigation(onClose,busy,!!file);
 useEffect(()=>{const prior=document.activeElement as HTMLElement|null,d=dialog.current;d?.showModal();const vp=window.visualViewport,resize=()=>{if(vp){d?.style.setProperty("--dialog-height",vp.height+"px");d?.style.setProperty("--dialog-top",vp.offsetTop+"px");}};resize();vp?.addEventListener("resize",resize);vp?.addEventListener("scroll",resize);return()=>{vp?.removeEventListener("resize",resize);vp?.removeEventListener("scroll",resize);d?.close();prior?.isConnected&&prior.focus({preventScroll:true});};},[]);
 useEffect(()=>{let alive=true;setReady(false);setError("");if(!file)return;
 (async()=>{if(file.size>24*1024*1024)throw Error("Фото має бути не більше 24 МБ.");if(!["image/jpeg","image/png","image/webp"].includes(file.type))throw Error("Оберіть JPG, PNG або WEBP.");let b:ImageBitmap;try{b=await createImageBitmap(file,{imageOrientation:"from-image"});}catch{b=await createImageBitmap(file);}if(!alive){b.close();return;}bitmap.current=b;setReady(true);})().catch(e=>{if(alive)setError(e.message||"Не вдалося відкрити фото.");});
 return()=>{alive=false;bitmap.current?.close();bitmap.current=null;};},[file,kind]);
 useEffect(()=>{if(!ready||!bitmap.current||!canvas.current)return;const c=canvas.current,b=bitmap.current,frame=photoCropDimensions(edit);c.width=frame.width;c.height=frame.height;const ctx=c.getContext("2d",{alpha:false});if(!ctx){setError("Редактор недоступний у цьому браузері.");return;}const t=photoCropTransform(b,frame,edit);ctx.fillStyle="#fff";ctx.fillRect(0,0,c.width,c.height);ctx.save();ctx.translate(t.centerX,t.centerY);ctx.rotate(t.rotationRadians);ctx.drawImage(b,-t.drawWidth/2,-t.drawHeight/2,t.drawWidth,t.drawHeight);ctx.restore();},[edit,ready]);
 const choose=(f:File|undefined)=>{if(f){setFile(f);setEdit(defaults(kind));}};
 async function save(){if(!canvas.current||!ready||busy)return;setBusy(true);setError("");try{const key=JSON.stringify(edit);
 if(intent.current?.key!==key||intent.current?.file!==file){const blob=await new Promise<Blob>((resolve,reject)=>canvas.current!.toBlob(b=>b?resolve(b):reject(Error("Не вдалося підготувати фото.")),"image/jpeg",.86));if(blob.size>4000000)throw Error("Фото завелике.");const bytes=new Uint8Array(await blob.arrayBuffer());let raw="";for(let i=0;i<bytes.length;i+=16384)raw+=String.fromCharCode(...bytes.subarray(i,i+16384));intent.current={file:file!,key,base64:btoa(raw),requestId:crypto.randomUUID()};setUploadIntent(intent.current);}
 if(onPrepared){if(await onPrepared({base64:intent.current.base64,requestId:intent.current.requestId})===false)return;if(draft)clearLiteratureDraft(draft.key);nav.complete();onClose();return;}
 const response=await fetch("/api/librarian/literature/image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,kind,expectedVersion:version,base64:intent.current.base64,requestId:intent.current.requestId})}),data=await response.json();if(!response.ok||!data.success)throw Error(typeof data.error==="string"?data.error:data.message||"Не вдалося зберегти фото.");if(draft)clearLiteratureDraft(draft.key);nav.complete();onClose();onSaved?.();
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <dialog ref={dialog} className={s.dialog} onCancel={e=>{e.preventDefault();e.stopPropagation();if(!busy)goBack();}} aria-label={kind==="reader"?"Змінити фото читача":"Змінити обкладинку"}><header><button type="button" className={s.backStep} disabled={busy} onClick={goBack}>← Назад</button><h2>{kind==="reader"?"Фото читача":"Обкладинка книги"}</h2><button type="button" disabled={busy} onClick={goBack} aria-label="Закрити редактор"><X/></button></header><div className={s.dialogBody}>
 <div className={s.actions}><button type="button" className={s.secondary} disabled={busy} onClick={()=>gallery.current?.click()}><ImagePlus size={18}/>Галерея</button><button type="button" className={s.secondary} disabled={busy} onClick={()=>camera.current?.click()}><Camera size={18}/>Додати фото з камери</button></div>
 <input ref={gallery} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{choose(e.target.files?.[0]);e.target.value="";}}/><input ref={camera} hidden type="file" accept="image/jpeg,image/png,image/webp" capture={kind==="reader"?"user":"environment"} onChange={e=>{choose(e.target.files?.[0]);e.target.value="";}}/>
 {error&&<p className={s.error} role="alert">{error}</p>}{file&&!ready&&!error&&<p role="status">Готуємо фото…</p>}
 {ready?<><div className={s.cropLayout}><div className={s.cropPreview} data-circular={kind==="reader"}><canvas ref={canvas} aria-label="Попередній перегляд обрізаного фото"/></div><div className={s.cropControls}>{([["cropWidth","Ширина кадру",1,5,.1],["cropHeight","Висота кадру",1,5,.1],["zoom","Масштаб",1,2.5,.05],["offsetX","По горизонталі",-1,1,.02],["offsetY","По вертикалі",-1,1,.02],["straighten","Вирівнювання",-45,45,1]] as const).filter(([key])=>kind!=="reader"||key!=="cropHeight").map(([key,label,min,max,step])=><label key={key}>{label} · {Number(edit[key]).toFixed(key==="straighten"?0:2)}<input type="range" min={min} max={max} step={step} value={edit[key]} disabled={busy} onChange={e=>setEdit(v=>({...v,[key]:Number(e.target.value),...(kind==="reader"&&key==="cropWidth"?{cropHeight:Number(e.target.value)}:{})}))}/></label>)}<div className={s.actions}><button type="button" className={s.secondary} disabled={busy} onClick={()=>setEdit(v=>({...v,rotation:((v.rotation+90)%360) as PhotoCropEdit["rotation"]}))}><RotateCw size={17}/>Повернути 90°</button><button type="button" className={s.textButton} disabled={busy} onClick={()=>setEdit(defaults(kind))}>Скинути</button></div></div></div><button type="button" className={s.primary} disabled={busy} onClick={()=>void save()}>{busy?"Зберігаємо…":"Зберегти фото"}</button></>:!file&&<p className={s.muted}>Оберіть джерело фото. Перед збереженням можна змінити кадр.</p>}
 </div></dialog>;
}
