"use client";
import {useEffect,useRef,useState} from 'react';
import {QRCodeWriter,BarcodeFormat} from '@zxing/library';
import s from './literature.module.css';
export default function ReaderAccess({row,disabled,onChanged}:{row:Record<string,any>;disabled:boolean;onChanged:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[link,setLink]=useState(''),[expires,setExpires]=useState(''),[bot,setBot]=useState(''),canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{fetch('/api/reader/config',{credentials:'same-origin',cache:'no-store'}).then(r=>r.json()).then(r=>setBot(r.telegram?.botUsername||'')).catch(()=>{});},[]);
 useEffect(()=>{if(!link||!canvas.current)return;const c=canvas.current,m=new QRCodeWriter().encode(link,BarcodeFormat.QR_CODE,c.width,c.height,new Map()),ctx=c.getContext('2d');if(!ctx)return;ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#143f2c';for(let y=0;y<m.getHeight();y++)for(let x=0;x<m.getWidth();x++)if(m.get(x,y))ctx.fillRect(x,y,1,1);},[link]);
 async function invite(purpose:'web'|'telegram'){setBusy(true);setError('');setLink('');try{const r=await fetch('/api/librarian/readers',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'invite',input:{readerId:row.id,purpose,expectedVersion:row.version}})}),d=await r.json();if(!r.ok||!d.success)throw Error(typeof d.error==='string'?d.error:d.error?.message||'Не вдалося створити запрошення.');setLink(purpose==='web'?new URL('/reader#invite='+d.result.token,location.origin).href:'https://t.me/'+bot+'?start=ra_'+d.result.token);setExpires(d.result.expiresAt);onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details><summary>Вхід читача — QR-запрошення</summary>{row.linked_teacher_user_id?<p className={s.muted}>Учитель входить через свій чинний кабінет. Окремий пароль або QR не потрібні.</p>:<><p className={s.muted}>Персональне одноразове запрошення на 48 годин. Покажіть його лише цьому читачеві. Нове запрошення скасовує попереднє невикористане; старі сеанси не завершує.</p><div className={s.actions}><button type="button" className={s.secondary} disabled={disabled||busy||row.access_status==='blocked'} onClick={()=>void invite('web')}>QR для входу на сайт</button><button type="button" className={s.secondary} disabled={disabled||busy||!bot||row.access_status==='blocked'||row.telegram_status==='active'} onClick={()=>void invite('telegram')}>QR для Telegram</button></div>{link&&<div><canvas ref={canvas} width={320} height={320} style={{maxWidth:'100%',height:'auto',display:'block'}} aria-label="Персональний QR-код входу"/><p className={s.muted}>Діє до {new Date(expires).toLocaleString('uk-UA')}</p><button type="button" className={s.secondary} onClick={()=>navigator.clipboard.writeText(link).catch(()=>setError('Не вдалося скопіювати. Дозвольте доступ до буфера або відскануйте QR.'))}>Скопіювати персональне посилання</button><button type="button" className={s.secondary} onClick={()=>setLink('')}>Приховати код</button></div>}</>}{error&&<p className={s.error} role="alert">{error}</p>}</details>;
}
