"use client";
import {useEffect,useRef,useState} from "react";
import {BarcodeFormat,QRCodeWriter} from "@zxing/library";
import s from "./literature.module.css";
type ReaderAccessRow={id?:string;version?:number;kind?:string;access_status?:string;credential_status?:string;must_change_pin?:number;telegram_status?:string;linked_teacher_user_id?:string|null};

export default function ReaderAccess({row,disabled,onChanged}:{row:ReaderAccessRow;disabled:boolean;onChanged:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[link,setLink]=useState(""),[code,setCode]=useState(""),[expires,setExpires]=useState(""),[bot,setBot]=useState(""),canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{fetch("/api/reader/config",{credentials:"same-origin",cache:"no-store"}).then(response=>response.json()).then(result=>setBot(result.telegram?.botUsername||"")).catch(()=>{});},[]);
 useEffect(()=>{if(!link||!canvas.current)return;const target=canvas.current,matrix=new QRCodeWriter().encode(link,BarcodeFormat.QR_CODE,target.width,target.height,new Map()),context=target.getContext("2d");if(!context)return;context.fillStyle="#fff";context.fillRect(0,0,target.width,target.height);context.fillStyle="#143f2c";for(let y=0;y<matrix.getHeight();y+=1)for(let x=0;x<matrix.getWidth();x+=1)if(matrix.get(x,y))context.fillRect(x,y,1,1);},[link]);
 async function request(action:string,input:Record<string,unknown>){const response=await fetch("/api/librarian/readers",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,input})}),data=await response.json();if(!response.ok||!data.success)throw Error(typeof data.error==="string"?data.error:data.error?.message||"Не вдалося створити вхід.");return data.result;}
 async function webAccess(){setBusy(true);setError("");setLink("");setCode("");try{const result=await request("web_access",{readerId:row.id,expectedVersion:row.version,confirmation:"CREATE_READER_WEB_ACCESS"});setCode(result.code);setLink(new URL("/reader#invite="+result.token,location.origin).href);setExpires(result.expiresAt);onChanged();}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}}
 async function telegramInvite(){setBusy(true);setError("");setLink("");setCode("");try{const result=await request("invite",{readerId:row.id,purpose:"telegram",expectedVersion:row.version});setLink("https://t.me/"+bot+"?start=ra_"+result.token);setExpires(result.expiresAt);onChanged();}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}}
 const status=row.credential_status==="active"?(row.must_change_pin?"Очікується перший вхід і створення PIN":"Власний PIN уже створено"):"Вхід на сайт ще не створено";
 return <details><summary>Вхід учня — список, PIN і QR</summary>{row.linked_teacher_user_id?<p className={s.muted}>Учитель входить через свій чинний кабінет. Окремий учнівський PIN не потрібний.</p>:row.kind!=="student"?<p className={s.muted}>Вхід зі списку доступний лише учням. Для вчителів використовується чинний кабінет учителя.</p>:<>
  <p className={s.muted}>{status}. Кнопка нижче створює одноразовий код і персональний QR на 48 годин. Обидва ведуть до створення власного 4-значного PIN; чинні вебсеанси цього учня буде завершено, Telegram залишиться підключеним.</p>
  <div className={s.actions}><button type="button" className={s.secondary} disabled={disabled||busy||row.access_status==="blocked"} onClick={()=>void webAccess()}>{row.credential_status==="active"?"Скинути PIN / створити новий вхід":"Створити вхід учня"}</button><button type="button" className={s.secondary} disabled={disabled||busy||!bot||row.access_status==="blocked"||row.telegram_status==="active"} onClick={()=>void telegramInvite()}>QR для Telegram</button></div>
  {code&&<div className={s.notice}><strong>Тимчасовий код: <span style={{fontVariantNumeric:"tabular-nums",fontSize:"1.35em",letterSpacing:".16em"}}>{code}</span></strong><p className={s.muted}>Передайте лише цьому учневі. Код показано один раз; після введення учень одразу створить власний PIN.</p><button type="button" className={s.secondary} onClick={()=>navigator.clipboard.writeText(code).catch(()=>setError("Не вдалося скопіювати код."))}>Скопіювати код</button></div>}
  {link&&<div><canvas ref={canvas} width={320} height={320} style={{maxWidth:"100%",height:"auto",display:"block"}} aria-label="Персональний QR-код входу"/><p className={s.muted}>Діє до {new Date(expires).toLocaleString("uk-UA")}</p><div className={s.actions}><button type="button" className={s.secondary} onClick={()=>navigator.clipboard.writeText(link).catch(()=>setError("Не вдалося скопіювати. Дозвольте доступ до буфера або відскануйте QR."))}>Скопіювати персональне посилання</button><button type="button" className={s.secondary} onClick={()=>{setLink("");setCode("");}}>Приховати</button></div></div>}
 </>}{error&&<p className={s.error} role="alert">{error}</p>}</details>;
}
