"use client";
import {useEffect,useState} from "react";
import s from "./literature.module.css";
type Item=Record<string,unknown>&{requestId:string;kind:string;sourceId:string};
type Packet={format:"literature-reviewed-delta-v1";items:Item[];images:{sourceId:string;base64:string;requestId:string}[]};
export default function SourceRefresh({disabled,onDone,onBusy}:{disabled:boolean;onDone:()=>void;onBusy:(busy:boolean)=>void}){
 const [packet,setPacket]=useState<Packet|null>(null),[busy,setBusy]=useState(false),[preview,setPreview]=useState<string[]>([]),[error,setError]=useState(""),[progress,setProgress]=useState("");
 useEffect(()=>{onBusy(busy);return()=>onBusy(false);},[busy,onBusy]);
 async function api(action:string,input:unknown){const r=await fetch("/api/librarian/literature",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,input})}),data=await r.json();if(!r.ok||!data.success)throw Error((typeof data.error==="string"?data.error:data.message)||"Перенесення не підтверджено.");return data.result;}
 return <div><p>Лише перевірений пакет змін з офіційного експорту. Дані підручників, входи читачів і повідомлення не змінюються.</p><p className={s.muted}>Перед перенесенням збережіть <a href="/librarian/recovery" target="_blank" rel="noreferrer">резервну копію</a>. Архів містить приватні дані — не поширюйте його.</p><label>Перевірений файл<input type="file" accept=".json,application/json" disabled={busy||disabled} onChange={async e=>{setPacket(null);setPreview([]);setError("");setProgress("");try{const file=e.target.files?.[0];if(!file)return;if(file.size>25000000)throw Error("Файл завеликий.");const parsed=JSON.parse(await file.text());if(parsed.format!=="literature-reviewed-delta-v1"||!Array.isArray(parsed.items)||parsed.items.length>20||!Array.isArray(parsed.images)||parsed.images.length>20)throw Error("Потрібен перевірений пакет перенесення.");setPacket(parsed);}catch(e){setError((e as Error).message);}}}/></label>
 <div className={s.actions}><button className={s.secondary} disabled={!packet||busy||disabled} onClick={async()=>{if(!packet)return;setBusy(true);setError("");setPreview([]);try{const rows=[];for(const item of packet.items){const result=await api("source_preview",item);rows.push(`${item.kind==="loan"?"Видача":item.kind==="book"?"Книга":"Довідник"}: ${result.label}${result.existingId?" · уже є запис":""}`);}setPreview(rows);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Перевірити пакет</button>
 <button className={s.primary} disabled={!packet||!preview.length||busy||disabled} onClick={async()=>{if(!packet)return;setBusy(true);setError("");try{const books=new Map<string,string>();for(let i=0;i<packet.items.length;i++){const item=packet.items[i];setProgress(`Переносимо запис ${i+1} з ${packet.items.length}…`);const result=await api("source_apply",item);if(item.kind==="book")books.set(item.sourceId,result.id);}for(let i=0;i<packet.images.length;i++){const image=packet.images[i],id=books.get(image.sourceId);if(!id)throw Error("Не знайдено видання для обкладинки.");setProgress(`Обкладинка ${i+1} з ${packet.images.length}…`);const r=await fetch("/api/librarian/literature/image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,kind:"edition",expectedVersion:1,base64:image.base64,requestId:image.requestId})}),data=await r.json();if(!r.ok||!data.success)throw Error((typeof data.error==="string"?data.error:data.message)||"Обкладинку не збережено.");}setProgress("Перенесення завершено. Повторне застосування цього самого файлу не дублює записи.");onDone();}catch(e){setError((e as Error).message);setProgress("Зупинено на непідтвердженому записі. Уже завершені дії збережені; цей самий файл можна повторити після звірки.");}finally{setBusy(false);}}}>Застосувати перевірені зміни</button></div>
 {preview.length>0&&<details open><summary>Записів: {preview.length}</summary><ul>{preview.map((item,index)=><li key={index}>{item}</li>)}</ul></details>}{progress&&<p className={s.notice} role="status">{progress}</p>}{error&&<p className={s.error} role="alert">{error}</p>}
 </div>;
}
