"use client";
import ReaderAccess from './reader-access';
import {telephoneHref} from "@/lib/telephone";
import { createContext, useContext, useEffect, useId, useRef, useState, type FormEvent, type ReactNode } from "react";
import { BookOpen, LayoutDashboard, Users, ArrowLeftRight, Plus, X, Search, ArrowLeft, Menu, Download, Pencil, Trash2, RefreshCw } from "lucide-react";
import { LIBRARY_EMBLEM_URL, librarianSectionHref } from "../_components/librarian-routes";
import LiteraturePhotoEditor,{type PreparedPhoto} from "./photo-editor";
import s from "./literature.module.css";
import {LiteratureNavigation,DraftScope,useDraftState,clearLiteratureDraft,useModalNavigation,useRouteState,useLiteratureNavigation,useRetainedState,ModalBackContext,useModalStepBack} from "./literature-navigation";
import SourceRefresh from "./source-refresh";
import ReaderCenter from "./reader-center";
import ClassAlignment from "./class-alignment";
import ReaderScanner from "@/app/reader/reader-scanner";
import {LITERATURE_TITLE,LYCEUM_NAME,countryLabel,countryCode} from "@/lib/literature-labels";
import {SuggestInput,EntityPicker,RecordPicker,choiceSource,type Choice} from "./literature-controls";

// The literature workspace intentionally owns its navigation and data routes.
type Row = Record<string, any>; // API records include source metadata with optional fields.
type Page = { items: Row[]; total: number; page: number; pages: number };
type View = "dashboard" | "books" | "readers" | "loans" | "reader-center";
type ModalState = { kind: "book" | "entity" | "reader" | "copy" | "issue" | "return" | "due" | "source" | "country" | "classes"; row?: Row; reader?: Row };
const TeacherDirectoryContext=createContext(false);
function TeacherDirectoryLink(){const telegram=useContext(TeacherDirectoryContext);return <a className={s.secondary} href={telegram?"/librarian/telegram/cabinet?target=teachers&tab=teachers":"/librarian/teachers?tab=teachers"}>Фото й дані — у головному довіднику вчителів</a>;}
function TeacherDirectoryFields({row}:{row:Row}){const phone=telephoneHref(row.phone);return <><p>Предмет / посада: {row.subject_position||"не вказано"}</p><p>Основний кабінет: {row.primary_location_name||"не вказано"}</p><p>Мобільний номер: {phone?<a href={phone}>{row.phone}</a>:row.phone||"не вказано"}</p></>;}
const CountryNavigation=createContext<(country:string)=>void>(()=>{});
const RelationNavigation=createContext<(row:Row)=>void>(()=>{});
const modalDraftKey=(m:ModalState)=>[m.kind,m.row?.kind||"",m.row?.id||"new",m.row?.version||0,m.row?.country||"",m.reader?.id||""].join(":");
const API = "/api/librarian/literature";
const kinds: Record<string,string> = {student:"Учень / учениця",teacher:"Учитель",staff:"Працівник",other:"Інший читач",unclassified:"Потребує звірки"};
const statuses: Record<string,string> = {requested:"Очікує підтвердження",ready:"Книжка готова до видачі",issued:"Видано",overdue:"Прострочено",returned:"Повернуто",reserved:"Зарезервовано",pending:"Очікує",cancelled:"Скасовано",on_shelf:"У бібліотеці",on_loan:"На руках",withdrawn:"Списано",unknown:"Потребує звірки"};
const today = () => new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Kyiv"}).format(new Date());
const dayAfter = (date:string, days=7) => new Date(Date.parse(date)+days*86400000).toISOString().slice(0,10);
const dateLabel = (value:unknown) => value ? new Date(String(value)).toLocaleDateString("uk-UA",{timeZone:"Europe/Kyiv"}) : "—";
const json = (value:unknown, fallback:any = {}) => { try { return typeof value==="string"?JSON.parse(value):value||fallback; } catch { return fallback; } };
const imageUrl = (id:string,kind="edition",version?:number) => `${API}/image?kind=${kind}&id=${encodeURIComponent(id)}&v=${version||0}`;
async function read<T>(path:string,signal?:AbortSignal):Promise<T> { const response=await fetch(path,{signal,cache:"no-store"}), data=await response.json();if(!response.ok||!data.success)throw Error((typeof data.error==="string"?data.error:data.message)||"Не вдалося завантажити дані.");return data.result; }
function useData<T>(path:string|null,epoch=0) { const [data,setData]=useState<T|null>(null),[loadedPath,setLoadedPath]=useState<string|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);useEffect(()=>{const abort=new AbortController();setLoading(!!path);setError("");if(!path)return()=>abort.abort();read<T>(path,abort.signal).then(value=>{if(!abort.signal.aborted){setData(value);setLoadedPath(path);}}).catch(error=>{if(!abort.signal.aborted)setError(error.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[path,epoch]);return {data:loadedPath===path?data:null,error,loading:loading||loadedPath!==path&&!!path}; }
function Busy({state}:{state:{loading:boolean;error:string}}) { return state.error?<p role="alert" className={s.error}>{state.error}</p>:state.loading?<p role="status" className={s.muted}>Завантажуємо…</p>:null; }
function Cover({row,large=false}:{row:Row;large?:boolean}) { const [failed,setFailed]=useState(false),url=row.cover_url||imageUrl(String(row.edition_id||row.id),"edition",row.version);useEffect(()=>setFailed(false),[url]);return <span className={`${s.cover} ${large?s.largeCover:""}`}>{!failed?<img src={url} alt={`Обкладинка: ${row.title}`} loading="lazy" onError={()=>setFailed(true)}/>:<span><BookOpen/><small>Без обкладинки</small></span>}</span>; }
function Avatar({row,large=false,zoomable=false}:{row:Row;large?:boolean;zoomable?:boolean}) {const [failed,setFailed]=useState(false),[zoom,setZoom]=useState(false),url=imageUrl(String(row.reader_id||row.id),"reader",row.profile_version||row.reader_version||row.version)+"&at="+encodeURIComponent(String(row.photo_updated_at||""));useEffect(()=>setFailed(false),[url]);const content=<span className={`${s.avatar} ${large?s.avatarLarge:""}`}>{row.has_photo&&!failed?<img src={url} alt={`Фото: ${row.full_name||row.author_name||"читач"}`} onError={()=>setFailed(true)}/>:String(row.full_name||row.author_name||"Ч").split(" ").slice(0,2).map(x=>x[0]).join("")}</span>;return <>{zoomable&&row.has_photo&&!failed?<button type="button" className={s.avatarButton} onClick={()=>setZoom(true)} aria-label="Збільшити фото читача">{content}</button>:content}{zoom&&<Modal title={row.full_name||row.author_name||"Фото читача"} onClose={()=>setZoom(false)}><img className={s.avatarPreview} src={url} alt="Збільшене фото читача"/></Modal>}</>;}
function Status({value}:{value:string}) { return <span className={s.badge} data-status={value}>{statuses[value]||value}</span>; }
function Pager({data,onPage}:{data:Page|null;onPage:(page:number)=>void}) { if(!data)return null;return <div className={s.pager}><span>Усього: {data.total.toLocaleString("uk-UA")}</span><div><button disabled={data.page<=1} onClick={()=>onPage(data.page-1)} aria-label="Попередня сторінка">←</button><span>{data.page} / {Math.max(1,data.pages)}</span><button disabled={data.page>=data.pages} onClick={()=>onPage(data.page+1)} aria-label="Наступна сторінка">→</button></div></div>; }
function Modal({title,children,onClose,busy=false,routed=false}:{title:string;children:ReactNode;onClose:()=>void;busy?:boolean;routed?:boolean}) {
 const ref=useRef<HTMLDialogElement>(null),heading=useId(),backRef=useRef<null|(()=>boolean)>(null),goBack=useModalNavigation(onClose,busy,false,()=>backRef.current?.()||false,routed);
 useEffect(()=>{const prior=document.activeElement as HTMLElement|null,d=ref.current;d?.showModal();const viewport=window.visualViewport;const resize=()=>{if(d&&viewport){d.style.setProperty("--dialog-height",viewport.height+"px");d.style.setProperty("--dialog-top",viewport.offsetTop+"px");}};resize();viewport?.addEventListener("resize",resize);viewport?.addEventListener("scroll",resize);return()=>{viewport?.removeEventListener("resize",resize);viewport?.removeEventListener("scroll",resize);d?.close();if(prior?.isConnected)prior.focus({preventScroll:true});};},[]);
 return <dialog ref={ref} className={s.dialog} aria-labelledby={heading} onCancel={e=>{if(e.target!==e.currentTarget)return;e.preventDefault();e.stopPropagation();if(!busy)goBack();}}><header><button type="button" className={s.backStep} disabled={busy} onClick={goBack}>← Назад</button><h2 id={heading}>{title}</h2><button type="button" aria-label="Закрити" disabled={busy} onClick={goBack}><X/></button></header><div className={s.dialogBody} data-scroll-key={title}><ModalBackContext.Provider value={callback=>{backRef.current=callback;return()=>{backRef.current=null;};}}>{children}</ModalBackContext.Provider></div></dialog>;
}
function BookLink({row,onBook}:{row:Row;onBook:(id:string)=>void}) { return <button type="button" className={s.bookLink} onClick={()=>onBook(String(row.edition_id||row.id))}><Cover row={row}/><span><strong>{row.title}</strong>{row.accession_no&&<small>№ {row.accession_no}</small>}</span></button>; }
function ActionButtons({children}:{children:ReactNode}) { return <div className={s.actions}>{children}</div>; }
function Field({label,name,value,required=false,type="text",long=false}:{label:string;name:string;value?:unknown;required?:boolean;type?:string;long?:boolean}) {const [text,setText]=useDraftState("field:"+name,String(value??""));return <label>{label}{long?<textarea name={name} value={text} onChange={e=>setText(e.target.value)} rows={4} maxLength={20000}/>:<input name={name} type={type} value={text} onChange={e=>setText(e.target.value)} required={required} maxLength={1000}/>}</label>; }
const BOOK_FIELDS: Record<string,string> = {type:"Тип матеріалу",author:"Автор",genre:"Категорія",publisher:"Видавництво",isbn10:"ISBN-10",isbn13:"ISBN-13",issn:"ISSN",edition:"Видання",year:"Рік",series:"Серія",tags:"Теги",volume:"Том",pages:"Сторінки",language:"Мова",callNumber:"Шифр / місце на полиці",annotation:"Анотація",description:"Опис",url:"URL",issueType:"Тип випуску",issuePeriod:"Період випуску"};
const ENTITY_FIELDS:Record<string,Record<string,string>>={author:{firstName:"Ім’я",lastName:"Прізвище",nickname:"Псевдонім",dateOfBirth:"Дата / рік народження",dateOfDeath:"Дата / рік смерті",country:"Країна",biography:"Біографія",publications:"Публікації",awards:"Відзнаки"},publisher:{city:"Місто",location:"Місцезнаходження",address:"Повна адреса",email:"Email",phone:"Телефон",country:"Країна",website:"Вебсторінка"},genre:{description:"Опис"},tag:{description:"Опис"},series:{description:"Опис"}};
const ENTITY_NAMES:Record<string,string>={author:"Автори",publisher:"Видавництва",genre:"Категорії",tag:"Теги",series:"Серії"};

export default function LiteratureWorkspace(props:{writesEnabled:boolean;admin:boolean;telegramMiniApp?:boolean}){return <TeacherDirectoryContext.Provider value={!!props.telegramMiniApp}><LiteratureNavigation><Workspace {...props}/></LiteratureNavigation></TeacherDirectoryContext.Provider>;}
function Workspace({writesEnabled,admin,telegramMiniApp=false}:{writesEnabled:boolean;admin:boolean;telegramMiniApp?:boolean}) {
  const [view,setView]=useState<View>("dashboard"),[catalog,setCatalog]=useState("books"),[page,setPage]=useState(1),[query,setQuery]=useState(""),[q,setQ]=useState(""),[sort,setSort]=useState("title"),[status,setStatus]=useState("all"),[classId,setClassId]=useState(""),[classQuery,setClassQuery]=useState(""),[role,setRole]=useState(""),[entity,setEntity]=useState(""),[filters,setFilters]=useState<Record<string,string>>({category:"",author:"",publisher:"",tag:""}),[filterIds,setFilterIds]=useState<Record<string,string>>({}),[archived,setArchived]=useState(false),[direction,setDirection]=useState("asc"),[from,setFrom]=useState(dayAfter(today(),-29)),[to,setTo]=useState(today()),[period,setPeriod]=useState({from:dayAfter(today(),-29),to:today()}),[entityPage,setEntityPage]=useState(""),[bookId,setBookId]=useState(""),[readerId,setReaderId]=useState(""),[modal,setModalState]=useState<ModalState|null>(null),[mobileMenu,setMobileMenu]=useState(false),[epoch,setEpoch]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const intent=useRef(new Map<string,string>()),shellRef=useRef<HTMLDivElement>(null),headerRef=useRef<HTMLElement>(null);
  useEffect(()=>{const refresh=()=>{if(!document.hidden&&!busy&&!modal)setEpoch(v=>v+1);};window.addEventListener("focus",refresh);document.addEventListener("visibilitychange",refresh);return()=>{window.removeEventListener("focus",refresh);document.removeEventListener("visibilitychange",refresh);};},[busy,modal]);
  useEffect(()=>{const header=headerRef.current,shell=shellRef.current;if(!header||!shell)return;const update=()=>shell.style.setProperty('--literature-header-height',Math.ceil(header.getBoundingClientRect().height)+'px');update();const observer=new ResizeObserver(update);observer.observe(header);return()=>observer.disconnect();},[]);
  useEffect(()=>{if(query===q)return;const id=setTimeout(()=>{setQ(query);setPage(1);},250);return()=>clearTimeout(id);},[query]);
  const options=useData<Row>(`${API}?view=options`,epoch);
  const path=(()=>{const params=new URLSearchParams({view:view==="books"?catalog==="books"?"books":catalog==="reviews"?"reviews":"entities":view,page:String(page),q});if(view==="dashboard"){params.set("from",period.from);params.set("to",period.to);}if(view==="books"){if(catalog!=="books")params.set("kind",catalog);else{params.set("sort",sort);params.set("entity",entity);for(const [key,value]of Object.entries(filters))params.set(filterIds[key]?key+"Id":key,filterIds[key]||value);}}if(view==="loans"){params.set("sort",["due","issued","reader","returned","created"].includes(sort)?sort:"due");params.set("status",status);params.set("direction",direction);}if(view==="readers"){params.set("class",classId);params.set("kind",role);}if(archived)params.set("archived","1");return `${API}?${params}`;})();
  const state=useData<Row>(entityPage||view==="reader-center"?null:path,epoch);
  const restored=useRef(false);
  const nav=useRouteState({view,catalog,page,query,q,sort,status,classId,classQuery,role,entity,filters,filterIds,archived,direction,from,to,period,entityPage,bookId,readerId,modal},v=>{restored.current=true;setView(v.view||"dashboard");setCatalog(v.catalog||"books");setPage(v.page||1);setQuery(v.query||"");setQ(v.q||"");setSort(v.sort||"title");setStatus(v.status||"all");setClassId(v.classId||"");setClassQuery(v.classQuery||"");setRole(v.role||"");setEntity(v.entity||"");setFilters(v.filters||{});setFilterIds(v.filterIds||{});setArchived(!!v.archived);setDirection(v.direction||"asc");setFrom(v.from||dayAfter(today(),-29));setTo(v.to||today());setPeriod(v.period||{from:dayAfter(today(),-29),to:today()});setEntityPage(v.entityPage||"");setBookId(v.bookId||"");setReaderId(v.readerId||"");setModalState(v.modal||null);setError("");});
  useEffect(()=>{const params=new URLSearchParams(window.location.search),v=params.get("view");if(v&&["dashboard","books","readers","loans","reader-center"].includes(v))setView(v as View);setEntityPage(params.get("entityPage")||"");setEntity(params.get("entity")||"");setCatalog(params.get("catalog")||"books");setBookId(params.get("book")||"");setReaderId(params.get("reader")||"");},[]);
  function setModal(value:ModalState|null){if(value)nav.push(window.location.href);setModalState(value);}
  function history(v:View,book="",reader="",detail=entityPage,filter=entity,section=catalog){const url=new URL(window.location.href);url.searchParams.set("view",v);url.searchParams.set("catalog",section);for(const [key,value] of [["book",book],["reader",reader],["entityPage",detail],["entity",filter]])value?url.searchParams.set(key,value):url.searchParams.delete(key);nav.push(url.toString());}
  useEffect(()=>nav.fallback(()=>{setBookId("");setReaderId("");setModal(null);setEntityPage("");setEntity("");if(view==="dashboard")setView("books");const u=new URL(window.location.href);["book","reader","entityPage","entity"].forEach(k=>u.searchParams.delete(k));u.searchParams.set("view",view==="dashboard"?"books":view);window.history.replaceState(window.history.state,"",u);}),[view]);
  function navigate(v:View){nav.request(()=>{setEntityPage("");setView(v);setPage(1);setQ("");setQuery("");setBookId("");setReaderId("");setArchived(false);setMobileMenu(false);setSort(v==="loans"?"due":"title");setEntity("");setFilters({category:"",author:"",publisher:"",tag:""});setFilterIds({});history(v,"","","","");});}
  function openBook(id:string){nav.request(()=>{setBookId(id);setReaderId("");history(view,id);});}
  function openReader(id:string){nav.request(()=>{setReaderId(id);setBookId("");history(view,"",id);});}
  function openEntity(row:Row){nav.request(()=>{setSort("title");setModal(null);setBookId("");setReaderId("");setView("books");setCatalog("books");setPage(1);setQuery("");setQ("");setFilters({category:"",author:"",publisher:"",tag:""});setFilterIds({});setArchived(false);if(["author","publisher"].includes(row.kind)){setEntityPage(row.id);setEntity("");history("books","","",row.id,"","books");}else{setEntityPage("");setEntity(row.id);history("books","","","",row.id,"books");}window.scrollTo({top:0});});}
  function clearFilterAddress(){const u=new URL(window.location.href);u.searchParams.delete("entity");window.history.replaceState(window.history.state,"",u);}
  function resetEntity(){setEntity("");setFilters({category:"",author:"",publisher:"",tag:""});setFilterIds({});setPage(1);history("books","","","","");}
  async function act(action:string,input:Row,refresh=true){if(busy||!writesEnabled)return null;const key=JSON.stringify({action,input});if(!intent.current.has(key))intent.current.set(key,crypto.randomUUID());setBusy(true);setError("");setNotice("");try{const response=await fetch(action==="reader_request_status"?API+"/readers":API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:action==="reader_request_status"?"request_status":action,input:{...input,requestId:intent.current.get(key)!}})}),data=await response.json();if(!response.ok||!data.success)throw Error((typeof data.error==="string"?data.error:data.message)||"Дію не підтверджено.");intent.current.delete(key);if(refresh)setEpoch(x=>x+1);setNotice("Збережено.");return data.result as Row;}catch(error){setError((error as Error).message);return null;}finally{setBusy(false);}}
  const pendingBooks=useRef(new Map<string,{result:Row;photo:PreparedPhoto}>()),[,setBookPending]=useState(false);
  async function saveBook(input:Row,photo:PreparedPhoto|null){const key=modalDraftKey(modal!);let pending=pendingBooks.current.get(key);setError("");
   if(!pending){const result=await act("edition_save",input,false);if(!result)return;if(!photo){clearLiteratureDraft(key);nav.complete();setEpoch(x=>x+1);return;}pending={result,photo};pendingBooks.current.set(key,pending);setBookPending(true);}
   setBusy(true);try{const response=await fetch(API+"/image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:pending.result.id,kind:"edition",expectedVersion:pending.result.version,base64:pending.photo.base64,requestId:pending.photo.requestId})}),data=await response.json();if(!response.ok||!data.success)throw Error("Книга вже збережена, але фото ще не підтверджено. Натисніть «Повторити збереження фото»: нова книга повторно не створиться.");pendingBooks.current.delete(key);setBookPending(false);clearLiteratureDraft(key);nav.complete();setEpoch(x=>x+1);setNotice("Книгу й обкладинку збережено.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  async function archive(kind:string,row:Row,restore=false){if(!window.confirm(restore?"Повернути картку з архіву?":kind==="entity"?"Видалити запис із довідника? Якщо він пов’язаний із книгами, спочатку змініть зв’язки в їхніх картках.":"Прибрати картку до архіву? Історія збережеться. За наявності неповернутих книг або резервувань дія буде заблокована."))return;if(await act("archive",{kind,id:row.id,expectedVersion:row.version,restore})){setBookId("");setReaderId("");setModal(null);history(view);}}
  const titles:Record<View,string>={dashboard:"Панель",books:"Каталог",readers:"Користувачі",loans:"Видачі","reader-center":"Читацький центр"};
  return <CountryNavigation.Provider value={country=>setModal({kind:"country",row:{country}})}><RelationNavigation.Provider value={openEntity}><div ref={shellRef} className={s.shell}><header ref={headerRef} className={s.header}>{(entityPage||entity||catalog!=="books"||nav.hasBack())&&<button type="button" className={s.backStep} onClick={nav.back}>← Назад</button>}<button className={s.menuButton} aria-label="Відкрити навігацію" aria-expanded={mobileMenu} onClick={()=>setMobileMenu(x=>!x)}><Menu/></button><a href={telegramMiniApp?"/librarian/telegram/cabinet?target=literature":"/librarian/literature"} className={s.brand}><img src={LIBRARY_EMBLEM_URL} alt="Емблема бібліотеки"/><span><strong>Єдина бібліотека<span>Художня та наукова література</span></strong><small>{LYCEUM_NAME}</small></span></a><a className={s.returnLink} aria-label="До Єдиної бібліотеки" href={librarianSectionHref("home",telegramMiniApp)}><ArrowLeft size={17}/><span>До Єдиної бібліотеки</span></a></header>
    <div className={s.layout}><aside className={`${s.sidebar} ${mobileMenu?s.menuOpen:""}`}><p>Кабінет бібліотекаря</p><nav aria-label={LITERATURE_TITLE}>{([["dashboard",LayoutDashboard],["books",BookOpen],["readers",Users],["loans",ArrowLeftRight],["reader-center",Users]] as const).map(([id,Icon])=><button key={id} aria-current={view===id?"page":undefined} onClick={()=>navigate(id)}><Icon size={20}/>{titles[id]}</button>)}<a href="/reader/catalog" className={s.publicReaderNav}><BookOpen size={20}/><span>Єдина бібліотека художньої та наукової літератури</span></a></nav><div className={s.sideFoot}>Єдина бібліотека<br/>Міжнародний ліцей МАУП</div></aside>
    <main className={s.main}><div className={s.heading}><div><p className={s.eyebrow}>Художня та наукова література</p><h1>{titles[view]}</h1></div><div className={s.actions}>{admin&&<button className={s.secondary} onClick={()=>setModal({kind:"source"})}>Архів джерела</button>}<button className={s.secondary} aria-label="Оновити" onClick={()=>setEpoch(x=>x+1)} disabled={busy}><RefreshCw size={16}/><span>Оновити</span></button></div></div>
    {error&&<p className={s.error} role="alert">{error}</p>}{notice&&<p className={s.notice} role="status">{notice}</p>}{!writesEnabled&&<p className={s.notice}>Доступний перегляд. Запис тимчасово вимкнено.</p>}
    {view==="reader-center"?<ReaderCenter refreshEpoch={epoch} admin={admin} writesEnabled={writesEnabled} onBook={openBook} onReader={openReader} onIssue={r=>setModal({kind:"issue",reader:{id:r.reader_id},row:{edition_id:r.edition_id,bookRequestId:r.id}})}/>:entityPage?<EntityPage key={entityPage} id={entityPage} epoch={epoch} onBook={openBook} onEdit={row=>setModal({kind:"entity",row:{...row,editing:true}})} disabled={!writesEnabled||busy} onBack={nav.back}/>:view==="dashboard"?<><form className={s.period} onSubmit={e=>{e.preventDefault();setPeriod({from,to});}}><label>Від<input type="date" value={from} onChange={e=>setFrom(e.target.value)} required/></label><label>До<input type="date" value={to} onChange={e=>setTo(e.target.value)} required/></label><button className={s.secondary}>Показати</button></form><Busy state={state}/>{state.data&&<Dashboard data={state.data} onBook={openBook} onReader={openReader} onIssue={()=>setModal({kind:"issue"})} onReturn={()=>setModal({kind:"return"})} onNewReader={()=>setModal({kind:"reader"})} onReaders={()=>navigate("readers")} onOverdue={()=>{navigate("loans");setStatus("overdue");}} disabled={!writesEnabled}/>}</>:<>
      {view==="books"&&<label className={s.mobileCatalog}>Розділ каталогу<select value={catalog} onChange={e=>{setCatalog(e.target.value);history("books","","",entityPage,entity,e.target.value);setPage(1);setQuery("");setQ("");}}>{[["books","Елементи каталогу"],...Object.entries(ENTITY_NAMES).filter(([key])=>key!=="series"),["reviews","Огляди"]].map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label>}
      {view==="books"&&<nav className={s.tabs} aria-label="Розділи каталогу">{[["books","Елементи каталогу"],...Object.entries(ENTITY_NAMES).filter(([key])=>key!=="series"),["reviews","Огляди"]].map(([id,title])=><button key={id} aria-current={catalog===id?"page":undefined} onClick={()=>{setCatalog(id);history("books","","",entityPage,entity,id);setPage(1);setQ("");setQuery("");}}>{title}</button>)}</nav>}
      <div className={s.toolbar}><form className={s.search} onSubmit={e=>{e.preventDefault();setQ(query);setPage(1);}}><Search size={18}/><input aria-label="Пошук" placeholder={view==="books"?"Назва, автор, ISBN…":"Прізвище, ім’я або номер…"} value={query} onChange={e=>setQuery(e.target.value)}/><button>Знайти</button></form>
      {view==="books"&&catalog==="books"&&<><label>Сортування<select value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="title">За назвою</option><option value="author">За автором</option><option value="category">За категорією</option><option value="publisher">За видавництвом</option><option value="newest">Нові надходження</option></select></label><ReaderScanner label="Сканувати ISBN" format="isbn" className={s.secondary} onDetected={code=>{setQuery(code);setQ(code);setPage(1);setEntity("");setFilters({category:"",author:"",publisher:"",tag:""});setFilterIds({});}}/><button className={s.primary} onClick={()=>setModal({kind:"book"})} disabled={!writesEnabled}><Plus size={17}/>Додати книгу</button></>}
      {view==="books"&&!["books","reviews"].includes(catalog)&&<button className={s.primary} disabled={!writesEnabled} onClick={()=>setModal({kind:"entity",row:{kind:catalog}})}><Plus size={17}/>Додати запис</button>}
      {view==="readers"&&<>{admin&&<button className={s.secondary} disabled={!writesEnabled} onClick={()=>setModal({kind:"classes"})}>Звірити класи</button>}<SuggestInput label="Клас" value={classQuery} onChange={v=>{setClassQuery(v);setClassId("");setPage(1);}} source={choiceSource("class")} onPick={c=>{setClassId(c.id);setRole("student");setPage(1);}} options={(options.data?.classes||[]).map((c:Row)=>({id:c.id,label:c.class_name,detail:c.label}))} placeholder="Усі класи"/><label>Категорія<select value={role} onChange={e=>{setRole(e.target.value);setPage(1);}}><option value="">Усі користувачі</option>{Object.entries(kinds).map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label><button className={s.primary} disabled={!writesEnabled} onClick={()=>setModal({kind:"reader"})}><Plus size={17}/>Додати користувача</button></>}
      {view==="loans"&&<><label>Статус<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="all">Усі</option>{["reserved","issued","overdue","returned","cancelled","pending"].map(id=><option key={id} value={id}>{statuses[id]}</option>)}</select></label><label>Сортування<select value={sort} onChange={e=>setSort(e.target.value)}><option value="due">За строком повернення</option><option value="issued">За датою видачі</option><option value="returned">За фактичним поверненням</option><option value="reader">За прізвищем</option><option value="created">За датою запису</option></select></label><label>Порядок<select value={direction} onChange={e=>setDirection(e.target.value)}><option value="asc">За зростанням</option><option value="desc">За спаданням</option></select></label><button className={s.primary} disabled={!writesEnabled} onClick={()=>setModal({kind:"issue"})}>Видати</button><button className={s.secondary} disabled={!writesEnabled} onClick={()=>setModal({kind:"return"})}>Повернути</button></>}
      {(view==="readers"||view==="books"&&catalog==="books")&&<label className={s.check}><input type="checkbox" checked={archived} onChange={e=>{setArchived(e.target.checked);setPage(1);}}/>Архів</label>}</div>
      {view==="books"&&catalog==="books"&&<details className={s.catalogFilters} data-context-key="catalog-filters"><summary>Фільтри{entity||Object.values(filters).some(Boolean)?" · застосовано":""}</summary><div className={s.filterGrid}>{[["category","genre","Категорія"],["author","author","Автор"],["publisher","publisher","Видавництво"],["tag","tag","Теги"]].map(([key,kind,label])=><SuggestInput key={key} label={label} source={choiceSource(kind)} onPick={c=>{setFilters(old=>({...old,[key]:c.label}));setFilterIds(old=>({...old,[key]:c.id}));setPage(1);}} value={filters[key]||""} onChange={value=>{setFilters(old=>({...old,[key]:value}));setFilterIds(old=>({...old,[key]:""}));setEntity("");clearFilterAddress();setPage(1);}} options={(options.data?.entities||[]).filter((x:Row)=>x.kind===kind).map((x:Row)=>({id:x.id,label:x.name}))} placeholder="Усі · введіть назву"/>)}{(entity||Object.values(filters).some(Boolean))&&<button className={s.textButton} onClick={()=>{setEntity("");clearFilterAddress();setFilters({category:"",author:"",publisher:"",tag:""});setFilterIds({});setPage(1);}}>Очистити фільтри</button>}</div></details>}
      {view==="books"&&catalog==="books"&&entity&&<div className={s.filterBadge}><span>{options.data?.entities?.find((x:Row)=>x.id===entity)?.name||"Обрана категорія"}</span><button className={s.textButton} onClick={resetEntity}>Скинути фільтр</button></div>}
      <Busy state={state}/>{state.data&&!state.loading&&<>
      {view==="books"&&catalog==="books"&&<><p className={s.resultCount}>Знайдено: <strong>{state.data.total}</strong> видань</p><div className={s.bookGrid}>{state.data.items.map((row:Row)=><CatalogCard key={row.id} row={row} onBook={openBook}><ActionButtons>{!archived?<button className={s.secondary} disabled={!writesEnabled} onClick={()=>setModal({kind:"copy",row})}>Додати копію</button>:<button className={s.secondary} disabled={!writesEnabled} onClick={()=>void archive("edition",row,true)}>Відновити</button>}</ActionButtons></CatalogCard>)}</div></>}
      {view==="books"&&!["books","reviews"].includes(catalog)&&<div className={s.entityList}>{state.data.items.map((row:Row)=><article className={s.entityRow} key={row.id}><div><button className={s.textButton} onClick={()=>openEntity(row)}>{row.name}</button><p>{row.books} книг</p>{row.metadata.country&&<button className={s.textButton} onClick={()=>setModal({kind:"country",row:{country:countryCode(row.metadata.country)}})}>{countryLabel(row.metadata.country)}</button>}{row.kind==="author"&&<small>{row.metadata.dateOfBirth||row.metadata.yearBorn||""}{row.metadata.dateOfDeath||row.metadata.yearDied?` — ${row.metadata.dateOfDeath||row.metadata.yearDied}`:""}</small>}</div><ActionButtons><button className={s.secondary} onClick={()=>openEntity(row)}>Книги</button><button className={s.secondary} onClick={()=>openEntity(row)}>Переглянути</button><button className={s.secondary} disabled={!writesEnabled} onClick={()=>setModal({kind:"entity",row:{...row,editing:true}})}>Редагувати</button><button className={s.danger} disabled={!writesEnabled} onClick={()=>void archive("entity",row)} aria-label={`Видалити ${row.name}`}><Trash2 size={17}/></button></ActionButtons></article>)}</div>}
      {view==="books"&&catalog==="reviews"&&<div className={s.entityList}>{state.data.items.map((row:Row)=><article className={s.review} key={row.id}><BookLink row={row} onBook={openBook}/><div className={s.person}><Avatar row={row}/>{row.reader_id?<button className={s.textButton} onClick={()=>openReader(row.reader_id)}>{row.author_name}</button>:<span>{row.author_name}</span>}<small>{row.reader_kind?kinds[row.reader_kind]:"Тип читача не встановлено"}{row.reader_kind==="student"&&row.class_name?` · ${row.class_name}`:row.reader_kind==="teacher"&&row.subject_position?` · ${row.subject_position}`:""}</small><span>{row.rating?"★".repeat(row.rating):""}</span></div><p>{row.body}</p><small>{row.date}</small><button className={s.danger} disabled={!writesEnabled} onClick={async()=>{if(window.confirm("Приховати цей відгук?"))await act("review_hide",{id:row.id,origin:row.origin,editionId:row.edition_id,readerId:row.reader_id,expectedVersion:row.version});}}>Видалити коментар</button></article>)}</div>}
      {view==="readers"&&<div className={s.entityList}>{state.data.items.map((row:Row)=><article className={s.readerRow} key={row.id}><div className={s.person}><Avatar row={row} large zoomable/><div><button className={s.textButton} onClick={()=>openReader(row.id)}>{row.full_name}</button><p>№ {row.member_no} · {row.class_name||row.source_group_label||kinds[row.kind]}</p><details data-context-key={"reader-extra:"+row.id}><summary>Докладніше</summary>{row.linked_teacher_user_id&&<TeacherDirectoryFields row={row}/>}<small>Telegram: {row.telegram_status==="active"?"підключено":"не підключено"}</small></details></div></div><div><strong>{row.loan_count} книг на руках</strong>{row.overdue_count>0&&<p className={s.red}>{row.overdue_count} прострочено</p>}<div className={s.readerBooks}>{json(row.active_books,[]).slice(0,3).map((book:Row)=><BookLink key={book.id} row={book} onBook={openBook}/>)}</div></div><ActionButtons><button className={s.secondary} onClick={()=>openReader(row.id)}>Картка</button>{archived&&<button className={s.secondary} disabled={!writesEnabled} onClick={()=>void archive("reader",row,true)}>Відновити</button>}</ActionButtons></article>)}</div>}
      {view==="loans"&&<LoanList rows={state.data.items} onBook={openBook} onReader={openReader} onModal={setModal} onAct={act} disabled={!writesEnabled||busy}/>}
      {state.data.items.length===0&&<div className={s.empty}><BookOpen/><p>Записів за цими умовами немає.</p></div>}<Pager data={state.data as Page} onPage={setPage}/></>}
    </>}
    {bookId&&<BookDetails key={bookId} mutationError={error} id={bookId} epoch={epoch} onReader={openReader} onAct={act} options={options.data} disabled={!writesEnabled||busy} onClose={()=>{setBookId("");setError("");}} onModal={setModal} onArchive={row=>void archive("edition",row)} onImage={()=>setEpoch(x=>x+1)}/>}
    {readerId&&<ReaderDetails key={readerId} mutationError={error} id={readerId} epoch={epoch} disabled={!writesEnabled||busy} onClose={()=>{setReaderId("");setError("");}} onBook={openBook} onReader={openReader} onModal={setModal} onAct={act} onArchive={row=>void archive("reader",row)} onImage={()=>setEpoch(x=>x+1)}/>}
    {modal&&<DraftScope key={modalDraftKey(modal)} draftKey={modalDraftKey(modal)}><Modal routed title={{book:modal.row?.id?"Редагувати книгу":"Нова книга",entity:modal.row?.id?"Картка довідника":"Новий запис",reader:modal.row?.id?"Редагувати користувача":"Новий користувач",copy:"Додати копію",issue:"Видати або зарезервувати",return:"Повернення книг",due:"Подовжити строк",source:"Архів зовнішньої Librarika",country:countryLabel(modal.row?.country),classes:"Звірка класів учнів"}[modal.kind]} busy={busy} onClose={()=>{setModal(null);setError("");}}>{error&&<p className={s.error} role="alert">{error}</p>}
      {modal.kind==="book"&&<BookForm row={modal.row} options={options.data} busy={busy||!writesEnabled} pending={pendingBooks.current.has(modalDraftKey(modal))} onSave={saveBook}/>}
      {modal.kind==="entity"&&<EntityForm options={options.data} onCountry={country=>{setBookId("");setModal({kind:"country",row:{country}});}} onDelete={row=>void archive("entity",row)} row={modal.row||{}} busy={busy||!writesEnabled} onSave={async input=>{if(await act("entity_save",input)){clearLiteratureDraft(modalDraftKey(modal));nav.complete();}}}/>}
      {modal.kind==="reader"&&options.data&&<ReaderForm row={modal.row} options={options.data} busy={busy||!writesEnabled} onSave={async input=>{if(await act("reader_save",input)){clearLiteratureDraft(modalDraftKey(modal));nav.complete();}}}/>}
      {modal.kind==="copy"&&<CopyForm row={modal.row!} options={options.data} busy={busy||!writesEnabled} onSave={async input=>{if(await act("copy_add",input)){clearLiteratureDraft(modalDraftKey(modal));nav.complete();}}}/>}
      {(modal.kind==="issue"||modal.kind==="return")&&<CirculationForm mode={modal.kind} initialReader={modal.reader} initialCopy={modal.row} options={options.data} busy={busy||!writesEnabled} epoch={epoch} onAct={async(a,i)=>{const result=await act(a,i);if(result&&a!=="return")clearLiteratureDraft(modalDraftKey(modal));return result;}} onDone={()=>{clearLiteratureDraft(modalDraftKey(modal));nav.complete();}}/>}
      {modal.kind==="classes"&&<ClassAlignment onBusy={setBusy} disabled={!writesEnabled} onDone={()=>setEpoch(x=>x+1)}/>}
      {modal.kind==="country"&&<CountryLibrary country={String(modal.row?.country||"")} options={options.data} onBook={id=>{setModal(null);openBook(id);}} onAuthor={openEntity}/>}
      {modal.kind==="source"&&admin&&<SourceRefresh onBusy={setBusy} disabled={!writesEnabled} onDone={()=>setEpoch(x=>x+1)}/>}
      {modal.kind==="due"&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await act("due",{circulationId:modal.row!.id,expectedVersion:modal.row!.version,dueAt:f.get("due")})){clearLiteratureDraft(modalDraftKey(modal));nav.complete();}}}><Field name="due" label="Нова дата повернення" type="date" required value={dayAfter(String(modal.row!.due_at||today()).slice(0,10))}/><button className={s.primary} disabled={busy}>Зберегти строк</button></form>}
    </Modal></DraftScope>}
    </main></div></div></RelationNavigation.Provider></CountryNavigation.Provider>;
}


function RelationValue({row,kind}:{row:Row;kind:string}){
 const open=useContext(RelationNavigation),seen=new Set<string>(),items=(row.entities||[]).filter((e:Row)=>e.kind===kind&&(kind!=="author"||["author","coauthor"].includes(e.role))&&!seen.has(e.id)&&!!seen.add(e.id));
 return items.length?<>{items.map((e:Row,i:number)=><span key={e.id}>{i>0?", ":""}<button type="button" className={s.textButton} onClick={()=>open(e)}>{e.name}</button></span>)}</>:<>{row.metadata?.[kind==="tag"?"tags":kind]||"—"}</>;
}
function CatalogCard({row,onBook,children}:{row:Row;onBook:(id:string)=>void;children?:ReactNode}){
 const [expanded,setExpanded]=useState(false);useEffect(()=>{const mq=window.matchMedia("(min-width:761px)"),sync=()=>setExpanded(mq.matches);sync();mq.addEventListener("change",sync);return()=>mq.removeEventListener("change",sync);},[]);
 return <article className={s.bookCard}><BookLink row={row} onBook={onBook}/><p className={s.stock}><strong>{row.copies} прим.</strong>{row.available!==undefined&&<span>{row.available} доступно</span>}</p><details className={s.cardMore} open={expanded} onToggle={e=>setExpanded(e.currentTarget.open)}><summary>Докладніше</summary><dl className={s.cardMetadata}>{[["author","Автор"],["genre","Категорія"],["publisher","Видавництво"],["tag","Теги"]].map(([kind,label])=><div key={kind}><dt>{label}</dt><dd><RelationValue row={row} kind={kind}/></dd></div>)}{row.metadata?.year&&<div><dt>Рік</dt><dd>{row.metadata.year}</dd></div>}{row.metadata?.type&&<div><dt>Тип</dt><dd>{row.metadata.type}</dd></div>}</dl><ActionButtons><button className={s.secondary} onClick={()=>onBook(row.id)}>Повна картка</button></ActionButtons>{children}</details></article>;
}
function EntityInformation({row}:{row:Row}){
 const meta=row.metadata||{},openCountry=useContext(CountryNavigation);
 return <dl className={s.details}>{Object.entries(ENTITY_FIELDS[row.kind]||{}).map(([key,label])=>{
 const value=meta[key]||(key==="dateOfBirth"?meta.yearBorn:key==="dateOfDeath"?meta.yearDied:"");if(!value)return null;const text=String(value);
 const href=key==="website"&&/^https?:\/\//i.test(text)?text:key==="email"&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(text)?"mailto:"+text:key==="phone"&&/[0-9]/.test(text)?"tel:"+text.replace(/[^+0-9]/g,""):"";
 return <div key={key}><dt>{label}</dt><dd>{key==="country"?<button className={s.textButton} onClick={()=>openCountry(countryCode(value))}>{countryLabel(value)}</button>:href?<a href={href} {...(key==="website"?{target:"_blank",rel:"noreferrer"}:{})}>{text}</a>:text}</dd></div>;
 })}</dl>;
}
function EntityPage({id,epoch,onBook,onEdit,onBack,disabled}:{id:string;epoch:number;onBook:(id:string)=>void;onEdit:(row:Row)=>void;onBack:()=>void;disabled:boolean}){
 const [page,setPage]=useRetainedState("entity-page:"+id,1),state=useData<Row>(`${API}?view=entity&id=${encodeURIComponent(id)}`,epoch),books=useData<Page>(`${API}?view=books&entity=${encodeURIComponent(id)}&page=${page}`,epoch),row=state.data;
 return <section className={s.entityPage}><button className={s.textButton} onClick={onBack}>← Назад</button><Busy state={state}/>{row&&<><div className={s.panelHeading}><h2>{row.name}</h2><button className={s.secondary} disabled={disabled} onClick={()=>onEdit(row)}><Pencil size={16}/>Редагувати</button></div><EntityInformation row={row}/><h2>{row.kind==="author"?"Книжки автора":"Видання цього видавництва"} {books.data&&<span className={s.badge}>{books.data.total}</span>}</h2><Busy state={books}/>{books.data&&!books.data.items.length&&<p className={s.empty}>{row.kind==="author"?"Наразі книжок автора в каталозі немає.":"Видань цього видавництва поки немає."}</p>}<div className={s.bookGrid}>{books.data?.items.map(book=><CatalogCard key={book.id} row={book} onBook={onBook}/>)}</div><Pager data={books.data} onPage={setPage}/></>}</section>;
}

function Dashboard({data,onBook,onReader,onIssue,onReturn,onNewReader,onReaders,onOverdue,disabled}:{data:Row;onBook:(id:string)=>void;onReader:(id:string)=>void;onIssue:()=>void;onReturn:()=>void;onNewReader:()=>void;onReaders:()=>void;onOverdue:()=>void;disabled:boolean}){
 const total=Number(data.stats?.current||0)+Number(data.stats?.overdue||0),percentage=total?Number(data.stats.current)/total*100:0;
 return <><div className={s.dashboardTop}><section className={s.panel}><h2>Статистика</h2><div className={s.stats}><div><BookOpen/><strong>{Number(data.stats.copies).toLocaleString("uk-UA")}</strong><span>Примірників</span></div><div><Users/><strong>{Number(data.stats.readers).toLocaleString("uk-UA")}</strong><span>Користувачів</span></div></div></section><section className={s.panel}><h2>Поточні видачі</h2><div className={s.donutLayout}><div role="img" aria-label={`Без прострочення: ${data.stats.current}. Прострочено: ${data.stats.overdue}.`} className={s.donut} style={{background:total?`conic-gradient(#24684d 0 ${percentage}%,#c34848 ${percentage}% 100%)`:"#e1e6e2"}}><span><strong>{total}</strong>на руках</span></div><div><p><i className={s.greenDot}/>{data.stats.current} без прострочення</p><p><i className={s.redDot}/>{data.stats.overdue} прострочено</p></div></div></section><section className={`${s.panel} ${s.chartPanel}`}><h2>Динаміка видач</h2><Activity data={data.activity} from={data.from} to={data.to}/></section></div>
 <div className={s.dashboardMiddle}><section className={s.panel}><h2>Видачі</h2><ActionButtons><button className={s.primary} disabled={disabled} onClick={onIssue}><ArrowLeftRight size={19}/>Видати</button><button className={s.secondary} disabled={disabled} onClick={onReturn}>Повернути</button></ActionButtons></section><section className={s.panel}><h2>Користувачі</h2><ActionButtons><button className={s.primary} disabled={disabled} onClick={onNewReader}><Plus size={18}/>Додати користувача</button><button className={s.secondary} onClick={onReaders}>Переглянути всіх</button></ActionButtons></section></div>
 <div className={s.dashboardBottom}><section className={s.panel}><h2>Нові надходження</h2><div className={s.newBooks}>{data.newBooks.map((row:Row)=><BookLink key={row.id} row={row} onBook={onBook}/>)}</div></section><section className={s.panel}><div className={s.panelHeading}><h2>Прострочені книги</h2><button className={s.textButton} onClick={onOverdue}>Переглянути всіх</button></div>{data.overdue.length?data.overdue.map((row:Row)=><div className={s.overdueRow} key={row.id}><BookLink row={row} onBook={onBook}/><div><button className={s.textButton} onClick={()=>onReader(row.reader_id)}>{row.full_name}</button><p className={s.red}>До {dateLabel(row.due_at)}</p></div></div>):<p className={s.muted}>Прострочених книг немає.</p>}</section></div></>;
}
function Activity({data,from,to}:{data:Row[];from:string;to:string}) { const total=data.reduce((n,r)=>n+Number(r.total),0),max=Math.max(1,...data.map(r=>Math.max(Number(r.students),Number(r.teachers)))),days=Math.max(1,Math.round((Date.parse(to)-Date.parse(from))/86400000)+1),points:Row[]=data.map(r=>({...r,x:30+(Date.parse(r.day)-Date.parse(from))/86400000/Math.max(1,days-1)*470}));return <><p className={s.chartTotal}><strong>{total}</strong> примірників за період</p><svg viewBox="0 0 540 180" className={s.chart} role="img" aria-label={`Видачі з ${dateLabel(from)} до ${dateLabel(to)}: ${total} примірників. Учні та вчителі окремо.`}>{[0,0.5,1].map(value=><g key={value}><line x1="30" x2="515" y1={135-value*105} y2={135-value*105} stroke="#dce5df"/><text x="5" y={139-value*105}>{Math.round(max*value)}</text></g>)}{points.map(r=><g key={r.day}><rect x={r.x-5} y={135-r.students/max*105} width="5" height={r.students/max*105} fill="#24684d"/><rect x={r.x+1} y={135-r.teachers/max*105} width="5" height={r.teachers/max*105} fill="#b7944c"/><title>{dateLabel(r.day)}: учні {r.students}, учителі {r.teachers}, разом {r.total}</title></g>)}<text x="30" y="162">{dateLabel(from)}</text><text x="515" y="162" textAnchor="end">{dateLabel(to)}</text></svg><div className={s.legend}><span><i className={s.greenDot}/>Учні</span><span><i className={s.goldDot}/>Учителі</span></div><details className={s.chartData}><summary>Числа за датами</summary>{data.length?<table><thead><tr><th>Дата</th><th>Учні</th><th>Учителі</th><th>Усього</th></tr></thead><tbody>{data.map(r=><tr key={r.day}><td>{dateLabel(r.day)}</td><td>{r.students}</td><td>{r.teachers}</td><td>{r.total}</td></tr>)}</tbody></table>:<p>За обраний період видач немає.</p>}</details></>; }
function LoanList({rows,onBook,onReader,onModal,onAct,disabled}:{rows:Row[];onBook:(id:string)=>void;onReader:(id:string)=>void;onModal:(state:ModalState)=>void;onAct:(action:string,input:Row)=>Promise<Row|null>;disabled:boolean}) {return <div className={s.loanList}>{rows.map(row=><article className={s.loan} key={row.record_kind+":"+row.id}><BookLink row={row} onBook={onBook}/><div><button className={s.textButton} onClick={()=>onReader(row.reader_id)}>{row.full_name}</button><small>Читацький № {row.member_no}</small></div><div className={s.loanDates}><span>Дата: {dateLabel(row.created_at)}</span>{row.record_kind!=="request"&&<><span>Отримано: {dateLabel(row.issued_at)}</span><span>До: <strong>{dateLabel(row.due_at)}</strong></span></>}{row.received_at&&<span>Повернуто: {dateLabel(row.received_at)}</span>}</div><Status value={row.display_status||row.status}/><ActionButtons>{row.record_kind==="request"&&<><button className={s.secondary} disabled={disabled} onClick={()=>onModal({kind:"issue",reader:{id:row.reader_id},row:{edition_id:row.edition_id,bookRequestId:row.id}})}>Видати</button>{row.status==="requested"&&<button className={s.secondary} disabled={disabled} onClick={async()=>{await onAct("reader_request_status",{id:row.id,expectedVersion:row.version,status:"ready"});}}>Підтвердити бронювання</button>}</>}{["issued","overdue"].includes(row.status)&&<><button className={s.secondary} disabled={disabled} onClick={()=>onModal({kind:"return",reader:{id:row.reader_id},row})}>Повернути</button><button className={s.secondary} disabled={disabled} onClick={()=>onModal({kind:"due",row})}>Подовжити</button></>}{["reserved","pending"].includes(row.status)&&<><button className={s.secondary} disabled={disabled} onClick={()=>onModal({kind:"issue",reader:{id:row.reader_id},row:{...row,id:row.copy_id,reservationId:row.id,expectedReservationVersion:row.version,version:row.copy_version}})}>Видати</button><button className={s.danger} disabled={disabled} onClick={async()=>{if(window.confirm("Скасувати резервування?"))await onAct("cancel",{id:row.id,expectedVersion:row.version});}}>Скасувати</button></>}</ActionButtons></article>)}</div>; }
function BookDetails({mutationError,id,epoch,options,disabled,onClose,onModal,onArchive,onImage,onReader,onAct}:{mutationError:string;id:string;epoch:number;onReader:(id:string)=>void;onAct:(action:string,input:Row)=>Promise<Row|null>;options:Row|null;disabled:boolean;onClose:()=>void;onModal:(state:ModalState)=>void;onArchive:(row:Row)=>void;onImage:()=>void}) {
 const [photo,setPhoto]=useState(false),relation=useContext(RelationNavigation),state=useData<Row>(`${API}?view=book&id=${encodeURIComponent(id)}`,epoch),row=state.data;
 return <Modal routed title="Картка книги" onClose={onClose}>{mutationError&&<p role="alert" className={s.error}>{mutationError}</p>}<Busy state={state}/>{row&&<><div className={s.bookHero}><div className={s.coverActions}><button type="button" className={s.coverButton} disabled={disabled} onClick={()=>setPhoto(true)} aria-label="Змінити обкладинку"><Cover row={row} large/></button><button className={s.textButton} disabled={disabled} onClick={()=>setPhoto(true)}>Змінити обкладинку</button></div><div><h3>{row.title}</h3><p><RelationValue row={row} kind="author"/></p><p>{row.copies.length} примірників · {row.available} доступно</p><ActionButtons><button className={s.secondary} disabled={disabled||row.publication_state==="archived"} onClick={()=>onModal({kind:"book",row})}><Pencil size={17}/>Редагувати</button><button className={s.primary} disabled={disabled||row.publication_state==="archived"} onClick={()=>onModal({kind:"copy",row})}>Додати копію</button><button className={s.danger} disabled={disabled} onClick={()=>onArchive(row)}><Trash2 size={17}/>Видалити</button></ActionButtons></div></div><dl className={s.details}>{Object.entries(BOOK_FIELDS).filter(([key])=>row.metadata[key]&&(!["issueType","issuePeriod"].includes(key)||/журнал|journal|magazine/i.test(String(row.metadata.type)))).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{["author","publisher","genre"].includes(key)&&row.entities.some((x:Row)=>x.kind===key)?<RelationValue row={row} kind={key}/>:key==="url"&&/^https?:\/\//i.test(String(row.metadata[key]))?<a href={row.metadata[key]} target="_blank" rel="noreferrer">{row.metadata[key]}</a>:String(row.metadata[key])}</dd></div>)}</dl><div className={s.entityLinks}>{row.entities.filter((e:Row,i:number,all:Row[])=>all.findIndex(x=>x.id===e.id)===i).map((e:Row)=><button key={`${e.id}-${e.role}`} className={s.secondary} onClick={()=>{const found=options?.entities.find((x:Row)=>x.id===e.id);relation(found||e);}}>{ENTITY_NAMES[e.kind]} · {e.name}</button>)}</div>{photo&&<DraftScope draftKey={"photo:edition:"+row.id+":"+row.version}><LiteraturePhotoEditor id={row.id} kind="edition" version={row.version} onSaved={onImage} onClose={()=>setPhoto(false)}/></DraftScope>}<BookReviews id={id} epoch={epoch} onReader={onReader} onAct={onAct} disabled={disabled}/><h3>Примірники</h3><div className={s.entityList}>{row.copies.map((c:Row)=><div className={s.copyRow} key={c.id}><div><strong>№ {c.accession_no}</strong>{c.copy_no&&<small>Копія {c.copy_no}</small>}<p>{c.location_name||"Місце не зазначено"}</p></div><Status value={c.loan_status||c.physical_state}/><button className={s.secondary} disabled={disabled||c.physical_state!=="on_shelf"||!!c.loan_status} onClick={()=>onModal({kind:"issue",row:{...c,title:row.title,edition_id:row.id}})}>Видати</button></div>)}</div></>}</Modal>;
}
function ReviewIdentity({row,onReader}:{row:Row;onReader:(id:string)=>void}){return <div className={s.person}><Avatar row={row}/><div>{row.reader_id?<button type="button" className={s.textButton} onClick={()=>onReader(row.reader_id)}>{row.author_name}</button>:<strong>{row.author_name}</strong>}<small>{row.reader_kind?kinds[row.reader_kind]:"Тип читача не встановлено"}{row.reader_kind==="student"&&row.class_name?" · "+row.class_name:row.reader_kind==="teacher"&&row.subject_position?" · "+row.subject_position:""}</small><span>{row.rating?"★".repeat(row.rating):""}</span></div></div>;}
function BookReviews({id,epoch,onReader,onAct,disabled}:{id:string;epoch:number;onReader:(id:string)=>void;onAct:(action:string,input:Row)=>Promise<Row|null>;disabled:boolean}){const [page,setPage]=useRetainedState("reviews-page:"+id,1),state=useData<Page>(API+"?view=reviews&edition="+encodeURIComponent(id)+"&page="+page,epoch);useEffect(()=>{if(state.data&&page>Math.max(1,state.data.pages))setPage(Math.max(1,state.data.pages));},[state.data,page]);return <section className={s.bookReviews}><h3>Відгуки читачів {state.data?"· "+state.data.total:""}</h3><Busy state={state}/>{state.data?.items.map(row=><article key={row.origin+row.id} className={s.review}><ReviewIdentity row={row} onReader={onReader}/><p>{row.body}</p><small>{row.date}</small><button type="button" disabled={disabled} className={s.textButton} onClick={async()=>{if(window.confirm("Приховати цей відгук?"))await onAct("review_hide",{id:row.id,origin:row.origin,editionId:row.edition_id,readerId:row.reader_id,expectedVersion:row.version});}}>Приховати відгук</button></article>)}{state.data&&!state.data.total&&<p className={s.muted}>Відгуків про цю книгу ще немає.</p>}{state.data&&state.data.pages>1&&<Pager data={state.data} onPage={setPage}/>}</section>;}
function ReaderDetails({mutationError,id,epoch,disabled,onClose,onBook,onReader,onModal,onAct,onArchive,onImage}:{mutationError:string;id:string;epoch:number;disabled:boolean;onClose:()=>void;onBook:(id:string)=>void;onReader:(id:string)=>void;onModal:(state:ModalState)=>void;onAct:(action:string,input:Row)=>Promise<Row|null>;onArchive:(row:Row)=>void;onImage:()=>void}) {
 const [photo,setPhoto]=useState(false),[page,setPage]=useRetainedState("reader-page:"+id,1),[status,setStatus]=useRetainedState("reader-status:"+id,"issued"),state=useData<Row>(`${API}?view=reader&id=${encodeURIComponent(id)}`,epoch),loans=useData<Page>(`${API}?view=loans&reader=${encodeURIComponent(id)}&status=${status}&page=${page}`,epoch),row=state.data;
 return <Modal routed title="Картка користувача" onClose={onClose}>{mutationError&&<p role="alert" className={s.error}>{mutationError}</p>}<Busy state={state}/>{row&&<><div className={s.person}><Avatar row={row} large zoomable/><div><h3>{row.full_name}</h3><p>№ {row.member_no} · {row.class_name||row.source_group_label||kinds[row.kind]}</p>{row.linked_teacher_user_id?<TeacherDirectoryFields row={row}/>:row.kind==="teacher"&&row.subject_position&&<p>Предмет / напрям: {row.subject_position}</p>}<details><summary>Контакти й підключення</summary>{!row.linked_teacher_user_id&&<p>Телефон: {row.phone||"не вказано"}</p>}{row.email&&<p>Email: {row.email}</p>}<p>Telegram: {row.telegram_status==="active"?"підключено":"не підключено"}</p></details></div></div><ActionButtons><button className={s.secondary} disabled={disabled} onClick={()=>onModal({kind:"reader",row})}>Редагувати</button><button className={s.primary} disabled={disabled} onClick={()=>onModal({kind:"issue",reader:row})}>Видати книгу</button><a className={s.secondary} href={`${API}?view=export&reader=${encodeURIComponent(id)}&status=all`} download><Download size={17}/>Excel — книги читача</a><button className={s.danger} disabled={disabled} onClick={()=>onArchive(row)}>Видалити</button></ActionButtons>{row.linked_teacher_user_id?<TeacherDirectoryLink/>:<button className={s.secondary} disabled={disabled} onClick={()=>setPhoto(true)}>Змінити фото читача</button>}{photo&&!row.linked_teacher_user_id&&<DraftScope draftKey={"photo:reader:"+row.id+":"+row.version}><LiteraturePhotoEditor id={row.id} kind="reader" version={row.version} onSaved={onImage} onClose={()=>setPhoto(false)}/></DraftScope>}<ReaderAccess row={row} disabled={disabled} onChanged={onImage}/><label>Книги<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="issued">На руках</option><option value="reserved">Заброньовані</option><option value="all">Уся історія</option></select></label><Busy state={loans}/>{loans.data&&<><LoanList rows={loans.data.items} onBook={onBook} onReader={onReader} onModal={onModal} onAct={onAct} disabled={disabled}/>{!loans.data.items.length&&<p className={s.muted}>Книг у цьому переліку немає.</p>}<Pager data={loans.data} onPage={setPage}/></>}</>}</Modal>;
}
function BookForm({row,options,busy,pending,onSave}:{row?:Row;options:Row|null;busy:boolean;pending:boolean;onSave:(input:Row,photo:PreparedPhoto|null)=>Promise<void>}) {
 const [type,setType]=useDraftState("type",String(row?.metadata?.type||"Книга")),[year,setYear]=useDraftState("year",String(row?.metadata?.year||"")),[isbn,setIsbn]=useDraftState("isbn",String(row?.metadata?.isbn13||"")),[photo,setPhoto]=useDraftState<PreparedPhoto|null>("cover-draft",null),[photoOpen,setPhotoOpen]=useState(false);
 const mapping:Record<string,string>={author:"author",genre:"genre",publisher:"publisher",tag:"tags",series:"series"};
 const initial=(kind:string):Choice[]=>{const linked=(row?.entities||[]).filter((x:Row)=>x.kind===kind&&x.role===kind);return linked.length?linked.map((x:Row)=>({id:x.id,label:x.name})):row?.metadata?.[mapping[kind]]&&!(kind==="author"&&row?.entities?.some((x:Row)=>x.role==="coauthor"))?[{id:"",label:String(row.metadata[mapping[kind]])}]:[];};
 return <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),meta:Record<string,string>=Object.fromEntries(Object.keys(BOOK_FIELDS).map(key=>[key,String(f.get(key)||"")])),entityIds:string[]=[],entityNames:Record<string,string[]>={};meta.type=type;
 for(const [kind,field]of Object.entries(mapping)){const values=json(f.get("entities:"+kind),[]) as Choice[];meta[field]=values.map(x=>x.label).join(", ");entityIds.push(...values.filter(x=>x.id).map(x=>x.id));entityNames[kind]=values.filter(x=>!x.id).map(x=>x.label);}
 await onSave({...row?.id?{id:row.id,expectedVersion:row.version,expectedMaterialVersion:row.material_version}:{},title:f.get("title"),metadata:meta,entityIds:Array.from(new Set(entityIds)),entityNames,published:row?.publication_state!=="draft"},photo);
 }}><fieldset disabled={busy||pending} className={s.formFields}><div className={s.newBookPhoto}>{photo?<img src={"data:image/jpeg;base64,"+photo.base64} alt="Обкладинка нової книги"/>:row?<Cover row={row}/>:<BookOpen size={34}/>}<div><strong>Обкладинка</strong><button type="button" className={s.secondary} onClick={()=>setPhotoOpen(true)}>{photo?"Змінити фото":"Додати фото · галерея або камера"}</button></div></div>{photoOpen&&<DraftScope draftKey={"book-cover-editor:"+(row?.id||"new")}><LiteraturePhotoEditor kind="edition" onPrepared={setPhoto} onClose={()=>setPhotoOpen(false)}/></DraftScope>}<Field name="title" label="Назва книги" required value={row?.title}/><div className={s.formGrid}>
 <label>Тип матеріалу<select value={type} onChange={e=>setType(e.target.value)}>{Array.from(new Set([type,"Книга","Журнал","Газета","Аудіокнига","Інше"])).map(v=><option key={v}>{v}</option>)}</select></label>
 <SuggestInput label="Рік" name="year" value={year} onChange={setYear} options={(options?.years||[]).map((y:string)=>({id:y,label:y}))} placeholder="Рік видання"/>
 {Object.entries(mapping).map(([kind,field])=><EntityPicker key={kind} kind={kind} label={BOOK_FIELDS[field]} initial={initial(kind)} options={(options?.entities||[]).filter((x:Row)=>x.kind===kind).map((x:Row)=>({id:x.id,label:x.name,detail:x.countryLabel}))}/>)}
 <div className={s.isbnField}><label>ISBN-13<input name="isbn13" value={isbn} onChange={e=>setIsbn(e.target.value)} inputMode="numeric"/></label><ReaderScanner label="Сканувати ISBN" format="isbn" className={s.secondary} disabled={busy} onDetected={setIsbn}/></div>
 {Object.entries(BOOK_FIELDS).filter(([key])=>!["type","year","isbn13",...Object.values(mapping)].includes(key)&&!(['issueType','issuePeriod'].includes(key)&&!/журнал|journal|magazine/i.test(type))).map(([key,label])=><Field key={key} name={key} label={label} value={row?.metadata?.[key]||(key==="url"?row?.metadata?.referenceUrl:"")} long={["annotation","description"].includes(key)}/>)}
 </div><p className={s.muted}>Оберіть підказку або введіть нову назву. Нові записи довідників збережуться разом із книгою.</p></fieldset><button className={s.primary} disabled={busy||!options}>{pending?"Повторити збереження фото":"Зберегти книгу"}</button></form>;
}
function EntityForm({row,busy,onSave,onDelete,onCountry,options}:{options:Row|null;onCountry:(country:string)=>void;onDelete:(row:Row)=>void;row:Row;busy:boolean;onSave:(input:Row)=>Promise<void>}) {
 const state=useData<Page>(row.id?`${API}?view=entities&kind=${row.kind}&id=${encodeURIComponent(row.id)}`:null),full=state.data?.items.find(x=>x.id===row.id)||row,meta=full.metadata||json(full.public_metadata_json),[editing,setEditing]=useState(!row.id||!!row.editing);
 if(row.id&&(state.loading||state.error))return <Busy state={state}/>;
 if(row.id&&!editing)return <><Busy state={state}/><h3>{row.name}</h3><dl className={s.details}>{Object.entries(ENTITY_FIELDS[row.kind]||{}).map(([key,label])=>{const value=meta[key]||(key==="dateOfBirth"?meta.yearBorn:key==="dateOfDeath"?meta.yearDied:"");return value?<div key={key}><dt>{label}</dt><dd>{key==="country"?<button className={s.textButton} onClick={()=>onCountry(countryCode(value))}>{countryLabel(value)}</button>:key==="website"&&/^https?:\/\//.test(String(value))?<a href={value} target="_blank" rel="noreferrer">{value}</a>:String(value)}</dd></div>:null;})}</dl><ActionButtons><button className={s.primary} disabled={busy||!full.version} onClick={()=>setEditing(true)}>Редагувати</button><button className={s.danger} disabled={busy||!full.version} onClick={()=>onDelete(full)}>Видалити</button></ActionButtons></>;
 return <EntityEdit key={full.id?`${full.id}:${full.version}`:"new"} full={full} meta={meta} kind={row.kind} options={options} busy={busy} onSave={onSave}/>;
}
function EntityEdit({full,meta,kind,options,busy,onSave}:{full:Row;meta:Row;kind:string;options:Row|null;busy:boolean;onSave:(input:Row)=>Promise<void>}){
 const [name,setName]=useDraftState("entity-name",String(full.name||"")),[country,setCountry]=useDraftState("country",countryLabel(meta.country));
 const countries=Array.from(new Set((options?.entities||[]).map((x:Row)=>x.countryLabel).filter(Boolean))) as string[];
 return <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const metadata=Object.fromEntries(Object.keys(ENTITY_FIELDS[kind]||{}).map(key=>[key,key==="country"?countryCode(country):String(f.get(key)||"")]));await onSave({...full.id?{id:full.id,expectedVersion:full.version}:{},kind,name,metadata});}}>
 <SuggestInput label={kind==="author"?"Повне ім’я автора":"Назва"} name="name" required value={name} onChange={setName} options={(options?.entities||[]).filter((x:Row)=>x.kind===kind&&x.id!==full.id).map((x:Row)=>({id:x.id,label:x.name}))}/>
 <div className={s.formGrid}>{Object.entries(ENTITY_FIELDS[kind]||{}).map(([key,label])=>key==="country"?<SuggestInput key={key} label={label} value={country} onChange={setCountry} options={countries.map(c=>({id:c,label:c}))}/>:<Field key={key} name={key} label={label} value={meta[key]||(key==="dateOfBirth"?meta.yearBorn:key==="dateOfDeath"?meta.yearDied:"")} long={key==="biography"||key==="description"}/>)}</div><button className={s.primary} disabled={busy}>Зберегти</button></form>;
}
function CountryLibrary({country,options,onBook,onAuthor}:{country:string;options:Row|null;onBook:(id:string)=>void;onAuthor:(row:Row)=>void}){
 const [page,setPage]=useRetainedState("country-page:"+country,1),state=useData<Page>(`${API}?view=books&country=${encodeURIComponent(country)}&page=${page}`),authors=(options?.entities||[]).filter((x:Row)=>x.kind==="author"&&x.countryCode===country);
 return <><h3>Автори · {countryLabel(country)}</h3><div className={s.countryAuthors}>{authors.map((a:Row)=><button key={a.id} type="button" className={s.secondary} onClick={()=>onAuthor(a)}>{a.name}</button>)}</div><h3>Книги цих авторів</h3><Busy state={state}/><div className={s.bookGrid}>{state.data?.items.map(row=><article key={row.id} className={s.bookCard}><BookLink row={row} onBook={onBook}/><p><RelationValue row={row} kind="author"/></p></article>)}</div>{state.data&&!state.data.items.length&&<p className={s.muted}>Книг за цим запитом немає.</p>}<Pager data={state.data} onPage={setPage}/></>;
}
function ReaderForm({row,options,busy,onSave}:{row?:Row;options:Row|null;busy:boolean;onSave:(input:Row)=>Promise<void>}) {
 const [kind,setKind]=useDraftState("reader-kind",row?.kind||"student"),[classId,setClassId]=useDraftState("class-id",String(row?.class_year_id||"")),[className,setClassName]=useDraftState("class-name",String(row?.class_name||"")),[group,setGroup]=useDraftState("source-group",String(row?.source_group_label||""));
 if(row?.linked_teacher_user_id)return <section><h3>{row.full_name}</h3><TeacherDirectoryFields row={row}/><p className={s.muted}>Фото й дані цього вчителя автоматично оновлюються з головного довідника. Читацький номер та історія видач зберігаються.</p><TeacherDirectoryLink/></section>;
 return <form onSubmit={async e=>{e.preventDefault();if(kind==="student"&&className&&!classId){e.currentTarget.querySelector<HTMLInputElement>('[role="combobox"]')?.focus();return;}const f=new FormData(e.currentTarget);await onSave({...row?.id?{id:row.id,expectedVersion:row.version}:{},fullName:f.get("name"),kind,phone:f.get("phone"),...(!row?.linked_teacher_user_id?{subjectPosition:kind==="teacher"?f.get("subject")||"":""}:{}),groupLabel:group,classYearId:kind==="student"?classId:""});}}><Field label="ПІБ" name="name" required value={row?.full_name}/><p className={s.muted}>{row?`Читацький № ${row.member_no}`:"Читацький номер створиться автоматично після збереження."}</p><div className={s.formGrid}><label>Категорія<select value={kind} onChange={e=>setKind(e.target.value)} disabled={!!row?.linked_teacher_user_id}>{Object.entries(kinds).map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label><Field label="Мобільний телефон" name="phone" type="tel" value={row?.phone}/><SuggestInput label="Клас / група з джерела" source={choiceSource("group")} value={group} onChange={setGroup} options={(options?.classes||[]).map((c:Row)=>({id:c.id,label:c.class_name,detail:c.label}))}/>
 {kind==="teacher"&&(row?.linked_teacher_user_id?<p>Предмет / напрям: {row.subject_position||"не вказано"} (з кабінету вчителя)</p>:<Field label="Предмет / напрям" name="subject" value={row?.subject_position}/>)}{kind==="student"&&<div><SuggestInput source={choiceSource("class")} label="Поточний клас" value={className} onChange={v=>{setClassName(v);setClassId("");}} onPick={c=>setClassId(c.id)} options={(options?.classes||[]).map((c:Row)=>({id:c.id,label:c.class_name,detail:c.label}))}/>{className&&!classId&&<small className={s.muted}>Оберіть точний клас із підказки.</small>}</div>}</div><button className={s.primary} disabled={busy||kind==="student"&&!!className&&!classId}>Зберегти користувача</button></form>;
}
function CopyForm({row,options,busy,onSave}:{row:Row;options:Row|null;busy:boolean;onSave:(input:Row)=>Promise<void>}) {return <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await onSave({editionId:row.id,expectedEditionVersion:row.version,accessionNo:f.get("number")||"",copyNo:f.get("copy")||"",locationId:f.get("location"),condition:f.get("condition")});}}><div className={s.bookHero}><Cover row={row}/><h3>{row.title}</h3></div><div className={s.formGrid}><Field name="number" label="Номер доступу (автоматично, якщо порожньо)"/><Field name="copy" label="Позначення копії"/><LocationSelect options={options}/><ConditionSelect/></div><button className={s.primary} disabled={busy||!options}>Додати примірник</button></form>; }
function LocationSelect({options,value}:{options:Row|null;value?:string}) {const initial=(options?.locations||[]).find((x:Row)=>x.id===(value||"LOC-LRK-MAIN")),[choice,setChoice]=useDraftState<Choice|null>("location",initial?{id:initial.id,label:initial.name}:null);return <RecordPicker label="Місце в бібліотеці" name="location" required value={choice} onChange={setChoice} source={choiceSource("location")} options={(options?.locations||[]).map((x:Row)=>({id:x.id,label:x.name}))}/>; }
function ConditionSelect({value="good"}:{value?:string}){const [condition,setCondition]=useDraftState("condition",value);return <label>Стан примірника<select name="condition" value={condition} onChange={e=>setCondition(e.target.value)}>{[["good","Добрий"],["worn","Зношений"],["damaged","Пошкоджений"],["unspecified","Не зазначено"]].map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label>;}

type CirculationProps={mode:"issue"|"return";initialReader?:Row;initialCopy?:Row;options:Row|null;busy:boolean;epoch:number;onAct:(action:string,input:Row)=>Promise<Row|null>;onDone:()=>void};
function CirculationForm(props:CirculationProps){return props.mode==="issue"?<IssueWizard {...props}/>:<ReturnForm {...props}/>;}
function IssueWizard({initialReader,initialCopy,busy,epoch,onAct,onDone}:CirculationProps){
 const [step,setStep]=useDraftState("issue-step",initialReader?initialCopy?3:2:1),[readerId,setReaderId]=useDraftState("issue-reader-id",String(initialReader?.id||"")),[editionId,setEditionId]=useDraftState("issue-edition-id",String(initialCopy?.edition_id||"")),[copyId,setCopyId]=useDraftState("issue-copy-id",String(initialCopy?.copy_id||initialCopy?.id||""));
 const [readerSearch,setReaderSearch]=useDraftState("issue-reader-search",""),[bookSearch,setBookSearch]=useDraftState("issue-book-search","");
 const [issued,setIssued]=useDraftState("issued",today()),[due,setDue]=useDraftState("due",dayAfter(today())),[dueEdited,setDueEdited]=useDraftState("due-edited",false),[action,setAction]=useDraftState("issue-action","issue");
 const reader=useData<Row>(readerId?`${API}?view=reader&id=${encodeURIComponent(readerId)}`:null,epoch),book=useData<Row>(editionId?`${API}?view=book&id=${encodeURIComponent(editionId)}`:null,epoch);
 const available=(book.data?.copies||[]).filter((c:Row)=>c.registration==="registered"&&c.physical_state==="on_shelf"&&(!c.loan_status||initialCopy?.reservationId&&c.id===initialCopy.id));
 useEffect(()=>{if(book.data?.id===editionId&&!copyId&&available.length===1)setCopyId(available[0].id);},[book.data,editionId,copyId]);
 useModalStepBack(()=>{if(step>1&&!busy){setStep(step-1);return true;}return false;});
 const chooseBook=(b:Row)=>{if(editionId!==b.id)setCopyId("");setEditionId(b.id);setStep(3);};
 return <div className={s.wizard}>
  <ol className={s.steps} aria-label="Етапи видачі">{["Читач","Книжка","Оформлення"].map((label,i)=><li key={label} aria-current={step===i+1?"step":undefined}><span>{i+1}.</span> {label}{i<2&&<span aria-hidden="true"> →</span>}</li>)}</ol>
  {step>1&&<button type="button" className={s.backStep} disabled={busy} onClick={()=>setStep(step-1)}><ArrowLeft size={17}/>Назад</button>}
  {step===1&&<section className={s.wizardStep}><SuggestInput label="Знайти читача" value={readerSearch} onChange={v=>{setReaderSearch(v);setReaderId("");}} source={choiceSource("reader")} onPick={c=>{setReaderId(c.id);setStep(2);}} placeholder="ПІБ або читацький номер"/>{readerId&&reader.data&&<button type="button" className={s.secondary} onClick={()=>setStep(2)}>Продовжити · {reader.data.full_name}</button>}</section>}
  {step===2&&<section className={s.wizardStep}>{reader.data&&<p className={s.chosenReader}>{reader.data.full_name} · № {reader.data.member_no}</p>}<SuggestInput label="Знайти книжку" value={bookSearch} onChange={v=>{setBookSearch(v);setEditionId("");setCopyId("");}} source={choiceSource("book")} onPick={c=>chooseBook({id:c.id})} placeholder="Назва, автор або ISBN"/>{editionId&&book.data&&<button type="button" className={s.secondary} onClick={()=>setStep(3)}>Продовжити · {book.data.title}</button>}</section>}
  {step===3&&<section className={s.wizardStep}><Busy state={reader}/><Busy state={book}/>{reader.data&&book.data&&<form onSubmit={async e=>{e.preventDefault();const copy=available.find((c:Row)=>c.id===copyId);if(!copy||busy||reader.loading||book.loading)return;const result=await onAct(action,{copyId,expectedCopyVersion:copy.version,readerId,expectedReaderVersion:reader.data!.version,issuedAt:issued,dueAt:due,confirmation:"ISSUE_THIS_COPY",...(initialCopy?.bookRequestId?{bookRequestId:initialCopy.bookRequestId}:{}),...(initialCopy?.reservationId&&copyId===initialCopy.id?{reservationId:initialCopy.reservationId,expectedReservationVersion:initialCopy.expectedReservationVersion}:{})});if(result)onDone();}}>
   <div className={s.issueSummary}><div className={s.person}><Avatar row={reader.data}/><div><strong>{reader.data.full_name}</strong><small>№ {reader.data.member_no} · {reader.data.class_name||reader.data.source_group_label||kinds[reader.data.kind]}</small></div></div><div className={s.bookHero}><Cover row={book.data}/><div><h3>{book.data.title}</h3><p>{book.data.metadata.author}</p></div></div></div>
   <RecordPicker label="Примірник" required value={available.some((c:Row)=>c.id===copyId)?{id:copyId,label:"№ "+available.find((c:Row)=>c.id===copyId).accession_no}:null} onChange={c=>setCopyId(c?.id||"")} options={available.map((c:Row)=>({id:c.id,label:"№ "+c.accession_no,detail:c.location_name||"Бібліотека"}))}/>{!available.length&&<p className={s.notice}>Доступних примірників немає. Оберіть іншу книжку.</p>}
   <div className={s.formGrid}><label>Дата видачі / резервування<input type="date" required value={issued} onInput={e=>{const value=e.currentTarget.value;setIssued(value);if(!dueEdited&&value)setDue(dayAfter(value));}} onChange={e=>{setIssued(e.target.value);if(!dueEdited&&e.target.value)setDue(dayAfter(e.target.value));}}/></label><label>Повернути до<input type="date" required min={issued} value={due} onInput={e=>{setDue(e.currentTarget.value);setDueEdited(true);}} onChange={e=>{setDue(e.target.value);setDueEdited(true);}}/><button type="button" className={s.textButton} onClick={()=>{setDue(dayAfter(issued||today()));setDueEdited(false);}}>+7 днів від видачі</button></label><label>Дія<select value={action} onChange={e=>setAction(e.target.value)}><option value="issue">Видати</option>{!initialCopy?.reservationId&&!initialCopy?.bookRequestId&&<option value="reserve">Зарезервувати</option>}</select></label></div><div className={s.wizardFooter}><button className={s.primary} disabled={busy||!available.some((c:Row)=>c.id===copyId)}>{busy?"Зберігаємо…":action==="issue"?"Підтвердити видачу":"Зарезервувати примірник"}</button></div>
  </form>}</section>}
 </div>;
}

function ReturnForm({initialReader,options,busy,epoch,onAct}:CirculationProps) {
 const [readerId,setReaderId]=useDraftState("return-reader",String(initialReader?.id||"")),[search,setSearch]=useDraftState("return-search",""),[loanPage,setLoanPage]=useDraftState("return-page",1);
 const reader=useData<Row>(readerId?`${API}?view=reader&id=${encodeURIComponent(readerId)}`:null,epoch),loans=useData<Page>(readerId?`${API}?view=loans&status=issued&reader=${encodeURIComponent(readerId)}&page=${loanPage}`:null,epoch);
 return <div className={s.circulation}>{readerId&&<Busy state={reader}/>}<SuggestInput label="Знайти читача" value={search} source={choiceSource("reader")} onChange={v=>{setSearch(v);setReaderId("");}} onPick={c=>{setReaderId(c.id);setLoanPage(1);}} placeholder="Прізвище, ім’я або читацький номер"/>

 {readerId&&reader.data&&<section className={s.selection}><div className={s.person}><Avatar row={reader.data}/><div><h3>{reader.data.full_name}</h3><p>№ {reader.data.member_no} · {reader.data.class_name||reader.data.source_group_label||kinds[reader.data.kind]}</p></div></div></section>}
 {readerId&&<><Busy state={loans}/>{!loans.loading&&loans.data?.items.map(l=><DraftScope key={l.id} draftKey={"return-loan:"+l.id+":"+l.version}><form className={s.returnForm} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const result=await onAct("return",{circulationId:l.id,expectedCirculationVersion:l.version,expectedCopyVersion:l.copy_version,returnLocationId:f.get("location"),condition:f.get("condition"),returnedAt:f.get("returned"),confirmation:"RETURN_THIS_COPY"});if(result)clearLiteratureDraft("return-loan:"+l.id+":"+l.version);}}><div className={s.bookHero}><Cover row={l}/><div><h3>{l.title}</h3><p>№ {l.accession_no} · до {dateLabel(l.due_at)}</p><Status value={l.display_status}/></div></div><div className={s.formGrid}><LocationSelect options={options} value={l.location_id}/><ConditionSelect value={l.condition}/><Field name="returned" label="Дата повернення" type="date" value={today()} required/></div><button className={s.primary} disabled={busy}>Підтвердити повернення</button></form></DraftScope>)}{loans.data&&!loans.data.items.length&&<p className={s.notice}>У цього читача немає неповернутих книг.</p>}<Pager data={loans.data} onPage={setLoanPage}/></>}
 </div>;
}
