"use client";
/* eslint-disable @next/next/no-img-element */
import {useCallback,useEffect,useRef,useState,type FormEvent} from "react";
import {ArrowDownToLine,ArrowUpFromLine,BookOpen,LayoutDashboard,LibraryBig,MessageCircle,Plus,ScanLine,Users,X} from "lucide-react";
import {READER_LOGO,readerDate,readerFetch} from "@/app/reader/reader-types";
import EditionEditor from "./edition-editor";
import {librarianSectionHref,librarianToolHref} from "../_components/librarian-routes";
import ReaderScanner from "@/app/reader/reader-scanner";
import s from "@/app/reader/reader.module.css";
type Row=Record<string,string|number|null>;
type Options={classes:Row[];teachers:Row[];locations:Row[];telegram?:{enabled:boolean;botUsername:string|null}};
const label:Record<string,string>={issued:"На руках",overdue:"Прострочено",returned:"Повернено",pending:"Очікує",reserved:"Зарезервовано",cancelled:"Скасовано",requested:"Замовлено",ready:"Готово до видачі",fulfilled:"Видано",rejected:"Відхилено",active:"Активний",inactive:"Не приєднано",blocked:"Доступ вимкнено",on_shelf:"У бібліотеці",on_loan:"На руках",unknown:"Не звірено",withdrawn:"Списано",draft:"Не опубліковано",published:"Опубліковано",unreconciled:"Очікує перенесення"};
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Kyiv"}).format(new Date());
export default function LiteratureWorkspace({writesEnabled,admin,telegramMiniApp=false}:{writesEnabled:boolean;admin:boolean;telegramMiniApp?:boolean}){
  const [tab,setTab]=useState("dashboard"),[stats,setStats]=useState<Row>({}),[readers,setReaders]=useState<Row[]>([]),[rows,setRows]=useState<Row[]>([]),[options,setOptions]=useState<Options>({classes:[],teachers:[],locations:[]}),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[modal,setModalState]=useState<{kind:string;row:Row}|null>(null),[codes,setCodes]=useState<Row[]>([]),[code,setCode]=useState(""),[reviews,setReviews]=useState<Row[]>([]),[reports,setReports]=useState<Row[]>([]),[invite,setInvite]=useState<{readerId:string;token:string;purpose:string;expiresAt:string}|null>(null);
  const intent=useRef<{key:string;id:string}|null>(null),generation=useRef(0),copyGeneration=useRef(0),viewRef=useRef(tab),refreshRef=useRef<()=>Promise<void>>(async()=>{});
  viewRef.current=tab;
  function setModal(value:React.SetStateAction<{kind:string;row:Row}|null>){copyGeneration.current++;setInvite(null);setModalState(value);}

  const loadReaders=useCallback(async()=>{setReaders((await readerFetch<{result:Row[]}>("/api/librarian/readers")).result);},[]);
  const refresh=useCallback(async()=>{const run=++generation.current;try{const url=new URL("/api/librarian/readers",window.location.origin);url.searchParams.set("view",tab==="catalog"?"editions":tab);url.searchParams.set("q",query);url.searchParams.set("status",status);
    if(tab==="dashboard"){const data=await readerFetch<{result:Row}>(url.href);if(run===generation.current&&viewRef.current===tab)setStats(data.result);}
    else if(tab==="moderation"){const data=await readerFetch<{result:{reviews:Row[];reports:Row[]}}>(url.href);if(run===generation.current&&viewRef.current===tab){setReviews(data.result.reviews);setReports(data.result.reports);}}
    else if(["readers","circulations","requests","catalog"].includes(tab)){const data=await readerFetch<{result:Row[]}>(url.href);if(run===generation.current&&viewRef.current===tab)setRows(data.result);}
  }catch(e){if(run===generation.current&&viewRef.current===tab)setError((e as Error).message);}},[tab,query,status]);
  refreshRef.current=refresh;
  useEffect(()=>{const timer=setTimeout(()=>void refresh(),200);return()=>{clearTimeout(timer);generation.current++;};},[refresh]);
  useEffect(()=>{void loadReaders().catch(()=>{});readerFetch<{result:Options}>("/api/librarian/readers?view=options").then(data=>setOptions(data.result)).catch(e=>setError(e.message));},[loadReaders]);
  function navigate(value:string){generation.current++;viewRef.current=value;setTab(value);setRows([]);setQuery("");setStatus("all");setError("");}
  async function act(action:string,input:Record<string,unknown>){if(busy||!writesEnabled)return null;const key=JSON.stringify({action,input});if(intent.current?.key!==key)intent.current={key,id:crypto.randomUUID()};setBusy(true);setError("");setNotice("");try{const data=await readerFetch<{result:Row}>("/api/librarian/readers",{action,input:{...input,...(action==="invite"?{}:{requestId:intent.current.id})}});intent.current=null;setNotice("Дію збережено.");await Promise.all([refreshRef.current(),loadReaders()]).catch(()=>setNotice("Дію збережено. Оновіть списки, коли відновиться зв’язок."));return data.result;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
  async function scan(value:string){const run=++copyGeneration.current;setCode(value);setError("");try{let decoded=value;if(value.startsWith("https://")){const url=new URL(value);if(url.origin!==window.location.origin)throw new Error("Це код іншого сайту.");decoded=url.searchParams.get("copy")||url.searchParams.get("book")||"";}const data=await readerFetch<{result:Row[]}>("/api/librarian/readers?view=copies&code="+encodeURIComponent(decoded));if(run===copyGeneration.current)setCodes(data.result);}catch(e){setError((e as Error).message);}}
  async function copies(edition:Row){setModal({kind:"copies",row:edition});const run=++copyGeneration.current;setCodes([]);try{const data=await readerFetch<{result:Row[]}>("/api/librarian/readers?view=copies&edition="+encodeURIComponent(String(edition.id)));if(run===copyGeneration.current)setCodes(data.result);}catch(e){setError((e as Error).message);}}
  function inputForm(event:FormEvent<HTMLFormElement>){event.preventDefault();return new FormData(event.currentTarget);}
  function copyCards(){return codes.length===0?<p className={s.muted}>Примірників не знайдено.</p>:codes.map(copy=><article className={s.loan} key={String(copy.id)}><div className={s.loanContent}><strong>{copy.title}</strong><p>№ {copy.accession_no} · прим. {copy.copy_no} · {label[String(copy.physical_state)]||copy.physical_state}</p></div>{copy.registration==="registered"&&copy.physical_state==="on_shelf"&&<button className={s.button} disabled={!writesEnabled||busy} onClick={()=>setModal({kind:"issue",row:{...copy,request_id:modal?.row.request_id||null,request_reader_id:modal?.row.request_reader_id||null}})}>Видати</button>}{copy.registration==="registered"&&copy.physical_state==="on_shelf"&&<button className={s.quiet} disabled={busy||!writesEnabled} onClick={()=>setModal({kind:"copy_move",row:copy})}>Місце / стан</button>}{copy.circulation_id&&<button className={s.secondary} onClick={()=>{setModal(null);navigate("circulations");setQuery(String(copy.title));}}>Переглянути видачу</button>}</article>);}
  return <div className={s.shell}><header className={s.header}><a className={s.brand} href={librarianSectionHref("home",telegramMiniApp)}><img src={READER_LOGO} alt="Лейбл бібліотеки"/><span><strong>Єдина бібліотека</strong><small>Міжнародний ліцей МАУП</small></span></a><a className={s.secondary} href={librarianSectionHref("home",telegramMiniApp)}>Усі інструменти</a></header><div className={s.layout}><nav className={s.sidebar} aria-label="Література та читачі">{[["dashboard","Огляд",LayoutDashboard],["catalog","Фонд",LibraryBig],["readers","Читачі",Users],["circulations","Видачі",BookOpen],["requests","Замовлення",ArrowUpFromLine],["moderation","Модерація",MessageCircle]].map(([id,name,Icon])=>{const Symbol=Icon as typeof BookOpen;return <button key={String(id)} className={tab===id?s.active:""} onClick={()=>navigate(String(id))}><Symbol size={20}/>{String(name)}</button>;})}<div className={s.sideNote}><a href={librarianToolHref("catalog",telegramMiniApp)}>Підручники й посібники ↗</a><br/><a href="/library">Каталог для читачів ↗</a></div></nav><main className={s.main}>
    <div className={s.sectionHead}><div><p className={s.eyebrow}>Кабінет бібліотекаря · Фонд</p><h1>Художня та наукова література</h1></div><button className={s.quiet} onClick={()=>void refresh()}>Оновити</button></div><div className={s.funds}><a className={s.quiet} href={librarianToolHref("catalog",telegramMiniApp)}>Підручники й посібники</a><span className={s.button}>Художня та наукова література</span></div>
    {error&&<p className={s.error} role="alert">{error}</p>}{notice&&<p className={s.notice} role="status">{notice}</p>}{!writesEnabled&&<p className={s.notice}>Запис тимчасово вимкнено; доступний перегляд.</p>}
    {tab==="dashboard"&&<><div className={s.stats}>{[["titles","Видань"],["copies","Примірників"],["readers","Читачів"],["issued","На руках"],["requested","Замовлень"],["reports","Скарг до розгляду"]].map(([key,name])=><div className={s.stat} key={key}><strong>{stats[key]||0}</strong><span>{name}</span></div>)}</div><div className={s.actions}><button className={s.button} onClick={()=>setModal({kind:"scan",row:{}})}><ScanLine size={18}/>Сканувати код</button><button className={s.secondary} onClick={()=>setModal({kind:"scan",row:{}})}><ArrowUpFromLine size={18}/>Видати книгу</button><button className={s.secondary} onClick={()=>navigate("circulations")}><ArrowDownToLine size={18}/>Повернути книгу</button><button className={s.secondary} disabled={!writesEnabled} onClick={()=>setModal({kind:"reader",row:{}})}><Plus size={18}/>Додати читача</button><button className={s.secondary} disabled={!writesEnabled||busy} onClick={()=>setModal({kind:"edition",row:{}})}>Додати книгу</button></div><p className={s.notice}>Початкові залишки під час перенесення визначаються за реєстром Librarika. Це не замінює фізичної інвентаризації. Особисті видачі читачам не дублюють класні відомості підручників.</p>{admin&&<p><a href="/librarian/migration">Стан перенесення та резервні копії</a></p>}</>}
    {["readers","circulations","catalog"].includes(tab)&&<div className={s.toolbar}><label className={s.search}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={tab==="readers"?"Ім’я або номер читача…":"Назва книги або ім’я читача…"} aria-label="Пошук у розділі"/></label>{tab==="circulations"&&<select aria-label="Стан видачі" value={status} onChange={e=>setStatus(e.target.value)}>{[["all","Усі"],["pending","Запити з Librarika"],["reserved","Зарезервовано"],["issued","На руках"],["overdue","Прострочено"],["returned","Повернено"],["cancelled","Скасовано"]].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select>}{tab==="readers"&&<button className={s.button} disabled={!writesEnabled} onClick={()=>setModal({kind:"reader",row:{}})}>Додати читача</button>}</div>}
    {tab==="readers"&&<div className={s.loanList}>{rows.map(row=><article className={s.loan} key={String(row.id)}><div className={s.loanContent}><button onClick={()=>setModal({kind:"reader",row})}>{row.full_name}</button><p>Квиток № {row.member_no} · {row.class_name||row.source_group_label||"Клас не зазначено"} · Книг на руках: {row.loan_count}</p></div><span className={s.badge}>{row.linked_teacher_user_id&&row.access_status==="active"?"Кабінет учителя":label[String(row.access_status)]||row.access_status}</span><button className={s.secondary} onClick={()=>setModal({kind:"reader",row})}>Картка читача</button></article>)}</div>}
    {tab==="catalog"&&<div className={s.loanList}>{rows.filter(row=>!query||String(row.title).toLocaleLowerCase("uk").includes(query.toLocaleLowerCase("uk"))).map(row=><article className={s.loan} key={String(row.id)}><div className={s.loanContent}><button onClick={()=>void copies(row)}>{row.title}</button><p>{row.isbn13} · {label[String(row.publication_state)]}</p></div><button className={s.secondary} onClick={()=>void copies(row)}>Примірники</button>{row.material_id&&<button className={s.quiet} disabled={busy||!writesEnabled} onClick={()=>setModal({kind:"edition",row})}>Редагувати</button>}<a className={s.quiet} href={`/library?book=${row.id}`} target="_blank" rel="noopener noreferrer">Картка книги ↗</a></article>)}</div>}
    {tab==="circulations"&&<div className={s.loanList}>{rows.map(row=><article className={s.loan} key={String(row.id)}>{row.cover_url&&<img src={String(row.cover_url)} alt=""/>}<div className={s.loanContent}><strong>{row.title}</strong><p>{row.full_name} · квиток № {row.member_no} · примірник № {row.accession_no}</p><p>{readerDate(String(row.issued_at||""))} — {readerDate(String(row.due_at||""))}{row.received_at&&` · повернено ${readerDate(String(row.received_at))}`}</p></div><span className={`${s.badge} ${["issued","overdue"].includes(String(row.status))&&row.due_at&&String(row.due_at).slice(0,10)<today()?s.overdue:""}`}>{["issued","overdue"].includes(String(row.status))&&row.due_at&&String(row.due_at).slice(0,10)<today()?"Прострочено":label[String(row.status)]}</span>{["issued","overdue"].includes(String(row.status))&&row.accounting_mode==="native"&&<div className={s.actions}><button className={s.button} disabled={!writesEnabled} onClick={()=>setModal({kind:"return",row})}>Повернути</button><button className={s.quiet} disabled={!writesEnabled} onClick={()=>setModal({kind:"due",row})}>Змінити строк</button></div>}</article>)}</div>}
    {tab==="requests"&&<div className={s.loanList}>{rows.map(row=><article className={s.loan} key={String(row.id)}><div className={s.loanContent}><strong>{row.title}</strong><p>{row.full_name} · № {row.member_no} · {row.note}</p></div><span className={s.badge}>{label[String(row.status)]}</span>{["requested","ready"].includes(String(row.status))&&<div className={s.actions}><button className={s.secondary} disabled={busy||!writesEnabled} onClick={()=>void act("request_status",{id:row.id,expectedVersion:row.version,status:"ready"})}>Готово</button><button className={s.quiet} onClick={()=>void copies({id:row.edition_id,title:row.title,request_id:row.id,request_reader_id:row.reader_id})}>Обрати примірник</button><button className={s.quiet} disabled={busy||!writesEnabled} onClick={()=>{if(window.confirm("Відхилити це замовлення?"))void act("request_status",{id:row.id,expectedVersion:row.version,status:"rejected"});}}>Відхилити</button></div>}</article>)}</div>}
    {tab==="moderation"&&<><h2 className={s.heading}>Відгуки перед публікацією</h2>{reviews.length===0&&<p className={s.muted}>Нових відгуків немає.</p>}{reviews.map(row=><article className={s.panel} style={{marginTop:15}} key={String(row.edition_id)+row.reader_id}><strong>{row.title} · {row.rating} / 5</strong><p className={s.muted}>{row.display_name}</p><p className={s.bodyText}>{row.body}</p><div className={s.actions}><button className={s.button} disabled={busy||!writesEnabled} onClick={()=>void act("moderate",{kind:"review",editionId:row.edition_id,readerId:row.reader_id,expectedVersion:row.version,publish:true})}>Опублікувати</button><button className={s.quiet} disabled={busy||!writesEnabled} onClick={()=>void act("moderate",{kind:"review",editionId:row.edition_id,readerId:row.reader_id,expectedVersion:row.version,publish:false})}>Приховати</button></div></article>)}<h2 className={s.heading} style={{marginTop:30}}>Скарги учасників</h2>{reports.length===0&&<p className={s.muted}>Відкритих скарг немає.</p>}{reports.map(row=><article className={s.panel} style={{marginTop:15}} key={String(row.id)}><strong>Від {row.reporter_name}</strong><p className={s.bodyText}>Причина: {row.reason}</p><blockquote className={s.notice}>{row.author_name}: {row.body||"Картка книги"}</blockquote><div className={s.actions}><button className={s.danger} disabled={busy||!writesEnabled} onClick={()=>void act("moderate",{kind:"report",id:row.id,hideMessage:true})}>Приховати повідомлення</button><button className={s.quiet} disabled={busy||!writesEnabled} onClick={()=>void act("moderate",{kind:"report",id:row.id,hideMessage:false})}>Закрити без приховування</button></div></article>)}</>}
    {["readers","circulations","requests","catalog"].includes(tab)&&rows.length===0&&<p className={s.empty}>Записів за цими умовами немає.</p>}
    {modal&&<AdminModal title={modal.kind==="edition"?"Картка книги":modal.kind==="copy_add"?"Новий примірник":modal.kind==="copy_move"?"Місце, стан або списання":modal.kind==="reader"?modal.row.id?String(modal.row.full_name):"Новий читач":modal.kind==="issue"?"Видача примірника":modal.kind==="return"?"Повернення примірника":modal.kind==="due"?"Строк повернення":modal.kind==="copies"?String(modal.row.title):"Сканувати книгу"} onClose={()=>{if(!busy){setModal(null);setInvite(null);}}}>
      {modal.kind==="edition"&&<EditionEditor id={modal.row.id?String(modal.row.id):undefined} writesEnabled={writesEnabled} onBusy={setBusy} onSaved={()=>{setModal(null);void refreshRef.current();}}/>}
      {error&&<p className={s.error} role="alert">{error}</p>}{["scan","copies"].includes(modal.kind)&&<><div className={s.actions}><ReaderScanner onDetected={value=>void scan(value)}/><input className={s.input} aria-label="Код книги" value={code} onChange={e=>setCode(e.target.value)} placeholder="Бібліотечний код або ISBN"/><button className={s.secondary} onClick={()=>void scan(code)}>Знайти</button></div>{modal.kind==="copies"&&modal.row.material_id&&<button className={s.button} disabled={busy||!writesEnabled} onClick={()=>setModal({kind:"copy_add",row:modal.row})}>Додати примірник</button>}{copyCards()}</>}
      {modal.kind==="reader"&&<><form key={String(modal.row.id||"new")} onSubmit={async e=>{const form=inputForm(e),result=await act("save",{...(modal.row.id?{id:modal.row.id,expectedVersion:modal.row.version}:{}),fullName:form.get("name"),memberNo:form.get("member"),kind:form.get("kind"),classYearId:form.get("class")||null});if(result)setModal(null);}}><div className={s.fields}><label className={s.field}>Повне ім’я<input name="name" defaultValue={String(modal.row.full_name||"")} required minLength={3} maxLength={180}/></label><label className={s.field}>Номер читацького квитка<input name="member" defaultValue={String(modal.row.member_no||"")} required maxLength={50}/></label><label className={s.field}>Категорія<select name="kind" defaultValue={String(modal.row.kind||"student")}>{[["student","Учень / учениця"],["teacher","Учитель"],["staff","Працівник"],["other","Інший читач"],["unclassified","Потребує звірки"]].map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><label className={s.field}>Поточний клас<select name="class" defaultValue={String(modal.row.class_year_id||"")}><option value="">Без призначеного класу</option>{options.classes.map(row=><option value={String(row.id)} key={String(row.id)}>{row.class_name} · {row.year_label}</option>)}</select><small>У джерелі: {modal.row.source_group_label||"не зазначено"}. Клас не вгадується автоматично.</small></label></div><div className={s.actions}><button className={s.button} disabled={busy||!writesEnabled}>Зберегти картку</button></div></form>
      {modal.row.id&&<>{!!modal.row.has_photo&&<img className={s.avatar} src={`/api/librarian/readers/${encodeURIComponent(String(modal.row.id))}/photo`} alt="Фото читача"/>}<p className={s.muted}>Телефон: {modal.row.phone||"не вказано"} · Ім’я у спільноті: {modal.row.display_name||"не обрано"}</p><div className={s.actions}>{!modal.row.linked_teacher_user_id&&["web","telegram"].map(purpose=><button key={purpose} className={s.secondary} disabled={busy||!writesEnabled||modal.row.access_status==="blocked"||(purpose==="telegram"&&!options.telegram?.botUsername)} onClick={async()=>{if(!window.confirm(`Створити персональне запрошення для ${modal.row.full_name}? Передайте його тільки цьому читачу.`))return;const result=await act("invite",{readerId:modal.row.id,purpose,expectedVersion:modal.row.version});if(result){setInvite({...result,readerId:String(modal.row.id)} as unknown as typeof invite);setModalState(current=>current?.row.id===modal.row.id?{...current,row:{...current.row,version:result.readerVersion}}:current);}}}>Запрошення: {purpose==="web"?"сайт":"Telegram"}</button>)}<button className={s.danger} disabled={busy||!writesEnabled} onClick={async()=>{const action=modal.row.access_status==="blocked"?"unblock":"disable";if(window.confirm(action==="disable"?"Вимкнути читацький доступ, усі сеанси та нагадування? Книги й історія залишаться.":"Зняти блокування? Раніше звірений учитель зможе знову користуватися своїм кабінетом; іншим читачам потрібне нове персональне запрошення.")){if(await act("access",{readerId:modal.row.id,expectedVersion:modal.row.version,action,confirmation:"CONFIRM_READER_ACCESS"}))setModal(null);}}}>{modal.row.access_status==="blocked"?"Зняти блокування":"Вимкнути доступ"}</button></div>
      {invite&&invite.readerId===modal.row.id&&<div className={s.notice}><strong>Персональне покликання — показано лише зараз</strong><p className={s.muted}>Діє до {new Date(invite.expiresAt).toLocaleString("uk-UA")}. Не публікуйте його у груповому чаті.</p><input className={s.input} style={{width:"100%"}} readOnly value={invite.purpose==="telegram"&&options.telegram?.botUsername?`https://t.me/${options.telegram.botUsername}?start=ra_${invite.token}`:window.location.origin+"/reader#invite="+invite.token} aria-label="Персональне запрошення" onFocus={e=>e.target.select()}/><p className={s.muted}>{invite.purpose==="telegram"?"Відкриття в Telegram здійснюється через приватний чат бота; бібліотекар передає персональне запрошення адресату.":"Відкрити на особистому пристрої читача."}</p></div>}
      {!modal.row.linked_teacher_user_id&&modal.row.kind!=="student"&&<details className={s.notice}><summary>Звірити з кабінетом учителя</summary><form onSubmit={async e=>{const form=inputForm(e);if(await act("teacher_link",{readerId:modal.row.id,expectedVersion:modal.row.version,teacherUserId:form.get("teacher"),confirmation:form.get("confirmation")}))setModal(null);}}><label className={s.field}>Існуючий учитель<select name="teacher" required><option value="">Оберіть точний профіль</option>{options.teachers.map(row=><option key={String(row.id)} value={String(row.id)}>{row.full_name}</option>)}</select></label><label className={s.field}>Введіть його повне ім’я для підтвердження<input name="confirmation" required/></label><p className={s.muted}>Звірте особу, а не лише схожість імен. Створення нового вчителя не потрібне.</p><button className={s.button} disabled={busy||!writesEnabled}>Приєднати до кабінету вчителя</button></form></details>}</>}
      </>}
      {modal.kind==="issue"&&<form key={String(modal.row.id)} onSubmit={async e=>{const form=inputForm(e),reader=readers.find(row=>row.id===form.get("reader"));if(!reader){setError("Оберіть читача.");return;}if(await act("issue",{copyId:modal.row.id,expectedCopyVersion:modal.row.version,readerId:reader.id,expectedReaderVersion:reader.version,...(modal.row.request_id?{bookRequestId:modal.row.request_id}:{}),issuedAt:form.get("issued"),dueAt:form.get("due"),confirmation:"ISSUE_THIS_COPY"}))setModal(null);}}><p className={s.notice}>{modal.row.title} · примірник № {modal.row.accession_no}</p><label className={s.field}>Кому видати<select name="reader" required defaultValue={String(modal.row.request_reader_id||"")}><option value="">Оберіть читача</option>{readers.filter(row=>row.status==="active"&&(!modal.row.request_reader_id||row.id===modal.row.request_reader_id)).map(row=><option key={String(row.id)} value={String(row.id)}>{row.full_name} · № {row.member_no} · {row.class_name||row.source_group_label}</option>)}</select></label><div className={s.fields} style={{marginTop:16}}><label className={s.field}>Дата видачі<input type="date" name="issued" defaultValue={today()} required/></label><label className={s.field}>Повернути до<input type="date" name="due" required/></label></div><p className={s.muted}>Кнопка нижче фіксує фактичну видачу саме цього примірника обраному читачу.</p><button className={s.button} disabled={busy||!writesEnabled}>Підтвердити видачу</button></form>}
      {modal.kind==="copy_add"&&<form onSubmit={async e=>{const form=inputForm(e);if(await act("copy_register",{editionId:modal.row.id,expectedEditionVersion:modal.row.version,accessionNo:form.get("accession"),copyNo:form.get("number"),locationId:form.get("location"),condition:form.get("condition")}))setModal(null);}}><p className={s.notice}>{modal.row.title}</p><label className={s.field}>Бібліотечний / інвентарний номер<input name="accession" required maxLength={80}/></label><label className={s.field}>Номер примірника<input name="number" maxLength={40}/></label><CopyPlacement options={options} row={{}}/><div className={s.actions}><button className={s.button} disabled={busy||!writesEnabled}>Зареєструвати фактичне надходження</button></div></form>}
      {modal.kind==="copy_move"&&<form onSubmit={async e=>{const form=inputForm(e),action=form.get("action");if(action==="withdraw"&&!window.confirm("Списати саме цей примірник? Історія збережеться; залишок зменшиться на одну книгу."))return;if(await act("copy_move",{copyId:modal.row.id,expectedVersion:modal.row.version,action,locationId:form.get("location"),condition:form.get("condition"),note:form.get("note"),confirmation:"CONFIRM_COPY_MOVEMENT"}))setModal(null);}}><p className={s.notice}>{modal.row.title} · № {modal.row.accession_no}</p><label className={s.field}>Дія<select name="action"><option value="transfer">Змінити місце або стан</option><option value="withdraw">Списати примірник</option></select></label><CopyPlacement options={options} row={modal.row}/><label className={s.field}>Примітка / причина списання<textarea name="note" maxLength={1000}/></label><button className={s.button} disabled={busy||!writesEnabled}>Підтвердити зміну обліку</button></form>}
      {modal.kind==="return"&&<form onSubmit={async e=>{const form=inputForm(e);if(await act("return",{circulationId:modal.row.id,expectedCirculationVersion:modal.row.version,expectedCopyVersion:modal.row.copy_version,returnLocationId:form.get("location"),condition:form.get("condition"),returnedAt:form.get("date"),confirmation:"RETURN_THIS_COPY"}))setModal(null);}}><p className={s.notice}>{modal.row.title}<br/>{modal.row.full_name} · примірник № {modal.row.accession_no}</p><div className={s.fields}><label className={s.field}>Дата повернення<input name="date" type="date" defaultValue={today()} required/></label><label className={s.field}>Куди повернуто<select name="location" defaultValue={String(modal.row.location_id)} required>{options.locations.map(row=><option key={String(row.id)} value={String(row.id)}>{row.name}</option>)}</select></label><label className={s.field}>Стан примірника<select name="condition" defaultValue={String(modal.row.condition||"unspecified")}><option value="unspecified">Не зазначено</option><option value="good">Добрий</option><option value="worn">Зношений</option><option value="damaged">Пошкоджений</option></select></label></div><div className={s.actions}><button className={s.button} disabled={busy||!writesEnabled}>Підтвердити фактичне повернення</button></div></form>}
      {modal.kind==="due"&&<form onSubmit={async e=>{const form=inputForm(e);if(await act("due",{circulationId:modal.row.id,expectedVersion:modal.row.version,dueAt:form.get("date")}))setModal(null);}}><p className={s.notice}>{modal.row.full_name} · {modal.row.title}</p><label className={s.field}>Новий строк повернення<input name="date" type="date" defaultValue={String(modal.row.due_at||"").slice(0,10)} required/></label><div className={s.actions}><button className={s.button} disabled={busy||!writesEnabled}>Зберегти новий строк</button></div></form>}
    </AdminModal>}
  </main></div></div>;
}
function AdminModal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog ref={ref} className={s.dialog} onCancel={e=>{e.preventDefault();onClose();}}><div className={s.dialogInner}><div className={s.dialogTop}><h2>{title}</h2><button className={s.iconButton} onClick={onClose} aria-label="Закрити"><X/></button></div><div style={{marginTop:22}}>{children}</div></div></dialog>;}
function CopyPlacement({options,row}:{options:Options;row:Row}){return <div className={s.fields}><label className={s.field}>Місце<select name="location" defaultValue={String(row.location_id||"")} required><option value="">Оберіть місце</option>{options.locations.map(item=><option key={String(item.id)} value={String(item.id)}>{item.name}</option>)}</select></label><label className={s.field}>Стан<select name="condition" defaultValue={String(row.condition||"good")}><option value="good">Добрий</option><option value="worn">Зношений</option><option value="damaged">Пошкоджений</option><option value="unspecified">Не зазначено</option></select></label></div>;}
