import {
  ArchiveRestore,
  ArchiveX,
  ArrowRight,
  ArrowRightLeft,
  Bell,
  BellOff,
  BookCopy,
  BookDown,
  BookOpenCheck,
  BookPlus,
  BookUp,
  CalendarClock,
  CalendarPlus,
  CalendarSync,
  ChartColumn,
  Camera,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleOff,
  ClipboardCheck,
  ClipboardList,
  ContactRound,
  Copy,
  DoorOpen,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileDown,
  FileUp,
  House,
  ImagePlus,
  Info,
  KeyRound,
  LibraryBig,
  Link2,
  ListFilter,
  LoaderCircle,
  LockKeyhole,
  LogOut,
  MapPin,
  MoveHorizontal,
  PackageOpen,
  PencilLine,
  Plus,
  QrCode,
  RefreshCw,
  RotateCcw,
  ScanBarcode,
  School,
  Search,
  Send,
  Settings2,
  Share2,
  ShoppingBasket,
  ShoppingCart,
  Trash2,
  Unlink,
  UserRound,
  UsersRound,
  X,
  type LucideIcon,
} from "lucide-react";

const SITE_ICONS = {
  home: House,
  fund: LibraryBig,
  circulation: BookOpenCheck,
  requests: ClipboardList,
  visits: CalendarClock,
  teachers: UsersRound,
  acquisitions: ShoppingBasket,
  management: Settings2,
  catalog: Search,
  "new-material": BookPlus,
  receipt: PackageOpen,
  transfer: MoveHorizontal,
  count: ClipboardCheck,
  writeoff: ArchiveX,
  "issue-teacher": BookUp,
  return: BookDown,
  "issue-class": BookCopy,
  "return-class": ArchiveRestore,
  "academic-year": CalendarPlus,
  "class-create": School,
  "class-update": PencilLine,
  "class-close": LockKeyhole,
  "class-reopen": RotateCcw,
  rollover: CalendarSync,
  locations: DoorOpen,
  contacts: ContactRound,
  orders: ShoppingCart,
  "teacher-acquisition": BookPlus,
  loans: BookOpenCheck,
  notifications: Bell,
  telegram: Send,
  more: Ellipsis,
  security: KeyRound,
  external: ExternalLink,
  logout: LogOut,
  search: Search,
  scan: ScanBarcode,
  camera: Camera,
  "image-add": ImagePlus,
  refresh: RefreshCw,
  copy: Copy,
  export: FileDown,
  import: FileUp,
  success: CircleCheck,
  error: CircleAlert,
  info: Info,
  delete: Trash2,
  close: X,
  next: ArrowRight,
  swap: ArrowRightLeft,
  previous: ChevronLeft,
  forward: ChevronRight,
  expand: ChevronDown,
  add: Plus,
  edit: PencilLine,
  "calendar-add": CalendarPlus,
  "mark-read": CheckCheck,
  "bell-off": BellOff,
  link: Link2,
  unlink: Unlink,
  visible: Eye,
  hidden: EyeOff,
  filter: ListFilter,
  location: MapPin,
  share: Share2,
  qr: QrCode,
  loading: LoaderCircle,
  "read-only": CircleOff,
  profile: UserRound,
  reports: ChartColumn,
} satisfies Record<string, LucideIcon>;

export type SiteIconName = keyof typeof SITE_ICONS;

export type SiteIconProps = {
  name: SiteIconName;
  className?: string;
  size?: number;
  strokeWidth?: number;
};

export default function SiteIcon({
  name,
  className,
  size = 20,
  strokeWidth = 2,
}: SiteIconProps) {
  const Icon = SITE_ICONS[name];
  return (
    <Icon
      aria-hidden="true"
      className={["site-icon", name === "loading" ? "site-icon--loading" : "", className].filter(Boolean).join(" ")}
      focusable="false"
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth
    />
  );
}
