export type VerifiedIsbnCandidate = {
  materialId: string;
  title: string;
  author: string;
  publicationYear: number | null;
  isbn: string;
  evidenceUrl: string;
  evidenceLabel: string;
};

// Generated by scripts/build-isbn-enrichment-queue.mjs from edition-specific
// evidence. Ambiguous editions, duplicate cards and title-only guesses stay out.
export const VERIFIED_ISBN_CANDIDATES = [
  {
    "materialId": "CAT-0038",
    "title": "Українська мова. Швидкі тести — 2 клас",
    "author": "Попова Н.",
    "publicationYear": 2016,
    "isbn": "9786177115204",
    "evidenceUrl": "https://balka-book.com/ua/ukrayinska_mova_2_klas-843/shvidki_testi_ukrayinska_mova_2_klas-38273",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0039",
    "title": "Я дружу зі словом — 2 клас",
    "author": "Пономарьова К.",
    "publicationYear": 2020,
    "isbn": "9786177485208",
    "evidenceUrl": "https://www.megakniga.com.ua/catalog/knigi/serednya-shkola/shkarpetki-panchohi-dityachi/2-2-9786177485208.html",
    "evidenceLabel": "megakniga.com.ua"
  },
  {
    "materialId": "CAT-0062",
    "title": "Математика. Довідник у таблицях — 1–4 класи",
    "author": "Бачинська І.",
    "publicationYear": 2019,
    "isbn": "9789662844337",
    "evidenceUrl": "https://ula-books.com.ua/molodsha-shkola/01794-matematika-14-klasi",
    "evidenceLabel": "ula-books.com.ua"
  },
  {
    "materialId": "CAT-0070",
    "title": "Робота над помилками на уроках української мови у 1-4 к. 1 ч.",
    "author": "Мачнева О.",
    "publicationYear": 2018,
    "isbn": "9786170032751",
    "evidenceUrl": "https://knigoland.com.ua/robota-nad-pomilkami-na-urokakh-ukr-movi-u-1-4-kl-met-sistema-oprats-vsikh-orfogr-za-alg-chast-1-item",
    "evidenceLabel": "knigoland.com.ua"
  },
  {
    "materialId": "CAT-0084",
    "title": "Ранкові зустрічі. Картки, матеріали для вчителів 1-4 к.",
    "author": "",
    "publicationYear": 2018,
    "isbn": "9789667492922",
    "evidenceUrl": "https://balka-book.com/ua/rozrobki_urokiv_1_klas-1072/nush_kartki_rankovi_zustrichi_1_4_kl_materiali_dlya_vchitelya_32_dvostoronni_kartki_ukr-90918",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0086",
    "title": "Символи України. 1-4 класи",
    "author": "Станіславська Г.",
    "publicationYear": 2011,
    "isbn": "9789661011730",
    "evidenceUrl": "https://mybook.biz.ua/ua/vihovannya-shkolyariv/simvoli-ukraini-hata-1-4-klasi-posibnik-dlya-vchitelya/",
    "evidenceLabel": "mybook.biz.ua"
  },
  {
    "materialId": "CAT-0106",
    "title": "Уроки літературного читання 1 ч. — 2 клас",
    "author": "Вашуленко О.",
    "publicationYear": 2014,
    "isbn": "9786176563778",
    "evidenceUrl": "https://balka-book.com/ua/rozrobki_urokiv_2_klas-1073/uroki_literaturnogo_chitannya_2_klas_navchalniy_posibnik_dlya_vchitelya_u_dvoh_chastinah_1ch_vashulenko_o_v-33142#lg=1&slide=0",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0146",
    "title": "Математика. Індивідуальні роботи — 1 клас",
    "author": "Козак М.",
    "publicationYear": 2020,
    "isbn": "9789660733992",
    "evidenceUrl": "https://books-shop.com.ua/product/matematyka-indyvidualni-roboty-1-klas/",
    "evidenceLabel": "books-shop.com.ua"
  },
  {
    "materialId": "CAT-0192",
    "title": "Книжка для читання з творчими завданнями — 3 клас",
    "author": "Коченгіна М.",
    "publicationYear": 2021,
    "isbn": "9786170965172",
    "evidenceUrl": "https://dumka.top/1-11-klasy-vse-dlya-schkoly/3-klas-nush/3-klas-zoshyty-nush/pozaklasne-chytannya-3-klas-nush/nush-3-klas-dyvokolo-knyzhka-dlya-dodatkovogo-chytannya-kochengina-m-v-9786170965172",
    "evidenceLabel": "dumka.top"
  },
  {
    "materialId": "CAT-0208",
    "title": "Канікули без нудьги. Я іду в 3 клас — 3 клас",
    "author": "Будна Н.",
    "publicationYear": 2024,
    "isbn": "9789661089487",
    "evidenceUrl": "https://www.yakaboo.ua/ua/kanikuli-bez-nud-gi-ja-idu-v-3-j-klas-nush.html?srsltid=AfmBOoodNrmkSs4RApzemxKrz0c0SZZciSG8sx5k88ytw20-_IuY02FW",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0217",
    "title": "Позакласне читання — 4 клас",
    "author": "Марченко В.",
    "publicationYear": 2018,
    "isbn": "9786176565475",
    "evidenceUrl": "https://dumka.top/1-11-klasy-vse-dlya-schkoly/4-klas-nush/4-klas-zoshyty/pozaklasne-chytannya-4-klas/nush-4-klas-pozaklasne-chytannya-chytayu-zalyubky-marchenko-v-s-978-617-656-547-5-1",
    "evidenceLabel": "dumka.top"
  },
  {
    "materialId": "CAT-0245",
    "title": "Паростки. Майстер-клас із написання есе — 4 клас",
    "author": "Лабащук О.",
    "publicationYear": 2019,
    "isbn": "9789660731271",
    "evidenceUrl": "https://mistgrani.com/parostki-mayster-klas-iz-napisannya-ese-4-kl",
    "evidenceLabel": "mistgrani.com"
  },
  {
    "materialId": "CAT-0274",
    "title": "Я досліджую світ 1 ч. — 1 клас",
    "author": "Будна Н.",
    "publicationYear": 2018,
    "isbn": "9789661055185",
    "evidenceUrl": "https://www.yakaboo.ua/ja-doslidzhuju-svit-konspekti-urokiv-1-klas-u-2-chastinah-chastina-1-posibnik-dlja-vchitelja.html?gad_source=1&gad_campaignid=22698815994&gbraid=0AAAAADoya-Z4ZwAzkNdy_D0zdBrXBeqig&gclid=CjwKCAjw9uPCBhATEiwABHN9Kw77bnJbqYUliq21HjEKbRIHJ_oggdrlDdmS4JhY8M0G_tL-m8_czxoCdYYQAvD_BwE",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0276",
    "title": "Нові години спілкування — 1 клас",
    "author": "Брязгіна Я.",
    "publicationYear": 2016,
    "isbn": "9786170027108",
    "evidenceUrl": "https://mybook.biz.ua/vospitanie-shkolnikov/vihovna-robota-1-klas-novi-godini-spilkuvannya-rozrobki-vihovnih-zahodiv-na-arkushah-z-perforacieyu/",
    "evidenceLabel": "mybook.biz.ua"
  },
  {
    "materialId": "CAT-0306",
    "title": "Календарне планування за програмою Шияна Р. — 3 клас",
    "author": "Жаркова І.",
    "publicationYear": 2021,
    "isbn": "9789660737068",
    "evidenceUrl": "https://knigoland.com.ua/kalendarne-planuvannya-za-programoyu-r-shiyana-3-klas-2020-2021-n-r-item",
    "evidenceLabel": "knigoland.com.ua"
  },
  {
    "materialId": "CAT-0317",
    "title": "Математика. Завдання для відпрацювання навичок — 4 клас",
    "author": "Володарська М.",
    "publicationYear": 2016,
    "isbn": "9786170026514",
    "evidenceUrl": "https://mybook.biz.ua/ua/metodika-vikladannya-navchalno-metodichna-literatura/matematika-4-klas-zavdannya-dlya-vidpracyuvannya-navichok/",
    "evidenceLabel": "mybook.biz.ua"
  },
  {
    "materialId": "CAT-0321",
    "title": "Тематичні дні у 4 класі — 4 клас",
    "author": "Маценко Н.",
    "publicationYear": 2021,
    "isbn": "9786170040015",
    "evidenceUrl": "https://knigoland.com.ua/tematichni-dni-u-4-mu-klasi-nur064-item",
    "evidenceLabel": "knigoland.com.ua"
  },
  {
    "materialId": "CAT-0322",
    "title": "Ранкові зустрічі І с. — 4 клас",
    "author": "Сигида С.",
    "publicationYear": 2021,
    "isbn": "9786170040060",
    "evidenceUrl": "https://knigoland.com.ua/rankovi-zustrichi-4klas-i-semestr-nur065-item",
    "evidenceLabel": "knigoland.com.ua"
  },
  {
    "materialId": "CAT-0325",
    "title": "Сходинками знань. Тематичне оцінювання — 4 клас",
    "author": "Безкоровайна О.",
    "publicationYear": 2016,
    "isbn": "9786176862970",
    "evidenceUrl": "https://www.yakaboo.ua/ua/shodinkami-znan-4-klas-tematichne-ocinjuvannja-4-klas-do-pidruchnika-zaharijchuk.html?srsltid=AfmBOoo50B-Oa1eug5_EUV4wixIHUqMmdPGHh1lJwNBxpEs5AlzO0ihA",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0358",
    "title": "Українська мова. Діагностувальні роботи — 5 клас",
    "author": "Панчук Г.",
    "publicationYear": 2024,
    "isbn": "9789660740556",
    "evidenceUrl": "https://balka-book.com/ukrayinska_mova_5_klas-950/ukranska-mova-dagnostuvaln-roboti-5-klas-za-progr-n-golub-o-goroshkno-199414?lang=ua",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0360",
    "title": "Українська мова. Робочий зошит. Ч. 2 — 5 клас",
    "author": "Ткачук Т.",
    "publicationYear": 2022,
    "isbn": "9789661073912",
    "evidenceUrl": "https://balka-book.com/ukrayinska_mova_5_klas-950/ukranska-mova-ntegrovaniy-kurs-robochiy-zoshit-za-modelnoyu-programoyu-o-zabolotnogo-ta-n-chastina-2-237208?lang=ua",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0371",
    "title": "Логіка. Зошит-конспект — 5 клас",
    "author": "Буковська О.",
    "publicationYear": 2021,
    "isbn": "9786176568025",
    "evidenceUrl": "https://www.knigoray.com.ua/5-klas-uk/logika-zoshit-konspekt-5-klas-bukovska-vasileva-9786176568025/",
    "evidenceLabel": "knigoray.com.ua"
  },
  {
    "materialId": "CAT-0376",
    "title": "Етика. Поточне та підсумкове оцінювання — 5 клас",
    "author": "Данилевська О.",
    "publicationYear": 2022,
    "isbn": "9789669453457",
    "evidenceUrl": "https://knigoland.com.ua/nush-5-klas-etika-zoshit-potochne-i-pidsumkove-otsinyuvannya-pbw-item",
    "evidenceLabel": "knigoland.com.ua"
  },
  {
    "materialId": "CAT-0378",
    "title": "Мистецтво. Робочий зошит — 5 клас",
    "author": "Масол Л.",
    "publicationYear": 2022,
    "isbn": "9789669833532",
    "evidenceUrl": "https://balka-book.com/mistetstvo_5_klas-941/mistetstvo_5_klas_robochiy_zoshit_albom-203629?lang=ua",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0407",
    "title": "Українська мова. Діагностувальні роботи — 6 клас",
    "author": "Панчук Г.",
    "publicationYear": 2024,
    "isbn": "9789660741805",
    "evidenceUrl": "https://www.yakaboo.ua/ua/ukrains-ka-mova-6-klas-zoshit-dlja-diagnostuval-nih-robit-3057870.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0416",
    "title": "Атлас. Всесвітня історія — 6 клас",
    "author": "",
    "publicationYear": 2020,
    "isbn": "9789664551431",
    "evidenceUrl": "https://grammata.kiev.ua/products/3134",
    "evidenceLabel": "grammata.kiev.ua"
  },
  {
    "materialId": "CAT-0423",
    "title": "Пізнаємо природу. Робочий зошит — 6 клас",
    "author": "Левчук О.",
    "publicationYear": 2023,
    "isbn": "9789661113441",
    "evidenceUrl": "https://www.geneza.ua/product/1144",
    "evidenceLabel": "geneza.ua"
  },
  {
    "materialId": "CAT-0424",
    "title": "Географія. Атлас (НУШ) — 6 клас",
    "author": "",
    "publicationYear": 2024,
    "isbn": "9789669466242",
    "evidenceUrl": "https://kgf.com.ua/index.php?route=product/product&path=62_122&product_id=429",
    "evidenceLabel": "kgf.com.ua"
  },
  {
    "materialId": "CAT-0427",
    "title": "Зошит для практичних робіт — 6 клас",
    "author": "Картографія",
    "publicationYear": 2023,
    "isbn": "9789669461124",
    "evidenceUrl": "https://kgf.com.ua/index.php?route=product/product&path=116&product_id=1096",
    "evidenceLabel": "kgf.com.ua"
  },
  {
    "materialId": "CAT-0428",
    "title": "Географія. Контрольні роботи — 6 клас",
    "author": "Зінкевич М.",
    "publicationYear": null,
    "isbn": "9789663089430",
    "evidenceUrl": "https://aston.te.ua/catalog/diahnostuvalni-tematychni-roboty-z-heohrafiia-6-klas/",
    "evidenceLabel": "aston.te.ua"
  },
  {
    "materialId": "CAT-0430",
    "title": "Фінансова грамотність. Робочий зошит — 6 клас",
    "author": "",
    "publicationYear": 2022,
    "isbn": "9789669441607",
    "evidenceUrl": "https://dumka.top/1-11-klasy-vse-dlya-schkoly/6-klas-nush/6-klas-zoshyty-ta-albomy/finansova-gramotnist-6-klas-zoshyty/finansovo-gramotnyj-spozhyvach-6-klas-robochyj-zoshyt-finansova-gramotnist?device=c",
    "evidenceLabel": "dumka.top"
  },
  {
    "materialId": "CAT-0431",
    "title": "Подорож у світ економіки. Робочий зошит — 6 клас",
    "author": "Капіруліна С.",
    "publicationYear": 2021,
    "isbn": "9789664965245",
    "evidenceUrl": "https://grammata.kiev.ua/products/9187",
    "evidenceLabel": "grammata.kiev.ua"
  },
  {
    "materialId": "CAT-0434",
    "title": "Мистецтво. Робочий зошит — 6 клас",
    "author": "Масол Л.",
    "publicationYear": 2023,
    "isbn": "9789669834249",
    "evidenceUrl": "https://balka-book.com/obrazotvorche_mistetstvo_6_klas-1203/obrazotvorche-mistetstvo-6-klas-robochiy-zoshitalbom-255980?lang=ua",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0466",
    "title": "Фінансова культура. Посібник — 7 клас",
    "author": "Смовженко Т.",
    "publicationYear": 2016,
    "isbn": "9789664842591",
    "evidenceUrl": "https://www.twirpx.com/file/2426886/",
    "evidenceLabel": "twirpx.com"
  },
  {
    "materialId": "CAT-0478",
    "title": "Історія України. Робочий зошит — 7 клас",
    "author": "Гук О.",
    "publicationYear": 2024,
    "isbn": "9789664965542",
    "evidenceUrl": "https://knigovo.com/zoshiti-storya-7-klas-nova-programa-1545/robochiyzoshitzstorukrani7klas-101285",
    "evidenceLabel": "knigovo.com"
  },
  {
    "materialId": "CAT-0491",
    "title": "Фізика збірник задач — 7 клас",
    "author": "Гельфгат І.",
    "publicationYear": 2019,
    "isbn": "9786170923790",
    "evidenceUrl": "https://balka-book.com/ua/fizika_7_klas-1065/fizika_7_klas_zbirnik_zadach_i_m_gelfgat_i_yu_nenashev-33326",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0497",
    "title": "Хімія. Робчий зошит — 7 клас",
    "author": "Мідак Л.",
    "publicationYear": 2024,
    "isbn": "9789663089447",
    "evidenceUrl": "https://aston.te.ua/catalog/khimiia-robochyj-zoshyt-7-klas/",
    "evidenceLabel": "aston.te.ua"
  },
  {
    "materialId": "CAT-0498",
    "title": "Біологія. Робочий зошит — 7 клас",
    "author": "Задорожний К.",
    "publicationYear": 2024,
    "isbn": "9789669835390",
    "evidenceUrl": "https://balka-book.com/ua/biologiya_7_klas-1055/bologya7klaszoshitmohdosyagnen-286157",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0503",
    "title": "Географія. Зошит для практичних робіт — 7 клас",
    "author": "Топузів О. М.",
    "publicationYear": 2024,
    "isbn": "9789669466822",
    "evidenceUrl": "https://kgf.com.ua/index.php?route=product/product&path=116&product_id=1115",
    "evidenceLabel": "kgf.com.ua"
  },
  {
    "materialId": "CAT-0508",
    "title": "Подорож у світ економіки — 7 клас",
    "author": "Капіруліна С.",
    "publicationYear": 2021,
    "isbn": "9789664965252",
    "evidenceUrl": "https://www.yakaboo.ua/ua/podorozh-u-svit-ekonomiki-7-klas-2272651.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0544",
    "title": "Українська література. Усі діагностувальні роботи — 8 клас",
    "author": "Куцінко О.",
    "publicationYear": 2025,
    "isbn": "9786170043702",
    "evidenceUrl": "https://www.yakaboo.ua/ua/ocinjuvannja-ukrains-ka-literatura-usi-diagnostuval-ni-roboti-8-klas-kzp032-150.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0552",
    "title": "Всесвітня історія. Діагностика освітнього рівня — 8 клас",
    "author": "Гісем",
    "publicationYear": 2025,
    "isbn": "9786175394175",
    "evidenceUrl": "https://balka-book.com/ua/vsesvitnya_istoriya_8_klas-1113/vsesvtnya-storya-dagnostika-osvtnogo-rvnya-8-klas-gsem-o-v-312923",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0556",
    "title": "Алгебра. Самостійні та діагностичні роботи. — 8 клас",
    "author": "Істер О.",
    "publicationYear": 2025,
    "isbn": "9786178370671",
    "evidenceUrl": "https://www.geneza.ua/product/1242",
    "evidenceLabel": "geneza.ua"
  },
  {
    "materialId": "CAT-0557",
    "title": "Геометрія. Самостійні та діагностичні роботи. — 8 клас",
    "author": "Істер О.",
    "publicationYear": 2025,
    "isbn": "9786178370688",
    "evidenceUrl": "https://www.geneza.ua/product/1243",
    "evidenceLabel": "geneza.ua"
  },
  {
    "materialId": "CAT-0558",
    "title": "Алгебра. Геометрія. 8 клас. Усі діагностувальні роботи",
    "author": "Старова О.",
    "publicationYear": 2025,
    "isbn": "9786170043344",
    "evidenceUrl": "https://www.yakaboo.ua/ua/ocinjuvannja-algebra-geometrija-8-klas-usi-diagnostuval-ni-roboti.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0566",
    "title": "Фізика збірник задач (НУШ) — 8 клас",
    "author": "Гельфгат І.",
    "publicationYear": 2025,
    "isbn": "9786170996350",
    "evidenceUrl": "https://www.yakaboo.ua/ua/fizika-8-klas-zbirnik-zadach-3379379.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0572",
    "title": "Хімія. Робочий зошит — 8 клас",
    "author": "Григорович О.",
    "publicationYear": 2025,
    "isbn": "9786170998224",
    "evidenceUrl": "https://balka-book.com/himiya_8_klas-1095/hmya-8-klas-robochiy-zoshit-do-pdruchnika-o-grigorovicha-311310?pv2=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJjIjoiVUFIIiwiZXhwIjoxNzU4MjY4MzI3LCJtIjoiMTAwMzczNjIxIiwibyI6IjMxMTMxMCIsInAiOjU2fQ.8Crku9ompnrBMuEmaY8BgYQP1Zl-wZG2uLF7Qqbwo7symrnLxASPASk_QWfNwUD8n0lUYMWqM3S78CQWu4FPgA&lang=ua",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0573",
    "title": "Хімія. Робчий зошит — 8 клас",
    "author": "Мідак Л.",
    "publicationYear": 2025,
    "isbn": "9789663089737",
    "evidenceUrl": "https://aston.te.ua/catalog/khimiia-robochyj-zoshyt-8-klas/",
    "evidenceLabel": "aston.te.ua"
  },
  {
    "materialId": "CAT-0584",
    "title": "Підприємництво і фінансова грамотність. Робочий зошит та сем. діагн. роб. — 8 клас",
    "author": "Гільберг Т.",
    "publicationYear": 2025,
    "isbn": "9786178370756",
    "evidenceUrl": "https://www.geneza.ua/product/1270",
    "evidenceLabel": "geneza.ua"
  },
  {
    "materialId": "CAT-0637",
    "title": "Алгебра. Контроль резельтатів навчання — 9 клас",
    "author": "Прокопенко Н.",
    "publicationYear": 2017,
    "isbn": "9786170933218",
    "evidenceUrl": "https://balka-book.com/algebra_geometriya_9_klas-1006/algebra_9_kl_kontrol_rezultativ_navchannya_do_pidr_prokopenko_n_s_ukr_nova_programa-83799?lang=ua",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0639",
    "title": "Алгебра. Зошит для самостійних та тематичних контрольних робіт. — 9 клас",
    "author": "Істер О. С.",
    "publicationYear": 2023,
    "isbn": "9786178363246",
    "evidenceUrl": "https://www.yakaboo.ua/ua/algebra-zoshit-dlja-samostijnih-ta-tematichnih-kontrol-nih-robit-9-klas.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0648",
    "title": "Алгебра. Самостійні та контрольні роботи — 9 клас",
    "author": "Мерзляк А.",
    "publicationYear": 2021,
    "isbn": "9789664742990",
    "evidenceUrl": "https://www.yakaboo.ua/ua/algebra-9-klas-samostijni-i-kontrol-ni-roboti-dlja-klasiv-z-pogliblenim-vivchennjam-matematiki.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0657",
    "title": "Хімія. Зошит для практичних робіт — 9 клас",
    "author": "Попель П.",
    "publicationYear": 2023,
    "isbn": "9789665806776",
    "evidenceUrl": "https://www.yakaboo.ua/ua/himija-zoshit-dlja-praktichnih-robit-9-klas.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0662",
    "title": "Географія. Зошит для практичних робіт — 9 клас",
    "author": "Топузов О.",
    "publicationYear": 2024,
    "isbn": "9789669468147",
    "evidenceUrl": "https://kgf.com.ua/index.php?route=product/product&path=116&product_id=860",
    "evidenceLabel": "kgf.com.ua"
  },
  {
    "materialId": "CAT-0694",
    "title": "Українська мова контрольні роботи — 10 клас",
    "author": "Авраменко О.",
    "publicationYear": 2018,
    "isbn": "9789663496719",
    "evidenceUrl": "https://www.yakaboo.ua/ua/ukrains-ka-mova-zoshit-dlja-kontrol-nih-robit-10-klas-1906335.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0698",
    "title": "Математика. Збірник задач — 10 клас",
    "author": "Мерзляк А.",
    "publicationYear": 2021,
    "isbn": "9789664743096",
    "evidenceUrl": "https://balka-book.com/algebra_geometriya_matematika_10_klas-1003/matematika_10_klas_riven_standartu_zbirnik_zadach_testiv_i_kontrolnih_robit_a_g_merzlyak_gimnaziya-86799?lang=ua",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0702",
    "title": "Алгебра. Зошит для самост. і контр. робіт — 10 клас",
    "author": "Істер О.",
    "publicationYear": 2019,
    "isbn": "9789661109178",
    "evidenceUrl": "https://knigoland.com.ua/algebra-10-kl-u-zoshit-dlya-sam-ta-temat-kontr-robit-item",
    "evidenceLabel": "knigoland.com.ua"
  },
  {
    "materialId": "CAT-0713",
    "title": "Всесвітня історія — 10 клас",
    "author": "Гісем",
    "publicationYear": 2019,
    "isbn": "9786170948069",
    "evidenceUrl": "https://balka-book.com/vsesvitnya_istoriya_10_klas-1111/kontrol_navch_dosyagnen_vsesvitnya_istoriya_10_kl_ukr_nova_programa-107232?lang=ua",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0714",
    "title": "Історі України. Всесвітня історія — 10 клас",
    "author": "Власов",
    "publicationYear": 2018,
    "isbn": "9789669454072",
    "evidenceUrl": "https://balka-book.com/ua/vsesvitnya_istoriya_10_klas-1111/storya-ukrani-vsesvtnya-storya-10-klas-testoviy-kontrol-rezultatv-navchannya-256284",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0720",
    "title": "Хімія робочий зошит — 10 клас",
    "author": "Григорович О.",
    "publicationYear": 2018,
    "isbn": "9786177673001",
    "evidenceUrl": "https://balka-book.com/himiya10_klas-1097/robochiy_zoshit_z_himiyi_10_klas_dod_zoshit_dlya_praktichnih_robit_ta_kontrolyu_znan_z_himiyi-142265?lang=ua",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0727",
    "title": "Географія. Зошит для практичних робіт — 10 клас",
    "author": "Даценко Л.",
    "publicationYear": 2021,
    "isbn": "9789669463128",
    "evidenceUrl": "https://kgf.com.ua/index.php?route=product/product&path=116&product_id=1030",
    "evidenceLabel": "kgf.com.ua"
  },
  {
    "materialId": "CAT-0758",
    "title": "Атлас. Всесвітня історія — 11 клас",
    "author": "",
    "publicationYear": 2020,
    "isbn": "9789664551455",
    "evidenceUrl": "https://knigovo.com/zoshiti-storya-11-klas-1653/atlas-z-vsesvtno-stor-dlya-11-klasu-seredina-xx-pochatok-xxi-ct-97373",
    "evidenceLabel": "knigovo.com"
  },
  {
    "materialId": "CAT-0759",
    "title": "Історія України. Контрольні роботи — 11 клас",
    "author": "Наумчук О.",
    "publicationYear": 2020,
    "isbn": "9789663087979",
    "evidenceUrl": "https://balka-book.com/istoriya_ukrayini_11_klas-992/istoriya_ukrayini_11_klas_zoshit_z_tematichnogo_kontrolyu_znan_uchniv_dlya_pidsumkovo_uzagalnyuvalnih_urokiv-202521",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0765",
    "title": "Алгебра. Зошит для поточного і тематичного оцінювання — 11 клас",
    "author": "Нелін Є.",
    "publicationYear": 2011,
    "isbn": "9789664741566",
    "evidenceUrl": "https://balka-book.com/ua/algebra_geometriya_matematika_11_klas-1002/algebra_11_klas_zoshit_dlya_potochnogo_i_tematichnogo_otsinyuvannya_akademichniy_riven_nelin_e_p-25310",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0768",
    "title": "Алгебра і геометрія — 11 клас",
    "author": "Істер О.",
    "publicationYear": 2017,
    "isbn": "9789661047111",
    "evidenceUrl": "https://mybook.biz.ua/ua/dodatkovi-navchalni-posibniki/algebra-ta-geometriya--11-kl-tematichni-kontrolni-roboti-i-zavdannya-dlya-ekza-novoyu-progr-navch-pos-vid-5-te-pererobl/",
    "evidenceLabel": "mybook.biz.ua"
  },
  {
    "materialId": "CAT-0771",
    "title": "Фізика лабораторні роботи — 11 клас",
    "author": "Божинова Ф.",
    "publicationYear": 2016,
    "isbn": "9786175405482",
    "evidenceUrl": "https://balka-book.com/ua/fizika_11_klas-1069/fizika_11_klas_riven_standartu_zoshit_dlya_laboratornih_robit_i_fizichnogo_praktikumu_bozhinova_f_ya-34029",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0777",
    "title": "Хімія. Зошит для практичних робіт — 11 клас",
    "author": "Попель П.",
    "publicationYear": 2019,
    "isbn": "9789665805823",
    "evidenceUrl": "https://www.yakaboo.ua/ua/zoshit-dlja-praktichnih-robit-z-himii-11-klas-riven-standartu.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0813",
    "title": "НМТ 2025. Історія України Типові тестові завдання — 9–11 класи",
    "author": "Власов В.",
    "publicationYear": 2024,
    "isbn": "9789669454881",
    "evidenceUrl": "https://www.yakaboo.ua/ua/nmt-2025-istorija-ukraini-tipovi-testovi-zavdannja.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0817",
    "title": "ЗНО Історія України 2019 — 9–11 класи",
    "author": "Власов В.",
    "publicationYear": 2018,
    "isbn": "9789661789271",
    "evidenceUrl": "https://www.yakaboo.ua/zno-2019-istorija-ukraini-tipovi-testovi-zavdannja.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0819",
    "title": "Історія України. Пам`ятки архітектури та образотворчого мистецтва — 9–11 класи",
    "author": "Земерова Т.",
    "publicationYear": 2024,
    "isbn": "9789660738928",
    "evidenceUrl": "https://www.yakaboo.ua/ua/istorija-ukraini-pam-jatki-arhitekturi-ta-obrazotvorchogo-mistectva-personalii-osnovni-dati-i-podii-testovi-zavdannja-u-formati-zno-2025.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0831",
    "title": "НМТ. Математика. Тестові завдання у форматі НМТ 2026 — 9–11 класи",
    "author": "Гальперіна А.",
    "publicationYear": 2025,
    "isbn": "9789669454874",
    "evidenceUrl": "https://www.yakaboo.ua/ua/nmt-2026-matematika-tipovi-testovi-zavdannja.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0843",
    "title": "Математика. Сучасна підготовка до ЗНО — 9–11 класи",
    "author": "Захарійченко Ю.",
    "publicationYear": 2022,
    "isbn": "9789664965122",
    "evidenceUrl": "https://www.yakaboo.ua/ua/suchasna-pidgotovka-do-zno-z-matematiki.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0852",
    "title": "Фізика. Типові тестові завдання. 2020 — 9–11 класи",
    "author": "Альошина М.",
    "publicationYear": 2019,
    "isbn": "9789669450500",
    "evidenceUrl": "https://www.yakaboo.ua/ua/zno-2020-fizika-tipovi-testovi-zavdannja.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0856",
    "title": "Фізика. Типові тестові завдання. 2017 — 9–11 класи",
    "author": "Альошина М.",
    "publicationYear": 2016,
    "isbn": "9789661786911",
    "evidenceUrl": "https://www.yakaboo.ua/ua/zno-2017-tipovi-testovi-zavdannja-fizika.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0859",
    "title": "Хімія. Типові тестові завдання 2020 — 9–11 класи",
    "author": "Кудіна Л.",
    "publicationYear": 2019,
    "isbn": "9789669450562",
    "evidenceUrl": "https://www.yakaboo.ua/ua/zno-2020-himija-tipovi-testovi-zavdannja.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0861",
    "title": "Хімія. Комплексне видання 2020 — 9–11 класи",
    "author": "Титаренко Н.",
    "publicationYear": 2019,
    "isbn": "9789669450555",
    "evidenceUrl": "https://www.yakaboo.ua/ua/himija-kompleksne-vidannja-zno-2020.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0864",
    "title": "НМТ Біологія. Компл. видання на 2025 — 9–11 класи",
    "author": "Барна І.",
    "publicationYear": 2024,
    "isbn": "9789660742932",
    "evidenceUrl": "https://www.yakaboo.ua/ua/biologija-kompleksna-pidgotovka-do-zno-nmt-2025.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0883",
    "title": "Українська література. 5 кл. Розробки уроків",
    "author": "Архипова В.",
    "publicationYear": 2022,
    "isbn": "9789660740969",
    "evidenceUrl": "https://balka-book.com/rozrobki_urokiv_5_klas-1076/ukrayinska_literatura_5_klas_rozrobki_urokiv_za_modelnoyu_programoyu_v_arhipovoyi_s_sichkar_s_shilo-228597?lang=ua",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0887",
    "title": "Українська мова. 6-й клас. Розробки уроків (за модельною програмою О. Заболотного)",
    "author": "Витвицька С.",
    "publicationYear": 2022,
    "isbn": "9789660742390",
    "evidenceUrl": "https://balka-book.com/rozrobki_urokiv_6_klas-1077/ukranska-mova-6-klas-rozrobki-urokv-za-modelnoyu-programoyu-o-zabolotnogo-v-zabolotnogo-263438?lang=ua",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0892",
    "title": "Навчальний посібник з топографії. 6 клас",
    "author": "картографія",
    "publicationYear": null,
    "isbn": "9789669461995",
    "evidenceUrl": "https://kgf.com.ua/index.php?route=product/product&path=62_121&product_id=440",
    "evidenceLabel": "kgf.com.ua"
  },
  {
    "materialId": "CAT-0898",
    "title": "Збірник диктантів і переказів з української мови. 7-9 класи",
    "author": "Панчук Г.",
    "publicationYear": 2024,
    "isbn": "9789660742581",
    "evidenceUrl": "https://www.yakaboo.ua/ua/panchuk-i-zbirnik-tekstiv-dlja-diktantiv-i-perekaziv-z-ukrains-koi-movi-7-9-kl-nush.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0903",
    "title": "Мій конспект. Українська мова. 8 клас. I семестр",
    "author": "Куцінко О.",
    "publicationYear": 2025,
    "isbn": "9786170043122",
    "evidenceUrl": "https://www.yakaboo.ua/ua/mij-konspekt-materiali-do-urokiv-ukrains-ka-mova-8-klas-i-semestr.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0904",
    "title": "Мій конспект. Українська мова. 8 клас. IІ семестр",
    "author": "Куцінко О.",
    "publicationYear": 2025,
    "isbn": "9786170043146",
    "evidenceUrl": "https://www.yakaboo.ua/ua/mij-konspekt-materiali-do-urokiv-ukrains-ka-mova-8-klas-ii-semestr-do-dvoh-osnovnih-model-nih-navchal-nih-program.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0905",
    "title": "Українська література. 8 клас",
    "author": "Куцінко О.",
    "publicationYear": 2025,
    "isbn": "9786170043658",
    "evidenceUrl": "https://www.yakaboo.ua/ua/ukrains-ka-literatura-8-klas-3376556.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-0907",
    "title": "Навчальний посібник з топографії. 8 клас",
    "author": "картографія",
    "publicationYear": null,
    "isbn": "9789669461988",
    "evidenceUrl": "https://kgf.com.ua/index.php?route=product/product&path=62_121&product_id=1037",
    "evidenceLabel": "kgf.com.ua"
  },
  {
    "materialId": "CAT-0925",
    "title": "The Fox and the Dog. Level 2",
    "author": "Mitchell H.",
    "publicationYear": 2005,
    "isbn": "9789604430086",
    "evidenceUrl": "https://petrovka-online.com/ru/level_2_fox_dog_cd_rom_mitchell_h_isbn_9789604430086",
    "evidenceLabel": "petrovka-online.com"
  },
  {
    "materialId": "CAT-0926",
    "title": "Puss in Boots. Level 3",
    "author": "Charles Perrault",
    "publicationYear": 2008,
    "isbn": "9789604432837",
    "evidenceUrl": "https://kitaabnow.com/product/mm-primary-readers-puss-in-boots-level-3/",
    "evidenceLabel": "kitaabnow.com"
  },
  {
    "materialId": "CAT-0927",
    "title": "Jingle`s Christmas adventure. Level 3",
    "author": "Mitchell H.",
    "publicationYear": 2005,
    "isbn": "9789604430369",
    "evidenceUrl": "https://petrovka-online.com/ru/level_3_jingles_christmas_adventure_cd_rom_mitchell_h_isbn_9789604430369",
    "evidenceLabel": "petrovka-online.com"
  },
  {
    "materialId": "CAT-0928",
    "title": "The Tin Soldier. Level 3",
    "author": "Hans Christian Andersen",
    "publicationYear": 2005,
    "isbn": "9789603799986",
    "evidenceUrl": "https://kitaabnow.com/product/the-tin-soldier-level-3-cd-rom/",
    "evidenceLabel": "kitaabnow.com"
  },
  {
    "materialId": "CAT-0929",
    "title": "Rumpelstiltskin. Level 3",
    "author": "The Brothers Grimm",
    "publicationYear": null,
    "isbn": "9789604430048",
    "evidenceUrl": "https://www.oxfordcorner.hu/en/spd/9789604430048/Primary-Readers-Level-3-Rumpelstiltskin-with-CD-RO",
    "evidenceLabel": "oxfordcorner.hu"
  },
  {
    "materialId": "CAT-0932",
    "title": "Tom Sawyer. Level 5",
    "author": "Mark Twain",
    "publicationYear": null,
    "isbn": "9789603798330",
    "evidenceUrl": "https://www.amazon.com/TOM-SAWYER-Level-Primary-Rea/dp/9603798339",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-0969",
    "title": "Activity Book 2. Level 2. Units 7-12",
    "author": "",
    "publicationYear": 2007,
    "isbn": "9780747310563",
    "evidenceUrl": "https://ksiegarniainternetowa.de/de/pingus_english_activity_book_2_level_2_units_7-12-9780747310563?selected_currency=eur",
    "evidenceLabel": "ksiegarniainternetowa.de"
  },
  {
    "materialId": "CAT-0981",
    "title": "Team. Together. 2 (Оригінал). Activity Book",
    "author": "Lesley Koustaff",
    "publicationYear": 2024,
    "isbn": "9781292292526",
    "evidenceUrl": "https://balka-book.com/angliyskie_kursyi-772/teamtogether2activitybook-232203?utm_source=google&utm_medium=cpc&utm_campaign=fnx_pmax_hudoshka&utm_content=&utm_term=&gad_source=1&gad_campaignid=23632429341&gbraid=0AAAAADKmp7Av2pcPSoHCNsOR4aLyQCjSX&gclid=CjwKCAjwxb7RBhA5EiwAQ-AAdHar8zz_mbT3Vz5h_vka0guFGM2CQLO89MuJJ-SssQdr48urX93gdRoCy_8QAvD_BwE&lang=ua",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0982",
    "title": "Team. Together. 2 (Оригінал). Pupils Book",
    "author": "Lesley Koustaff",
    "publicationYear": 2024,
    "isbn": "9781292310657",
    "evidenceUrl": "https://balka-book.com/angliyskie_kursyi-772/teamtogether2pupilsbook-235357?utm_source=google&utm_medium=cpc&utm_campaign=fnx_pmax_hudoshka&utm_content=&utm_term=&gad_source=1&gad_campaignid=23632429341&gbraid=0AAAAADKmp7Av2pcPSoHCNsOR4aLyQCjSX&gclid=CjwKCAjwxb7RBhA5EiwAQ-AAdDgTVPtbkhPs46ecvhtmUuFpGkTEldWbVvBIJYKr1Bhh1YmLM6jEhxoCNoUQAvD_BwE&lang=ua",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-0984",
    "title": "Team. Together. 3 (Оригінал). Activity Book",
    "author": "Kay Bentley",
    "publicationYear": 2024,
    "isbn": "9781292292533",
    "evidenceUrl": "https://lbc.net.ua/pochatkova-shkola/seriya-team-together/zoshyt-team-together-3-activity-book",
    "evidenceLabel": "lbc.net.ua"
  },
  {
    "materialId": "CAT-0987",
    "title": "Team. Together. 4 (Оригінал). Activity Book",
    "author": "Ines Avello",
    "publicationYear": 2024,
    "isbn": "9781292292557",
    "evidenceUrl": "https://lbcbooks.com.ua/dlya-uchniv-pochatkovoyi-shkoly/zoshyt-team-together-4-activity-book",
    "evidenceLabel": "lbcbooks.com.ua"
  },
  {
    "materialId": "CAT-0996",
    "title": "Wider World 3 Student’s Book",
    "author": "Каролін Барраклоу",
    "publicationYear": null,
    "isbn": "9781292422749",
    "evidenceUrl": "https://www.yakaboo.ua/ua/kniga-wider-world-3-2nd-edition-student-s-book-ebook.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1004",
    "title": "Focus 1 (Оригінал) Teacher`s book",
    "author": "",
    "publicationYear": null,
    "isbn": "9781292301853",
    "evidenceUrl": "https://oxford-book.com.ua/uk/vidavnictvo-pearson-longman/43696-kniga-dlya-uchitelya-focus-2nd-ed-1-teachers-book.html",
    "evidenceLabel": "oxford-book.com.ua"
  },
  {
    "materialId": "CAT-1007",
    "title": "Focus 3 Student’s Book 9 кл.",
    "author": "",
    "publicationYear": null,
    "isbn": "9781292415970",
    "evidenceUrl": "https://www.yakaboo.ua/ua/focus-3-student-s-book-active-book-mel.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1034",
    "title": "Get 200. Book 1",
    "author": "",
    "publicationYear": null,
    "isbn": "9786177821440",
    "evidenceUrl": "https://tsp-books.com/catalog/products/tovar/?naming=get_200!_new_edition__student%27s_book_1&id=7669&book=product&gad_source=1&gad_campaignid=21262502343&gbraid=0AAAAABZD72Km2e1wIuPztUMfj7Oll1p7b&gclid=CjwKCAjw3_PCBhA2EiwAkH_j4pNh6T6XY0XViu-CMVvPaBaWFadaKASkXDpZnwGlbEhUCo9Sbsi8_BoC0EYQAvD_BwE",
    "evidenceLabel": "tsp-books.com"
  },
  {
    "materialId": "CAT-1040",
    "title": "Cambridge Primary. English. Workbook 1 (оригінал)",
    "author": "Еллі Шотман",
    "publicationYear": 2021,
    "isbn": "9781108963640",
    "evidenceUrl": "https://www.yakaboo.ua/ua/cambridge-global-english-workbook-1-with-digital-access.html?gad_source=1&gad_campaignid=16978434679&gbraid=0AAAAADoya-b1okRFyoVGnGMCcXTrxdnGa&gclid=CjwKCAjw3_PCBhA2EiwAkH_j4t_3QapDcx8SIlwD49TRYJ0iVyD7ncuw6PWLCP-V6dc4oV2VKs6xTBoCYCcQAvD_BwE",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1042",
    "title": "Cambridge Primary. Mathematics. Teacher`s 1 (оригінал)",
    "author": "Черрі Мозлі",
    "publicationYear": 2024,
    "isbn": "9781108771498",
    "evidenceUrl": "https://www.yakaboo.ua/ua/cambridge-primary-mathematics-1-teacher-s-resource-with-digital-access.html?gad_source=1&gad_campaignid=16978434679&gbraid=0AAAAADoya-b1okRFyoVGnGMCcXTrxdnGa&gclid=CjwKCAjw3_PCBhA2EiwAkH_j4mEZgd-N1J0aMNngZw1qPJOeLxBgXWiiDSRM9PwqeYiqOZSfHP6mLhoCUrgQAvD_BwE",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1045",
    "title": "Cambridge Primary. Computing. Learner`s 1 (оригінал)",
    "author": "",
    "publicationYear": 2024,
    "isbn": "9781009296984",
    "evidenceUrl": "https://readeat.com/product/203846-cambridge-primary-computing-1-learners-book-with-digital-access-1-year",
    "evidenceLabel": "readeat.com"
  },
  {
    "materialId": "CAT-1051",
    "title": "Cambridge Primary. English. Learner`s 2 (оригінал)",
    "author": "Еллі Шотман",
    "publicationYear": 2021,
    "isbn": "9781108963626",
    "evidenceUrl": "https://www.yakaboo.ua/ua/sambridge-global-english-learner-s-book-2-digital-access-1-year-for-cambridge-primary-english-as-a-second-language.html?gad_source=1&gad_campaignid=16978434679&gbraid=0AAAAADoya-b1okRFyoVGnGMCcXTrxdnGa&gclid=CjwKCAjw3_PCBhA2EiwAkH_j4vNNeV4qQOofPaGbWHjkdRICiPFwAZZbAdC5WA4CqB0a5bPIfOeVaRoC-2YQAvD_BwE",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1055",
    "title": "Cambridge Primary. Computing. Learner`s 2 (оригінал)",
    "author": "Jon Chippindall",
    "publicationYear": null,
    "isbn": "9781009309219",
    "evidenceUrl": "https://www.amazon.com/Cambridge-Primary-Computing-Learners-Digital/dp/1009309218",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1065",
    "title": "Cambridge Primary. Computing. Learner`s 3 (оригінал)",
    "author": "Jon Chippindall",
    "publicationYear": null,
    "isbn": "9781009309226",
    "evidenceUrl": "https://www.amazon.com/Cambridge-Primary-Computing-Learners-Digital/dp/1009309226",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1067",
    "title": "Cambridge Primary. Sciense. Workbook 3 (оригінал)",
    "author": "Джон Боард",
    "publicationYear": 2021,
    "isbn": "9781108742771",
    "evidenceUrl": "https://www.yakaboo.ua/ua/cambridge-primary-science-workbook-3-with-digital-access-1-year.html?srsltid=AfmBOory3NbxXiWDuxPi_wb6lECmsoEn3Qr86g1p8h2zks4wXl8zglQy",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1070",
    "title": "Cambridge Primary. English. Workbook 4 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108760010",
    "evidenceUrl": "https://www.amazon.sg/Cambridge-Primary-English-Workbook-Digital/dp/1108760015",
    "evidenceLabel": "amazon.sg"
  },
  {
    "materialId": "CAT-1083",
    "title": "Cambridge Primary. Primary English. Workbook 5 (оригінал)",
    "author": "Sally Burt",
    "publicationYear": 2021,
    "isbn": "9781108760072",
    "evidenceUrl": "https://www.amazon.co.uk/Cambridge-Primary-English-Workbook-Digital/dp/1108760074",
    "evidenceLabel": "amazon.co.uk"
  },
  {
    "materialId": "CAT-1086",
    "title": "Cambridge Primary. Mathematics. Workbook 5 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108746311",
    "evidenceUrl": "https://oxford-book.com.ua/uk/cambridge-primary-mathematics/71773-cambridge-primary-mathematics-5-workbook-with-digital-access-1-year-9781108746311.html?srsltid=AfmBOop1LYy4ZGev7-lrObu6IbDf195ECM4FQFVitjZUOiGVKY5jjdhc",
    "evidenceLabel": "oxford-book.com.ua"
  },
  {
    "materialId": "CAT-1088",
    "title": "Cambridge Primary. Computing. Learner`s 5 (оригінал)",
    "author": "Ceredig Cattanech-Chell",
    "publicationYear": 2021,
    "isbn": "9781009309288",
    "evidenceUrl": "https://www.amazon.com/Cambridge-Primary-Computing-Learners-Digital/dp/1009309285",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1090",
    "title": "Cambridge Primary. Sciense. Workbook 5 (оригінал)",
    "author": "Fiona Baxter",
    "publicationYear": 2021,
    "isbn": "9781108742962",
    "evidenceUrl": "https://www.amazon.ae/Cambridge-University-Primary-Science-Workbook/dp/1108742963",
    "evidenceLabel": "amazon.ae"
  },
  {
    "materialId": "CAT-1099",
    "title": "Cambridge Primary. Mathematics. Workbook 6 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108746335",
    "evidenceUrl": "https://www.amazon.co.uk/Cambridge-Primary-Mathematics-Workbook-Digital/dp/1108746330",
    "evidenceLabel": "amazon.co.uk"
  },
  {
    "materialId": "CAT-1100",
    "title": "Cambridge Primary. Mathematics. Learner`s 6 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108746328",
    "evidenceUrl": "https://www.amazon.co.uk/Cambridge-Primary-Mathematics-Learners-Digital/dp/1108746322",
    "evidenceLabel": "amazon.co.uk"
  },
  {
    "materialId": "CAT-1101",
    "title": "Cambridge Primary. Computing. Learner`s 6 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781009320542",
    "evidenceUrl": "https://www.amazon.com.au/Cambridge-Primary-Computing-Learners-Digital/dp/1009320548",
    "evidenceLabel": "amazon.com.au"
  },
  {
    "materialId": "CAT-1105",
    "title": "Cambridge Primary. Global English. Teacher`s 7 (оригінал)",
    "author": "Annie Altamirano",
    "publicationYear": 2021,
    "isbn": "9781108921671",
    "evidenceUrl": "https://www.amazon.co.uk/Cambridge-English-Teachers-Resource-Digital/dp/1108921671",
    "evidenceLabel": "amazon.co.uk"
  },
  {
    "materialId": "CAT-1106",
    "title": "Cambridge Primary. Global English. Workbook 7 (оригінал)",
    "author": "Olivia Johnston",
    "publicationYear": 2021,
    "isbn": "9781108963701",
    "evidenceUrl": "https://www.amazon.co.uk/Cambridge-Global-English-Workbook-Digital/dp/1108963706",
    "evidenceLabel": "amazon.co.uk"
  },
  {
    "materialId": "CAT-1107",
    "title": "Cambridge Primary. Global English. Learner`s 7 (оригінал)",
    "author": "Chris Barker",
    "publicationYear": null,
    "isbn": "9781108816588",
    "evidenceUrl": "https://www.amazon.com/Cambridge-English-Learners-Digital-Secondary/dp/1108816584",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1108",
    "title": "Cambridge Primary. Mathematics. Teacher`s 7 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108771405",
    "evidenceUrl": "https://www.amazon.co.uk/Cambridge-Secondary-Mathematics-Teachers-Resource/dp/1108771408",
    "evidenceLabel": "amazon.co.uk"
  },
  {
    "materialId": "CAT-1110",
    "title": "Cambridge Primary. Mathematics. Learner`s 7 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108771436",
    "evidenceUrl": "https://www.amazon.in/Cambridge-Secondary-Mathematics-Learners-Digital/dp/1108771432",
    "evidenceLabel": "amazon.in"
  },
  {
    "materialId": "CAT-1111",
    "title": "Cambridge Primary. Computing. Learner`s 7 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781009297059",
    "evidenceUrl": "https://www.amazon.com/Cambridge-Secondary-Computing-Learners-Digital/dp/1009297058",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1112",
    "title": "Cambridge Primary. Sciense. Teacher`s 7 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108785143",
    "evidenceUrl": "https://www.amazon.com/Cambridge-Secondary-Science-Teachers-Resource/dp/110878514X",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1113",
    "title": "Cambridge Primary. Sciense. Workbook 7 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108742818",
    "evidenceUrl": "https://www.amazon.com/Cambridge-Secondary-Science-Workbook-Digital/dp/1108742815",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1114",
    "title": "Cambridge Primary. Sciense. Learner`s 7 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108742788",
    "evidenceUrl": "https://www.amazon.co.uk/Cambridge-Secondary-Science-Learners-Digital/dp/1108742785",
    "evidenceLabel": "amazon.co.uk"
  },
  {
    "materialId": "CAT-1115",
    "title": "Cambridge Primary. Global English. Teacher`s 8 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108921695",
    "evidenceUrl": "https://www.amazon.ae/Cambridge-English-Teachers-Resource-Digital/dp/1108921698",
    "evidenceLabel": "amazon.ae"
  },
  {
    "materialId": "CAT-1116",
    "title": "Cambridge Primary. Global English. Workbook 8 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108963718",
    "evidenceUrl": "https://www.amazon.com/Cambridge-Global-English-Workbook-Digital/dp/1108963714",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1117",
    "title": "Cambridge Primary. Global English. Learner`s 8 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108816649",
    "evidenceUrl": "https://www.amazon.com/Cambridge-Global-English-Learners-Digital/dp/1108816649",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1119",
    "title": "Cambridge Primary. Mathematics. Workbook 8 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108746403",
    "evidenceUrl": "https://www.amazon.ae/Cambridge-Secondary-Mathematics-Workbook-Digital/dp/1108746403",
    "evidenceLabel": "amazon.ae"
  },
  {
    "materialId": "CAT-1120",
    "title": "Cambridge Primary. Mathematics. Learner`s 8 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108771528",
    "evidenceUrl": "https://www.amazon.co.uk/Cambridge-Secondary-Mathematics-Learners-Digital/dp/1108771521",
    "evidenceLabel": "amazon.co.uk"
  },
  {
    "materialId": "CAT-1121",
    "title": "Cambridge Primary. Computing. Learner`s 8 (оригінал)",
    "author": "Victoria Ellis",
    "publicationYear": null,
    "isbn": "9781009309295",
    "evidenceUrl": "https://www.amazon.com/Cambridge-Secondary-Computing-Learners-Digital/dp/1009309293",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1122",
    "title": "Cambridge Primary. Sciense. Teacher`s 8 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108785181",
    "evidenceUrl": "https://www.amazon.com/Cambridge-Secondary-Science-Teachers-Resource/dp/1108785182",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1123",
    "title": "Cambridge Primary. Sciense. Workbook 8 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108799058",
    "evidenceUrl": "https://www.amazon.com/Cambridge-Secondary-Science-Language-Workbook/dp/1108799051",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1124",
    "title": "Cambridge Primary. Sciense. Learner`s 8 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108742825",
    "evidenceUrl": "https://www.amazon.co.uk/Cambridge-Secondary-Science-Learners-Digital/dp/1108742823",
    "evidenceLabel": "amazon.co.uk"
  },
  {
    "materialId": "CAT-1125",
    "title": "Cambridge Primary. Global English. Teacher`s 9 (оригінал)",
    "author": "Annie Altamirano",
    "publicationYear": 2022,
    "isbn": "9781108921718",
    "evidenceUrl": "https://www.amazon.co.uk/Cambridge-English-Teachers-Resource-Digital/dp/110892171X",
    "evidenceLabel": "amazon.co.uk"
  },
  {
    "materialId": "CAT-1126",
    "title": "Cambridge Primary. Global English. Workbook 9 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108963671",
    "evidenceUrl": "https://www.amazon.com/Cambridge-Global-English-Workbook-Digital/dp/1108963676",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1127",
    "title": "Cambridge Primary. Global English. Learner`s 9 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108816670",
    "evidenceUrl": "https://www.amazon.com/Cambridge-Global-English-Learners-Digital/dp/1108816673",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1128",
    "title": "Cambridge Primary. Mathematics. Teacher`s 9 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108783897",
    "evidenceUrl": "https://www.amazon.com/Cambridge-Secondary-Mathematics-Teachers-Resource/dp/1108783899",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1130",
    "title": "Cambridge Primary. Mathematics. Learner`s 9 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108783774",
    "evidenceUrl": "https://www.amazon.co.uk/Cambridge-Secondary-Mathematics-Learners-Digital/dp/1108783775",
    "evidenceLabel": "amazon.co.uk"
  },
  {
    "materialId": "CAT-1131",
    "title": "Cambridge Primary. Computing. Learner`s 9 (оригінал)",
    "author": "",
    "publicationYear": null,
    "isbn": "9781009320634",
    "evidenceUrl": "https://www.amazon.com/Cambridge-Secondary-Computing-Learners-Digital/dp/1009320637",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1132",
    "title": "Cambridge Primary. Sciense. Teacher`s 9 (оригінал)",
    "author": "Mary Jones",
    "publicationYear": null,
    "isbn": "9781108785228",
    "evidenceUrl": "https://www.amazon.com/Cambridge-Secondary-Science-Teachers-Resource/dp/1108785220",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1143",
    "title": "Cambridge Primary. English. Workbook 2",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108789943",
    "evidenceUrl": "https://www.amazon.com/Cambridge-Primary-English-Workbook-Digital/dp/1108789943",
    "evidenceLabel": "amazon.com"
  },
  {
    "materialId": "CAT-1144",
    "title": "Cambridge Primary. English. Learner`s 2",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108789882",
    "evidenceUrl": "https://www.cambridgebookshop.co.uk/products/cambridge-primary-english-learners-book-2-second-edition-with-digital-access-1-year",
    "evidenceLabel": "cambridgebookshop.co.uk"
  },
  {
    "materialId": "CAT-1146",
    "title": "Cambridge Primary. Mathematics. Learner`s 2",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108746441",
    "evidenceUrl": "https://www.yakaboo.ua/ua/cambridge-primary-mathematics-2-learner-s-book-with-digital-access.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1150",
    "title": "Cambridge Primary. English. Learner`s 3",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108819541",
    "evidenceUrl": "https://www.cambridge.org/pa/education/subject/english/first-language-english/cambridge-primary-and-lower-secondary-english-2nd-edition/cambridge-primary-english-2nd-edition-digital-learners-book-3-1-year-learners-book-3-digital-access-1-year?format=DO&isbn=9781108819541",
    "evidenceLabel": "cambridge.org"
  },
  {
    "materialId": "CAT-1153",
    "title": "Cambridge Primary Global Perspectives 3: Learner's",
    "author": "",
    "publicationYear": null,
    "isbn": "9781009354196",
    "evidenceUrl": "https://rozetka.com.ua/ua/488110914/p488110914/",
    "evidenceLabel": "rozetka.com.ua"
  },
  {
    "materialId": "CAT-1159",
    "title": "Cambridge Primary. Mathematics. Learner`s 4",
    "author": "",
    "publicationYear": null,
    "isbn": "9781108745291",
    "evidenceUrl": "https://www.cambridge.org/pa/education/subject/mathematics/cambridge-primary-and-lower-secondary-mathematics-2nd-edition/cambridge-primary-mathematics-2nd-edition-digital-learners-book-4-1-year-learners-book-4-digital-access-1-year?format=DO&isbn=9781108745291",
    "evidenceLabel": "cambridge.org"
  },
  {
    "materialId": "CAT-1160",
    "title": "Cambridge Primary Global Perspectives 4: Learner's",
    "author": "",
    "publicationYear": null,
    "isbn": "9781009325639",
    "evidenceUrl": "https://www.yakaboo.ua/ua/cambridge-primary-global-perspectives-learner-s-skills-book-4-with-digital-access.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1163",
    "title": "Colega 1. Libro",
    "author": "Марія Луіза Хортелано",
    "publicationYear": 2013,
    "isbn": "9788477116561",
    "evidenceUrl": "https://www.yakaboo.ua/ua/colega-1-libro-del-alumno-cd.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1171",
    "title": "Espanol. А2. Libro Por supuesto!",
    "author": "Марія-Анджелес Паломіно",
    "publicationYear": 2023,
    "isbn": "9788490817575",
    "evidenceUrl": "https://www.yakaboo.ua/ua/espanol-por-supuesto-2-a2-libro-del-alumno.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1185",
    "title": "El manco de Lepanto. Nivel 1",
    "author": "",
    "publicationYear": null,
    "isbn": "9788477116172",
    "evidenceUrl": "https://cfl.com.ua/ru/spanish/esp-readers/grandes-personajes-de-la-historia/9788477116172-gph-1-el-manco-de-lepanto/",
    "evidenceLabel": "cfl.com.ua"
  },
  {
    "materialId": "CAT-1189",
    "title": "Paul, Lisa & Co Starter Kursbuch",
    "author": "Моніка Боверманн",
    "publicationYear": 2016,
    "isbn": "9783190015597",
    "evidenceUrl": "https://www.yakaboo.ua/ua/starter-kursbuch.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1191",
    "title": "Paul, Lisa. A 1.1 Kursbuch",
    "author": "Моніка Боверманн",
    "publicationYear": 2018,
    "isbn": "9783193015594",
    "evidenceUrl": "https://www.yakaboo.ua/ua/paul-lisa-co-a1-1-deutsch-fur-kinder-kursbuch.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1193",
    "title": "Paul, Lisa. A 1.2 Kursbuch",
    "author": "Моніка Боверманн",
    "publicationYear": 2019,
    "isbn": "9783196015591",
    "evidenceUrl": "https://www.yakaboo.ua/ua/paul-lisa-co-a1-2-kursbuch.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1196",
    "title": "Beste Freunde A 1.2 Arbeitsbuch",
    "author": "Мануела Джорджіякакі",
    "publicationYear": 2023,
    "isbn": "9783198210512",
    "evidenceUrl": "https://www.yakaboo.ua/ua/beste-freunde-arbeitsbuch-mit-audios-online-a1-2.html?gad_source=1&gad_campaignid=20742056632&gbraid=0AAAAADoya-bhJFMpx-zOXzwfwf5_tjRyu&gclid=CjwKCAjwvO7CBhAqEiwA9q2YJQ_o9gWM5U26nF6W9h38aVFtoS9o9pelCp99KonFrZtVZV7wfoQfRhoCBL4QAvD_BwE",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1197",
    "title": "Beste Freunde А2/2 Kursbuch",
    "author": "Аня Шуманн",
    "publicationYear": 2016,
    "isbn": "9783195010528",
    "evidenceUrl": "https://www.yakaboo.ua/ua/beste-freunde-a2-2-kursbuch.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1200",
    "title": "Die Deutschprofis A1 Kursbuch",
    "author": "Ольга Сверлова",
    "publicationYear": 2021,
    "isbn": "9783126764704",
    "evidenceUrl": "https://www.yakaboo.ua/ua/die-deutschprofis-a1-kursbuch-mit-audios-und-clips-online.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1201",
    "title": "Die Deutschprofis A1 Ubungsbuch",
    "author": "Ольга Сверлова",
    "publicationYear": 2021,
    "isbn": "9783126764711",
    "evidenceUrl": "https://www.yakaboo.ua/ua/die-deutschprofis-a1-ubungsbuch.html?gad_source=1&gad_campaignid=16978434679&gbraid=0AAAAADoya-aw6n4UAVhzY0pWiCkL8MMcI&gclid=CjwKCAjwvO7CBhAqEiwA9q2YJQ5hvlw34E-CEgioiRA6YeZ5LTUPe96Lfiu4xZzK5r4Ijn2g9VL8LRoC64MQAvD_BwE",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1203",
    "title": "Die Deutschprofis A2 Kursbuch",
    "author": "Ольга Сверлова",
    "publicationYear": 2017,
    "isbn": "9783126764803",
    "evidenceUrl": "https://www.yakaboo.ua/ua/die-deutschprofis-a2-kursbuch-pidruchnik.html?gad_source=1&gad_campaignid=16978434679&gbraid=0AAAAADoya-aw6n4UAVhzY0pWiCkL8MMcI&gclid=CjwKCAjwvO7CBhAqEiwA9q2YJUUEBvFOez97g9UQMFsH-8Qn3GBioZOvftJBhzIVIgq1YGMpz2NhqxoCyBQQAvD_BwE",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1207",
    "title": "Die Deutschprofis B1 Kursbuch",
    "author": "Ольга Сверлова",
    "publicationYear": 2020,
    "isbn": "9783126764902",
    "evidenceUrl": "https://www.yakaboo.ua/ua/die-deutschprofis-b1-kursbuch-mit-audios-und-clips.html?gad_source=1&gad_campaignid=16978434679&gbraid=0AAAAADoya-aw6n4UAVhzY0pWiCkL8MMcI&gclid=CjwKCAjwvO7CBhAqEiwA9q2YJcu-7F3BbPpZstBov7IZmEbKzLL9vz7UN84-bEEV4k0i3i_a5MmVEBoCVacQAvD_BwE",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1208",
    "title": "Die Deutschprofis B1 Ubungsbuch",
    "author": "Ольга Сверлова",
    "publicationYear": 2018,
    "isbn": "9786177198863",
    "evidenceUrl": "https://www.yakaboo.ua/ua/die-deutschprofis-v1-ubunsbuch-robochij-zoshit.html?gad_source=1&gad_campaignid=16978434679&gbraid=0AAAAADoya-aw6n4UAVhzY0pWiCkL8MMcI&gclid=CjwKCAjwvO7CBhAqEiwA9q2YJUYAXSTHRiniSrpLIf_tD1DikqhSS_HxTuJxUrWgsxf0j-RdcPBaYBoC1QoQAvD_BwE",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1209",
    "title": "Die Deutschprofis B1 Lehrerhandbuch",
    "author": "Тюнде Сарвари",
    "publicationYear": 2018,
    "isbn": "9783126764933",
    "evidenceUrl": "https://www.yakaboo.ua/ua/die-deutschprofis-b1-lehrerhandbuch.html?srsltid=AfmBOoqYozQEgw7XNaSoML4HtqMiDHOzoTSynIKQTTnh5QzgD9SYQQvw",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1226",
    "title": "Зошит до підручника Jezyk Polski 5",
    "author": "Біленька-Свистович Л.",
    "publicationYear": 2019,
    "isbn": "9789660732063",
    "evidenceUrl": "https://balka-book.com/ua/osnovi_zdorov_ya_5_klas-944/robochiy_zoshit_z_polskoyi_movi_5_klas_1_rik_navchannya_do_pidruchnika_bilenka_svistovich_l-87104?utm_source=google&utm_medium=cpc&utm_campaign=fnx_pmax_education_school&utm_content=&utm_term=&gad_source=1&gad_campaignid=21467252836&gbraid=0AAAAADKmp7DP7spVYEEAjWaGcJ8u8WYaD&gclid=CjwKCAjwvO7CBhAqEiwA9q2YJTp7VPLnC8LYD76SaiNllosswRh5WP7LEBVsid0xfpnU31i4AVTdBhoCJ6EQAvD_BwE",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-1240",
    "title": "Zajecia komputerowe",
    "author": "Michał Kęska",
    "publicationYear": 2012,
    "isbn": "9788326706202",
    "evidenceUrl": "https://www.poczytaj.pl/podrecznik/zajecia-komputerowe-1-szkola-podstawowa-podrecznik-z-cwiczeniami-cd-michal-keska,233609",
    "evidenceLabel": "poczytaj.pl"
  },
  {
    "materialId": "CAT-1245",
    "title": "Polska. Zeszyt do kaligrafii",
    "author": "Рудницька О.",
    "publicationYear": 2018,
    "isbn": "9789660731653",
    "evidenceUrl": "https://www.yakaboo.ua/ua/zoshit-dlja-pis-ma-z-pol-s-koi-movi-chervonij.html?srsltid=AfmBOoqTHJV96qUH76QRBlkh8JGeJ_y8HEhnskcogSoeirhXGg0TLrex",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1248",
    "title": "Історія Польщі",
    "author": "Андрущенко І.",
    "publicationYear": 2017,
    "isbn": "9789664985564",
    "evidenceUrl": "https://www.yakaboo.ua/ua/historia-polski-istorija-pol-schi.html?srsltid=AfmBOophpyHz77vZF8iVzrBTKuFq1UTHGDm6yBM4nn9XRkYQw6s5NB3v",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1253",
    "title": "Польська мова. Довідничок для учнів. 1-4 к.",
    "author": "Масляк В.",
    "publicationYear": 2018,
    "isbn": "9789660732254",
    "evidenceUrl": "https://balka-book.com/pochatkova_shkola-1619/polska_mova_dovidnichok_dlya_uchniv_1_4_klasiv-77187?utm_source=google&utm_medium=cpc&utm_campaign=fnx_pmax_education_others&utm_content=&utm_term=&gad_source=1&gad_campaignid=20697872375&gbraid=0AAAAADKmp7BwZGq4Q6pvwr_LdlgbSxRuh&gclid=CjwKCAjwvO7CBhAqEiwA9q2YJZYqGYUJxZz2j8DCVf3lcJXoBJYdsL8i1UyLrba07p43nhCEq28E1hoCCasQAvD_BwE&lang=ua",
    "evidenceLabel": "balka-book.com"
  },
  {
    "materialId": "CAT-1263",
    "title": "ZigZag 3 Méthode de Français — Livre",
    "author": "Елен Вант’є",
    "publicationYear": 2019,
    "isbn": "9782090384338",
    "evidenceUrl": "https://www.yakaboo.ua/ua/zigzag-3-livre-de-leleve-cd-audio.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1264",
    "title": "ZigZag 3 Méthode de Français — Cahier d'activités",
    "author": "Елен Вант’є",
    "publicationYear": 2019,
    "isbn": "9782090384345",
    "evidenceUrl": "https://www.yakaboo.ua/ua/zigzag-3-cahier-activites.html?gad_source=1&gad_campaignid=20742056632&gbraid=0AAAAADoya-bhJFMpx-zOXzwfwf5_tjRyu&gclid=CjwKCAjwvO7CBhAqEiwA9q2YJSR5BmWteALJl32F8VPUg5L_sj5KaDRQ9b6jLzKHGhe3xrRNACM0FRoC3cMQAvD_BwE",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1265",
    "title": "Pixel 1 Livre",
    "author": "",
    "publicationYear": 2017,
    "isbn": "9782090389241",
    "evidenceUrl": "https://www.yakaboo.ua/ua/nouveau-pixel-livre-de-l-eleve-1-dvd-rom.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1269",
    "title": "Pixel 2 Livre",
    "author": "Сільві Шмітт",
    "publicationYear": 2016,
    "isbn": "9782090389272",
    "evidenceUrl": "https://www.yakaboo.ua/ua/methode-de-francais-pixel-2-livre-de-l-eleve.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1271",
    "title": "Pixel 3 Livre",
    "author": "Колетт Гіббе",
    "publicationYear": 2016,
    "isbn": "9782090389302",
    "evidenceUrl": "https://readeat.com/product/124095-pixel-nouveau-3-livre-de-leleve-dvd-rom?gad_source=1&gad_campaignid=20996424205&gbraid=0AAAAAqD_l774d_iNx-UAUSRQY3SYKArRn&gclid=CjwKCAjwvO7CBhAqEiwA9q2YJYx1HUkhqdteEqPEC_5K_hlZjwkneGGJZe0vvRdM8tES-r1WpQMO1xoC7dMQAvD_BwE",
    "evidenceLabel": "readeat.com"
  },
  {
    "materialId": "CAT-1272",
    "title": "Pixel 3 Cahier d'activités",
    "author": "Патрісія Роберт",
    "publicationYear": 2016,
    "isbn": "9782090389319",
    "evidenceUrl": "https://www.yakaboo.ua/ua/nouveau-pixel-3-niveau-a2-cahier-d-activites.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1274",
    "title": "Pixel 4 Livre",
    "author": "Сільві Шмітт",
    "publicationYear": 2013,
    "isbn": "9782090387674",
    "evidenceUrl": "https://www.yakaboo.ua/ua/step-up-to-ielts-self-study-sb.html",
    "evidenceLabel": "yakaboo.ua"
  },
  {
    "materialId": "CAT-1278",
    "title": "Decibel 2 Livre",
    "author": "",
    "publicationYear": 2016,
    "isbn": "9782278083367",
    "evidenceUrl": "https://www.yakaboo.ua/ua/decibel-2-niv-a2-1-livre-cd-mp3-dvd.html",
    "evidenceLabel": "yakaboo.ua"
  }
] as const satisfies readonly VerifiedIsbnCandidate[];
