import {normalizeCatalogSearchText} from "./catalog-d1.ts";
import {normalizeIsbn} from "./isbn.ts";
import {beginLibraryCommand,finishLibraryCommand,libraryCommand,rebuildReaderStock} from "./library-copy-store.ts";
import {readerBatch,readerFail,readerResource,requireChanged,type ReaderDatabase,type LibraryActor} from "./reader-core.ts";

export const EDITION_FIELDS=["author","publisher","year","isbn","isbn13","issn","edition","volume","language","pages","description","annotation","series","genre","ddc","callNumber","type","coauthors","editors","illustrators","isbn10","asin","lccn","oclc","upc","subject"] as const;
const ENTITY_FIELDS=["biography","country","nickname","dateOfBirth","yearDied","publications","awards","website","description"];
type Metadata=Record<string,string>;
function fields(value:unknown,allowed:readonly string[]):Metadata{if(!value||typeof value!=="object"||Array.isArray(value))readerFail("metadata_invalid","Перевірте дані картки.");const result:Metadata={};for(const[key,entry]of Object.entries(value)){if(!allowed.includes(key)||typeof entry!=="string"||entry.length>(["description","annotation","biography","publications","awards"].includes(key)?20000:1000)||/[\u0000-\u0008]/.test(entry))readerFail("metadata_invalid","Некоректне або завелике поле картки.");result[key]=entry.trim();}return result;}
export async function getLibrarianEdition(db:ReaderDatabase,id:string){const row=await db.prepare("SELECT e.id,e.title,e.material_id,e.version,e.publication_state,e.public_metadata_json,m.version material_version,COALESCE((SELECT version FROM material_cover_assets ca WHERE ca.material_id=m.id),0) cover_version FROM library_editions e LEFT JOIN materials m ON m.id=e.material_id WHERE e.id=?").bind(id).first();if(!row)readerFail("edition_missing","Картку не знайдено.",404);const entities=await db.prepare("SELECT entity_id FROM library_edition_entities WHERE edition_id=? AND role IN ('author','publisher','genre')").bind(id).all();return {...row,metadata:JSON.parse(String(row.public_metadata_json)),entityIds:(entities.results||[]).map(r=>r.entity_id)};}
export async function saveLibraryEdition(db:ReaderDatabase,actor:LibraryActor,input:{requestId:string;id?:string;expectedVersion?:number;expectedMaterialVersion?:number;title:string;metadata:Metadata;entityIds:string[];published:boolean}){
  const patch=fields(input.metadata,EDITION_FIELDS);if(typeof input.title!=="string"||input.title.trim().length<1||input.title.length>500||typeof input.published!=="boolean"||!Array.isArray(input.entityIds)||input.entityIds.length>100||!input.entityIds.every(readerResource)||new Set(input.entityIds).size!==input.entityIds.length)readerFail("edition_fields","Перевірте назву, довідники й стан публікації.");
  const command=await libraryCommand(db,actor,input.requestId,"library.edition.save",input);if(command.replayed)return command.replayed;
  const existing=input.id?await db.prepare("SELECT e.material_id,e.version,e.public_metadata_json,m.version material_version FROM library_editions e JOIN materials m ON m.id=e.material_id WHERE e.id=? AND m.status='active'").bind(input.id).first():null;
  if(input.id&&(!existing||existing.version!==input.expectedVersion||existing.material_version!==input.expectedMaterialVersion))readerFail("edition_changed","Картку змінено або її облік ще не активовано. Оновіть дані.",409);
  const metadata={...(existing?JSON.parse(String(existing.public_metadata_json)):{}),...patch},id=input.id||"ED-"+crypto.randomUUID(),title=input.title.trim(),now=new Date().toISOString();
  const isbn=normalizeIsbn(String(metadata.isbn13||metadata.isbn||""))||"",year=/^\d{4}$/.test(metadata.year||"")?Number(metadata.year):null;
  const number=existing?null:Number((await db.prepare("SELECT COALESCE(MAX(catalog_number),0) n FROM materials").first())?.n||0)+1,materialId=existing?String(existing.material_id):"CAT-"+String(number).padStart(4,"0");
  const result={id,materialId,version:existing?Number(existing.version)+1:1,materialVersion:existing?Number(existing.material_version)+1:1},entityJson=JSON.stringify(input.entityIds);
  const statements=[beginLibraryCommand(db,actor,input.requestId,"library.edition.save",command.hash,id,now),
    db.prepare("SELECT CASE WHEN (SELECT COUNT(*) FROM library_catalog_entities WHERE id IN (SELECT value FROM json_each(?)) AND kind IN ('author','publisher','genre'))=? THEN 1 ELSE json('entity_changed') END").bind(entityJson,input.entityIds.length),
    db.prepare("SELECT CASE WHEN ?='' OR NOT EXISTS(SELECT 1 FROM materials WHERE isbn_normalized=? AND id!=? AND status='active') THEN 1 ELSE json('duplicate_isbn') END").bind(isbn,isbn,materialId)];
  const search=normalizeCatalogSearchText([title,metadata.author,metadata.publisher,metadata.genre,metadata.isbn,metadata.isbn13].join(" "));
  if(existing)statements.push(db.prepare("DELETE FROM materials_fts WHERE rowid=(SELECT rowid FROM materials WHERE id=?)").bind(materialId),db.prepare("UPDATE materials SET title=?,sort_title=?,search_text=?,author=?,publisher=?,publication_year=?,isbn=?,isbn_normalized=?,rubric=?,version=version+1,updated_at=? WHERE id=? AND version=? AND status='active'").bind(title,normalizeCatalogSearchText(title),search,String(metadata.author||""),String(metadata.publisher||""),year,String(metadata.isbn13||metadata.isbn||""),isbn,String(metadata.genre||""),now,materialId,Number(input.expectedMaterialVersion)),requireChanged(db,1),db.prepare("UPDATE library_editions SET title=?,public_metadata_json=?,publication_state=?,version=version+1,updated_at=? WHERE id=? AND version=?").bind(title,JSON.stringify(metadata),input.published?"published":"draft",now,id,Number(input.expectedVersion)),requireChanged(db,1));
  else statements.push(db.prepare("INSERT INTO materials(id,catalog_number,title,sort_title,search_text,author,publisher,publication_year,isbn,isbn_normalized,rubric,publication_type,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,'Книга','active',?,?)").bind(materialId,number!,title,normalizeCatalogSearchText(title),search,String(metadata.author||""),String(metadata.publisher||""),year,String(metadata.isbn13||metadata.isbn||""),isbn,String(metadata.genre||""),now,now),db.prepare("INSERT INTO library_editions(id,material_id,fund,title,public_metadata_json,publication_state,created_at,updated_at) VALUES(?,?,'literature',?,?,?,?,?)").bind(id,materialId,title,JSON.stringify(metadata),input.published?"published":"draft",now,now));
  statements.push(db.prepare("INSERT INTO materials_fts(rowid,title,author,isbn_normalized,publisher,rubric,subject,publication_type,search_text) SELECT rowid,title,author,isbn_normalized,publisher,rubric,subject,publication_type,search_text FROM materials WHERE id=?").bind(materialId),
    db.prepare("DELETE FROM library_edition_entities WHERE edition_id=? AND role IN ('author','publisher','genre')").bind(id),db.prepare("INSERT INTO library_edition_entities(edition_id,entity_id,role) SELECT ?,id,kind FROM library_catalog_entities WHERE id IN (SELECT value FROM json_each(?))").bind(id,entityJson),rebuildReaderStock(db,materialId,now),...finishLibraryCommand(db,actor,input.requestId,"library.edition.save",id,result,now));await readerBatch(db,statements);return result;
}
export async function saveLibraryEntity(db:ReaderDatabase,actor:LibraryActor,input:{requestId:string;id?:string;expectedVersion?:number;kind:string;name:string;metadata:Metadata}){
  const patch=fields(input.metadata,ENTITY_FIELDS);if(!["author","publisher","genre"].includes(input.kind)||typeof input.name!=="string"||!input.name.trim()||input.name.length>300)readerFail("entity_fields","Перевірте тип і назву довідника.");
  if(patch.website){try{const url=new URL(patch.website);if(url.protocol!=="https:"||url.username||url.password)throw Error();}catch{readerFail("publisher_website","Вебсайт має бути повною безпечною HTTPS-адресою.");}}
  const command=await libraryCommand(db,actor,input.requestId,"library.entity.save",input);if(command.replayed)return command.replayed;const id=input.id||"ENTITY-"+crypto.randomUUID(),now=new Date().toISOString(),result={id,version:input.id?Number(input.expectedVersion)+1:1};
  await readerBatch(db,[beginLibraryCommand(db,actor,input.requestId,"library.entity.save",command.hash,id,now),input.id?db.prepare("UPDATE library_catalog_entities SET name=?,public_metadata_json=json_patch(public_metadata_json,?),version=version+1 WHERE id=? AND version=? AND kind=?").bind(input.name.trim(),JSON.stringify(patch),id,Number(input.expectedVersion),input.kind):db.prepare("INSERT INTO library_catalog_entities(id,kind,name,slug,public_metadata_json) VALUES(?,?,?,?,?)").bind(id,input.kind,input.name.trim(),id,JSON.stringify(patch)),requireChanged(db,1),...finishLibraryCommand(db,actor,input.requestId,"library.entity.save",id,result,now)]);return result;
}
