import {normalizeCatalogSearchText} from "./catalog-d1.ts";
import {normalizeIsbn} from "./isbn.ts";
import {sha256Text} from "./librarika-import-plan.ts";
import {readerBatch,readerFail,readerResource,requireChanged,stableJson,uuidValid,type LibraryActor,type ReaderDatabase} from "./reader-core.ts";
type Statements=Parameters<ReaderDatabase["batch"]>[0];
export const SOURCE_LOCATION="LOC-LRK-MAIN";
export async function libraryCommand(db:ReaderDatabase,actor:LibraryActor,requestId:string,kind:string,input:unknown){
  if(!uuidValid(requestId))readerFail("request_id","Оновіть форму дії.");
  const hash=await sha256Text(stableJson({actorId:actor.id,kind,input})),saved=await db.prepare("SELECT actor_user_id,request_hash,status,result_json FROM mutation_commands WHERE id=?").bind(requestId).first();
  if(saved&&(saved.actor_user_id!==actor.id||saved.request_hash!==hash))readerFail("command_conflict","Ідентифікатор дії вже використано з іншими даними.",409);
  return {hash,replayed:saved?.status==="completed"?JSON.parse(String(saved.result_json)):null};
}
export function beginLibraryCommand(db:ReaderDatabase,actor:LibraryActor,requestId:string,kind:string,hash:string,targetId:string,now:string){
  return db.prepare(`INSERT INTO mutation_commands(id,kind,actor_user_id,status,target_type,target_id,request_hash,created_at,updated_at)
    VALUES(?,?,(SELECT id FROM users WHERE id=? AND status='active' AND role IN ('admin','librarian')),'processing','library_copy',?,?,?,?)`).bind(requestId,kind,actor.id,targetId,hash,now,now);
}
export function finishLibraryCommand(db:ReaderDatabase,actor:LibraryActor,requestId:string,kind:string,targetId:string,result:unknown,now:string):Statements{return[
  db.prepare("INSERT INTO audit_events(id,actor_user_id,actor_email,action,entity_type,entity_id,request_id,metadata_json,created_at) VALUES(?,?,?,?,'library_copy',?,?,?,?)").bind(crypto.randomUUID(),actor.id,actor.email,kind,targetId,requestId,JSON.stringify(result),now),
  db.prepare("UPDATE mutation_commands SET status='completed',result_json=?,updated_at=?,completed_at=? WHERE id=? AND status='processing'").bind(JSON.stringify(result),now,now,requestId),requireChanged(db,1),
];}
export function rebuildReaderStock(db:ReaderDatabase,materialId:string,now:string){return db.prepare(`
 INSERT INTO material_stock_totals(material_id,total_quantity,library_quantity,other_location_quantity,loaned_quantity,reserved_quantity,updated_at)
 SELECT m.id,
 COALESCE((SELECT SUM(quantity) FROM holdings WHERE material_id=m.id),0)+COALESCE(outstanding.quantity,0),
 COALESCE((SELECT SUM(h.quantity) FROM holdings h JOIN locations l ON l.id=h.location_id WHERE h.material_id=m.id AND l.type='library'),0),
 COALESCE((SELECT SUM(h.quantity) FROM holdings h JOIN locations l ON l.id=h.location_id WHERE h.material_id=m.id AND l.type!='library'),0),
 COALESCE(outstanding.quantity,0),COALESCE((SELECT SUM(reserved_quantity-issued_quantity-released_quantity) FROM material_request_reservations WHERE material_id=m.id),0),?
 FROM materials m LEFT JOIN (SELECT material_id,SUM(quantity) quantity FROM (
 SELECT i.material_id,i.quantity_issued-i.quantity_returned quantity FROM loan_items i JOIN loans l ON l.id=i.loan_id WHERE l.status!='cancelled'
 UNION ALL SELECT i.material_id,i.quantity_issued-i.quantity_returned FROM class_loan_items i JOIN class_loans l ON l.id=i.class_loan_id WHERE l.status!='cancelled' AND i.lifecycle_status='active'
 UNION ALL SELECT e.material_id,1 FROM reader_circulations l JOIN library_copies c ON c.id=l.copy_id JOIN library_editions e ON e.id=c.edition_id WHERE l.accounting_mode='native' AND l.status IN ('issued','overdue')
 ) q GROUP BY material_id) outstanding ON outstanding.material_id=m.id WHERE m.id=?
 ON CONFLICT(material_id) DO UPDATE SET total_quantity=excluded.total_quantity,library_quantity=excluded.library_quantity,other_location_quantity=excluded.other_location_quantity,loaned_quantity=excluded.loaned_quantity,reserved_quantity=excluded.reserved_quantity,updated_at=excluded.updated_at`).bind(now,materialId);}
function dateOnly(value:unknown){if(typeof value!=="string"||!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(Date.parse(value+"T00:00:00Z"))||new Date(value+"T00:00:00Z").toISOString().slice(0,10)!==value)readerFail("date_invalid","Перевірте дату.");return value;}
function expectedVersion(value:unknown){if(!Number.isInteger(value)||Number(value)<1)readerFail("version_invalid","Оновіть дані перед дією.");return Number(value);}
function conditionValue(value:unknown){if(!["unspecified","good","worn","damaged"].includes(String(value)))readerFail("condition_invalid","Оберіть стан примірника.");return String(value);}
function copyInvariant(db:ReaderDatabase,copyId:string){return db.prepare(`SELECT CASE WHEN EXISTS(SELECT 1 FROM library_copies c JOIN library_editions e ON e.id=c.edition_id WHERE c.id=? AND c.registration='registered' AND e.material_id IS NOT NULL AND (
  (c.physical_state='on_loan' AND (SELECT count(*) FROM reader_circulations l WHERE l.copy_id=c.id AND l.accounting_mode='native' AND l.status IN ('issued','overdue'))=1)
  OR (c.physical_state IN ('on_shelf','withdrawn') AND NOT EXISTS(SELECT 1 FROM reader_circulations l WHERE l.copy_id=c.id AND l.status IN ('issued','overdue'))))) THEN 1 ELSE json('copy_state_conflict') END`).bind(copyId);}

/** Each activation is one atomic edition command; existing inventory is never re-imported or overwritten. */
export async function activateImportedEdition(db:ReaderDatabase,actor:LibraryActor,input:{requestId:string;editionId:string;expectedVersion:number;existingMaterialId?:string|null;confirmation:string}){
  if(input.confirmation!=="ACTIVATE_SOURCE_EDITION"||!readerResource(input.editionId))readerFail("activation_confirmation","Підтвердьте перенесення обліку цього видання.");expectedVersion(input.expectedVersion);
  const command=await libraryCommand(db,actor,input.requestId,"library.edition.activate",input);if(command.replayed)return command.replayed;
  const edition=await db.prepare("SELECT e.* FROM library_editions e JOIN library_import_runs r ON r.id=e.import_run_id WHERE e.id=? AND e.version=? AND e.material_id IS NULL AND e.publication_state='draft' AND r.state IN ('verified','reconciled') AND json_extract(r.reconciliation_json,'$.contract.sourceCompleteness.authorDetailsComplete')=1 AND json_array_length(r.reconciliation_json,'$.contract.sourceCompleteness.authorsPending')=0 AND (coalesce(json_extract(e.public_metadata_json,'$.coverKind'),'')='placeholder' OR coalesce(length(json_extract(e.public_metadata_json,'$.coverSha256')),0)!=64 OR EXISTS(SELECT 1 FROM library_import_cover_receipts cr WHERE cr.import_run_id=e.import_run_id AND cr.sha256=json_extract(e.public_metadata_json,'$.coverSha256')))").bind(input.editionId,input.expectedVersion).first();
  if(!edition)readerFail("edition_not_ready","Видання не підтверджене або вже перенесене.",409);
  const sourceCounts=await db.prepare("SELECT COUNT(*) copies,SUM(CASE WHEN EXISTS(SELECT 1 FROM reader_circulations l WHERE l.copy_id=c.id AND l.status IN ('issued','overdue')) THEN 1 ELSE 0 END) loaned FROM library_copies c WHERE c.edition_id=? AND c.registration='unreconciled'").bind(input.editionId).first();
  const copies=Number(sourceCounts?.copies||0),loaned=Number(sourceCounts?.loaned||0);if(copies<1||copies>1000)readerFail("edition_copies","Потрібна перевірка примірників видання.",409);
  const metadata=JSON.parse(String(edition.public_metadata_json)) as Record<string,unknown>,value=(key:string)=>typeof metadata[key]==="string"||typeof metadata[key]==="number"?String(metadata[key]):"";
  const isbn=normalizeIsbn(value("isbn13")||value("isbn"))||"";
  let materialId=input.existingMaterialId||"",catalogNumber=0;
  if(materialId){const existing=await db.prepare("SELECT id,catalog_number,isbn_normalized FROM materials WHERE id=? AND status='active' AND archived_at IS NULL").bind(materialId).first();if(!existing||!isbn||existing.isbn_normalized!==isbn)readerFail("edition_match","Існуюче видання не має точного підтвердженого ISBN.",409);catalogNumber=Number(existing.catalog_number);}
  else{const maximum=await db.prepare("SELECT COALESCE(MAX(catalog_number),0) n FROM materials").first();catalogNumber=Number(maximum?.n||0)+1;materialId=`CAT-${String(catalogNumber).padStart(4,"0")}`;}
  const now=new Date().toISOString(),result={editionId:input.editionId,materialId,copies,loaned,available:copies-loaned,version:input.expectedVersion+1,stockBasis:"source_register_not_physical_count"};
  const statements:Statements=[beginLibraryCommand(db,actor,input.requestId,"library.edition.activate",command.hash,input.editionId,now),
    db.prepare("SELECT CASE WHEN EXISTS(SELECT 1 FROM users WHERE id=? AND role='admin' AND status='active') THEN 1 ELSE json('admin_required') END").bind(actor.id),
    db.prepare("INSERT INTO locations(id,name,type,is_public,sort_order,status,created_at,updated_at) VALUES(?,'Фонд Librarika — Main (за джерельним реєстром)','library',0,5,'active',?,?) ON CONFLICT(id) DO NOTHING").bind(SOURCE_LOCATION,now,now),
    db.prepare("SELECT CASE WHEN EXISTS(SELECT 1 FROM library_editions e JOIN library_import_runs r ON r.id=e.import_run_id WHERE e.id=? AND e.version=? AND e.material_id IS NULL AND e.publication_state='draft' AND r.state IN ('verified','reconciled') AND json_extract(r.reconciliation_json,'$.contract.sourceCompleteness.authorDetailsComplete')=1 AND json_array_length(r.reconciliation_json,'$.contract.sourceCompleteness.authorsPending')=0 AND (coalesce(json_extract(e.public_metadata_json,'$.coverKind'),'')='placeholder' OR coalesce(length(json_extract(e.public_metadata_json,'$.coverSha256')),0)!=64 OR EXISTS(SELECT 1 FROM library_import_cover_receipts cr WHERE cr.import_run_id=e.import_run_id AND cr.sha256=json_extract(e.public_metadata_json,'$.coverSha256')))) AND NOT EXISTS(SELECT 1 FROM library_copies WHERE edition_id=? AND registration!='unreconciled') THEN 1 ELSE json('edition_changed') END").bind(input.editionId,input.expectedVersion,input.editionId),
  ];
  if(input.existingMaterialId)statements.push(db.prepare(`SELECT CASE WHEN EXISTS(SELECT 1 FROM materials WHERE id=? AND isbn_normalized=? AND status='active' AND archived_at IS NULL)
    AND NOT EXISTS(SELECT 1 FROM holdings WHERE material_id=?) AND NOT EXISTS(SELECT 1 FROM loan_items WHERE material_id=?) AND NOT EXISTS(SELECT 1 FROM class_loan_items WHERE material_id=?) AND NOT EXISTS(SELECT 1 FROM material_request_reservations WHERE material_id=?)
    AND NOT EXISTS(SELECT 1 FROM library_editions WHERE material_id=?) THEN 1 ELSE json('existing_stock_requires_reconciliation') END`).bind(materialId,isbn,materialId,materialId,materialId,materialId,materialId));
  else statements.push(db.prepare(`INSERT INTO materials(id,catalog_number,title,sort_title,search_text,rubric,publication_type,author,publication_year,isbn,isbn_normalized,publisher,status,version,created_at,updated_at)
    SELECT ?,?,?,?,?,?,?,?,?,?,?,?,'active',1,?,? WHERE ?='' OR NOT EXISTS(SELECT 1 FROM materials WHERE isbn_normalized=? AND status='active' AND archived_at IS NULL)`).bind(materialId,catalogNumber,String(edition.title),normalizeCatalogSearchText(String(edition.title)),normalizeCatalogSearchText([edition.title,value("author"),value("publisher"),value("genre"),value("isbn13"),value("isbn")].join(" ")),value("genre"),"Книга",value("author"),/^\d{4}$/.test(value("year"))?Number(value("year")):null,value("isbn13")||value("isbn"),isbn,value("publisher"),now,now,isbn,isbn),requireChanged(db,1));
  statements.push(db.prepare("UPDATE library_editions SET material_id=?,publication_state='published',version=version+1,updated_at=? WHERE id=? AND version=? AND material_id IS NULL").bind(materialId,now,input.editionId,input.expectedVersion),requireChanged(db,1));
  if(!input.existingMaterialId)statements.push(db.prepare("INSERT INTO materials_fts(rowid,title,author,isbn_normalized,publisher,rubric,subject,publication_type,search_text) SELECT rowid,title,author,isbn_normalized,publisher,rubric,subject,publication_type,search_text FROM materials WHERE id=?").bind(materialId));
  if(copies-loaned>0)statements.push(db.prepare("INSERT INTO holdings(material_id,location_id,condition,quantity,version,updated_at) VALUES(?,?,'unspecified',?,1,?)").bind(materialId,SOURCE_LOCATION,copies-loaned,now));
  statements.push(db.prepare("UPDATE reader_circulations SET accounting_mode='native',version=version+1,updated_at=? WHERE copy_id IN (SELECT id FROM library_copies WHERE edition_id=?) AND accounting_mode='unreconciled'").bind(now,input.editionId),
    db.prepare("UPDATE library_copies SET registration='registered',location_id=?,condition='unspecified',physical_state=CASE WHEN EXISTS(SELECT 1 FROM reader_circulations l WHERE l.copy_id=library_copies.id AND l.status IN ('issued','overdue')) THEN 'on_loan' ELSE 'on_shelf' END,version=version+1,updated_at=? WHERE edition_id=? AND registration='unreconciled'").bind(SOURCE_LOCATION,now,input.editionId),requireChanged(db,copies),
    db.prepare("INSERT INTO library_copy_movements(id,copy_id,command_id,kind,previous_state,next_state,destination_location_id,note,created_at) SELECT 'REG-'||id,id,?,'register','unknown',physical_state,location_id,'Початковий облік за реєстром Librarika; не акт фізичної інвентаризації',? FROM library_copies WHERE edition_id=?").bind(input.requestId,now,input.editionId),
    db.prepare("UPDATE library_historical_reviews SET publication_state='published' WHERE edition_id=? AND publication_state='draft'").bind(input.editionId),rebuildReaderStock(db,materialId,now),
    db.prepare("SELECT CASE WHEN (SELECT total_quantity FROM material_stock_totals WHERE material_id=?)=? AND (SELECT loaned_quantity FROM material_stock_totals WHERE material_id=?)=? THEN 1 ELSE json('activation_totals_mismatch') END").bind(materialId,copies,materialId,loaned),
    ...finishLibraryCommand(db,actor,input.requestId,"library.edition.activate",input.editionId,result,now));
  await readerBatch(db,statements);return result;
}

export async function issueReaderCopy(db:ReaderDatabase,actor:LibraryActor,input:{requestId:string;copyId:string;expectedCopyVersion:number;readerId:string;expectedReaderVersion:number;issuedAt:string;dueAt:string;bookRequestId?:string|null;confirmation:string}){
  if(input.confirmation!=="ISSUE_THIS_COPY")readerFail("issue_confirm","Підтвердьте видачу конкретного примірника.");expectedVersion(input.expectedCopyVersion);expectedVersion(input.expectedReaderVersion);dateOnly(input.issuedAt);dateOnly(input.dueAt);if(input.dueAt<input.issuedAt)readerFail("due_before_issue","Строк повернення має бути не раніше дати видачі.");
  const command=await libraryCommand(db,actor,input.requestId,"library.copy.issue",input);if(command.replayed)return command.replayed;
  const copy=await db.prepare("SELECT c.*,e.material_id,h.quantity holding_quantity FROM library_copies c JOIN library_editions e ON e.id=c.edition_id JOIN holdings h ON h.material_id=e.material_id AND h.location_id=c.location_id AND h.condition=c.condition WHERE c.id=? AND c.registration='registered' AND c.physical_state='on_shelf'").bind(input.copyId).first();if(!copy)readerFail("copy_unavailable","Цей примірник недоступний для видачі.",409);
  const now=new Date().toISOString(),id="RLOAN-"+crypto.randomUUID(),result={id,copyId:input.copyId,readerId:input.readerId,dueAt:input.dueAt};
  const statements:Statements=[beginLibraryCommand(db,actor,input.requestId,"library.copy.issue",command.hash,input.copyId,now),
    db.prepare(`INSERT INTO reader_circulations(id,copy_id,reader_id,status,issued_at,due_at,accounting_mode,created_at,updated_at)
      VALUES(?,(SELECT c.id FROM library_copies c JOIN library_editions e ON e.id=c.edition_id JOIN materials m ON m.id=e.material_id JOIN locations loc ON loc.id=c.location_id WHERE c.id=? AND c.version=? AND c.registration='registered' AND c.physical_state='on_shelf' AND m.status='active' AND loc.status='active'),
       (SELECT id FROM library_readers WHERE id=? AND version=? AND status='active'),'issued',?,?,'native',?,?)`).bind(id,input.copyId,input.expectedCopyVersion,input.readerId,input.expectedReaderVersion,input.issuedAt,input.dueAt,now,now),
    db.prepare("UPDATE library_copies SET physical_state='on_loan',version=version+1,updated_at=? WHERE id=? AND version=? AND physical_state='on_shelf'").bind(now,input.copyId,input.expectedCopyVersion),requireChanged(db,1),
    Number(copy.holding_quantity)===1?db.prepare("DELETE FROM holdings WHERE material_id=? AND location_id=? AND condition=? AND quantity=1").bind(String(copy.material_id),String(copy.location_id),String(copy.condition)):
    db.prepare("UPDATE holdings SET quantity=quantity-1,version=version+1,updated_at=? WHERE material_id=? AND location_id=? AND condition=? AND quantity>1").bind(now,String(copy.material_id),String(copy.location_id),String(copy.condition)),requireChanged(db,1),
    db.prepare("INSERT INTO library_copy_movements(id,copy_id,circulation_id,command_id,kind,previous_state,next_state,source_location_id,note,created_at) VALUES(?,?,?,?,'issue','on_shelf','on_loan',?,'',?)").bind(crypto.randomUUID(),input.copyId,id,input.requestId,String(copy.location_id),now),
  ];
  if(input.bookRequestId)statements.push(db.prepare("UPDATE reader_book_requests SET status='fulfilled',fulfilled_circulation_id=?,version=version+1,updated_at=? WHERE id=? AND reader_id=? AND edition_id=? AND status IN ('requested','ready')").bind(id,now,input.bookRequestId,input.readerId,String(copy.edition_id)),requireChanged(db,1));
  statements.push(copyInvariant(db,input.copyId),rebuildReaderStock(db,String(copy.material_id),now),...finishLibraryCommand(db,actor,input.requestId,"library.copy.issue",input.copyId,result,now));await readerBatch(db,statements);return result;
}
export async function returnReaderCopy(db:ReaderDatabase,actor:LibraryActor,input:{requestId:string;circulationId:string;expectedCirculationVersion:number;expectedCopyVersion:number;returnLocationId:string;condition:string;returnedAt:string;confirmation:string}){
  if(input.confirmation!=="RETURN_THIS_COPY")readerFail("return_confirm","Підтвердьте фактичне повернення примірника.");expectedVersion(input.expectedCirculationVersion);expectedVersion(input.expectedCopyVersion);dateOnly(input.returnedAt);conditionValue(input.condition);
  const command=await libraryCommand(db,actor,input.requestId,"library.copy.return",input);if(command.replayed)return command.replayed;
  const loan=await db.prepare("SELECT l.*,c.version copy_version,c.location_id,e.material_id FROM reader_circulations l JOIN library_copies c ON c.id=l.copy_id JOIN library_editions e ON e.id=c.edition_id WHERE l.id=? AND l.accounting_mode='native' AND l.status IN ('issued','overdue')").bind(input.circulationId).first();if(!loan)readerFail("loan_closed","Видачу вже закрито або її облік ще не перенесено.",409);if(loan.issued_at&&input.returnedAt<String(loan.issued_at).slice(0,10))readerFail("return_date","Повернення не може бути раніше видачі.");
  const now=new Date().toISOString(),result={id:input.circulationId,copyId:String(loan.copy_id),returnedAt:input.returnedAt};
  await readerBatch(db,[beginLibraryCommand(db,actor,input.requestId,"library.copy.return",command.hash,String(loan.copy_id),now),
    db.prepare("UPDATE reader_circulations SET status='returned',received_at=?,version=version+1,updated_at=? WHERE id=? AND version=? AND accounting_mode='native' AND status IN ('issued','overdue')").bind(input.returnedAt,now,input.circulationId,input.expectedCirculationVersion),requireChanged(db,1),
    db.prepare("INSERT INTO holdings(material_id,location_id,condition,quantity,version,updated_at) VALUES(?,(SELECT id FROM locations WHERE id=? AND status='active' AND type!='service'),?,1,1,?) ON CONFLICT(material_id,location_id,condition) DO UPDATE SET quantity=holdings.quantity+1,version=holdings.version+1,updated_at=excluded.updated_at").bind(String(loan.material_id),input.returnLocationId,input.condition,now),
    db.prepare("UPDATE library_copies SET physical_state='on_shelf',location_id=?,condition=?,version=version+1,updated_at=? WHERE id=? AND version=? AND physical_state='on_loan' AND registration='registered'").bind(input.returnLocationId,input.condition,now,String(loan.copy_id),input.expectedCopyVersion),requireChanged(db,1),
    db.prepare("INSERT INTO library_copy_movements(id,copy_id,circulation_id,command_id,kind,previous_state,next_state,source_location_id,destination_location_id,note,created_at) VALUES(?,?,?,?,'return','on_loan','on_shelf',?,?,'',?)").bind(crypto.randomUUID(),String(loan.copy_id),input.circulationId,input.requestId,String(loan.location_id),input.returnLocationId,now),
    db.prepare("UPDATE reader_notification_outbox SET status='cancelled',lease_token=NULL,lease_until=NULL WHERE circulation_id=? AND status IN ('pending','processing')").bind(input.circulationId),
    copyInvariant(db,String(loan.copy_id)),rebuildReaderStock(db,String(loan.material_id),now),...finishLibraryCommand(db,actor,input.requestId,"library.copy.return",String(loan.copy_id),result,now)]);return result;
}
export async function changeReaderDueDate(db:ReaderDatabase,actor:LibraryActor,input:{requestId:string;circulationId:string;expectedVersion:number;dueAt:string}){
  dateOnly(input.dueAt);expectedVersion(input.expectedVersion);const command=await libraryCommand(db,actor,input.requestId,"library.loan.due",input);if(command.replayed)return command.replayed;const now=new Date().toISOString(),result={id:input.circulationId,version:input.expectedVersion+1,dueAt:input.dueAt};
  await readerBatch(db,[beginLibraryCommand(db,actor,input.requestId,"library.loan.due",command.hash,input.circulationId,now),db.prepare("UPDATE reader_circulations SET due_at=?,status='issued',version=version+1,updated_at=? WHERE id=? AND version=? AND accounting_mode='native' AND status IN ('issued','overdue') AND (issued_at IS NULL OR substr(issued_at,1,10)<=?)").bind(input.dueAt,now,input.circulationId,input.expectedVersion,input.dueAt),requireChanged(db,1),db.prepare("UPDATE reader_notification_outbox SET status='cancelled',lease_token=NULL,lease_until=NULL WHERE circulation_id=? AND status IN ('pending','processing')").bind(input.circulationId),...finishLibraryCommand(db,actor,input.requestId,"library.loan.due",input.circulationId,result,now)]);return result;
}

export async function registerLibraryCopy(db:ReaderDatabase,actor:LibraryActor,input:{requestId:string;editionId:string;expectedEditionVersion:number;accessionNo:string;copyNo:string;locationId:string;condition:string}){
  expectedVersion(input.expectedEditionVersion);conditionValue(input.condition);
  if(typeof input.accessionNo!=="string"||!input.accessionNo.trim()||input.accessionNo.length>80||typeof input.copyNo!=="string"||input.copyNo.length>40)readerFail("copy_number","Вкажіть бібліотечний номер до 80 символів і номер примірника до 40 символів.");
  const command=await libraryCommand(db,actor,input.requestId,"library.copy.register",input);if(command.replayed)return command.replayed;
  const edition=await db.prepare("SELECT material_id FROM library_editions WHERE id=? AND version=? AND material_id IS NOT NULL").bind(input.editionId,input.expectedEditionVersion).first();if(!edition)readerFail("edition_changed","Оновіть картку книги.",409);
  const id="COPY-"+crypto.randomUUID(),now=new Date().toISOString(),result={id,editionId:input.editionId,accessionNo:input.accessionNo.trim()};
  await readerBatch(db,[beginLibraryCommand(db,actor,input.requestId,"library.copy.register",command.hash,id,now),
    db.prepare("SELECT CASE WHEN EXISTS(SELECT 1 FROM library_editions e JOIN materials m ON m.id=e.material_id WHERE e.id=? AND e.version=? AND m.status='active') AND NOT EXISTS(SELECT 1 FROM library_copies WHERE accession_no=?) THEN 1 ELSE json('copy_number_or_edition_changed') END").bind(input.editionId,input.expectedEditionVersion,input.accessionNo.trim()),
    db.prepare("INSERT INTO holdings(material_id,location_id,condition,quantity,version,updated_at) VALUES(?,(SELECT id FROM locations WHERE id=? AND type!='service' AND status='active'),?,1,1,?) ON CONFLICT(material_id,location_id,condition) DO UPDATE SET quantity=holdings.quantity+1,version=holdings.version+1,updated_at=excluded.updated_at").bind(String(edition.material_id),input.locationId,input.condition,now),
    db.prepare("INSERT INTO library_copies(id,edition_id,accession_no,copy_no,location_id,condition,registration,physical_state,created_at,updated_at) VALUES(?,?,?,?,?,?,'registered','on_shelf',?,?)").bind(id,input.editionId,input.accessionNo.trim(),input.copyNo.trim(),input.locationId,input.condition,now,now),
    db.prepare("INSERT INTO library_copy_movements(id,copy_id,command_id,kind,previous_state,next_state,destination_location_id,note,created_at) VALUES(?,?,?,'register','unknown','on_shelf',?,'Новий примірник, зареєстрований бібліотекарем',?)").bind(crypto.randomUUID(),id,input.requestId,input.locationId,now),
    copyInvariant(db,id),rebuildReaderStock(db,String(edition.material_id),now),...finishLibraryCommand(db,actor,input.requestId,"library.copy.register",id,result,now)]);return result;
}
export async function moveLibraryCopy(db:ReaderDatabase,actor:LibraryActor,input:{requestId:string;copyId:string;expectedVersion:number;action:"transfer"|"withdraw";locationId?:string;condition?:string;note:string;confirmation:string}){
  expectedVersion(input.expectedVersion);if(!["transfer","withdraw"].includes(input.action)||input.confirmation!=="CONFIRM_COPY_MOVEMENT"||typeof input.note!=="string"||input.note.length>1000||(input.action==="withdraw"&&input.note.trim().length<3))readerFail("copy_movement","Підтвердьте дію; для списання потрібна причина.");
  const command=await libraryCommand(db,actor,input.requestId,"library.copy.move",input);if(command.replayed)return command.replayed;
  const copy=await db.prepare("SELECT c.*,e.material_id,h.quantity FROM library_copies c JOIN library_editions e ON e.id=c.edition_id JOIN holdings h ON h.material_id=e.material_id AND h.location_id=c.location_id AND h.condition=c.condition WHERE c.id=? AND c.version=? AND c.registration='registered' AND c.physical_state='on_shelf'").bind(input.copyId,input.expectedVersion).first();if(!copy)readerFail("copy_not_on_shelf","Змінювати місце чи списувати можна лише примірник у бібліотеці. Спочатку оформіть повернення.",409);
  const withdraw=input.action==="withdraw",destination=withdraw?String(copy.location_id):String(input.locationId),condition=withdraw?String(copy.condition):conditionValue(input.condition);
  if(!withdraw&&destination===copy.location_id&&condition===copy.condition)readerFail("copy_no_change","Місце та стан примірника не змінилися.");
  const now=new Date().toISOString(),state=withdraw?"withdrawn":"on_shelf",kind=withdraw?"withdraw":destination===copy.location_id?"condition":"transfer",result={id:input.copyId,version:input.expectedVersion+1,state};
  const statements:Statements=[beginLibraryCommand(db,actor,input.requestId,"library.copy.move",command.hash,input.copyId,now)];
  if(!withdraw)statements.push(db.prepare("INSERT INTO holdings(material_id,location_id,condition,quantity,version,updated_at) VALUES(?,(SELECT id FROM locations WHERE id=? AND type!='service' AND status='active'),?,1,1,?) ON CONFLICT(material_id,location_id,condition) DO UPDATE SET quantity=holdings.quantity+1,version=holdings.version+1,updated_at=excluded.updated_at").bind(String(copy.material_id),destination,condition,now));
  statements.push(db.prepare("UPDATE library_copies SET location_id=?,condition=?,physical_state=?,version=version+1,updated_at=? WHERE id=? AND version=? AND registration='registered' AND physical_state='on_shelf'").bind(destination,condition,state,now,input.copyId,input.expectedVersion),requireChanged(db,1),
    Number(copy.quantity)===1?db.prepare("DELETE FROM holdings WHERE material_id=? AND location_id=? AND condition=? AND quantity=1").bind(String(copy.material_id),String(copy.location_id),String(copy.condition)):db.prepare("UPDATE holdings SET quantity=quantity-1,version=version+1,updated_at=? WHERE material_id=? AND location_id=? AND condition=? AND quantity>1").bind(now,String(copy.material_id),String(copy.location_id),String(copy.condition)),requireChanged(db,1),
    db.prepare("INSERT INTO library_copy_movements(id,copy_id,command_id,kind,previous_state,next_state,source_location_id,destination_location_id,note,created_at) VALUES(?,?,?,?,'on_shelf',?,?,?,?,?)").bind(crypto.randomUUID(),input.copyId,input.requestId,kind,state,String(copy.location_id),withdraw?null:destination,input.note.trim(),now),copyInvariant(db,input.copyId),rebuildReaderStock(db,String(copy.material_id),now),...finishLibraryCommand(db,actor,input.requestId,"library.copy.move",input.copyId,result,now));await readerBatch(db,statements);return result;
}
