import {normalizeCatalogSearchText} from './catalog-d1.ts';
import {readerFail,readerResource,type ReaderDatabase} from './reader-core.ts';
export const cabinetCover="'/api/reader/cover?id='||e.id||'&v='||e.version";
const fold=(column:string)=>[...'АБВГҐДЕЄЖЗИІЇЙКЛМНОПРСТУФХЦЧШЩЬЮЯЫЭЪЁ'].reduce((sql,c)=>`replace(${sql},'${c}','${c.toLowerCase()}')`,`lower(${column})`);
const visible="e.fund='literature' AND e.publication_state='published' AND (m.id IS NULL OR m.status='active')";
const from='library_editions e LEFT JOIN materials m ON m.id=e.material_id';
const relations=`(SELECT json_group_array(json_object('id',n.id,'kind',n.kind,'name',n.name,'role',x.role,'count',(SELECT count(DISTINCT related.id) FROM library_edition_entities rx JOIN library_editions related ON related.id=rx.edition_id LEFT JOIN materials rm ON rm.id=related.material_id WHERE rx.entity_id=n.id AND related.fund='literature' AND related.publication_state='published' AND (rm.id IS NULL OR rm.status='active')))) FROM library_edition_entities x JOIN library_catalog_entities n ON n.id=x.entity_id WHERE x.edition_id=e.id)`;
const projection=`e.id,e.title,${cabinetCover} cover_url,json_extract(e.public_metadata_json,'$.author') author,json_extract(e.public_metadata_json,'$.publisher') publisher,json_extract(e.public_metadata_json,'$.year') year,coalesce(json_extract(e.public_metadata_json,'$.type'),'Книга') type,${relations} relations_json,
 (SELECT count(*) FROM library_copies c WHERE c.edition_id=e.id AND c.registration='registered' AND c.physical_state!='withdrawn') total,
 (SELECT count(*) FROM library_copies c WHERE c.edition_id=e.id AND c.registration='registered' AND c.physical_state='on_shelf' AND NOT EXISTS(SELECT 1 FROM reader_circulations l WHERE l.copy_id=c.id AND l.status IN ('pending','reserved','issued','overdue'))) available`;
export function cabinetCard(row:Record<string,unknown>){const {relations_json,...rest}=row;const entities=[...new Map<string,any>(JSON.parse(String(relations_json||'[]')).map((e:any)=>[e.id,e])).values()];return {...rest,entities,author:entities.filter((x:any)=>x.kind==='author'&&['primary','author','coauthor'].includes(x.role)).map((x:any)=>x.name).join(', ')||row.author||'',publisher:entities.filter((x:any)=>x.kind==='publisher').map((x:any)=>x.name).join(', ')||row.publisher||''};}
export async function assertReaderEdition(db:ReaderDatabase,id:unknown){if(typeof id!=='string'||!readerResource(id)||!await db.prepare(`SELECT e.id FROM ${from} WHERE e.id=? AND ${visible}`).bind(id).first())readerFail('book_missing','Книга недоступна в художній бібліотеці.',404);return id;}
export async function cabinetCatalog(db:ReaderDatabase,url:URL){
 const raw=(url.searchParams.get('q')||'').trim(),q=normalizeCatalogSearchText(raw),page=Number(url.searchParams.get('page')||1),sort=url.searchParams.get('sort')||'title';
 if(q.length>100||!Number.isInteger(page)||page<1||page>10000||!['title','newest'].includes(sort))readerFail('catalog_query','Перевірте параметри пошуку.');
 const where=[visible],bind:(string|number)[]=[];
 if(q){where.push(`(m.search_text LIKE ? ESCAPE '!' OR ${fold('e.title')} LIKE ? ESCAPE '!' OR EXISTS(SELECT 1 FROM library_edition_entities sx JOIN library_catalog_entities sn ON sn.id=sx.entity_id WHERE sx.edition_id=e.id AND sn.kind='author' AND ${fold('sn.name')} LIKE ? ESCAPE '!'))`);bind.push('%'+q.replace(/[!%_]/g,v=>'!'+v)+'%','%'+raw.toLowerCase().replace(/[!%_]/g,v=>'!'+v)+'%','%'+raw.toLowerCase().replace(/[!%_]/g,v=>'!'+v)+'%');}
 for(const kind of ['genre','author','publisher','tag','series']){const id=url.searchParams.get(kind);if(id){if(!readerResource(id))readerFail('filter','Некоректний фільтр.');where.push('EXISTS(SELECT 1 FROM library_edition_entities x JOIN library_catalog_entities n ON n.id=x.entity_id WHERE x.edition_id=e.id AND x.entity_id=? AND n.kind=?)');bind.push(id,kind);}}
 const w=where.join(' AND '),total=Number((await db.prepare(`SELECT count(*) n FROM ${from} WHERE ${w}`).bind(...bind).first())?.n||0);
 const rows=await db.prepare(`SELECT ${projection} FROM ${from} WHERE ${w} ORDER BY ${sort==='newest'?'e.created_at DESC,e.id DESC':'coalesce(m.sort_title,e.title),e.id'} LIMIT 20 OFFSET ?`).bind(...bind,(page-1)*20).all();
 return {items:(rows.results||[]).map(cabinetCard),total,page,pages:Math.ceil(total/20)};
}
export async function cabinetFacets(db:ReaderDatabase,url:URL){const kind=url.searchParams.get('kind')||'genre',q=normalizeCatalogSearchText(url.searchParams.get('q')||''),page=Number(url.searchParams.get('page')||1);if(!['genre','author','publisher','tag','series'].includes(kind)||q.length>100||!Number.isInteger(page)||page<1||page>10000)readerFail('filter','Перевірте пошук.');
 // Empty focus does not load a directory. Only an explicit typed query requests suggestions.
 if(!q)return {items:[],more:false};const rows=await db.prepare(`SELECT n.id,n.kind,n.name,count(DISTINCT e.id) count FROM library_catalog_entities n JOIN library_edition_entities x ON x.entity_id=n.id JOIN library_editions e ON e.id=x.edition_id LEFT JOIN materials m ON m.id=e.material_id WHERE ${visible} AND n.kind=? AND ${fold('n.name')} LIKE ? ESCAPE '!' GROUP BY n.id ORDER BY n.name,n.id LIMIT 21 OFFSET ?`).bind(kind,'%'+q.replace(/[!%_]/g,v=>'!'+v)+'%',(page-1)*20).all();return {items:(rows.results||[]).slice(0,20),more:(rows.results||[]).length>20};}
export async function cabinetBook(db:ReaderDatabase,id:string){await assertReaderEdition(db,id);const row=await db.prepare(`SELECT ${projection},e.public_metadata_json FROM ${from} WHERE e.id=?`).bind(id).first();const {public_metadata_json,...card}=row!;const meta=JSON.parse(String(public_metadata_json||'{}'));
 const reviews=await db.prepare(`SELECT x.rating,x.body,CASE WHEN p.community_enabled=1 THEN p.display_name ELSE 'Читач бібліотеки' END display_name,x.updated_at date FROM library_ratings x JOIN reader_profiles p ON p.reader_id=x.reader_id WHERE x.edition_id=? AND x.review_state='published'
 UNION ALL SELECT rating,body,'Відгук з архіву бібліотеки',source_date_display FROM library_historical_reviews WHERE edition_id=? AND publication_state='published' ORDER BY date DESC LIMIT 100`).bind(id,id).all();

 return {...cabinetCard(card),annotation:meta.annotation||meta.description||'',reviews:reviews.results||[]};
}
export async function cabinetScan(db:ReaderDatabase,raw:string){let code=raw.trim();if(!code||code.length>200)readerFail('scan','Введіть код книги.');if(code.startsWith('https://')){let u:URL;try{u=new URL(code);}catch{readerFail('scan','Некоректний код.');}if(u!.hostname!=='yedyna-biblioteka-liceiu.nazarijshvetz1.chatgpt.site')readerFail('scan','Цей код належить іншому сайту.');code=u!.searchParams.get('book')||u!.searchParams.get('copy')||'';}
 const isbn=code.replace(/[^0-9X]/gi,'').toUpperCase();const rows=await db.prepare(`SELECT ${projection} FROM ${from} WHERE ${visible} AND (e.id=? OR e.material_id=? OR m.isbn_normalized=? OR json_extract(e.public_metadata_json,'$.isbn13')=? OR json_extract(e.public_metadata_json,'$.isbn10')=? OR EXISTS(SELECT 1 FROM library_copies c WHERE c.edition_id=e.id AND c.registration='registered' AND c.physical_state!='withdrawn' AND (c.id=? OR c.accession_no=?))) ORDER BY e.title LIMIT 100`).bind(code,code,isbn||'no-isbn',isbn||'no-isbn',isbn||'no-isbn',code,code).all();return {items:(rows.results||[]).map(cabinetCard)};}
