import {cabinetCatalog,cabinetCover,assertReaderEdition} from './reader-cabinet-catalog.ts';
import {readerBatch,readerFail,readerReceipt,readerReplay,requireChanged,type ReaderDatabase,type ReaderIdentity} from './reader-core.ts';
export const kyivDay=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Kyiv'}).format(new Date());
const loanFrom='reader_circulations l JOIN library_copies c ON c.id=l.copy_id JOIN library_editions e ON e.id=c.edition_id';
const loanStatus="CASE WHEN l.status IN ('issued','overdue') AND substr(l.due_at,1,10)<? THEN 'overdue' WHEN l.status='overdue' THEN 'issued' ELSE l.status END";
const pageOf=(u:URL)=>{const p=Number(u.searchParams.get('page')||1);if(!Number.isInteger(p)||p<1||p>10000)readerFail('page','Некоректна сторінка.');return p;};
export async function cabinetLoans(db:ReaderDatabase,who:ReaderIdentity,u:URL){const page=pageOf(u),requests=u.searchParams.get('tab')==='requests',filter=u.searchParams.get('status')||'active';if(!['active','overdue','returned','all'].includes(filter))readerFail('filter','Невідомий фільтр.');
 const where=["l.reader_id=? AND e.fund='literature'"],values:(string|number)[]=[who.readerId];if(filter==='active')where.push("l.status IN ('issued','overdue')");if(filter==='overdue'){where.push("l.status IN ('issued','overdue') AND substr(l.due_at,1,10)<?");values.push(kyivDay());}if(filter==='returned')where.push("l.status='returned'");
 const source=requests?'reader_book_requests q JOIN library_editions e ON e.id=q.edition_id':loanFrom,w=requests?"q.reader_id=? AND e.fund='literature'":where.join(' AND '),bind=requests?[who.readerId]:values;
 const total=Number((await db.prepare(`SELECT count(*) n FROM ${source} WHERE ${w}`).bind(...bind).first())?.n||0);
 const rows=await db.prepare(`SELECT ${requests?'q.id,q.status,q.created_at,q.updated_at,q.version':`l.id,${loanStatus} status,l.issued_at,l.due_at,l.received_at,l.updated_at`},e.id edition_id,e.title,${cabinetCover} cover_url FROM ${source} WHERE ${w} ORDER BY ${requests?'q.created_at DESC,q.id':'l.updated_at DESC,l.id'} LIMIT 20 OFFSET ?`).bind(...requests?[]:[kyivDay()],...bind,(page-1)*20).all();return {items:rows.results||[],total,page,pages:Math.ceil(total/20)};
}
export async function cabinetHome(db:ReaderDatabase,who:ReaderIdentity){const counts=await db.prepare(`SELECT count(*) active,coalesce(sum(CASE WHEN substr(l.due_at,1,10)<? THEN 1 ELSE 0 END),0) overdue FROM ${loanFrom} WHERE l.reader_id=? AND e.fund='literature' AND l.status IN ('issued','overdue')`).bind(kyivDay(),who.readerId).first();const recent=await cabinetLoans(db,who,new URL('https://local/?status=all'));const newBooks=await cabinetCatalog(db,new URL('https://local/?sort=newest'));return {counts,history:recent.items.slice(0,4),newBooks:newBooks.items.slice(0,3)};}
export async function cabinetActivity(db:ReaderDatabase,who:ReaderIdentity,u:URL){const page=pageOf(u),kind=u.searchParams.get('kind')||'reviews';if(!['reviews','recent','proposals'].includes(kind))readerFail('activity','Невідомий розділ.');
 const source=kind==='proposals'?'reader_literature_proposals x':kind==='recent'?'reader_recent_views x JOIN library_editions e ON e.id=x.edition_id':'library_ratings x JOIN library_editions e ON e.id=x.edition_id';
 const where=kind==='proposals'?'x.reader_id=?':"x.reader_id=? AND e.fund='literature' AND e.publication_state='published'";
 const projection=kind==='proposals'?'x.id,x.title,x.author,x.note,x.status,x.reply,x.created_at':kind==='recent'?`x.viewed_at,e.id edition_id,e.title,${cabinetCover} cover_url`:`x.rating,x.body,x.review_state status,x.updated_at,e.id edition_id,e.title,${cabinetCover} cover_url`;
 const total=Number((await db.prepare(`SELECT count(*) n FROM ${source} WHERE ${where}`).bind(who.readerId).first())?.n||0);const rows=await db.prepare(`SELECT ${projection} FROM ${source} WHERE ${where} ORDER BY ${kind==='recent'?'x.viewed_at':kind==='proposals'?'x.created_at':'x.updated_at'} DESC LIMIT 20 OFFSET ?`).bind(who.readerId,(page-1)*20).all();return {items:rows.results||[],total,page,pages:Math.ceil(total/20)};
}
export async function recordCabinetView(db:ReaderDatabase,who:ReaderIdentity,input:any){const id=await assertReaderEdition(db,input.editionId),r=await readerReplay(db,who,input.requestId,'recent_view',input);if(r.replayed)return r.replayed;const now=new Date().toISOString(),result={id};await readerBatch(db,[readerReceipt(db,who,input.requestId,'recent_view',r.hash,result,now),db.prepare('INSERT INTO reader_recent_views(reader_id,edition_id,viewed_at) VALUES(?,?,?) ON CONFLICT(reader_id,edition_id) DO UPDATE SET viewed_at=excluded.viewed_at').bind(who.readerId,id,now),db.prepare('DELETE FROM reader_recent_views WHERE reader_id=? AND edition_id NOT IN (SELECT edition_id FROM reader_recent_views WHERE reader_id=? ORDER BY viewed_at DESC,edition_id LIMIT 100)').bind(who.readerId,who.readerId)]);return result;}
export async function proposeCabinetBook(db:ReaderDatabase,who:ReaderIdentity,input:any){if(input.confirmation!=='SEND_BOOK_PROPOSAL'||typeof input.title!=='string'||input.title.trim().length<2||input.title.length>300||typeof input.author!=='string'||input.author.length>200||typeof input.note!=='string'||input.note.length>2000)readerFail('proposal','Додайте назву книги й перевірте поля.');const r=await readerReplay(db,who,input.requestId,'literature_proposal',input);if(r.replayed)return r.replayed;const id=crypto.randomUUID(),now=new Date().toISOString(),result={id,status:'submitted'};await readerBatch(db,[readerReceipt(db,who,input.requestId,'literature_proposal',r.hash,result,now),db.prepare("SELECT CASE WHEN (SELECT count(*) FROM reader_literature_proposals WHERE reader_id=? AND created_at>?)<10 THEN 1 ELSE json('proposal_limit') END").bind(who.readerId,new Date(Date.now()-86400000).toISOString()),db.prepare("INSERT INTO reader_literature_proposals(id,reader_id,title,author,note,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").bind(id,who.readerId,input.title.trim(),input.author.trim(),input.note.trim(),now,now)]);return result;}
