import {readerBatch,readerFail,readerReceipt,readerReplay,requireChanged,type ReaderDatabase,type ReaderIdentity,type LibraryActor} from './reader-core.ts';
import {assertReaderEdition,cabinetCover} from './reader-cabinet-catalog.ts';
import {beginLibraryCommand,finishLibraryCommand,libraryCommand} from './library-copy-store.ts';
const notBlocked="NOT EXISTS(SELECT 1 FROM reader_blocks b WHERE (b.reader_id=? AND b.blocked_reader_id=x.reader_id) OR (b.blocked_reader_id=? AND b.reader_id=x.reader_id))";
async function consent(db:ReaderDatabase,who:ReaderIdentity){if(!await db.prepare('SELECT 1 ok FROM reader_profiles WHERE reader_id=? AND community_enabled=1').bind(who.readerId).first())readerFail('community_consent','Увімкніть участь у спільноті в обліковому записі.',403);}
export async function readerFeed(db:ReaderDatabase,who:ReaderIdentity,u:URL){await consent(db,who);const page=Number(u.searchParams.get('page')||1),post=u.searchParams.get('post');if(!Number.isInteger(page)||page<1||page>10000)readerFail('page','Перевірте сторінку.');const table=post?'reader_feed_comments':'reader_feed_posts';
 if(post&&!await db.prepare(`SELECT x.id FROM reader_feed_posts x WHERE x.id=? AND x.status='visible' AND ${notBlocked}`).bind(post,who.readerId,who.readerId).first())readerFail('post','Допис недоступний.',404);
 const where=`x.status='visible' AND ${notBlocked}${post?" AND x.post_id=? AND EXISTS(SELECT 1 FROM reader_feed_posts parent WHERE parent.id=x.post_id AND parent.status='visible' AND NOT EXISTS(SELECT 1 FROM reader_blocks b WHERE (b.reader_id=? AND b.blocked_reader_id=parent.reader_id) OR (b.blocked_reader_id=? AND b.reader_id=parent.reader_id)))":''}`,args=post?[who.readerId,who.readerId,post,who.readerId,who.readerId]:[who.readerId,who.readerId];const total=Number((await db.prepare(`SELECT count(*) n FROM ${table} x WHERE ${where}`).bind(...args).first())?.n||0);
 const rows=await db.prepare(`SELECT x.id,x.reader_id,x.body,x.version,x.created_at,CASE WHEN p.community_enabled=1 THEN p.display_name ELSE 'Читач бібліотеки' END display_name,${post?'NULL edition_id,NULL title,NULL cover_url,0 comments':`CASE WHEN e.publication_state='published' THEN e.id ELSE NULL END edition_id,CASE WHEN e.publication_state='published' THEN e.title ELSE NULL END title,CASE WHEN e.publication_state='published' THEN ${cabinetCover} ELSE NULL END cover_url,(SELECT count(*) FROM reader_feed_comments c WHERE c.post_id=x.id AND c.status='visible') comments`} FROM ${table} x JOIN reader_profiles p ON p.reader_id=x.reader_id ${post?'':'LEFT JOIN library_editions e ON e.id=x.edition_id'} WHERE ${where} ORDER BY x.created_at DESC,x.id DESC LIMIT 20 OFFSET ?`).bind(...args,(page-1)*20).all();return {items:rows.results||[],total,page,pages:Math.ceil(total/20)};
}
export async function saveFeedContent(db:ReaderDatabase,who:ReaderIdentity,input:any){await consent(db,who);if(!['post','comment','remove_post','remove_comment'].includes(input.kind))readerFail('feed','Невідома дія.');const replay=await readerReplay(db,who,input.requestId,'feed',input);if(replay.replayed)return replay.replayed;const now=new Date().toISOString(),remove=input.kind.startsWith('remove'),isPost=input.kind.endsWith('post'),table=isPost?'reader_feed_posts':'reader_feed_comments',id=remove?input.id:crypto.randomUUID(),result={id},statements=[readerReceipt(db,who,input.requestId,'feed',replay.hash,result,now),db.prepare("SELECT CASE WHEN EXISTS(SELECT 1 FROM reader_profiles WHERE reader_id=? AND community_enabled=1) THEN 1 ELSE json('community_consent_changed') END").bind(who.readerId)];
 if(remove){if(!Number.isInteger(input.expectedVersion))readerFail('version','Оновіть допис.');statements.push(db.prepare(`UPDATE ${table} SET status='removed',body='',version=version+1,updated_at=? WHERE id=? AND reader_id=? AND version=? AND status='visible'`).bind(now,id,who.readerId,input.expectedVersion),requireChanged(db,1));}
 else{if(typeof input.body!=='string'||!input.body.trim()||input.body.length>(isPost?4000:2000))readerFail('feed_body','Напишіть текст без особистих даних.');if(isPost&&input.editionId)await assertReaderEdition(db,input.editionId);statements.push(db.prepare(`SELECT CASE WHEN (SELECT count(*) FROM ${table} WHERE reader_id=? AND created_at>?)<10 THEN 1 ELSE json('feed_rate_limit') END`).bind(who.readerId,new Date(Date.now()-60000).toISOString()));
 if(isPost)statements.push(db.prepare('INSERT INTO reader_feed_posts(id,reader_id,edition_id,body,created_at,updated_at) VALUES(?,?,?,?,?,?)').bind(id,who.readerId,input.editionId||null,input.body.trim(),now,now));else statements.push(db.prepare(`INSERT INTO reader_feed_comments(id,reader_id,post_id,body,created_at,updated_at) VALUES(?,?,(SELECT x.id FROM reader_feed_posts x WHERE x.id=? AND x.status='visible' AND ${notBlocked}),?,?,?)`).bind(id,who.readerId,input.postId,who.readerId,who.readerId,input.body.trim(),now,now));}
 await readerBatch(db,statements);return result;
}
export async function cabinetModeration(db:ReaderDatabase,u:URL){const view=u.searchParams.get('section')||'requests',page=Number(u.searchParams.get('page')||1);if(!Number.isInteger(page)||page<1||page>10000)readerFail('page','Некоректна сторінка.');let source,projection,where,order;
 if(view==='requests'){source='reader_book_requests x JOIN library_editions e ON e.id=x.edition_id JOIN library_readers r ON r.id=x.reader_id';projection=`x.*,e.title,'/api/librarian/literature/image?kind=edition&id='||e.id||'&v='||e.version cover_url,r.full_name,r.version reader_version`;where="e.fund='literature'";order="CASE WHEN x.status='requested' THEN 0 WHEN x.status='ready' THEN 1 ELSE 2 END,x.created_at DESC";}
 else if(view==='proposals'){source='reader_literature_proposals x JOIN library_readers r ON r.id=x.reader_id';projection='x.*,r.full_name';where='1';order="CASE WHEN x.status='submitted' THEN 0 ELSE 1 END,x.created_at DESC";}
 else if(['posts','comments'].includes(view)){source=(view==='posts'?'reader_feed_posts':'reader_feed_comments')+' x JOIN library_readers r ON r.id=x.reader_id';projection='x.*,r.full_name';where="x.status!='removed'";order='x.created_at DESC';}else readerFail('view','Невідомий розділ.');
 const total=Number((await db.prepare(`SELECT count(*) n FROM ${source} WHERE ${where}`).first())?.n||0);const rows=await db.prepare(`SELECT ${projection} FROM ${source} WHERE ${where} ORDER BY ${order},x.id LIMIT 20 OFFSET ?`).bind((page-1)*20).all();return {items:rows.results||[],total,page,pages:Math.ceil(total/20)};
}
export async function moderateCabinet(db:ReaderDatabase,actor:LibraryActor,input:any){const types:Record<string,string>={post:'reader_feed_posts',comment:'reader_feed_comments',proposal:'reader_literature_proposals'},table=types[input.kind];if(!table||!Number.isInteger(input.expectedVersion))readerFail('moderate','Оновіть форму.');if(input.kind==='proposal'?!['submitted','in_review','approved','received','rejected'].includes(input.status):!['visible','hidden','removed'].includes(input.status))readerFail('status','Перевірте статус.');if(typeof input.reply!=='string'||input.reply.length>2000)readerFail('reply','Відповідь — до 2000 символів.');const command=await libraryCommand(db,actor,input.requestId,'reader.cabinet.moderate',input);if(command.replayed)return command.replayed;const now=new Date().toISOString(),result={id:input.id,status:input.status};await readerBatch(db,[beginLibraryCommand(db,actor,input.requestId,'reader.cabinet.moderate',command.hash,input.id,now),db.prepare(`UPDATE ${table} SET status=?,${input.kind==='proposal'?'reply=?':"body=CASE WHEN ?='removed' THEN '' ELSE body END"},version=version+1,updated_at=? WHERE id=? AND version=?`).bind(input.status,input.kind==='proposal'?input.reply:input.status,now,input.id,input.expectedVersion),requireChanged(db,1),...finishLibraryCommand(db,actor,input.requestId,'reader.cabinet.moderate',input.id,result,now)]);return result;}
