import {getRuntimeBoolean} from './runtime-env.ts';
import {normalizeCatalogSearchText} from './catalog-d1.ts';
import {readerBatch,readerFail,requireChanged,type ReaderDatabase} from './reader-core.ts';
// Identity comes only from the already-authenticated canonical teacher account.
// Exact, unique full-name source matching was explicitly approved by the owner.
const exact=(s:unknown)=>String(s||'').normalize('NFC').trim().replace(/\s+/g,' ').toLocaleLowerCase('uk-UA');
export async function ensureTeacherReader(db:ReaderDatabase,teacherId:string,actor?:{id:string;email:string}){
 const teacher=await db.prepare("SELECT u.id,u.full_name,u.sort_name,p.subject_position FROM users u JOIN teacher_profiles p ON p.teacher_user_id=u.id WHERE u.id=? AND u.status='active' AND p.closed_at IS NULL").bind(teacherId).first();if(!teacher)readerFail('teacher_inactive','Учительський акаунт недоступний.',403);
 let linked=await db.prepare('SELECT id,access_version,status,access_status FROM library_readers WHERE linked_teacher_user_id=?').bind(teacherId).first();
 if(linked){if(linked.status!=='active'||linked.access_status!=='active')readerFail('reader_blocked','Читацький профіль призупинено бібліотекарем.',403);return linked;}
 if(!getRuntimeBoolean('LIBRARIAN_WRITES_ENABLED'))readerFail('writes_disabled','Приєднання тимчасово вимкнено адміністратором.',503);
 const snapshotSql="SELECT json_group_array(json_array(id,full_name,version,kind,status,access_status,linked_teacher_user_id)) value FROM (SELECT * FROM library_readers WHERE kind!='student' ORDER BY id)",teacherSnapshotSql="SELECT json_group_array(json_array(id,full_name,version)) value FROM (SELECT u.id,u.full_name,p.version FROM users u JOIN teacher_profiles p ON p.teacher_user_id=u.id WHERE u.status='active' AND p.closed_at IS NULL ORDER BY u.id)";
 const snapshot=String((await db.prepare(snapshotSql).first())?.value||'[]'),teacherSnapshot=String((await db.prepare(teacherSnapshotSql).first())?.value||'[]');
 const teachers=(await db.prepare("SELECT u.id,u.full_name FROM users u JOIN teacher_profiles p ON p.teacher_user_id=u.id WHERE u.status='active' AND p.closed_at IS NULL").all()).results||[];
 const candidates=((await db.prepare("SELECT id,full_name,version,access_version,status,access_status,linked_teacher_user_id FROM library_readers WHERE kind!='student'").all()).results||[]).filter(r=>exact(r.full_name)===exact(teacher.full_name));
 if(candidates.length>1||teachers.filter(t=>exact(t.full_name)===exact(teacher.full_name)).length>1)readerFail('teacher_reader_ambiguous','Є однойменні записи. Бібліотекар має підтвердити читацький профіль.',409);
 const candidate=candidates[0],now=new Date().toISOString();if(candidate&&(candidate.linked_teacher_user_id||candidate.status!=='active'||candidate.access_status==='blocked'))readerFail('teacher_reader_conflict','Потрібна звірка читацького профілю бібліотекарем.',409);
 const id=String(candidate?.id||('TEACHER-'+teacherId)),statements=[db.prepare(`SELECT CASE WHEN ((${snapshotSql})=?) AND ((${teacherSnapshotSql})=?) AND EXISTS(SELECT 1 FROM users WHERE id=? AND full_name=?) THEN 1 ELSE json('teacher_reader_changed') END`).bind(snapshot,teacherSnapshot,teacherId,String(teacher.full_name))];
 if(actor)statements.unshift(db.prepare("SELECT CASE WHEN EXISTS(SELECT 1 FROM users WHERE id=? AND role='admin' AND status='active') THEN 1 ELSE json('teacher_sync_forbidden') END").bind(actor.id));
 if(candidate){statements.push(db.prepare("UPDATE library_readers SET linked_teacher_user_id=?,kind='teacher',access_status='active',access_version=access_version+1,version=version+1,updated_at=? WHERE id=? AND version=? AND linked_teacher_user_id IS NULL AND status='active' AND access_status!='blocked' AND EXISTS(SELECT 1 FROM users u JOIN teacher_profiles p ON p.teacher_user_id=u.id WHERE u.id=? AND u.status='active' AND p.closed_at IS NULL)").bind(teacherId,now,id,Number(candidate.version),teacherId),requireChanged(db,1),db.prepare('UPDATE reader_sessions SET revoked_at=? WHERE reader_id=? AND revoked_at IS NULL').bind(now,id),db.prepare('UPDATE reader_invites SET revoked_at=? WHERE reader_id=? AND consumed_at IS NULL AND revoked_at IS NULL').bind(now,id),db.prepare("UPDATE reader_telegram_connections SET status='disabled',disabled_at=?,version=version+1 WHERE reader_id=?").bind(now,id));}
 else {statements.push(db.prepare('INSERT INTO reader_number_allocations(request_id,reader_id,created_at) VALUES(?,?,?)').bind('teacher:'+teacherId,id,now),db.prepare("INSERT INTO library_readers(id,member_no,full_name,sort_name,kind,status,access_status,linked_teacher_user_id,created_at,updated_at) SELECT ?,CAST(26000000+ordinal AS TEXT),?,?,'teacher','active','active',?,?,? FROM reader_number_allocations WHERE request_id=? AND EXISTS(SELECT 1 FROM users u JOIN teacher_profiles p ON p.teacher_user_id=u.id WHERE u.id=? AND u.status='active' AND p.closed_at IS NULL)").bind(id,String(teacher.full_name),normalizeCatalogSearchText(String(teacher.full_name)),teacherId,now,now,'teacher:'+teacherId,teacherId),requireChanged(db,1));}
 statements.push(db.prepare("INSERT INTO reader_profiles(reader_id,display_name,subject_position,updated_at) VALUES(?,'Читач',?,?) ON CONFLICT(reader_id) DO NOTHING").bind(id,String(teacher.subject_position||''),now),db.prepare("INSERT INTO audit_events(id,actor_user_id,actor_email,action,entity_type,entity_id,metadata_json,created_at) VALUES(?,?,'','reader.teacher_reconcile','library_reader',?,?,?)").bind(crypto.randomUUID(),actor?.id||teacherId,id,JSON.stringify({teacherId,trigger:actor?'librarian_reconciliation':'authenticated_teacher',mode:candidate?'unique_exact_match':'new_reader_profile'}),now));
 try{await readerBatch(db,statements);}catch(e){linked=await db.prepare("SELECT id,access_version,status,access_status FROM library_readers WHERE linked_teacher_user_id=? AND status='active' AND access_status='active'").bind(teacherId).first();if(linked)return linked;throw e;}
 return (await db.prepare('SELECT id,access_version,status,access_status FROM library_readers WHERE id=?').bind(id).first())!;
}
export async function teacherReaderAudit(db:ReaderDatabase){const teachers=(await db.prepare("SELECT u.id,u.full_name,r.id reader_id,r.member_no,r.access_status FROM users u JOIN teacher_profiles p ON p.teacher_user_id=u.id LEFT JOIN library_readers r ON r.linked_teacher_user_id=u.id WHERE u.status='active' AND p.closed_at IS NULL ORDER BY u.sort_name").all()).results||[];const unresolved=(await db.prepare("SELECT r.id,r.full_name,r.member_no,r.status,(SELECT count(*) FROM reader_circulations l WHERE l.reader_id=r.id AND l.status IN ('issued','overdue','pending','reserved')) open_loans FROM library_readers r WHERE r.kind!='student' AND r.linked_teacher_user_id IS NULL ORDER BY r.sort_name").all()).results||[];return {teachers,unresolved};}
export async function syncTeacherReaders(db:ReaderDatabase,actor?:{id:string;email:string},after:unknown=''){
 if(typeof after!=='string'||after.length>200)readerFail('teacher_cursor','Оновіть звірку.');
 // At most two identities per request: under 50 D1 statements, including API authorization.
 const rows=(await db.prepare("SELECT u.id FROM users u JOIN teacher_profiles p ON p.teacher_user_id=u.id WHERE u.status='active' AND p.closed_at IS NULL AND u.id>? ORDER BY u.id LIMIT 3").bind(after).all()).results||[],batch=rows.slice(0,2),results=[];
 for(const teacher of batch){try{const reader=await ensureTeacherReader(db,String(teacher.id),actor);results.push({teacherId:teacher.id,readerId:reader.id,status:'linked'});}catch(e){results.push({teacherId:teacher.id,status:'review',message:e instanceof Error&&'code' in e?e.message:'Не вдалося підтвердити прив’язку; повторіть звірку.'});}}
 return {results,processed:batch.length,nextCursor:rows.length>2?String(batch.at(-1)!.id):null};
}
