import {readerInbox,markReaderMessage} from '@/lib/reader-messages';
import {env} from 'cloudflare:workers';
import {requireReaderSession} from '@/lib/reader-auth';import {readerJson,readerApiError,readerWriteBody} from '@/lib/reader-api';import {readerFail,type ReaderDatabase} from '@/lib/reader-core';
import {cabinetCatalog,cabinetBook,cabinetFacets,cabinetEntities,cabinetEntity,cabinetScan,assertReaderEdition} from '@/lib/reader-cabinet-catalog';import {cabinetHome,cabinetLoans,cabinetActivity,recordCabinetView,proposeCabinetBook} from '@/lib/reader-cabinet';
import {getReaderBookState,requestReaderBook,cancelReaderBookRequest,saveReaderRating} from '@/lib/reader-profile-store';
export const dynamic='force-dynamic';
export async function GET(request:Request){try{const db=env.DB as unknown as ReaderDatabase,who=await requireReaderSession(db,request),u=new URL(request.url),view=u.searchParams.get('view')||'home',id=u.searchParams.get('id')||'';let result;
 if(view==='messages')result=await readerInbox(db,who,u);else if(view==='catalog')result=await cabinetCatalog(db,u);else if(view==='facets')result=await cabinetFacets(db,u);else if(view==='entities')result=await cabinetEntities(db,u);else if(view==='entity')result=await cabinetEntity(db,u);else if(view==='scan')result=await cabinetScan(db,u.searchParams.get('code')||'');else if(view==='book')result={book:await cabinetBook(db,id),own:await getReaderBookState(db,who,id)};else if(view==='home')result=await cabinetHome(db,who);else if(view==='loans')result=await cabinetLoans(db,who,u);else if(view==='activity')result=await cabinetActivity(db,who,u);else readerFail('view','Невідомий розділ.');return readerJson({success:true,result});}catch(e){return readerApiError(e);}}
export async function POST(request:Request){try{const db=env.DB as unknown as ReaderDatabase,who=await requireReaderSession(db,request),body=await readerWriteBody(request),input=body.input as any;if(!input||typeof input!=='object'||Array.isArray(input))readerFail('input','Перевірте форму.');let result;if(['request','rating','view'].includes(String(body.action)))await assertReaderEdition(db,input.editionId);
 if(body.action==='read_message')result=await markReaderMessage(db,who,input.id);else if(body.action==='request')result=await requestReaderBook(db,who,input);else if(body.action==='cancel')result=await cancelReaderBookRequest(db,who,input);else if(body.action==='rating')result=await saveReaderRating(db,who,input);else if(body.action==='view')result=await recordCabinetView(db,who,input);else if(body.action==='proposal')result=await proposeCabinetBook(db,who,input);else readerFail('action','Невідома дія.');return readerJson({success:true,result});}catch(e){return readerApiError(e);}}
