"use client";
/* eslint-disable @next/next/no-img-element */
import {useEffect,useState} from "react";
import {readerFetch,readerDate,type ReaderLoan,type ReaderRequest} from "./reader-types";
import s from "./reader.module.css";
const statuses:Record<string,string>={issued:"На руках",overdue:"Прострочено",returned:"Повернено",pending:"Очікує",reserved:"Зарезервовано",cancelled:"Скасовано",requested:"Замовлено",ready:"Готово до видачі",fulfilled:"Видано",rejected:"Відхилено"};
export default function BooksPanel({onBook,readerId}:{onBook:(id:string)=>void;readerId:string}){
  const [data,setData]=useState<{loans:ReaderLoan[];requests:ReaderRequest[]}>({loans:[],requests:[]}),[error,setError]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[tab,setTab]=useState("current"),[cancel,setCancel]=useState<string|null>(null);
  async function refresh(){try{setData(await readerFetch("/api/reader/books",undefined,"GET",readerId));}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
  useEffect(()=>{void refresh();},[]);
  const active=data.loans.filter(l=>["issued","overdue"].includes(l.status)),today=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Kyiv"}).format(new Date());
  const isOverdue=(l:ReaderLoan)=>["issued","overdue"].includes(l.status)&&!!l.due_at&&l.due_at.slice(0,10)<today;
  async function cancelRequest(q:ReaderRequest){setBusy(true);setError("");try{await readerFetch("/api/reader/books",{action:"cancel",input:{requestId:crypto.randomUUID(),id:q.id,expectedVersion:q.version}},"POST",readerId);setCancel(null);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const list=tab==="current"?active:data.loans.filter(l=>!["issued","overdue"].includes(l.status));
  return <section><div className={s.sectionHead}><div><span className={s.eyebrow}>Читаю, відкриваю, повертаю</span><h1>Мої книги</h1></div><button className={s.quiet} onClick={()=>void refresh()}>Оновити</button></div><div className={s.stats}><div className={s.stat}><strong>{active.length}</strong><span>Книг на руках</span></div><div className={s.stat}><strong>{active.filter(isOverdue).length}</strong><span>Потрібно повернути</span></div><div className={s.stat}><strong>{data.requests.filter(q=>["requested","ready"].includes(q.status)).length}</strong><span>Моїх замовлень</span></div></div>
    <div className={s.funds}>{[["current","На руках"],["requests","Замовлення"],["history","Історія"]].map(([id,label])=><button key={id} className={tab===id?s.selected:""} onClick={()=>setTab(id)}>{label}</button>)}</div>{error&&<p className={s.error} role="alert">{error}</p>}{loading?<p className={s.muted}>Завантажуємо твої книги…</p>:tab==="requests"?<div className={s.loanList}>{data.requests.length===0&&<p className={s.empty}>Замовлень поки немає. Знайди цікаву книгу в каталозі.</p>}{data.requests.map(q=><article className={s.loan} key={q.id}>{q.cover_url&&<img src={q.cover_url} alt=""/>}<div className={s.loanContent}><button onClick={()=>onBook(q.edition_id)}>{q.title}</button><p>{readerDate(q.created_at)}{q.note&&` · ${q.note}`}</p></div><span className={s.badge}>{statuses[q.status]||q.status}</span>{["requested","ready"].includes(q.status)&&(cancel===q.id?<div className={s.actions}><span className={s.muted}>Скасувати це замовлення?</span><button className={s.danger} disabled={busy} onClick={()=>void cancelRequest(q)}>Так, скасувати</button><button className={s.quiet} onClick={()=>setCancel(null)}>Залишити</button></div>:<button className={s.quiet} onClick={()=>setCancel(q.id)}>Скасувати</button>)}</article>)}</div>:<div className={s.loanList}>{list.length===0&&<p className={s.empty}>{tab==="current"?"Зараз на тебе не записано книг.":"Тут з’являтиметься історія читання."}</p>}{list.map(l=><article className={s.loan} key={l.id}>{l.cover_url&&<img src={l.cover_url} alt=""/>}<div className={s.loanContent}><button onClick={()=>onBook(l.edition_id)}>{l.title}</button><p>{l.author} · Примірник № {l.accession_no||l.copy_no}</p><p>Видано: {readerDate(l.issued_at)} · Повернути до: <strong>{readerDate(l.due_at)}</strong>{l.received_at&&` · Повернено: ${readerDate(l.received_at)}`}</p></div><span className={`${s.badge} ${isOverdue(l)?s.overdue:""}`}>{isOverdue(l)?"Потрібно повернути":statuses[l.status]||l.status}</span></article>)}</div>}
    <p className={s.muted}>Фактичну видачу, повернення та зміну строку оформлює бібліотекар. Замовлення саме по собі не означає, що книгу вже видано.</p></section>;
}
