"use client";
import {useEffect,useRef,useState} from "react";
import {Bell,BookOpen,Check,MessageCircle,Share2,ShoppingBag,X} from "lucide-react";
import {readerFetch,type BookDetail,type ReaderProfile} from "./reader-types";
import styles from "./reader.module.css";
type OwnState={rating:{rating:number;body:string;review_state:string;version:number}|null;subscribed:boolean;request:{id:string;status:string}|null};
export default function BookDialog({id,profile,onClose,onEntity,onShare,onLogin}:{id:string;profile:ReaderProfile|null;onClose:()=>void;onEntity:(id:string,kind:string)=>void;onShare:(id:string)=>void;onLogin:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null),intent=useRef<string|null>(null);
  const [book,setBook]=useState<BookDetail|null>(null),[own,setOwn]=useState<OwnState>({rating:null,subscribed:false,request:null}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const [confirm,setConfirm]=useState(false),[note,setNote]=useState(""),[rating,setRating]=useState(0),[body,setBody]=useState(""),[ownLoaded,setOwnLoaded]=useState(false);
  useEffect(()=>{dialog.current?.showModal();let current=true;readerFetch<{result:BookDetail}>("/api/library/catalog?book="+encodeURIComponent(id)).then(data=>{if(current)setBook(data.result);}).catch(error=>{if(current)setMessage(error.message);});return()=>{current=false;};},[id]);
  async function refresh(){if(!profile||!book||book.fund==="education")return;const data=await readerFetch<OwnState>("/api/reader/books?edition="+encodeURIComponent(String(book.id)),undefined,"GET",profile.id);setOwn(data);setRating(data.rating?.rating||0);setBody(data.rating?.body||"");setOwnLoaded(true);}
  useEffect(()=>{void refresh().catch(()=>{});},[profile?.id,book?.id]);
  async function act(action:string,input:Record<string,unknown>,success:string){if(!profile){onLogin();return;}setBusy(true);setMessage("");try{await readerFetch("/api/reader/books",{action,input:{requestId:intent.current||crypto.randomUUID(),editionId:book?.id,...input}},"POST",profile.id);intent.current=null;setConfirm(false);setMessage(success);try{await refresh();}catch{setMessage(success+" Онови картку, щоб побачити актуальний стан.");setOwnLoaded(false);}}catch(error){setMessage(error instanceof Error?error.message:"Не вдалося зберегти.");await refresh().catch(()=>{});}finally{setBusy(false);}}
  async function share(){if(!book)return;const url=new URL("/library",window.location.origin);url.searchParams.set("book",String(book.id));try{if(navigator.share)await navigator.share({title:book.title,text:"Зазирни до цієї книги в Єдиній бібліотеці",url:url.href});else{await navigator.clipboard.writeText(url.href);setMessage("Покликання на книгу скопійовано.");}}catch{/* Cancelling the platform share sheet does not send a message. */}}
  const value=(key:string)=>{const value=book?.metadata[key];return typeof value==="string"||typeof value==="number"?String(value):"";};
  return <dialog ref={dialog} className={styles.dialog} onCancel={onClose} onClick={event=>{if(event.target===event.currentTarget)onClose();}} aria-labelledby="reader-book-title"><div className={styles.dialogInner}>
    <div className={styles.dialogTop}><div><p className={styles.eyebrow}>Книжкова полиця ліцею</p><h2 id="reader-book-title">{book?.title||"Відкриваємо книгу…"}</h2></div><button className={styles.iconButton} onClick={onClose} aria-label="Закрити інформацію про книгу"><X size={20}/></button></div>
    {message&&<p className={styles.notice} role="status">{message}</p>}
    {book&&<><div className={styles.detailTop}><div>{value("coverUrl")?<img className={styles.detailCover} src={value("coverUrl")} alt={`Обкладинка «${book.title}»`}/>:<div className={styles.coverWrap}><BookOpen size={64}/></div>}</div><div><dl className={styles.detailMeta}>{[["Автор","author"],["Видавництво","publisher"],["Рік видання","year"],["Сторінок","pages"],["ISBN","isbn"],["Жанр","genre"],["Мова","language"]].filter(([,key])=>value(key)).map(([label,key])=><span key={key} style={{display:"contents"}}><dt>{label}</dt><dd>{value(key)}</dd></span>)}</dl><p className={styles.muted}>{Number(book.available)>0?`Доступно в бібліотеці: ${book.available}`:"Наявність уточнить бібліотекар"} · У фонді: {book.total}</p><div className={styles.chips}>{book.entities.map(entity=><button key={entity.id+entity.role} onClick={()=>onEntity(entity.id,entity.kind)}>{entity.name}</button>)}</div></div></div>
      <div className={styles.actions}>{book.fund==="literature"?<><button className={styles.button} disabled={busy||!!own.request||!!profile&&!ownLoaded} onClick={()=>{if(!profile){onLogin();return;}intent.current=crypto.randomUUID();setConfirm(true);}}>{own.request?<Check size={17}/>:<ShoppingBag size={17}/>} {own.request?"Замовлення надіслано":"Замовити книгу"}</button><button className={styles.secondary} disabled={busy||!!profile&&!ownLoaded} onClick={()=>void act("subscribe",{subscribed:!own.subscribed},own.subscribed?"Підписку скасовано.":"Книгу додано до підписок. Telegram-сповіщення можна ввімкнути у профілі.")}><Bell size={16}/>{own.subscribed?"У підписках":"Стежити за книгою"}</button></>:<a className={styles.button} href={typeof window!=="undefined"&&window.location.pathname.includes("/telegram")?"/teacher/telegram":profile?.teacherLinked?"/teacher?tab=orders&material="+book.materialId:"/teacher"}>Замовлення з фонду бібліотеки</a>}<button className={styles.secondary} onClick={()=>void share()}><Share2 size={16}/>Поділитися</button></div>
      {confirm&&<section className={styles.panel}><h3>Підтвердь замовлення</h3><p className={styles.muted}>Це заявка на одну книгу. Видачу конкретного примірника оформлює бібліотекар.</p><label className={styles.field}>Примітка, якщо потрібна<textarea maxLength={1000} value={note} onChange={event=>{setNote(event.target.value);intent.current=crypto.randomUUID();}}/></label><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>void act("request",{note,confirmation:"CONFIRM_BOOK_REQUEST"},"Замовлення отримано бібліотекою. Його стан — у «Моїх книгах».")}>Підтвердити замовлення</button><button className={styles.quiet} disabled={busy} onClick={()=>{setConfirm(false);intent.current=null;}}>Скасувати</button></div></section>}
      {value("description")&&<section className={styles.detailSection}><h3>Про книгу</h3><div className={styles.bodyText}>{value("description")}</div></section>}{value("annotation")&&<section className={styles.detailSection}><h3>Анотація</h3><div className={styles.bodyText}>{value("annotation")}</div></section>}
      <details className={styles.detailSection}><summary>Усі бібліографічні відомості</summary><dl className={styles.detailMeta}>{[["Співавтори","coauthors"],["Редактори","editors"],["Ілюстратори","illustrators"],["Видання","edition"],["Том","volume"],["Серія","series"],["Тип","type"],["Предмет","subject"],["ISBN-10","isbn10"],["ISBN-13","isbn13"],["ISSN","issn"],["ASIN","asin"],["LCCN","lccn"],["DDC","ddc"],["OCLC","oclc"],["UPC","upc"],["Шифр","callNumber"]].filter(([,key])=>value(key)).map(([label,key])=><span style={{display:"contents"}} key={key}><dt>{label}</dt><dd>{value(key)}</dd></span>)}</dl>{book.links.map(link=><p key={link.url}><a href={link.url} target="_blank" rel="noopener noreferrer">{link.label}</a></p>)}</details>
      {book.copies.length>0&&<details className={styles.detailSection}><summary>Примірники бібліотеки ({book.copies.length})</summary>{book.copies.map(copy=><p className={styles.muted} key={copy.id}>№ {copy.accession_no} · примірник {copy.copy_no} · {copy.physical_state==="on_shelf"?"У бібліотеці":copy.physical_state==="on_loan"?"На руках":"Потребує уточнення"}</p>)}</details>}
      {book.fund==="literature"&&<section className={styles.detailSection}><div className={styles.sectionHead}><h3>Твоє враження важливе</h3><button className={styles.quiet} onClick={()=>profile?onShare(String(book.id)):onLogin()}><MessageCircle size={16}/>Обговорити</button></div>{profile?<><div className={styles.ratingButtons} aria-label="Оцінка книги">{[1,2,3,4,5].map(star=><button key={star} className={rating>=star?styles.chosen:""} aria-label={`${star} зірок`} aria-pressed={rating===star} disabled={!ownLoaded||busy} onClick={()=>setRating(star)}>★</button>)}</div><label className={styles.field}>Відгук<textarea disabled={!ownLoaded||busy} value={body} onChange={event=>setBody(event.target.value)} maxLength={4000} placeholder="Що сподобалося? Кому ти порадиш цю книгу?"/></label><p className={styles.muted}>Текст з’явиться після перевірки бібліотекарем. Не пиши телефони, адреси та інші особисті дані.</p><button className={styles.secondary} disabled={busy||!ownLoaded||rating===0} onClick={()=>{intent.current=null;void act("rating",{rating,body,expectedVersion:own.rating?.version||0},body.trim()?"Відгук збережено та передано на перевірку.":"Оцінку збережено.");}}>Зберегти оцінку й відгук</button></>:<p className={styles.muted}><button className={styles.quiet} onClick={onLogin}>Увійди до кабінету</button>, щоб оцінити книгу або залишити відгук.</p>}{book.reviews.map((review,index)=><article className={styles.review} key={index}><strong>{review.display_name}</strong><span className={styles.stars}> · {"★".repeat(review.rating)}</span>{review.body&&<p>{review.body}</p>}</article>)}</section>}
    </>}
  </div></dialog>;
}
