"use client";
import {useEffect,useId,useLayoutEffect,useRef,useState,type ReactNode} from 'react';import {createPortal} from 'react-dom';import {BookOpen,X} from 'lucide-react';
import {useModalNavigation} from '../librarian/literature/literature-navigation';import {readerFetch} from './reader-types';import s from './cabinet.module.css';
export type Row=Record<string,any>;export type Page={items:Row[];total:number;page:number;pages:number};
type InfinitePageEntry={chunks:Map<number,Row[]>;total:number;pages:number;raw?:Row};
export type InfinitePageCache=Map<string,InfinitePageEntry>;
export function useCabinetData<T>(url:string|null,epoch=0){const [data,setData]=useState<T|null>(null),[loadedUrl,setLoadedUrl]=useState<string|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);useEffect(()=>{let alive=true;setLoading(!!url);setError('');if(!url)return;readerFetch<{result:T}>(url).then(d=>{if(alive){setData(d.result);setLoadedUrl(url);}}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[url,epoch]);return {data:loadedUrl===url?data:null,error,loading};}
export function useInfiniteCabinetData(baseUrl:string,wantedPage:number,epoch:number,cache:InfinitePageCache,nestedKey=''){
 const [,render]=useState(0),[retry,setRetry]=useState(0),key=nestedKey+'|'+baseUrl,entry=cache.get(key),target=Math.max(1,Math.floor(wantedPage||1));let requestPage=target;
 for(let page=1;page<=target;page++)if(!entry?.chunks.has(page)){requestPage=page;break;}
 const separator=baseUrl.includes('?')?'&':'?',remote=useCabinetData<Row>(baseUrl+separator+'page='+requestPage,epoch*1000+retry),pageData=(nestedKey?remote.data?.[nestedKey]:remote.data) as Page|null;
 useEffect(()=>{if(!pageData)return;const next=cache.get(key)||{chunks:new Map<number,Row[]>(),total:0,pages:0};next.chunks.set(pageData.page,pageData.items||[]);next.total=Number(pageData.total||0);next.pages=Number(pageData.pages||0);next.raw=remote.data||undefined;for(const page of [...next.chunks.keys()])if(page>next.pages)next.chunks.delete(page);cache.set(key,next);render(value=>value+1);},[cache,key,pageData,remote.data]);
 const current=cache.get(key),ordered:string[]=[],byId=new Map<string,Row>();if(current)for(let page=1;page<=target;page++)for(const row of current.chunks.get(page)||[]){const id=String(row.edition_id||row.id);if(!byId.has(id))ordered.push(id);byId.set(id,row);}
 let contiguous=0;if(current)for(let page=1;page<=Math.min(target,current.pages);page++){if(!current.chunks.has(page))break;contiguous=page;}
 return {data:current?{items:ordered.map(id=>byId.get(id)!),total:current.total,page:contiguous,pages:current.pages}:null,raw:current?.raw||remote.data,error:remote.error,loading:remote.loading,retry:()=>setRetry(value=>value+1)};
}
export function InfinitePager({data,loading,error,onNext,onRetry}:{data:Page|null;loading:boolean;error:string;onNext:(page:number)=>void;onRetry:()=>void}){const sentinel=useRef<HTMLButtonElement>(null),requested=useRef(0),hasMore=!!data&&data.page<data.pages;useEffect(()=>{if(!hasMore||loading||error||!sentinel.current||typeof IntersectionObserver==='undefined')return;const observer=new IntersectionObserver(entries=>{if(!entries.some(entry=>entry.isIntersecting)||document.querySelector('dialog[open]'))return;const next=(data?.page||0)+1;if(next>requested.current){requested.current=next;onNext(next);}}, {rootMargin:'280px 0px'});observer.observe(sentinel.current);return()=>observer.disconnect();},[data?.page,error,hasMore,loading,onNext]);useEffect(()=>{requested.current=data?.page||0;},[data?.page]);if(error)return <div className={s.infiniteFooter}><button type="button" className={s.secondary} onClick={onRetry}>Спробувати ще раз</button></div>;if(!hasMore)return null;return <div className={s.infiniteFooter} aria-live="polite"><button ref={sentinel} type="button" className={s.secondary} disabled={loading} onClick={()=>{const next=(data?.page||0)+1;if(next>requested.current){requested.current=next;onNext(next);}}}>{loading?'Завантажуємо далі…':'Показати далі'}</button></div>;}
export function Feedback({state}:{state:{error:string;loading:boolean}}){return state.error?<p className={s.error} role="alert">{state.error}</p>:state.loading?<p className={s.muted} role="status">Завантажуємо…</p>:null;}
export function Cover({book}:{book:Row}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[book.cover_url]);return <span className={s.cover}>{book.cover_url&&!failed?<img src={book.cover_url} alt={`Обкладинка «${book.title}»`} loading="lazy" onError={()=>setFailed(true)}/>:<BookOpen aria-label="Без обкладинки" size={34}/>}</span>;}
const readerEntityKinds=['genre','author','publisher','tag','series'];
export function BookEntityLinks({book,kinds,onEntity}:{book:Row;kinds:string[];onEntity:(entity:Row)=>void}){const entities=(Array.isArray(book.entities)?book.entities:[]).filter((entity:Row)=>readerEntityKinds.includes(entity.kind)&&kinds.includes(entity.kind));return <>{entities.map((entity:Row,index:number)=><span key={entity.id+':'+entity.kind}>{index>0&&', '}<button type="button" className={s.entityLink} onClick={()=>onEntity(entity)}>{entity.name}</button></span>)}</>;}
export function PublicationLine({book,onEntity}:{book:Row;onEntity:(entity:Row)=>void}){const publishers=(Array.isArray(book.entities)?book.entities:[]).filter((entity:Row)=>entity.kind==='publisher');return (publishers.length||book.publisher||book.year)?<p className={s.muted}>{publishers.length?<BookEntityLinks book={book} kinds={['publisher']} onEntity={onEntity}/>:book.publisher}{book.year&&<> · {book.year}</>}</p>:null;}
export function BookPublicMeta({book}:{book:Row}){return book.pages||book.websiteUrl?<p className={s.bookPublicMeta}>{book.pages&&<span>{book.pages} сторінок</span>}{book.websiteUrl&&<a href={book.websiteUrl} target="_blank" rel="noopener noreferrer">{book.websiteLabel||'Сайт книги'} ↗</a>}</p>:null;}
export function BookRow({book,onBook,onEntity,children}:{book:Row;onBook:(id:string)=>void;onEntity?:(entity:Row)=>void;children?:ReactNode}){const id=book.edition_id||book.id,authors=(Array.isArray(book.entities)?book.entities:[]).filter((entity:Row)=>entity.kind==='author');return <article className={s.bookRow} data-clickable="true" onClick={event=>{if(!(event.target as Element).closest('button,a,input,select,textarea,summary,details'))onBook(id);}}><button type="button" className={s.coverButton} onClick={()=>onBook(id)} aria-label={`Відкрити «${book.title}»`}><Cover book={book}/></button><div className={s.bookInfo}><button type="button" className={s.bookTitle} onClick={()=>onBook(id)}>{book.title}</button>{book.author&&(onEntity&&authors.length?<p className={s.muted}><BookEntityLinks book={book} kinds={['author']} onEntity={onEntity}/></p>:<p className={s.muted}>{book.author}</p>)}{onEntity?<PublicationLine book={book} onEntity={onEntity}/>:(book.publisher||book.year)?<p className={s.muted}>{[book.publisher,book.year].filter(Boolean).join(' · ')}</p>:null}<BookPublicMeta book={book}/>{children}</div></article>;}
export function Pager({data,onPage}:{data:Page|null;onPage:(n:number)=>void}){return data&&data.pages>1?<div className={s.pager}><button className={s.secondary} disabled={data.page<=1} onClick={()=>onPage(data.page-1)}>←</button><span>{data.page} / {data.pages}</span><button className={s.secondary} disabled={data.page>=data.pages} onClick={()=>onPage(data.page+1)}>→</button></div>:null;}
export function Modal({title,children,onClose,busy=false,dirty=false,routed=false,guardDraft=true}:{title:string;children:ReactNode;onClose:()=>void;busy?:boolean;dirty?:boolean;routed?:boolean;guardDraft?:boolean}){const ref=useRef<HTMLDialogElement>(null),id=useId(),back=useModalNavigation(onClose,busy,dirty,undefined,routed,guardDraft);useEffect(()=>{const d=ref.current,prior=document.activeElement as HTMLElement|null;d?.showModal();const vp=window.visualViewport,update=()=>{d?.style.setProperty('--available-height',(vp?.height||innerHeight)+'px');d?.style.setProperty('--viewport-top',(vp?.offsetTop||0)+'px');};update();vp?.addEventListener('resize',update);vp?.addEventListener('scroll',update);return()=>{vp?.removeEventListener('resize',update);vp?.removeEventListener('scroll',update);d?.close();prior?.isConnected&&prior.focus({preventScroll:true});};},[]);return <dialog ref={ref} className={s.modal} onCancel={e=>{e.preventDefault();e.stopPropagation();if(!busy)back();}} aria-labelledby={id}><header><button className={s.textButton} disabled={busy} onClick={back}>← Назад</button><h2 id={id}>{title}</h2><button className={s.textButton} disabled={busy} aria-label="Закрити" onClick={back}><X size={20}/></button></header><div className={s.modalBody} data-scroll-key={'reader:'+title}>{children}</div></dialog>;}
export function Suggest({label,kind,value,onText,onSelect}:{label:string;kind:string;value:string;onText:(s:string)=>void;onSelect:(row:Row)=>void}){const input=useRef<HTMLInputElement>(null),host=useRef<HTMLDivElement>(null),list=useRef<HTMLDivElement>(null),side=useRef<'up'|'down'>('down'),raf=useRef(0),requestingMore=useRef(false),id=useId(),[open,setOpen]=useState(false),[items,setItems]=useState<Row[]>([]),[page,setPage]=useState(1),[more,setMore]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[target,setTarget]=useState<Element|null>(null),[bounds,setBounds]=useState({left:0,top:0,width:200,maxHeight:200}),[active,setActive]=useState(0);const query=value.trim();
 useEffect(()=>{requestingMore.current=false;setPage(1);setItems([]);setMore(false);setError('');setActive(0);},[kind,value]);
 useEffect(()=>{if(!open||!query){setItems([]);setMore(false);requestingMore.current=false;return;}let alive=true;setLoading(true);const t=setTimeout(()=>{const params=new URLSearchParams({view:kind==='book'?'catalog':'facets',kind,q:query,page:String(page)});readerFetch<{result:Row}>('/api/reader/cabinet?'+params).then(d=>{if(alive){setItems(prev=>page===1?d.result.items:[...prev,...d.result.items.filter((x:Row)=>!prev.some(y=>y.id===x.id))]);setMore(kind==='book'?page<d.result.pages:d.result.more);setError('');}}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive){requestingMore.current=false;setLoading(false);}});},200);return()=>{alive=false;clearTimeout(t);};},[kind,query,page,open]);
 useLayoutEffect(()=>{if(!open||!query)return;const portalTarget=input.current?.closest('dialog')||document.body;setTarget(portalTarget);const measure=()=>{const r=input.current?.getBoundingClientRect(),vp=window.visualViewport;if(!r)return;const vpTop=vp?.offsetTop||0,vpLeft=vp?.offsetLeft||0,vpBottom=vpTop+(vp?.height||innerHeight),vpRight=vpLeft+(vp?.width||innerWidth),dialogRect=portalTarget instanceof HTMLDialogElement?portalTarget.getBoundingClientRect():null,visibleTop=Math.max(vpTop,dialogRect?.top??vpTop)+6,visibleBottom=Math.min(vpBottom,dialogRect?.bottom??vpBottom)-6,visibleLeft=Math.max(vpLeft,dialogRect?.left??vpLeft)+6,visibleRight=Math.min(vpRight,dialogRect?.right??vpRight)-6;if(r.bottom<visibleTop||r.top>visibleBottom||visibleRight-visibleLeft<80){setOpen(false);return;}const below=Math.max(0,visibleBottom-r.bottom-4),above=Math.max(0,r.top-visibleTop-4);if(side.current==='down'&&below<112&&above>below+44)side.current='up';else if(side.current==='up'&&above<112&&below>above+44)side.current='down';const available=side.current==='up'?above:below;if(available<44){side.current=above>=below?'up':'down';}const height=Math.min(240,Math.max(0,side.current==='up'?above:below)),width=Math.max(80,Math.min(r.width,visibleRight-visibleLeft)),left=Math.max(visibleLeft,Math.min(r.left,visibleRight-width)),top=side.current==='up'?Math.max(visibleTop,r.top-height-4):Math.min(r.bottom+4,visibleBottom-height);const next={left,top,width,maxHeight:height};setBounds(previous=>Object.keys(next).every(key=>Math.abs(previous[key as keyof typeof previous]-next[key as keyof typeof next])<1)?previous:next);};const schedule=(event?:Event)=>{if(event?.target instanceof Node&&list.current?.contains(event.target))return;cancelAnimationFrame(raf.current);raf.current=requestAnimationFrame(measure);};schedule();window.addEventListener('scroll',schedule,true);window.addEventListener('resize',schedule);window.visualViewport?.addEventListener('resize',schedule);window.visualViewport?.addEventListener('scroll',schedule);const outside=(e:PointerEvent)=>{if(!host.current?.contains(e.target as Node)&&!(e.target as Element).closest?.('[data-reader-options="'+id+'"]'))setOpen(false);};document.addEventListener('pointerdown',outside);return()=>{cancelAnimationFrame(raf.current);window.removeEventListener('scroll',schedule,true);window.removeEventListener('resize',schedule);window.visualViewport?.removeEventListener('resize',schedule);window.visualViewport?.removeEventListener('scroll',schedule);document.removeEventListener('pointerdown',outside);};},[open,query,id]);
 useEffect(()=>{const box=list.current,option=document.getElementById(id+'-option-'+active);if(!open||!box||!option)return;const outer=box.getBoundingClientRect(),row=option.getBoundingClientRect();if(row.top<outer.top)box.scrollTop-=outer.top-row.top;else if(row.bottom>outer.bottom)box.scrollTop+=row.bottom-outer.bottom;},[active,id,open]);
 const choose=(row:Row)=>{onSelect(row);setOpen(false);},loadMore=()=>{if(!more||loading||requestingMore.current)return;requestingMore.current=true;setMore(false);setPage(value=>value+1);};return <div className={s.field} ref={host}><label htmlFor={id}>{label}</label><div className={s.inputWrap}><input id={id} ref={input} role="combobox" aria-autocomplete="list" aria-expanded={open&&!!query} aria-controls={id+'-list'} aria-activedescendant={open&&items[active]?id+'-option-'+active:undefined} autoComplete="off" placeholder={kind==='book'?'Назва, автор або категорія':undefined} title={kind==='book'?'Назва, автор, категорія':undefined} value={value} onFocus={()=>{if(query)setOpen(true);}} onChange={e=>{onText(e.target.value);setOpen(!!e.target.value.trim());}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();setOpen(false);e.stopPropagation();}if(e.key==='ArrowDown'){e.preventDefault();setActive(i=>Math.min(items.length-1,i+1));}if(e.key==='ArrowUp'){e.preventDefault();setActive(i=>Math.max(0,i-1));}if(e.key==='Enter'&&open&&items[active]){e.preventDefault();choose(items[active]);}}}/>{value&&<button type="button" aria-label={'Очистити: '+label} onClick={()=>{onText('');setOpen(false);input.current?.focus();}}><X size={17}/></button>}</div>{open&&query&&target&&createPortal(<div ref={list} data-reader-options={id} className={s.suggestions} style={bounds} onScroll={event=>{const node=event.currentTarget;if(node.scrollTop+node.clientHeight>=node.scrollHeight-48)loadMore();}}><div role="listbox" id={id+'-list'} aria-label={label}>{items.map((row,i)=><button type="button" className={kind==='book'?s.bookSuggestion:undefined} role="option" id={id+'-option-'+i} aria-selected={active===i} key={row.id} onPointerDown={e=>e.preventDefault()} onClick={()=>choose(row)}>{kind==='book'?<><Cover book={row}/><span className={s.bookSuggestionText}><strong>{row.title}</strong><small>{row.author||'Автор не вказаний'}</small></span></>:<>{row.name}{row.count!==undefined&&<span> · {row.count}</span>}</>}</button>)}</div>{loading?<p role="status">Шукаємо…</p>:error?<p role="alert">{error}</p>:!items.length?<p>Нічого не знайдено.</p>:more&&<button type="button" onPointerDown={e=>e.preventDefault()} onClick={loadMore}>Показати ще</button>}</div>,target)}</div>;}
