"use client";
import {useEffect,useId,useLayoutEffect,useRef,useState,type ReactNode} from 'react';import {createPortal} from 'react-dom';import {BookOpen,X} from 'lucide-react';
import {useModalNavigation} from '../librarian/literature/literature-navigation';import {readerFetch} from './reader-types';import s from './cabinet.module.css';
export type Row=Record<string,any>;export type Page={items:Row[];total:number;page:number;pages:number};
export function useCabinetData<T>(url:string|null,epoch=0){const [data,setData]=useState<T|null>(null),[loadedUrl,setLoadedUrl]=useState<string|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);useEffect(()=>{let alive=true;setLoading(!!url);setError('');if(!url)return;readerFetch<{result:T}>(url).then(d=>{if(alive){setData(d.result);setLoadedUrl(url);}}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[url,epoch]);return {data:loadedUrl===url?data:null,error,loading};}
export function Feedback({state}:{state:{error:string;loading:boolean}}){return state.error?<p className={s.error} role="alert">{state.error}</p>:state.loading?<p className={s.muted} role="status">Завантажуємо…</p>:null;}
export function Cover({book}:{book:Row}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[book.cover_url]);return <span className={s.cover}>{book.cover_url&&!failed?<img src={book.cover_url} alt={`Обкладинка «${book.title}»`} loading="lazy" onError={()=>setFailed(true)}/>:<BookOpen aria-label="Без обкладинки" size={34}/>}</span>;}
const readerEntityKinds=['genre','author','publisher','tag','series'];
export function BookEntityLinks({book,kinds,onEntity}:{book:Row;kinds:string[];onEntity:(entity:Row)=>void}){const entities=(Array.isArray(book.entities)?book.entities:[]).filter((entity:Row)=>readerEntityKinds.includes(entity.kind)&&kinds.includes(entity.kind));return <>{entities.map((entity:Row,index:number)=><span key={entity.id+':'+entity.kind}>{index>0&&', '}<button type="button" className={s.entityLink} onClick={()=>onEntity(entity)}>{entity.name}</button></span>)}</>;}
export function PublicationLine({book,onEntity}:{book:Row;onEntity:(entity:Row)=>void}){const publishers=(Array.isArray(book.entities)?book.entities:[]).filter((entity:Row)=>entity.kind==='publisher');return (publishers.length||book.publisher||book.year)?<p className={s.muted}>{publishers.length?<BookEntityLinks book={book} kinds={['publisher']} onEntity={onEntity}/>:book.publisher}{book.year&&<> · {book.year}</>}</p>:null;}
export function BookPublicMeta({book}:{book:Row}){return book.pages||book.websiteUrl?<p className={s.bookPublicMeta}>{book.pages&&<span>{book.pages} стор.</span>}{book.websiteUrl&&<a href={book.websiteUrl} target="_blank" rel="noopener noreferrer">{book.websiteLabel||'Сайт книги'} ↗</a>}</p>:null;}
export function BookRow({book,onBook,onEntity,children}:{book:Row;onBook:(id:string)=>void;onEntity?:(entity:Row)=>void;children?:ReactNode}){const id=book.edition_id||book.id,authors=(Array.isArray(book.entities)?book.entities:[]).filter((entity:Row)=>entity.kind==='author');return <article className={s.bookRow} data-clickable="true" onClick={event=>{if(!(event.target as Element).closest('button,a,input,select,textarea,summary,details'))onBook(id);}}><button type="button" className={s.coverButton} onClick={()=>onBook(id)} aria-label={`Відкрити «${book.title}»`}><Cover book={book}/></button><div className={s.bookInfo}><button type="button" className={s.bookTitle} onClick={()=>onBook(id)}>{book.title}</button>{book.author&&(onEntity&&authors.length?<p className={s.muted}><BookEntityLinks book={book} kinds={['author']} onEntity={onEntity}/></p>:<p className={s.muted}>{book.author}</p>)}{children}</div></article>;}
export function Pager({data,onPage}:{data:Page|null;onPage:(n:number)=>void}){return data&&data.pages>1?<div className={s.pager}><button className={s.secondary} disabled={data.page<=1} onClick={()=>onPage(data.page-1)}>←</button><span>{data.page} / {data.pages}</span><button className={s.secondary} disabled={data.page>=data.pages} onClick={()=>onPage(data.page+1)}>→</button></div>:null;}
export function Modal({title,children,onClose,busy=false,dirty=false,routed=false}:{title:string;children:ReactNode;onClose:()=>void;busy?:boolean;dirty?:boolean;routed?:boolean}){const ref=useRef<HTMLDialogElement>(null),id=useId(),back=useModalNavigation(onClose,busy,dirty,undefined,routed);useEffect(()=>{const d=ref.current,prior=document.activeElement as HTMLElement|null;d?.showModal();const vp=window.visualViewport,update=()=>{d?.style.setProperty('--available-height',(vp?.height||innerHeight)+'px');d?.style.setProperty('--viewport-top',(vp?.offsetTop||0)+'px');};update();vp?.addEventListener('resize',update);vp?.addEventListener('scroll',update);return()=>{vp?.removeEventListener('resize',update);vp?.removeEventListener('scroll',update);d?.close();prior?.isConnected&&prior.focus({preventScroll:true});};},[]);return <dialog ref={ref} className={s.modal} onCancel={e=>{e.preventDefault();e.stopPropagation();if(!busy)back();}} aria-labelledby={id}><header><button className={s.textButton} disabled={busy} onClick={back}>← Назад</button><h2 id={id}>{title}</h2><button className={s.textButton} disabled={busy} aria-label="Закрити" onClick={back}><X size={20}/></button></header><div className={s.modalBody} data-scroll-key={'reader:'+title}>{children}</div></dialog>;}
export function Suggest({label,kind,value,onText,onSelect}:{label:string;kind:string;value:string;onText:(s:string)=>void;onSelect:(row:Row)=>void}){const input=useRef<HTMLInputElement>(null),host=useRef<HTMLDivElement>(null),id=useId(),[open,setOpen]=useState(false),[items,setItems]=useState<Row[]>([]),[page,setPage]=useState(1),[more,setMore]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[target,setTarget]=useState<Element|null>(null),[bounds,setBounds]=useState({left:0,top:0,width:200,maxHeight:200}),[active,setActive]=useState(0);const query=value.trim();
 useEffect(()=>{setPage(1);setItems([]);setActive(0);},[value]);
 useEffect(()=>{if(!open||!query){setItems([]);setMore(false);return;}let alive=true;setLoading(true);const t=setTimeout(()=>{const params=new URLSearchParams({view:kind==='book'?'catalog':'facets',kind,q:query,page:String(page)});readerFetch<{result:Row}>('/api/reader/cabinet?'+params).then(d=>{if(alive){setItems(prev=>page===1?d.result.items:[...prev,...d.result.items.filter((x:Row)=>!prev.some(y=>y.id===x.id))]);setMore(kind==='book'?page<d.result.pages:d.result.more);setError('');}}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});},200);return()=>{alive=false;clearTimeout(t);};},[kind,query,page,open]);
 useLayoutEffect(()=>{if(!open||!query)return;setTarget(input.current?.closest('dialog')||document.body);const update=()=>{const r=input.current?.getBoundingClientRect(),vp=window.visualViewport;if(!r)return;const top=vp?.offsetTop||0,height=vp?.height||innerHeight,width=vp?.width||innerWidth,left=vp?.offsetLeft||0,below=top+height-r.bottom-8,above=r.top-top-8,up=below<150&&above>below;setBounds({left:Math.max(left+6,Math.min(r.left,left+width-Math.min(r.width,width-12)-6)),top:up?Math.max(top+6,r.top-Math.min(240,above)-4):r.bottom+4,width:Math.min(r.width,width-12),maxHeight:Math.max(44,Math.min(240,up?above:below))});};update();window.addEventListener('scroll',update,true);window.addEventListener('resize',update);window.visualViewport?.addEventListener('resize',update);const outside=(e:PointerEvent)=>{if(!host.current?.contains(e.target as Node)&&!(e.target as Element).closest?.('[data-reader-options="'+id+'"]'))setOpen(false);};document.addEventListener('pointerdown',outside);return()=>{window.removeEventListener('scroll',update,true);window.removeEventListener('resize',update);window.visualViewport?.removeEventListener('resize',update);document.removeEventListener('pointerdown',outside);};},[open,query,id]);
 useEffect(()=>{if(open)document.getElementById(id+'-option-'+active)?.scrollIntoView({block:'nearest'});},[active]);
 const choose=(row:Row)=>{onSelect(row);setOpen(false);};return <div className={s.field} ref={host}><label htmlFor={id}>{label}</label><div className={s.inputWrap}><input id={id} ref={input} role="combobox" aria-autocomplete="list" aria-expanded={open&&!!query} aria-controls={id+'-list'} aria-activedescendant={open&&items[active]?id+'-option-'+active:undefined} autoComplete="off" value={value} onFocus={()=>{if(query)setOpen(true);}} onChange={e=>{onText(e.target.value);setOpen(!!e.target.value.trim());}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();setOpen(false);e.stopPropagation();}if(e.key==='ArrowDown'){e.preventDefault();setActive(i=>Math.min(items.length-1,i+1));}if(e.key==='ArrowUp'){e.preventDefault();setActive(i=>Math.max(0,i-1));}if(e.key==='Enter'&&open&&items[active]){e.preventDefault();choose(items[active]);}}}/>{value&&<button type="button" aria-label={'Очистити: '+label} onClick={()=>{onText('');setOpen(false);input.current?.focus();}}><X size={17}/></button>}</div>{open&&query&&target&&createPortal(<div data-reader-options={id} className={s.suggestions} style={bounds}><div role="listbox" id={id+'-list'} aria-label={label}>{items.map((row,i)=><button type="button" className={kind==='book'?s.bookSuggestion:undefined} role="option" id={id+'-option-'+i} aria-selected={active===i} key={row.id} onPointerDown={e=>e.preventDefault()} onClick={()=>choose(row)}>{kind==='book'?<><Cover book={row}/><span className={s.bookSuggestionText}><strong>{row.title}</strong><small>{row.author||'Автор не вказаний'}</small></span></>:<>{row.name}{row.count!==undefined&&<span> · {row.count}</span>}</>}</button>)}</div>{loading?<p role="status">Шукаємо…</p>:error?<p role="alert">{error}</p>:!items.length?<p>Нічого не знайдено.</p>:more&&<button type="button" onPointerDown={e=>e.preventDefault()} onClick={()=>setPage(n=>n+1)}>Показати ще</button>}</div>,target)}</div>;}
