"use client";
import {useEffect,useState} from "react";
import {ArrowLeft,ArrowRight,BookOpen,Search,SlidersHorizontal} from "lucide-react";
import {readerFetch,type CatalogCard,type CatalogFacet} from "./reader-types";
import ReaderScanner from "./reader-scanner";
import styles from "./reader.module.css";

export default function ReaderCatalog({onBook,initialEntity}:{onBook:(id:string)=>void;initialEntity?:{id:string;kind:string}|null}){
  const [fund,setFund]=useState("literature"),[query,setQuery]=useState(""),[search,setSearch]=useState(""),[sort,setSort]=useState("title"),[page,setPage]=useState(1);
  const [genre,setGenre]=useState(""),[author,setAuthor]=useState(""),[publisher,setPublisher]=useState(""),[grade,setGrade]=useState(""),[filters,setFilters]=useState(false);
  const [facets,setFacets]=useState<CatalogFacet[]>([]),[items,setItems]=useState<CatalogCard[]>([]),[total,setTotal]=useState(0),[pages,setPages]=useState(0),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
  const [scanCode,setScanCode]=useState(""),[scanResults,setScanResults]=useState<{copy_id:string;edition_id:string;title:string;accession_no:string;copy_no:string}[]|null>(null);
  useEffect(()=>{const timer=setTimeout(()=>{setSearch(query);setPage(1);},300);return()=>clearTimeout(timer);},[query]);
  useEffect(()=>{readerFetch<{result:CatalogFacet[]}>("/api/library/catalog?facets=1").then(data=>setFacets(data.result)).catch(()=>{});},[]);
  useEffect(()=>{if(initialEntity){setFund("literature");setGenre(initialEntity.kind==="genre"?initialEntity.id:"");setAuthor(initialEntity.kind==="author"?initialEntity.id:"");setPublisher(initialEntity.kind==="publisher"?initialEntity.id:"");setFilters(true);setPage(1);}},[initialEntity]);
  useEffect(()=>{let active=true;setLoading(true);setMessage("");const params=new URLSearchParams({fund,q:search,sort,page:String(page),genre,author,publisher,grade});readerFetch<{result:{items:CatalogCard[];total:number;pages:number}}>("/api/library/catalog?"+params).then(data=>{if(active){setItems(data.result.items);setTotal(data.result.total);setPages(data.result.pages);}}).catch(error=>{if(active)setMessage(error.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[fund,search,sort,page,genre,author,publisher,grade]);
  function switchFund(value:string){setFund(value);setPage(1);setScanResults(null);}
  async function scan(code:string){setScanCode(code);setMessage("");try{const data=await readerFetch<{result:{matches:NonNullable<typeof scanResults>}}>("/api/library/catalog?scan="+encodeURIComponent(code));setScanResults(data.result.matches);if(data.result.matches.length===1)onBook(data.result.matches[0].edition_id);}catch(error){setMessage(error instanceof Error?error.message:"Код не знайдено.");}}
  return <section aria-label="Каталог бібліотеки"><div className={styles.sectionHead}><h2>Обирай своє наступне читання</h2><span className={styles.muted}>{loading?"Завантажуємо…":`${total} видань`}</span></div>
    <div className={styles.funds} aria-label="Розділи фонду"><button className={fund==="literature"?styles.selected:""} onClick={()=>switchFund("literature")}>Художня та наукова література</button><button className={fund==="education"?styles.selected:""} onClick={()=>switchFund("education")}>Підручники й посібники</button></div>
    <div className={styles.toolbar}><label className={styles.search}><Search size={18}/><input aria-label="Знайти книгу" placeholder="Назва, автор або ISBN…" value={query} onChange={event=>setQuery(event.target.value)}/></label><button className={styles.secondary} onClick={()=>setFilters(!filters)} aria-expanded={filters}><SlidersHorizontal size={16}/>Фільтри</button><select aria-label="Порядок книг" value={sort} onChange={event=>{setSort(event.target.value);setPage(1);}}><option value="title">За назвою</option><option value="newest">Нещодавно додані</option><option value="rating">За оцінкою</option></select></div>
    {filters&&<div className={styles.filterRow}>{fund==="literature"?[["genre","Усі жанри",genre,setGenre],["author","Усі автори",author,setAuthor],["publisher","Усі видавництва",publisher,setPublisher]].map(([kind,label,value,setter])=><select key={String(kind)} aria-label={String(label)} value={String(value)} onChange={event=>{(setter as (value:string)=>void)(event.target.value);setPage(1);}}><option value="">{String(label)}</option>{facets.filter(item=>item.kind===kind).map(item=><option key={item.id} value={item.id}>{item.name} ({item.count})</option>)}</select>):<select aria-label="Клас посібника" value={grade} onChange={event=>{setGrade(event.target.value);setPage(1);}}><option value="">Усі класи</option>{Array.from({length:11},(_,index)=><option key={index+1} value={index+1}>{index+1} клас</option>)}</select>}</div>}
    <details className={styles.notice}><summary>Є книга перед тобою? Знайди її за кодом</summary><div className={styles.actions}><ReaderScanner onDetected={code=>void scan(code)}/><input className={styles.input} aria-label="Бібліотечний номер або ISBN" value={scanCode} onChange={event=>setScanCode(event.target.value)} placeholder="Номер примірника або ISBN"/><button className={styles.secondary} onClick={()=>void scan(scanCode)} disabled={!scanCode.trim()}>Знайти</button></div>{scanResults&&<div>{scanResults.length===0?<p>Цього коду немає в опублікованому каталозі. Перевір номер або звернися до бібліотекаря.</p>:scanResults.map(result=><button className={styles.quiet} key={result.copy_id} onClick={()=>onBook(result.edition_id)}>{result.title} · № {result.accession_no} · прим. {result.copy_no}</button>)}</div>}</details>
    {message&&<p className={styles.error} role="status">{message}</p>}{!loading&&!message&&items.length===0&&<div className={styles.empty}><BookOpen size={35}/><h3>Спробуй інший пошук</h3><p>Зміни назву або очисть фільтри. Якщо цього розділу ще немає — бібліотекар готує його до відкриття.</p><button className={styles.secondary} onClick={()=>{setQuery("");setGenre("");setAuthor("");setPublisher("");setGrade("");}}>Очистити фільтри</button></div>}
    <div className={styles.grid} aria-busy={loading}>{items.map(book=><button className={styles.card} key={book.edition_id||book.material_id} onClick={()=>onBook(book.edition_id||book.material_id)}><div className={styles.coverWrap}>{book.cover_url?<img src={book.cover_url} alt="" loading="lazy" onError={event=>{event.currentTarget.style.visibility="hidden";}}/>:<BookOpen className={styles.coverFallback} size={64}/>}</div><h3>{book.title}</h3><p>{book.author||book.publisher||"Бібліотечне видання"}</p><div className={styles.bookMeta}><span className={book.available>0?styles.available:styles.unavailable}>{book.available>0?`Є в бібліотеці · ${book.available}`:"Уточнити наявність"}</span>{book.rating!==null&&<span className={styles.stars}>★ {Number(book.rating).toFixed(1)}</span>}</div></button>)}</div>
    {pages>1&&<div className={styles.pagination}><button className={styles.secondary} disabled={page===1||loading} onClick={()=>setPage(page-1)} aria-label="Попередня сторінка"><ArrowLeft size={16}/></button><span>{page} / {pages}</span><button className={styles.secondary} disabled={page===pages||loading} onClick={()=>setPage(page+1)} aria-label="Наступна сторінка"><ArrowRight size={16}/></button></div>}
  </section>;
}
