"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {BookOpen,MessageCircle,Send,Users,X,ShieldAlert} from "lucide-react";
import {readerFetch,type ReaderProfile} from "./reader-types";
import s from "./reader.module.css";
type Thread={id:string;kind:string;title:string;edition_id:string|null;owner_reader_id:string;membership_status:string;role:string;partner_name:string|null};
type Message={id:string;reader_id:string;body:string;edition_id:string|null;book_title:string|null;display_name:string;created_at:string};
type DirectoryReader={id:string;display_name:string};
export default function CommunityPanel({profile,sharedBook,onShared,onBook,onProfile}:{profile:ReaderProfile;sharedBook:string|null;onShared:()=>void;onBook:(id:string)=>void;onProfile:()=>void}){
  const [threads,setThreads]=useState<Thread[]>([]),[selected,setSelected]=useState<string|null>(null),[messageState,setMessageState]=useState<{thread:string|null;rows:Message[]}>({thread:null,rows:[]}),[text,setText]=useState(""),[group,setGroup]=useState(""),[query,setQuery]=useState(""),[people,setPeople]=useState<DirectoryReader[]>([]),[mode,setMode]=useState<"direct"|"invite"|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[report,setReport]=useState<Message|null>(null),[reason,setReason]=useState(""),[blocks,setBlocks]=useState<DirectoryReader[]>([]);
  const intent=useRef<{key:string;id:string}|null>(null),messageEnd=useRef<HTMLDivElement>(null),selectedRef=useRef(selected),generation=useRef(0),draftRef=useRef({text,sharedBook});
  draftRef.current={text,sharedBook};
  selectedRef.current=selected;
  const messages=messageState.thread===selected?messageState.rows:[];
  const current=threads.find(t=>t.id===selected);
  const refresh=useCallback(async()=>{if(!profile.communityEnabled)return;const result=await readerFetch<{result:Thread[]}>("/api/reader/community",undefined,"GET",profile.id);setThreads(result.result);},[profile.communityEnabled,profile.id]);
  const refreshMessages=useCallback(async()=>{if(!selected||current?.membership_status!=="accepted")return;const run=++generation.current;const result=await readerFetch<{result:Message[]}>("/api/reader/community?thread="+encodeURIComponent(selected),undefined,"GET",profile.id);if(selectedRef.current===selected&&run===generation.current)setMessageState({thread:selected,rows:result.result});},[selected,current?.membership_status,profile.id]);
  useEffect(()=>{void refresh().catch(e=>setError(e.message));},[refresh]);
  useEffect(()=>{generation.current++;setMessageState({thread:selected,rows:[]});setText("");setReport(null);void refreshMessages().catch(e=>setError(e.message));return()=>{generation.current++;};},[refreshMessages]);
  useEffect(()=>{if(!profile.communityEnabled)return;const timer=setInterval(()=>{if(!document.hidden){void refresh().catch(()=>{});void refreshMessages().catch(()=>{});}},12000);return()=>clearInterval(timer);},[profile.communityEnabled,refresh,refreshMessages]);
  useEffect(()=>{messageEnd.current?.scrollIntoView({block:"nearest"});},[messages.length]);
  useEffect(()=>{if(!mode||query.trim().length<2){setPeople([]);return;}let live=true;const timer=setTimeout(()=>{readerFetch<{result:DirectoryReader[]}>("/api/reader/community?q="+encodeURIComponent(query),undefined,"GET",profile.id).then(data=>{if(live)setPeople(data.result);}).catch(e=>{if(live)setError(e.message);});},300);return()=>{live=false;clearTimeout(timer);};},[query,mode]);
  async function act(action:string,input:Record<string,unknown>){if(busy)return null;setBusy(true);setError("");setNotice("");const key=JSON.stringify({action,input});if(intent.current?.key!==key)intent.current={key,id:crypto.randomUUID()};try{const response=await readerFetch<{result:{id?:string}}>("/api/reader/community",{action,input:{...input,requestId:intent.current.id}},"POST",profile.id);intent.current=null;await refresh().catch(()=>setNotice("Дію збережено. Оновіть список розмов, коли відновиться зв’язок."));return response.result;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
  async function person(reader:DirectoryReader){if(mode==="invite"&&selected){if(await act("invite",{threadId:selected,recipientId:reader.id})){setMode(null);setNotice("Запрошення надіслано всередині читацької спільноти.");}}else{const result=await act("create",{kind:"direct",title:"",recipientId:reader.id});if(result?.id){setSelected(result.id);setMode(null);}}}
  async function send(){if(!selected)return;const result=await act("message",{threadId:selected,body:text,editionId:sharedBook});if(result&&selectedRef.current===selected){if(draftRef.current.text===text)setText("");if(draftRef.current.sharedBook===sharedBook)onShared();await refreshMessages().catch(()=>setNotice("Повідомлення надіслано. Оновіть розмову, коли відновиться зв’язок."));}}
  async function openDiscussion(){if(!sharedBook)return;const result=await act("create",{kind:"book",title:"",editionId:sharedBook});if(result?.id){setSelected(result.id);onShared();}}
  async function loadBlocks(){try{setBlocks((await readerFetch<{result:DirectoryReader[]}>("/api/reader/community?blocks=1",undefined,"GET",profile.id)).result);}catch(e){setError((e as Error).message);}}
  if(!profile.communityEnabled)return <section><div className={s.sectionHead}><h1>Читацька спільнота</h1><Users/></div><div className={s.empty}><MessageCircle size={38}/><h2>Книги цікавіше обговорювати разом</h2><p>Обговорення книг, читацькі групи й особисті розмови доступні за твоєю згодою. Обери ім’я для спільноти й увімкни спілкування у профілі.</p><button className={s.button} onClick={onProfile}>Налаштувати профіль</button></div></section>;
  return <section><div className={s.sectionHead}><div><span className={s.eyebrow}>Читаємо разом</span><h1>Читацька спільнота</h1></div><Users size={25}/></div><p className={s.muted}>Спілкуйся доброзичливо. Не публікуй телефони, адреси й чужі особисті дані. Бібліотекар розглядає скарги на конкретні повідомлення; особисті чати не є наскрізно зашифрованими.</p>
    {error&&<p className={s.error} role="alert">{error}</p>}{notice&&<p className={s.notice} role="status">{notice}</p>}{sharedBook&&<div className={s.notice}><BookOpen size={16}/> Книгу обрано: <button className={s.quiet} onClick={()=>onBook(sharedBook)}>Переглянути</button><div className={s.actions}><button className={s.button} disabled={busy} onClick={()=>void openDiscussion()}>Долучитися до обговорення книги</button><span className={s.muted}>Або обери розмову нижче й надішли картку книги.</span><button className={s.quiet} onClick={onShared}>Прибрати</button></div></div>}
    <div className={s.actions}><button className={s.secondary} onClick={()=>{setMode("direct");setQuery("");}}>Нова особиста розмова</button><button className={s.quiet} onClick={()=>void refresh()}>Оновити</button></div>
    <details className={s.notice}><summary>Створити читацьку групу</summary><div className={s.actions}><input className={s.input} aria-label="Назва читацької групи" value={group} onChange={e=>setGroup(e.target.value)} maxLength={120} placeholder="Наприклад, Клуб пригод"/><button className={s.button} disabled={busy||group.trim().length<3} onClick={async()=>{const result=await act("create",{kind:"group",title:group});if(result?.id){setSelected(result.id);setGroup("");setMode("invite");}}}>Створити групу</button></div></details>
    <div className={s.communitySplit}><div className={s.threadList} aria-label="Мої розмови">{threads.length===0&&<p className={s.muted}>Твої розмови й запрошення з’являться тут.</p>}{threads.map(thread=><button key={thread.id} className={thread.id===selected?s.active:""} aria-pressed={thread.id===selected} onClick={()=>{setSelected(thread.id);setError("");}}><strong>{thread.kind==="direct"?thread.partner_name||"Особиста розмова":thread.title}</strong><small className={s.muted} style={{display:"block"}}>{thread.membership_status==="invited"?"Нове запрошення":thread.kind==="book"?"Обговорення книги":thread.kind==="group"?"Читацька група":"Особиста розмова"}</small></button>)}</div>
    <div className={s.panel}>{!current?<p className={s.empty}>Обери розмову або створи нову.</p>:<><div className={s.sectionHead}><h2 style={{fontSize:23}}>{current.kind==="direct"?current.partner_name||"Особиста розмова":current.title}</h2>{current.kind==="group"&&current.role==="owner"&&<button className={s.quiet} onClick={()=>{setMode("invite");setQuery("");}}>Запросити</button>}</div>{current.membership_status==="invited"?<div className={s.notice}><p>Тебе запрошують до розмови. Повідомлення доступні тільки після прийняття.</p><div className={s.actions}><button className={s.button} disabled={busy} onClick={()=>void act("respond",{threadId:current.id,accept:true})}>Прийняти</button><button className={s.quiet} disabled={busy} onClick={()=>void act("respond",{threadId:current.id,accept:false})}>Відхилити</button></div></div>:<><div className={s.messages} aria-live="polite">{messages.length===0&&<p className={s.muted}>Повідомлень поки немає.{current.kind==="direct"?" Для особистого чату дочекайся прийняття запрошення.":" Почни розмову про книги."}</p>}{messages.map(message=><article key={message.id} className={`${s.message} ${message.reader_id===profile.id?s.own:""}`}><strong>{message.display_name}</strong>{message.body&&<p>{message.body}</p>}{message.edition_id&&message.book_title&&<button className={s.sharedBook} onClick={()=>onBook(message.edition_id!)}><BookOpen size={15}/> {message.book_title}</button>}<small>{new Date(message.created_at).toLocaleString("uk-UA",{dateStyle:"short",timeStyle:"short"})}</small>{message.reader_id!==profile.id&&<details><summary>Дії</summary><button className={s.quiet} style={{color:"inherit"}} onClick={()=>{setReport(message);setReason("");}}>Поскаржитися</button><button className={s.quiet} onClick={async()=>{if(window.confirm("Заблокувати цього учасника? Його повідомлення буде приховано для тебе.")){if(await act("block",{readerId:message.reader_id,blocked:true}))await refreshMessages();}}}>Заблокувати</button></details>}</article>)}<div ref={messageEnd}/></div>
    {sharedBook&&<p className={s.notice}>До наступного повідомлення буде додано обрану книгу.</p>}<form className={s.composer} onSubmit={e=>{e.preventDefault();void send();}}><textarea className={s.input} aria-label="Повідомлення" placeholder="Твоє повідомлення…" value={text} maxLength={4000} onChange={e=>setText(e.target.value)}/><button className={s.button} disabled={busy||(!text.trim()&&!sharedBook)} aria-label="Надіслати повідомлення"><Send size={19}/></button></form></>}
    <button className={s.quiet} disabled={busy} style={{marginTop:18}} onClick={async()=>{const closes=current.kind==="direct"||(current.kind==="group"&&current.role==="owner");if(window.confirm(closes?"Закрити цю розмову? Нові повідомлення стануть недоступні.":"Вийти з цієї розмови?")){if(await act("leave",{threadId:current.id}))setSelected(null);}}}>{current.role==="owner"&&current.kind==="group"?"Закрити групу":"Вийти з розмови"}</button></>}</div></div>
    <details className={s.notice} onToggle={e=>{if(e.currentTarget.open)void loadBlocks();}}><summary>Заблоковані учасники</summary>{blocks.length===0?<p className={s.muted}>Список порожній.</p>:blocks.map(person=><p key={person.id}>{person.display_name} <button className={s.quiet} disabled={busy} onClick={async()=>{if(await act("block",{readerId:person.id,blocked:false}))await loadBlocks();}}>Розблокувати</button></p>)}</details>
    {mode&&<CommunityModal title={mode==="invite"?"Запросити до групи":"Знайти учасника"} onClose={()=>setMode(null)}><label className={s.field}>Ім’я у спільноті<input value={query} onChange={e=>setQuery(e.target.value)} autoFocus maxLength={50} placeholder="Щонайменше 2 символи"/></label><p className={s.muted}>Пошук лише серед читачів, які добровільно ввімкнули спілкування.</p>{people.map(person=><p key={person.id}><button className={s.secondary} disabled={busy} onClick={()=>void personAction(person)}>{person.display_name} · Запросити</button></p>)}{query.length>=2&&people.length===0&&<p className={s.muted}>Учасників не знайдено.</p>}</CommunityModal>}
    {report&&<CommunityModal title="Повідомити бібліотекаря" onClose={()=>setReport(null)}><p className={s.muted}>Бібліотекар отримає вибране повідомлення, автора й причину скарги.</p><blockquote className={s.notice}>{report.body||report.book_title}</blockquote><label className={s.field}>Що сталося?<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={2000}/></label><div className={s.actions}><button className={s.button} disabled={busy||reason.trim().length<5} onClick={async()=>{if(await act("report",{threadId:selected,messageId:report.id,reason})){setReport(null);setNotice("Скаргу передано бібліотекарю.");}}}><ShieldAlert size={16}/>Надіслати скаргу</button></div></CommunityModal>}
  </section>;
  async function personAction(value:DirectoryReader){await person(value);}
}
function CommunityModal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog ref={ref} className={s.dialog} onCancel={onClose}><div className={s.dialogInner}><div className={s.dialogTop}><h2>{title}</h2><button className={s.iconButton} onClick={onClose} aria-label="Закрити"><X/></button></div><div className={s.detailSection}>{children}</div></div></dialog>;}
