"use client";
/* eslint-disable @next/next/no-img-element */
import {useEffect,useRef,useState,type FormEvent} from "react";
import {Camera,UserRound,ShieldCheck} from "lucide-react";
import {readerFetch,type ReaderProfile} from "./reader-types";
import s from "./reader.module.css";

async function preparePhoto(file:File){
  if(!/^image\/(jpeg|png|webp)$/.test(file.type)||file.size>12*1024*1024)throw new Error("Оберіть JPEG, PNG або WebP до 12 МБ.");
  const url=URL.createObjectURL(file),image=new Image();
  try{image.src=url;await image.decode();if(image.naturalWidth*image.naturalHeight>40000000)throw new Error("Фото завелике. Зменште його й спробуйте ще раз.");
    const scale=Math.min(1,600/image.naturalWidth,900/image.naturalHeight),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));
    const context=canvas.getContext("2d");if(!context)throw new Error("Не вдалося підготувати фото.");context.fillStyle="#fff";context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,canvas.width,canvas.height);
    // Canvas re-encoding drops EXIF/GPS; the original file never leaves this device.
    return canvas.toDataURL("image/jpeg",.86).split(",")[1];
  }finally{URL.revokeObjectURL(url);}
}
export default function ProfilePanel({profile,onProfile,telegram}:{profile:ReaderProfile;onProfile:(p:ReaderProfile)=>void;telegram:boolean}){
  const [name,setName]=useState(profile.displayName),[phone,setPhone]=useState(profile.phone),[community,setCommunity]=useState(profile.communityEnabled),[loans,setLoans]=useState(profile.notifyLoans),[books,setBooks]=useState(profile.notifyBooks),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const intent=useRef<string|null>(null);
  useEffect(()=>{setName(profile.displayName);setPhone(profile.phone);setCommunity(profile.communityEnabled);setLoans(profile.notifyLoans);setBooks(profile.notifyBooks);intent.current=null;},[profile]);
  async function save(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError("");setNotice("");try{const response=await readerFetch<{profile:ReaderProfile}>("/api/reader/profile",{requestId:intent.current||=crypto.randomUUID(),expectedVersion:profile.version,displayName:name,phone,communityEnabled:community,notifyLoans:loans,notifyBooks:books},"PATCH",profile.id);onProfile(response.profile);setNotice("Профіль збережено.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function photo(file?:File,remove=false){if(busy||(!file&&!remove))return;setBusy(true);setError("");setNotice("");try{const body={requestId:crypto.randomUUID(),expectedVersion:profile.version,...(!remove?{base64:await preparePhoto(file!)}:{})};await readerFetch("/api/reader/photo",body,remove?"DELETE":"POST",profile.id);onProfile((await readerFetch<{profile:ReaderProfile}>("/api/reader/profile",undefined,"GET",profile.id)).profile);setNotice(remove?"Фото прибрано з профілю.":"Фото оновлено.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function changed(){intent.current=null;}
  return <section><div className={s.sectionHead}><div><span className={s.eyebrow}>Мій простір</span><h1>Профіль читача</h1></div><UserRound size={26}/></div>
    {error&&<p className={s.error} role="alert">{error}</p>}{notice&&<p className={s.notice} role="status">{notice}</p>}
    <div className={s.profileGrid}><div><div className={`${s.panel} ${s.profileCard}`}>{profile.photoUrl?<img className={s.avatar} src={profile.photoUrl} alt="Моє фото"/>:<div className={s.avatar}><UserRound size={40}/></div>}<div><h2>{profile.fullName}</h2><p>Читацький квиток № {profile.memberNo||"—"}</p><p>{profile.kind==="teacher"?"Учитель":profile.kind==="student"?"Учень / учениця":"Читач бібліотеки"}</p></div></div>
    <label className={s.field} style={{marginTop:15}}><span><Camera size={15}/> Моє фото</span><input className={s.hiddenInput} type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{void photo(e.target.files?.[0]);e.target.value="";}}/><small>Фото бачиш ти та уповноважений бібліотекар. Оригінал із метаданими не завантажується.</small></label>{profile.photoUrl&&<button className={s.quiet} disabled={busy} onClick={()=>void photo(undefined,true)}>Прибрати фото</button>}</div>
    <form className={s.panel} onSubmit={save} onChange={changed}><div className={s.fields}><label className={s.field}>Повне ім’я<input value={profile.fullName} readOnly/><small>Якщо є помилка — повідом бібліотекаря.</small></label><label className={s.field}>Мій клас<input value={profile.classLabel||"Не зазначено"} readOnly/><small>{profile.academicYear|| (profile.classSource==="imported"?"Дані перенесено з реєстру Librarika":"Клас визначає бібліотекар")}</small></label><label className={s.field}>Мобільний телефон<input value={phone} onChange={e=>setPhone(e.target.value)} type="tel" autoComplete="tel" maxLength={30} placeholder="За бажанням"/><small>Не відображається у спільноті чи каталозі.</small></label><label className={s.field}>Ім’я у читацькій спільноті<input value={name} onChange={e=>setName(e.target.value)} minLength={2} maxLength={50} required/><small>Можна обрати псевдонім.</small></label></div>
    <div className={s.detailSection}><h3>Спілкування та сповіщення</h3><label className={s.check}><input type="checkbox" checked={community} onChange={e=>setCommunity(e.target.checked)}/><span>Долучитися до читацької спільноти<small className={s.muted} style={{display:"block"}}>Інші учасники бачитимуть обране ім’я, зможуть запросити до чату чи групи. Особистий чат починається після прийняття запрошення.</small></span></label><label className={s.check}><input type="checkbox" checked={loans} onChange={e=>setLoans(e.target.checked)}/><span>Отримувати в Telegram нагадування про повернення моїх книг</span></label><label className={s.check}><input type="checkbox" checked={books} onChange={e=>setBooks(e.target.checked)}/><span>Повідомляти в Telegram про доступність книг, на які я підписався / підписалася<small className={s.muted} style={{display:"block"}}>Після ввімкнення можеш отримати повідомлення і про підписані книги, які вже є на полиці.</small></span></label>
    <p className={s.muted}>{profile.telegramConnected?"Telegram під’єднано до цього профілю.":profile.teacherLinked?"Керуйте підключенням Telegram у кабінеті вчителя.":"Для повідомлень під’єднайте свій Telegram через персональне запрошення бібліотекаря."}</p></div>
    <button className={s.button} disabled={busy} type="submit">{busy?"Зберігаємо…":"Зберегти профіль"}</button><p className={s.muted}><ShieldCheck size={14}/> Не передавай персональне запрошення іншій людині.</p>{profile.teacherLinked&&<a className={s.secondary} href={telegram?"/teacher/telegram/cabinet":"/teacher"}>До кабінету вчителя</a>}</form></div></section>;
}
