"use client";
/* eslint-disable @next/next/no-img-element */
import {useCallback,useEffect,useRef,useState} from "react";
import {BookOpen,BookMarked,Heart,LibraryBig,LogIn,MessageCircle,UserRound,X} from "lucide-react";
import ReaderCatalog from "./catalog-panel";
import BookDialog from "./book-dialog";
import ProfilePanel from "./profile-panel";
import BooksPanel from "./books-panel";
import CommunityPanel from "./community-panel";
import {READER_LOGO,readerFetch,type ReaderProfile} from "./reader-types";
import s from "./reader.module.css";

async function telegramApp(){
  if(!window.Telegram?.WebApp)await new Promise<void>((resolve,reject)=>{const prior=document.querySelector<HTMLScriptElement>('script[data-reader-telegram="true"]');if(prior){if(window.Telegram?.WebApp){resolve();return;}prior.addEventListener("load",()=>resolve(),{once:true});prior.addEventListener("error",()=>reject(new Error("Не вдалося відкрити Telegram.")),{once:true});return;}
    const script=document.createElement("script");script.src="https://telegram.org/js/telegram-web-app.js";script.dataset.readerTelegram="true";script.onload=()=>resolve();script.onerror=()=>{script.remove();reject(new Error("Не вдалося відкрити Telegram."));};document.head.append(script);});
  const app=window.Telegram?.WebApp;if(!app?.initData)throw new Error("Відкрий цей кабінет кнопкою в приватному чаті з бібліотечним ботом.");app.ready();app.expand();app.setHeaderColor?.("#173522");app.setBackgroundColor?.("#faf8f1");return app;
}
export default function ReaderPortal({telegram=false}:{telegram?:boolean}){
  const [profile,setProfile]=useState<ReaderProfile|null>(null),[section,setSection]=useState("catalog"),[book,setBook]=useState<string|null>(null),[entity,setEntity]=useState<{id:string;kind:string}|null>(null),[filter,setFilter]=useState<{id:string;kind:string}|null>(null),[shared,setShared]=useState<string|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[invite,setInvite]=useState(""),[inviteName,setInviteName]=useState(""),[consent,setConsent]=useState(false),[bot,setBot]=useState<string|null>(null);
  const started=useRef(false),epoch=useRef(0),loginSection=()=>{setBook(null);setEntity(null);setSection("login");};
  const profileEpoch=epoch.current;
  const updateProfile=(next:ReaderProfile)=>{if(epoch.current===profileEpoch)setProfile(current=>current?.id===next.id?next:current);};
  const refresh=useCallback(async()=>{const data=await readerFetch<{profile:ReaderProfile;telegram:{botUsername:string|null}}>("/api/reader/session");setProfile(data.profile);setBot(data.telegram.botUsername);return data.profile;},[]);
  useEffect(()=>{readerFetch<{telegram:{botUsername:string|null}}>("/api/reader/config").then(data=>setBot(data.telegram.botUsername)).catch(()=>{});},[]);
  useEffect(()=>{if(started.current)return;started.current=true;const url=new URL(window.location.href),fragment=new URLSearchParams(url.hash.slice(1)),token=fragment.get("invite")||"";
    const initialBook=url.searchParams.get("book");if(initialBook&&/^[A-Za-z0-9_-]{1,100}$/.test(initialBook))setBook(initialBook);
    const initialTab=url.searchParams.get("tab");if(initialTab&&["catalog","books","profile","community"].includes(initialTab))setSection(initialTab);
    if(token){setInvite(token);setSection("login");window.history.replaceState(null,"",url.pathname+url.search);readerFetch<{preview:{fullName:string}}>("/api/reader/session",{action:"preview",token,purpose:telegram?"telegram":"web"}).then(data=>setInviteName(data.preview.fullName)).catch(e=>setError(e.message)).finally(()=>setLoading(false));return;}
    (async()=>{if(telegram){try{const app=await telegramApp();await readerFetch("/api/reader/session",{action:"telegram",initData:app.initData});await refresh();}catch(e){setProfile(null);setError((e as Error).message);setSection("login");}}else await refresh().catch(()=>{});})().finally(()=>setLoading(false));
  },[refresh,telegram]);
  async function login(){if(!consent||!inviteName||busy)return;setBusy(true);setError("");try{const app=telegram?await telegramApp():null;await readerFetch("/api/reader/session",{action:telegram?"telegram":"invite",token:invite,confirmation:"CONNECT_MY_READER_PROFILE",...(app?{initData:app.initData}:{})});setInvite("");setInviteName("");await refresh();setSection("profile");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function logout(){const readerId=profile?.id;epoch.current++;setBusy(true);setError("");try{await readerFetch("/api/reader/session",{},"DELETE",readerId);setProfile(null);setSection("catalog");setBook(null);setShared(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function navigate(tab:string){setSection(tab);setError("");}
  const protectedSection=["books","profile","community"].includes(section),needsLogin=section==="login"||(protectedSection&&!profile);
  return <div className={s.shell}><header className={s.header}><a className={s.brand} href="/"><img src={READER_LOGO} alt="Лейбл бібліотеки"/><span><strong>Єдина бібліотека</strong><small>Міжнародний ліцей МАУП</small></span></a><div className={s.headerLinks}><a href="/textbooks">Е-підручники</a>{profile?<button className={s.quiet} onClick={()=>navigate("profile")}><UserRound size={16}/>Мій профіль</button>:<button className={s.secondary} onClick={loginSection}><LogIn size={15}/>Увійти</button>}</div></header>
  <div className={s.layout}><nav className={s.sidebar} aria-label="Кабінет читача">{[["catalog","Каталог",LibraryBig],["books","Мої книги",BookMarked],["community","Спільнота",MessageCircle],["profile","Профіль",UserRound]].map(([id,label,Icon])=>{const Symbol=Icon as typeof BookOpen;return <button key={String(id)} className={section===id?s.active:""} aria-current={section===id?"page":undefined} onClick={()=>navigate(String(id))}><Symbol size={21}/>{String(label)}</button>;})}<a href="/suggest-book"><Heart size={21}/>Запропонувати книгу</a><div className={s.sideNote}>Місце, де кожна книга<br/>знаходить свого читача.<br/><br/><a href="/">На головну бібліотеки ↗</a></div></nav>
  <main className={s.main}><div hidden={section!=="catalog"}><section className={s.hero}><div><span className={s.eyebrow}>Твоя історія починається тут</span><h1>Знайди книгу,<br/>яка стане твоєю.</h1><p>Від захопливих пригод до великих відкриттів. Обирай, читай і ділися враженнями у бібліотеці ліцею.</p></div><BookOpen className={s.heroMark} size={118} strokeWidth={.7}/></section><ReaderCatalog onBook={setBook} initialEntity={filter}/></div>
    {error&&section!=="login"&&<p className={s.error} role="alert">{error}</p>}
    {needsLogin&&<section className={s.panel}><span className={s.eyebrow}>Особистий кабінет</span><h1 className={s.heading}>Твої книги завжди поруч</h1>{loading?<p className={s.muted}>Перевіряємо доступ…</p>:invite?<><p className={s.notice}>Персональне запрошення для: <strong>{inviteName||"перевіряємо…"}</strong></p><label className={s.check}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={!inviteName}/><span>Це мій читацький профіль. Хочу приєднати його {telegram?"до свого Telegram":"на цьому пристрої"}.</span></label><button className={s.button} disabled={!consent||!inviteName||busy} onClick={()=>void login()}>{busy?"Приєднуємо…":"Приєднати мій профіль"}</button><p className={s.muted}>Не підтверджуй, якщо бачиш чуже ім’я. Звернися до бібліотекаря.</p></>:<><p className={s.bodyText}>Для першого входу отримай персональне запрошення у бібліотекаря. Воно під’єднає саме твій читацький квиток — придумувати пароль не потрібно.</p><p className={s.muted}>Після підключення можна відкривати свій кабінет кнопкою в Telegram. Каталог доступний і без входу.</p><div className={s.actions}>{bot&&<a className={s.button} href={`https://t.me/${bot}?start=reader`}>Відкрити бібліотечного бота</a>}<a className={s.secondary} href={telegram?"/teacher/telegram":"/teacher"}>Вхід для вчителя</a><button className={s.quiet} onClick={()=>navigate("catalog")}>Переглядати каталог</button></div></>}{error&&<p className={s.error} role="alert">{error}</p>}</section>}
    {profile&&section==="profile"&&<><ProfilePanel key={profile.id} profile={profile} onProfile={updateProfile} telegram={telegram}/>{!profile.teacherLinked&&<button className={s.quiet} style={{marginTop:22}} disabled={busy} onClick={()=>void logout()}>Вийти на цьому пристрої</button>}</>}
    {profile&&section==="books"&&<BooksPanel key={profile.id} readerId={profile.id} onBook={setBook}/>}{profile&&section==="community"&&<CommunityPanel key={profile.id} profile={profile} sharedBook={shared} onShared={()=>setShared(null)} onBook={setBook} onProfile={()=>navigate("profile")}/>}
    <footer className={s.footer}><span>Єдина бібліотека · Міжнародний ліцей МАУП</span><span>Читай. Досліджуй. Ділися відкриттями.</span></footer>
  </main></div>{book&&<BookDialog key={book} id={book} profile={profile} onClose={()=>setBook(null)} onEntity={(id,kind)=>setEntity({id,kind})} onShare={id=>{setShared(id);setBook(null);navigate("community");}} onLogin={loginSection}/>} {entity&&<EntityDialog id={entity.id} onClose={()=>setEntity(null)} onFilter={()=>{setFilter(entity);setEntity(null);setBook(null);navigate("catalog");}}/>}</div>;
}
function EntityDialog({id,onClose,onFilter}:{id:string;onClose:()=>void;onFilter:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null),[data,setData]=useState<{name:string;kind:string;metadata:Record<string,unknown>}|null>(null),[error,setError]=useState("");
  useEffect(()=>{dialog.current?.showModal();let live=true;readerFetch<{result:NonNullable<typeof data>}>("/api/library/catalog?entity="+encodeURIComponent(id)).then(result=>{if(live)setData(result.result);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[id]);
  const value=(key:string)=>typeof data?.metadata[key]==="string"||typeof data?.metadata[key]==="number"?String(data.metadata[key]):"";
  const website=value("website"),safeWebsite=/^https?:\/\//i.test(website);
  return <dialog ref={dialog} className={s.dialog} onCancel={onClose}><div className={s.dialogInner}><div className={s.dialogTop}><div><p className={s.eyebrow}>{data?.kind==="author"?"Знайомство з автором":data?.kind==="publisher"?"Видавництво":"Жанр бібліотеки"}</p><h2>{data?.name||"Завантаження…"}</h2></div><button className={s.iconButton} onClick={onClose} aria-label="Закрити"><X/></button></div>{error&&<p className={s.error}>{error}</p>}{data&&<><p className={s.muted}>{[value("country"),value("dateOfBirth"),value("yearDied")].filter(Boolean).join(" · ")}</p><div className={s.bodyText}>{value("biography")||value("description")||"Додаткової довідки у вихідному каталозі немає."}</div>{value("publications")&&<p className={s.bodyText}>{value("publications")}</p>}{value("awards")&&<p className={s.bodyText}>{value("awards")}</p>}{safeWebsite&&<p><a href={website} target="_blank" rel="noopener noreferrer">Вебсайт видавництва ↗</a></p>}<div className={s.actions}><button className={s.button} onClick={onFilter}>Переглянути книги в каталозі</button></div></>}</div></dialog>;
}
