export type ReaderProfile={id:string;fullName:string;memberNo:string;kind:string;classLabel:string;classSource:string;academicYear:string|null;displayName:string;phone:string;photoUrl:string|null;communityEnabled:boolean;notifyLoans:boolean;notifyBooks:boolean;version:number;telegramConnected:boolean;teacherLinked:boolean};
export type CatalogCard={material_id:string;edition_id:string|null;title:string;author:string;publisher:string;year:number|null;cover_url:string|null;genre:string;available:number;total:number;rating:number|null;class_from:number|null;class_to:number|null};
export type CatalogFacet={id:string;kind:string;name:string;count:number};
export type BookDetail={id:string;title:string;materialId:string;fund:string;metadata:Record<string,unknown>;available:number;total:number;entities:{id:string;kind:string;name:string;role:string}[];copies:{id:string;accession_no:string;copy_no:string;physical_state:string;condition:string}[];reviews:{rating:number;body:string;display_name:string;date:string}[];links:{url:string;label:string}[]};
export type ReaderLoan={id:string;status:string;issued_at:string|null;due_at:string|null;received_at:string|null;edition_id:string;title:string;author:string;cover_url:string|null;accession_no:string;copy_no:string};
export type ReaderRequest={id:string;edition_id:string;status:string;note:string;version:number;created_at:string;title:string;cover_url:string|null};
export async function readerFetch<T>(url:string,body?:unknown,method=body===undefined?"GET":"POST",readerId?:string):Promise<T>{const response=await fetch(url,{method,cache:"no-store",headers:{...(body===undefined?{}:{"Content-Type":"application/json"}),...(readerId?{"X-Reader-Id":readerId}:{})},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error||"Не вдалося завантажити дані.");return data as T;}
export const readerDate=(value:string|null)=>{if(!value)return "Не зазначено";const match=value.match(/^(\d{4})-(\d{2})-(\d{2})/);return match?`${match[3]}.${match[2]}.${match[1]}`:value;};
export const READER_LOGO="https://nazarijshvetz1.github.io/library-site/library-logo.png";
