"use client";
import {useEffect,useRef,useState} from 'react';import {Home,LibraryBig,BookMarked,MessageCircle,Activity,UserRound} from 'lucide-react';import {READER_LOGO,readerFetch,type ReaderProfile} from './reader-types';import {LiteratureNavigation,DraftScope,useRouteState,clearLiteratureDraft} from '../librarian/literature/literature-navigation';import {HomePanel,CatalogPanel,LoansPanel,ActivityPanel,AccountPanel,ProposalForm} from './cabinet-panels';import CabinetBook from './cabinet-book';import CabinetFeed from './cabinet-feed';import type {Row} from './cabinet-controls';import s from './cabinet.module.css';
const tabs=[['home','Головна',Home],['catalog','Каталог',LibraryBig],['books','Мої видачі',BookMarked],['community','Спільнота',MessageCircle],['activity','Активність',Activity],['profile','Обліковий запис',UserRound]] as const;
type Props={profile:ReaderProfile;onProfile:(p:ReaderProfile)=>void;telegram:boolean;onLogout:()=>void};
export default function ReaderWorkspace(props:Props){return <LiteratureNavigation key={props.profile.id}><Workspace {...props}/></LiteratureNavigation>;}
function Workspace({profile,onProfile,telegram,onLogout}:Props){const [tab,setTab]=useState('home'),[book,setBook]=useState(''),[catalog,setCatalog]=useState<Row>({}),[loans,setLoans]=useState<Row>({}),[activity,setActivity]=useState<Row>({}),[community,setCommunity]=useState<Row>({}),[scan,setScan]=useState(''),[proposal,setProposal]=useState(false),[epoch,setEpoch]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),intents=useRef(new Map<string,string>());
 const nav=useRouteState({tab,book,catalog,loans,activity,community:{page:community.page,post:community.post,commentPage:community.commentPage},proposal},v=>{setTab(v.tab||'home');setBook(v.book||'');setCatalog(v.catalog||{});setLoans(v.loans||{});setActivity(v.activity||{});setCommunity(old=>({...old,page:v.community?.page,post:v.community?.post,commentPage:v.community?.commentPage}));setProposal(!!v.proposal);});
 useEffect(()=>{const u=new URL(location.href),t=u.searchParams.get('tab'),b=u.searchParams.get('book');if(tabs.some(x=>x[0]===t))setTab(t!);if(b&&/^[A-Za-z0-9_-]{1,100}$/.test(b)){setTab('catalog');setBook(b);}},[]);
 useEffect(()=>nav.fallback(()=>{setBook('');setProposal(false);setTab(book?'catalog':'home');const u=new URL(location.href);u.searchParams.delete('book');u.searchParams.set('tab',book?'catalog':'home');history.replaceState(history.state,'',u.href);}),[book]);
 useEffect(()=>{const t=(window.Telegram?.WebApp as any)?.BackButton;if(!telegram||!t)return;const back=()=>nav.back();t.onClick(back);if(tab!=='home'||book||proposal)t.show();else t.hide();return()=>t.offClick(back);},[tab,book,proposal,telegram]);
 useEffect(()=>{const update=()=>{if(!document.hidden)setEpoch(n=>n+1);};const timer=setInterval(update,30000);window.addEventListener('focus',update);return()=>{clearInterval(timer);window.removeEventListener('focus',update);};},[]);
 useEffect(()=>{if(!profile.teacherLinked)return;let current=true;readerFetch<{profile:ReaderProfile}>('/api/reader/profile',undefined,'GET',profile.id).then(d=>{if(current)onProfile(d.profile);}).catch(()=>{});return()=>{current=false;};},[profile.id,profile.teacherLinked,epoch,tab]);
 async function act(action:string,input:Row){if(busy)return null;const key=JSON.stringify({action,input});if(!intents.current.has(key))intents.current.set(key,crypto.randomUUID());setBusy(true);setMessage('');try{const r=await readerFetch<{result:Row}>('/api/reader/cabinet',{action,input:{...input,requestId:intents.current.get(key)}},'POST',profile.id);intents.current.delete(key);setEpoch(n=>n+1);if(action==='proposal'){clearLiteratureDraft('proposal:'+profile.id);setMessage('Пропозицію надіслано бібліотекарю.');}return r.result;}catch(e){setMessage((e as Error).message);return null;}finally{setBusy(false);}}
 function go(next:string){if(next===tab&&!book)return;const u=new URL(location.href);u.searchParams.set('tab',next);u.searchParams.delete('book');nav.push(u.href);setTab(next);setBook('');setMessage('');window.scrollTo({top:0});}
 function openBook(id:string){const u=new URL(location.href);u.searchParams.set('book',id);nav.push(u.href);setBook(id);}
 useEffect(()=>{if(book)void readerFetch('/api/reader/cabinet',{action:'view',input:{editionId:book,requestId:crypto.randomUUID()}},'POST',profile.id).then(()=>setEpoch(n=>n+1)).catch(()=>{});},[book,profile.id]);
 function filter(e:Row){go('catalog');setCatalog({filters:{[e.kind]:e},page:1,expanded:true});}
 return <div className={s.shell}><header className={s.header}>{tab!=='home'&&!book&&<button className={s.back} onClick={nav.back} aria-label="Назад">←<span> Назад</span></button>}<img src={READER_LOGO} alt="Емблема бібліотеки"/><div><strong>Єдина бібліотека</strong><span>Художня та наукова література</span><small>Міжнародний ліцей МАУП</small></div></header><main className={s.main}>{message&&<p className={s.notice} role="status">{message}</p>}<div hidden={tab!=='home'}>{tab==='home'&&<HomePanel profile={profile} epoch={epoch} onBook={openBook} onCatalog={code=>{go('catalog');setScan(code||'');}}/>}</div><div hidden={tab!=='catalog'}><CatalogPanel state={catalog} setState={setCatalog} onBook={openBook} onPropose={()=>setProposal(true)} scanCode={scan} onScanDone={()=>setScan('')}/></div><div hidden={tab!=='books'}>{tab==='books'&&<LoansPanel state={loans} setState={setLoans} epoch={epoch} act={act} busy={busy} onBook={openBook}/>}</div><div hidden={tab!=='community'}><CabinetFeed profile={profile} state={community} setState={setCommunity} onBook={openBook} onAccount={()=>go('profile')}/></div><div hidden={tab!=='activity'}>{tab==='activity'&&<ActivityPanel state={activity} setState={setActivity} epoch={epoch} onBook={openBook}/>}</div><div hidden={tab!=='profile'}><AccountPanel profile={profile} onProfile={onProfile} telegram={telegram} onLogout={onLogout}/></div></main><nav className={s.nav} aria-label="Кабінет читача">{tabs.map(([id,label,Icon])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>go(id)}><Icon size={21}/><span>{label}</span></button>)}</nav>{book&&<DraftScope key={profile.id+':'+book} draftKey={'reader-book:'+profile.id+':'+book}><CabinetBook id={book} epoch={epoch} act={act} busy={busy} error={message} onClose={()=>setBook('')} onEntity={filter} onDiscuss={b=>{go('community');setCommunity(v=>({...v,book:b,bookQuery:b.title}));}}/></DraftScope>}{proposal&&<DraftScope draftKey={'proposal:'+profile.id}><ProposalForm act={act} busy={busy} error={message} onClose={()=>setProposal(false)}/></DraftScope>}</div>;
}
