"use client";
/* eslint-disable @next/next/no-img-element */
import {useCallback,useEffect,useRef,useState} from "react";
import ReaderWorkspace from "./reader-workspace";
import {READER_LOGO,readerFetch,type ReaderProfile} from "./reader-types";
import s from "./reader.module.css";

const TELEGRAM_SCRIPT_URL="https://telegram.org/js/telegram-web-app.js";
const wait=(milliseconds:number)=>new Promise<void>(resolve=>window.setTimeout(resolve,milliseconds));
type DirectoryItem={loginId:string;fullName:string;classLabel:string};

async function telegramApp(){
 let script=document.querySelector<HTMLScriptElement>('script[data-reader-telegram="true"]');
 if(!window.Telegram?.WebApp&&!script){script=document.createElement("script");script.src=TELEGRAM_SCRIPT_URL;script.dataset.readerTelegram="true";script.onerror=()=>{script!.dataset.readerTelegramError="true";};document.head.append(script);}
 for(let attempt=0;attempt<80;attempt+=1){const app=window.Telegram?.WebApp;if(app?.initData){app.ready();app.expand();app.setHeaderColor?.("#173522");app.setBackgroundColor?.("#faf8f1");return app;}if(script?.dataset.readerTelegramError==="true")throw new Error("Не вдалося завантажити Telegram. Перевір з’єднання та відкрий запрошення ще раз.");await wait(50);}
 throw new Error("Telegram не передав дані входу. Закрий це вікно та знову відкрий персональне запрошення в чаті з бібліотечним ботом.");
}

export default function ReaderPortal({telegram=false}:{telegram?:boolean}){
 const [profile,setProfile]=useState<ReaderProfile|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [invite,setInvite]=useState(""),[inviteName,setInviteName]=useState(""),[inviteClass,setInviteClass]=useState(""),[consent,setConsent]=useState(false),[bot,setBot]=useState<string|null>(null),[telegramReady,setTelegramReady]=useState(false);
 const [query,setQuery]=useState(""),[results,setResults]=useState<DirectoryItem[]>([]),[searching,setSearching]=useState(false),[selected,setSelected]=useState<DirectoryItem|null>(null);
 const [accessCode,setAccessCode]=useState(""),[setupToken,setSetupToken]=useState(""),[newPin,setNewPin]=useState(""),[pinConfirm,setPinConfirm]=useState(""),[showSecret,setShowSecret]=useState(false);
 const started=useRef(false),telegramInitData=useRef(""),searchSequence=useRef(0);
 const updateProfile=(next:ReaderProfile)=>setProfile(current=>current?.id===next.id?next:current);
 const refresh=useCallback(async()=>{const data=await readerFetch<{profile:ReaderProfile;telegram:{botUsername:string|null}}>("/api/reader/session");setProfile(data.profile);setBot(data.telegram.botUsername);return data.profile;},[]);
 useEffect(()=>{readerFetch<{telegram:{botUsername:string|null}}>("/api/reader/config").then(data=>setBot(data.telegram.botUsername)).catch(()=>{});},[]);
 useEffect(()=>{if(started.current)return;started.current=true;const url=new URL(window.location.href),fragment=new URLSearchParams(url.hash.slice(1)),token=fragment.get("invite")||"";
  if(token){queueMicrotask(()=>setInvite(token));void(async()=>{let launchError="";if(telegram){try{const app=await telegramApp();telegramInitData.current=app.initData;setTelegramReady(true);}catch(reason){telegramInitData.current="";setTelegramReady(false);launchError=(reason as Error).message;}}window.history.replaceState(null,"",url.pathname+url.search);try{const data=await readerFetch<{preview:{fullName:string;classLabel?:string}}>("/api/reader/session",{action:"preview",token,purpose:telegram?"telegram":"web"});setInviteName(data.preview.fullName);setInviteClass(data.preview.classLabel||"");if(launchError)setError(launchError);}catch(reason){setError((reason as Error).message);}finally{setLoading(false);}})();return;}
  void(async()=>{if(telegram){try{const app=await telegramApp();telegramInitData.current=app.initData;setTelegramReady(true);await readerFetch("/api/reader/session",{action:"telegram",initData:app.initData});await refresh();}catch(reason){telegramInitData.current="";setTelegramReady(false);setProfile(null);setError((reason as Error).message);}}else await refresh().catch(reason=>{if((reason as {status?:number}).status!==401)setError((reason as Error).message);});})().finally(()=>setLoading(false));
 },[refresh,telegram]);
 useEffect(()=>{if(telegram||invite||selected||setupToken)return;const normalized=query.normalize("NFKC").trim().replace(/\s+/gu," ");if(normalized.length<3)return;const sequence=++searchSequence.current,controller=new AbortController(),timer=window.setTimeout(()=>{fetch("/api/reader/directory?q="+encodeURIComponent(normalized),{cache:"no-store",signal:controller.signal}).then(async response=>{const data=await response.json();if(!response.ok||!data.success)throw new Error(typeof data.error==="string"?data.error:data.error?.message||"Не вдалося знайти учня.");if(searchSequence.current===sequence)setResults(Array.isArray(data.items)?data.items:[]);}).catch(reason=>{if(reason.name!=="AbortError"&&searchSequence.current===sequence){setResults([]);setError(reason.message);}}).finally(()=>{if(searchSequence.current===sequence)setSearching(false);});},300);return()=>{window.clearTimeout(timer);controller.abort();};},[invite,query,selected,setupToken,telegram]);
 function choose(item:DirectoryItem){setSelected(item);setQuery(item.fullName);setResults([]);setAccessCode("");setSetupToken("");setNewPin("");setPinConfirm("");setError("");}
 function changeStudent(){setSelected(null);setQuery("");setResults([]);setAccessCode("");setSetupToken("");setNewPin("");setPinConfirm("");setShowSecret(false);setError("");}
 async function ordinaryLogin(){if(!selected||!/^[0-9]{4}$/u.test(accessCode)||busy)return;setBusy(true);setError("");try{const result=await readerFetch<{requiresPinSetup?:boolean;setupToken?:string}>("/api/reader/session",{action:"login",loginId:selected.loginId,code:accessCode});if(result.requiresPinSetup&&result.setupToken){setSetupToken(result.setupToken);setAccessCode("");setShowSecret(false);return;}await refresh();}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}}
 async function finishPin(){if(!setupToken||!/^[0-9]{4}$/u.test(newPin)||newPin!==pinConfirm||busy)return;setBusy(true);setError("");try{await readerFetch("/api/reader/session",{action:"set_pin",setupToken,pin:newPin,pinConfirm});setSetupToken("");setNewPin("");setPinConfirm("");await refresh();}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}}
 async function inviteLogin(){if(!inviteName||busy||(telegram&&!telegramReady)||(!telegram&&(!consent||!/^[0-9]{4}$/u.test(newPin)||newPin!==pinConfirm)))return;setBusy(true);setError("");try{let initData=telegramInitData.current;if(telegram&&!initData){const app=await telegramApp();initData=app.initData;telegramInitData.current=initData;setTelegramReady(true);}await readerFetch("/api/reader/session",{action:telegram?"telegram":"invite",token:invite,confirmation:"CONNECT_MY_READER_PROFILE",...(telegram?{initData}:{pin:newPin,pinConfirm})});setInvite("");setInviteName("");setNewPin("");setPinConfirm("");await refresh();}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}}
 async function logout(){const readerId=profile?.id;setBusy(true);setError("");try{await readerFetch("/api/reader/session",{},"DELETE",readerId);setProfile(null);changeStudent();}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}}
 if(profile)return <ReaderWorkspace profile={profile} onProfile={updateProfile} telegram={telegram} onLogout={()=>void logout()}/>;
 return <div className={s.shell}><header className={s.header}><a className={s.brand} href="/reader"><img src={READER_LOGO} alt="Емблема бібліотеки"/><span><strong>Єдина бібліотека</strong><small>Художня та наукова література</small><small>Міжнародний ліцей МАУП</small></span></a></header><main className={s.main}>
  <section className={`${s.panel} ${s.loginPanel}`}><span className={s.eyebrow}>Особистий кабінет</span><h1 className={s.heading}>Твої книги завжди поруч</h1>
   {loading?<p className={s.muted}>Перевіряємо безпечний вхід…</p>:invite?<div className={s.loginForm}><div className={s.selectedIdentity}><span>Персональне запрошення</span><strong>{inviteName||"Перевіряємо…"}</strong>{inviteClass&&<small>{inviteClass}</small>}</div>
    {!telegram&&<><label className={s.check}><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)} disabled={!inviteName}/><span>Це мій профіль. Хочу створити власний PIN для входу.</span></label><PinSetupFields pin={newPin} confirm={pinConfirm} show={showSecret} onPin={setNewPin} onConfirm={setPinConfirm} onShow={setShowSecret}/></>}
    {telegram&&telegramReady&&<p className={s.bodyText}>Перевір ім’я та підтвердь підключення цього профілю до свого Telegram.</p>}
    {telegram&&!telegramReady?<div className={s.actions}>{bot?<a className={s.button} href={"https://t.me/"+bot+"?start=ra_"+encodeURIComponent(invite)}>Відкрити запрошення через бота</a>:<p className={s.muted}>Закрий це вікно та знову відкрий персональне запрошення у приватному чаті з ботом.</p>}</div>:<button className={s.button} disabled={!inviteName||busy||(!telegram&&(!consent||newPin.length!==4||newPin!==pinConfirm))} onClick={()=>void inviteLogin()}>{busy?"Підключаємо…":telegram?"Так, це мій профіль — підключити":"Створити PIN і увійти"}</button>}
    <p className={s.muted}>Не підтверджуй, якщо бачиш чуже ім’я. Звернися до бібліотекаря.</p></div>:telegram?<><p className={s.bodyText}>Відкрий персональне QR-запрошення у приватному чаті з бібліотечним ботом. Після першого підключення кабінет відкриватиметься автоматично.</p><div className={s.actions}>{bot&&<a className={s.button} href={"https://t.me/"+bot+"?start=reader"}>Відкрити бібліотечного бота</a>}<a className={s.quiet} href="/teacher/telegram">Вхід для вчителя</a></div></>:setupToken?<div className={s.loginForm}><div className={s.selectedIdentity}><span>Створення власного PIN</span><strong>{selected?.fullName}</strong>{selected?.classLabel&&<small>{selected.classLabel}</small>}</div><p className={s.muted}>Тимчасовий код прийнято. Придумай 4 цифри, які використовуватимеш надалі.</p><PinSetupFields pin={newPin} confirm={pinConfirm} show={showSecret} onPin={setNewPin} onConfirm={setPinConfirm} onShow={setShowSecret}/><button className={s.button} disabled={busy||newPin.length!==4||newPin!==pinConfirm} onClick={()=>void finishPin()}>{busy?"Зберігаємо…":"Зберегти PIN і увійти"}</button></div>:<div className={s.loginForm}><p className={s.bodyText}>Знайди себе у списку учнів і введи власний PIN. Для першого входу введи тимчасовий код, який дав бібліотекар.</p>
    {selected?<><div className={s.selectedIdentity}><span>Обраний учень</span><strong>{selected.fullName}</strong>{selected.classLabel&&<small>{selected.classLabel}</small>}<button type="button" className={s.quiet} onClick={changeStudent}>Змінити учня</button></div><label className={s.loginField}><span>Тимчасовий код або PIN</span><div className={s.pinInput}><input inputMode="numeric" autoComplete="current-password" type={showSecret?"text":"password"} value={accessCode} maxLength={4} pattern="[0-9]{4}" onChange={event=>setAccessCode(event.target.value.replace(/\D/gu,"").slice(0,4))} placeholder="4 цифри"/><button type="button" onClick={()=>setShowSecret(value=>!value)}>{showSecret?"Сховати":"Показати"}</button></div></label><button className={s.button} disabled={busy||accessCode.length!==4} onClick={()=>void ordinaryLogin()}>{busy?"Перевіряємо…":"Увійти"}</button></>:<label className={`${s.loginField} ${s.identitySearch}`}><span>Прізвище або ім’я учня</span><input role="combobox" aria-autocomplete="list" aria-expanded={results.length>0} aria-controls="reader-directory-results" autoComplete="off" value={query} onChange={event=>{const value=event.target.value,ready=value.normalize("NFKC").trim().length>=3;searchSequence.current+=1;setQuery(value);setResults([]);setSearching(ready);setError("");}} placeholder="Введіть щонайменше 3 літери"/>{(searching||query.trim().length>=3)&&<div id="reader-directory-results" role="listbox" className={s.suggestions}>{searching?<p>Шукаємо…</p>:results.length?results.map(item=><button type="button" role="option" aria-selected="false" key={item.loginId} onClick={()=>choose(item)}><strong>{item.fullName}</strong><small>{item.classLabel||"Клас не вказано"}</small></button>):<p>Збігів не знайдено. Перевір написання або звернися до бібліотекаря.</p>}</div>}</label>}
    <p className={s.loginHelp}>У списку видно лише ПІБ і клас. Читацький номер, телефон та інші особисті дані не показуються.</p><div className={s.actions}>{bot&&<a className={s.secondary} href={"https://t.me/"+bot+"?start=reader"}>Відкрити Telegram-бота</a>}<a className={s.quiet} href="/teacher">Вхід для вчителя</a></div></div>}
   {error&&<p className={s.error} role="alert">{error}</p>}
  </section><footer className={s.footer}><span>Єдина бібліотека · Міжнародний ліцей МАУП</span><span>Читай. Досліджуй. Ділися відкриттями.</span></footer>
 </main></div>;
}

function PinSetupFields({pin,confirm,show,onPin,onConfirm,onShow}:{pin:string;confirm:string;show:boolean;onPin:(value:string)=>void;onConfirm:(value:string)=>void;onShow:(value:boolean)=>void}){
 const numeric=(value:string)=>value.replace(/\D/gu,"").slice(0,4);
 return <div className={s.pinFields}><label className={s.loginField}><span>Новий PIN</span><div className={s.pinInput}><input inputMode="numeric" autoComplete="new-password" type={show?"text":"password"} value={pin} maxLength={4} pattern="[0-9]{4}" onChange={event=>onPin(numeric(event.target.value))} placeholder="4 цифри"/><button type="button" onClick={()=>onShow(!show)}>{show?"Сховати":"Показати"}</button></div></label><label className={s.loginField}><span>Повторіть PIN</span><input inputMode="numeric" autoComplete="new-password" type={show?"text":"password"} value={confirm} maxLength={4} pattern="[0-9]{4}" onChange={event=>onConfirm(numeric(event.target.value))} placeholder="Ще раз 4 цифри"/></label>{pinConfirmMessage(pin,confirm)}</div>;
}
function pinConfirmMessage(pin:string,confirm:string){return confirm&&pin!==confirm?<p className={s.pinMismatch} role="status">PIN-коди не збігаються.</p>:null;}
